### ISSUE TITLE
Scaffold out codebase

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#1]
Can use https://github.com/unicef-polymer/etools-frontend-template for now for frontend...

Have 3-4 services with a compose file etc.

Can take code from https://github.com/unicef/etools-infra etc. as well. This repo will though have 3-4 services, each with folder/Dockerfile unlike other separate ones. Thanks.

**Comment by n1207n** [comment]
Added some git commits for this:

+ nginx_proxy

+ db

+ polymer

+ django_api

+ docker-compose-dev.yml

I haven't tested yet but probably continue on tomorrow. django_api is heavily stripped-out etools.

**Comment by chachra** [comment]
Upgrade all packages in polymer and django backend to the latest ones.

**Comment by n1207n** [comment]
docker-compose is ready for dev.
