### ISSUE TITLE
Type of currency is always displayed as USD $ in export

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1004]
dev.prp

Iraq workspace

 export XLS from Programme documents list page all PD's in export will display amounts in USD $ even though some of the PDs have different curreny type.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/47381252-8e5e8900-d6cd-11e8-9329-3645836b7358.png)

![image](https://user-images.githubusercontent.com/32198614/47381294-acc48480-d6cd-11e8-987c-4575327666ba.png)

**Comment by sethgold8** [comment]
You can test right now on PRP.Dev with
user: silin_admin
Rwanda
Partner: CHANCE FOR CHILDHOOD CFC

**Comment by sethgold8** [comment]
working :)
![Screen Shot 2018-12-12 at 3.29.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f16b7191a37bf110224f5c585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe74852a0133664e6762431.png)
