### ISSUE TITLE
Locations dont appear for signed PD

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1005]
dev. prp

Iraq workspace

Locations dont appear for signed PD in IP PRP

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/47381508-32483480-d6ce-11e8-8b07-0d5ff3d9b895.png)

**Comment by sethgold8** [comment]
@KKaselkar PMP needs to make sure Admin level for Locations cannot be null.

![Screen Shot 2018-11-21 at 4.32.08 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37cf111294f5f575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e94953a3163e66e4762431.png)
