### ISSUE TITLE
960 - Error message at the bottom while changing the calculation method

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1007]
dev.prp

Iraq workspace

Change the calculation method and click on save button system displays an error message at the bottom left corner "an error occured, please try again later"

**Comment by sethgold8** [comment]
@KKaselkar @askhawaja @robertavram Error is due to email system not active for Dev environment. We send an email to the UNICEF Focal points  when the calculation method changes. Since the email system is not hooked up in Dev PRP, the error occurs.
