### ISSUE TITLE
Check calculation for Ratio and % indicator

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#1008]
app/IRQ/ip-reporting/pd/1250/report/1763/view?page=1

**Comment by sethgold8** [comment]
Calculations seem to be working for HR2 PCA 2016/04/PD2018501 app/IRQ/ip-reporting/pd/1250/report/1785/view?page=1

If you can reproduce, let us know

**Comment by sethgold8** [comment]
Pushed back because for HR 2 in PCA 2016/04/PD2018501
Achievement in reporting period should be 40.4%
172/425 = 40.4%

![Screen Shot 2018-10-24 at 12.48.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f76b7191a379ed0c2f59415c4dbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f34fe14954a4163467e271376e0a.png)

**Comment by n1207n** [comment]
Fix should be deployed to dev environment but we may need to delete submitted/accepted progress reports to calculate achievement in reporting period correctly.

Keep in mind when you delete progress report, LLO indicator's total cumulative progress may not get reset. When you enter data on new progress reports and submit them, total cumulative progress will likely get corrected.

**Comment by sethgold8** [comment]
@KKaselkar let us know if you don't see it working for past reports. 
![Screen Shot 2018-10-24 at 5.06.44 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f76b7191a37df1122d4f5b5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df24be54f53a412376aee7e2431.png)

**Comment by KKaselkar** [comment]
Calculation for ratio works fine calculation for percentage needs change will create another ticket for this
