### ISSUE TITLE
Overall status is a mandatory field

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-partner-reporting-portal#1009]
Country: Rwanda
PD: RWA/PCA201879/PD2018106
Report: QPR1 
user: pawl21@gmail.com

Steps to reproduce: 
1. enter all data apart from the Overall status 
2. Submit. 

The submission is allowed. At  the begining the system displayed "No data to show" and all of the entered indicator data disappeared. After logging out and back in, I can see this:
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b6fe776743c32000a1b8c2/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb2876ddb02def112d580c5e4bac41515d41fbff8e29a0a42062c80d55b98e30063e937f03a6aa8317b500bf248b4c87bfbd884bc1e83937aa.PNG)

expected result: 
The user should be unable to submit without filling in the Overall status.

**Comment by sethgold8** [comment]
@marcindo unable to reproduce. See photo below 

![Screen Shot 2018-10-23 at 2.48.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f06b7191a37af116234f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19f41c95df24be24e54a71b3164e5722431.png) 

Did you enter this data from the PMP side? Can you reproduce from PRP submission side?

**Comment by mpawlowski85** [comment]
ok - this one is weird. I cannot reproduce this now either. Closing this for now.
