### ISSUE TITLE
I am able to submit a report without rating the output

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-partner-reporting-portal#1015]
Workspace: Rwanda
PD: RWA/PCA201879/PD2018108
user: pawl21@gmail.com (IP Auth Officer) 

Steps to reproduce: 
1. Go to a QPR
2. Fill in all of the fields on the "Reporting on Results" tab, apart from the "Overall Status" rating. 
3. Fill in all of the fields in the "Other info" tab and include an attachment - wait long enough to let the system save the text. 
4. Hit Submit 

result: The report is submitted and the "Overall Status" field shows "No Status" 
![image](https://user-images.githubusercontent.com/26120371/47610585-846abc00-da26-11e8-9b8b-7422a7b52cd7.png)

Expected: The "Overall status" is a mandatory field in QPR and the user should not be able to submit the report without it.

**Comment by sethgold8** [comment]
@mpawlowski85 specification should be: overall status should be mandatory. Not the narrative

cc @n1207n

**Comment by sethgold8** [comment]
Working :)

Validation to make sure status is set

![Screen Shot 2018-11-26 at 11.53.23 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f56b7191a379ee0c2e52415d4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe24f53a6133467e472306e0a.png)
