### ISSUE TITLE
Not all indicators appearing when 'generate uploader template'

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#1018]
@KKaselkar @askhawaja @robertavram  we are showing all indicators but segmenting them by dissagregations via tabs in the bottom left bc backend cannot handle two different dissagregations in one sheet due to dynamic columns

demo: app/ZIM/ip-reporting/pd/898/report/78/edit?page=1
Partner: Nutrition Action Zimbabwe

![Screen Shot 2018-10-29 at 3.33.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456fa6b7191a37bf111284f5b5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be94856a1103660e4702431.png)

![Screen Shot 2018-10-29 at 3.33.58 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456fa6b7191a37bf111284f5a575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be94856a1173e63ee772431.png)

**Comment by KKaselkar** [comment]
Issue is resolved indicators appear as per the disaggregations
