### ISSUE TITLE
Percentage value shows incorrect value on indicators page

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1023]
demo.prp
Zimbabwe workspace

Percentage indicator displays incorrect  value for total progress against he target on indicators page

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/47877901-64a31180-ddf3-11e8-9c09-198aa452f264.png)

**Comment by sethgold8** [comment]
@KKaselkar I see we are multiplying Achieved by 100% so total progress = 2647. Target = .95

From there: 2647/.95 = 2786% or current progress

**Comment by sethgold8** [comment]
Current progress now matches achieved as a percentage. Below is a photo showing the #s underlined in red

![Screen Shot 2018-11-21 at 3.10.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37bf1132b4f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e94954ad173f60e6702431.png)
