### ISSUE TITLE
Error while adding OCHA plans

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1025]
demo.prp
For (Sudan, Zimbabwe, etc) when I try to add OCHA plans system throws the following error:

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/47935968-99c26900-deb2-11e8-88c2-4b49f97952b7.png)

**Comment by sethgold8** [comment]
Country must have correct ‘Country Short Code’ when pulling a Response Plan from OCHA. If receiving the error Countries in the workspace have invalid setup, cannot proceed ; check to make sure the Country Short Code is correct in Django Admin page.

**Comment by KKaselkar** [comment]
Resolved. Thanks
