### ISSUE TITLE
Disaggregation tables: better styling and convert dates

### ISSUE THREAD

**Issue by ErinOC** [unicef/etools-partner-reporting-portal#103]
The current disaggregation table styling differs from the mockup: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016144

- Background color
- White lines to divide cells
- Bold text
- Needs date formatting (add moment.js)

Please branch off https://github.com/unicef/etools-partner-reporting-portal/pull/152 and send in a PR. Please see @rkrupinski comment below as well.

Best way to replicate is the 3-level disagg table.

**Comment by rkrupinski** [comment]
Yep, those tables require some heavy tweaking. Any spare time this sprint, @ErinOC ?
