### ISSUE TITLE
Start date in uploader in incorrect

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1030]
Start date in the uploader is wrong for the first entry date (column AE) for the uploader is wrong for the first reporting period. I set it to start 1 July but it was 1 April in the uploader. All other dates are correct.

**Comment by sethgold8** [comment]
Working. Can you give example with screen shots and steps to reproduce.

Below is an indicator with start dates
![Screen Shot 2018-11-07 at 2.28.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a37af110234f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ae74f5ca3123361e5742431.png)

And column AE
![Screen Shot 2018-11-07 at 2.27.49 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a37af1102c4f5b565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ae74f5ca3103467e67e2431.png)

**Comment by KKaselkar** [comment]
passed tested in dev
