### ISSUE TITLE
Cannot change the dates at the cluster level for the conflicting dates with activity level indicator

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1034]
When editing (adding) locations to an activity indicator in a project, I got an error saying "Start date of reporting period cannot come before the activity's start date"; but I am not able to change dates (I'm trying to work out if this is due to the cluster activity having dates that conflict wit the project into which it is being assigned)

**Comment by sethgold8** [comment]
@KKaselkar are you referring to not being able to edit the start date for a Partner Activity Indicator? If not, please clarify
![Screen Shot 2018-11-07 at 2.44.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a37af1162f4f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ae74e55a3173667e0762431.png
