### ISSUE TITLE
Reports are not generated for Cluster Objective Indicators

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1036]
dev.prp 
Iraq workspace

Created Cluster objective and cluster objective indicators with weekly reporting frequency start date as 21 Oct 2018 but no reports are being generated till now.

https://dev.partnerreportingportal.org/app/IRQ/cluster-reporting/plan/2/response-parameters/clusters/objective/47/indicators?page=1&page_size=10

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/48227802-5adc5980-e371-11e8-8019-61b58e2fb4eb.png)

**Comment by sethgold8** [comment]
@KKaselkar what are the response plan dates? What is the response PLan?

**Comment by sethgold8** [comment]
@KKaselkar closing this as we have seen Cluster Objectives generate many times
