### ISSUE TITLE
Reports are not generated for indicators added to a Project from OCHA

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1037]
dev.prp
Iraq workspace

RP: Iraq humanitarian action plan 2010
Cluster for the project: Shelter sector outcome team
User was logged in as IMO

**Comment by sethgold8** [comment]
@KKaselkar if a response plan end date is in 2010 and the indicator is in 2018 (or falls outside of RP), it will not generate.

Let me know date of indicator generated and RP
