### ISSUE TITLE
Adding projects - cluster member

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1038]
dev.prp environment
Iraq workspace
Login as Cluster Member.
1) System throws error message twice while adding custom projects 
2) project from ocha option is also enable alongwith the error message.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/48375374-bff7be00-e695-11e8-8bf2-a3ddf7683990.png)


![image](https://user-images.githubusercontent.com/32198614/48375388-cdad4380-e695-11e8-9083-f3bd2bd38b17.png)

**Comment by sethgold8** [comment]
Fixed

**Comment by KKaselkar** [comment]
issue fixed in dev

**Comment by KKaselkar** [comment]
resolved in demo
