### ISSUE TITLE
Indicators: add frontend tests

### ISSUE THREAD

**Issue by ErinOC** [unicef/etools-partner-reporting-portal#104]
Tests are needed for:
- Indicators list
- Filter by PD (added in the indicators filter branch)
- Indicator details dropdown (just on a basic level; disaggregation tables are still in progress and testing for those will happen in another ticket)

**Comment by n1207n** [comment]
We'll need to deal with frontend testing at some point. Closing this and I'll create a new ticket to target this topic.
