### ISSUE TITLE
Incorrect details for exports - Ratio Indicator

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1042]
For all indicators Percentage indicator is displayed as ratio in the export. 
Target for ratio indicator is displayed in decimal instead of N/D.
The below example is from cluster objective indicator

Plan Political Affairs in Sudan 2018
Protection Cluster
Sudan workspace
dev.prp

app/SUD/cluster-reporting/plan/31/results/draft?page_size=10&page=1

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/48494298-98226a80-e7fb-11e8-8e4b-bec582e95557.png)

**Comment by sethgold8** [comment]
Opened new ticket to solve this #150

closing
