### ISSUE TITLE
Max 2 decimal points for ratio indicators

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1043]
Please display maximum 2 decimal points for ratio indicators.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/48495376-d456ca80-e7fd-11e8-81bf-e72d6f318c21.png)

**Comment by sethgold8** [comment]
@groinder can you implement?

**Comment by sethgold8** [comment]
Updated
![Screen Shot 2018-11-15 at 12.55.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f66b7191a379ed0c2e54415e46bc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f34fe34e54a1103364e47f3e6e0a.png)

**Comment by KKaselkar** [comment]
tested in dev it works

**Comment by KKaselkar** [comment]
Resolved in demo
