### ISSUE TITLE
Ratio indicators - total progress is displayed in percentage

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1044]
For all the ratio indicators the total progress is displays as % instead of decimal values.

Plan Political Affairs in Sudan 2018
Protection Cluster
Sudan workspace
dev.prp

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/48509662-bac67a80-e81f-11e8-921b-f1104b43763f.png)

**Comment by sethgold8** [comment]
@groinder we need to display Total Progress as a Ratio for Ratio Indicators only.

Grab totals calculated value and add 1. For the example above (271%) it should be  2.71:1

**Comment by sethgold8** [comment]
Fixed
![Screen Shot 2018-11-15 at 12.52.53 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f66b7191a379ed0c2e53415a4dbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f34fe34e54a111376ae471366e0a.png)

**Comment by KKaselkar** [comment]
issue resolved in dev

**Comment by KKaselkar** [comment]
resolved in  demo
