### ISSUE TITLE
No data displayed on dashboard

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1045]
Dashboard doesnt display any results for IMO or partner.

Plan Political Affairs in Sudan 2018
Protection Cluster
Sudan workspace
dev.prp

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/48510520-15f96c80-e822-11e8-8f48-523d77972770.png)

**Comment by sethgold8** [comment]
IMO cannot be partner. If so, no data will show
