### ISSUE TITLE
IMO to not able to update the PAI baseline requested by partner

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#1048]
Partner adds a location at PAI level and sends the message to IMO to update the baseline.
IMO to not able to update the PAI baseline requested by partner

Dev.prp

**Comment by sethgold8** [comment]
IMO must update CAI from 'Locations' button

![Screen Shot 2018-11-21 at 4.10.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37cf1132b4f5b585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df249e94950a1113166e7702431.png)

Then PAI will adopt
![Screen Shot 2018-11-21 at 4.11.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37cf1132a4f5d585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df249e94950a1153f6be67e2431.png)
