### ISSUE TITLE
Add 'Submitted Partner Activity' to 'Indicators by Progress Status' + Add 'Submitted ' to 'List of Constrained Indicators'

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#1049]
- [x] The Pie chart represents Submitted Partner Activity indicators. We need to add the words 'Partner Activity' in front of "'Indicators by Progress Status'

![Screen Shot 2018-11-14 at 3.39.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f76b7191a37bf111224f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e34e5dac14356aee712431.png)

 - [x] Title below should be: Submitted List of Partner Activity Indicator 
![Screen Shot 2018-11-14 at 4.09.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f76b7191a37cf112224f5e585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29841c95df249e34955a21a3e6be5742431.png)

**Comment by KKaselkar** [comment]
resolved in demo
