### ISSUE TITLE
CRUD endpoints for cluster objectives

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#105]
Model for cluster objectives should already be there. Make changes as required for this ticket.

Starting from this mockup and next few screens: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533795

- list (with filters)
- create
- detail
- edit

tabs like indicators, activities etc. will be handled in different tasks.

**Comment by lkolacz** [comment]
branch name `feature-CRUD-cluster-objectives-#105`
