### ISSUE TITLE
Getting 500 error When IMO tries to 'Send Back' Submitted Report

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#1051]
Getting 500 error When IMO tries to 'Sent Back' Submitted Report

![Screen Shot 2018-11-15 at 1.11.30 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f66b7191a379f1132a4f5c5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29841c95df249e24c53a7133667e0722431.png)

**Comment by KKaselkar** [comment]
resolving the ticket this works in demo
