### ISSUE TITLE
Unable to change user role in ID Management

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-partner-reporting-portal#1059]
When in ID Management I try to edit a role that is already assigned to a user. When I hit edit, there is a modal window. When i select the "role" drop down list - it is not possible to change anything, as the list does not display - the screenshot is available below.
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b6fe776743c32000a1b8c2/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb2876ddb02def112d580c5e4bac41515d41fbff8e29a0a42062c80d55b98e30063e937f03a6aa8317b500bf248f4e84b2bc8b48c3e03c37aa.PNG)

**Comment by sethgold8** [comment]
@kosior getting this error message when trying to edit permission on Demo Environment

user: admin_ao
![Screen Shot 2018-12-06 at 4.53.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216454f56b7191a37cf117284f5b575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe04951a6123f62e0702431.png)

**Comment by sethgold8** [comment]
Working now in dev :) cc  @mpawlowski85
![Screen Shot 2018-12-17 at 1.36.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f46b7191a379f1112d4f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df24ee14557a2123365e7722431.png)
