### ISSUE TITLE
CRUD endpoints for cluster activity and partner project

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#106]
After #105 is done can work on this. Models for both should be in place, make changes as necessary.

cluster acitvity: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533943

partner projects: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232532635

DO NOT work on partner activity related API's in this task please.

Same as #105, list (with filters+pagination), create, edit, detail etc. are part of scope here.

**Comment by lkolacz** [comment]
branch name for this task `feature-CRUD-cluster-activity-partner-project-#106`
