### ISSUE TITLE
Reporting on the same indicators in multiple projects

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-partner-reporting-portal#1065]
Currently there is no way for a partner to report on the same indicator in multiple projects. 

This functionality must be enabled. 
Please let me know of there are questions/concerns.

**Comment by sethgold8** [comment]
@mpawlowski85 You can 
1) filter by project, 
2) generate uploader template and enter data
3) then import it back to the system.
![Screen Shot 2018-12-17 at 11.41.40 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f46b7191a379ee0c2f50415b4ebc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe44d52a11b3264ef73356e0a.png)

**Comment by mpawlowski85** [comment]
@sethgold8 sorry about that - it was my mistake - I meant to say multiple projects. 
My understanding is that the process is as follows: 
- Cluster partner sets up a project 
- The project adopts indicators

The cluster partner cannot adopt the same indicator in multiple projects.  

The request is to enable a partner to adopt the same indicator in multiple projects and report on them.
Let me know if this make sense. Happy to discuss further.

**Comment by sethgold8** [comment]
@mpawlowski85 Project does not adopt indicators. 

Are you referring to Partner adopting Cluster Activity Indicators which would be a Project Activity Indicator?

**Comment by mpawlowski85** [comment]
I will raise a new issue on this
