### ISSUE TITLE
Changes to handling of 0/0 percentage indicator reports

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#1079]
- [x] Allow 0/0 then as legitimate data entry (already allowed to be entered)
- [x]  in "view mode" of the table data then show the 0/0, currently its blank.
- [x]  Once done make sure all calculations basically ignore the 0/0 entries.
- [x]  X/0 (X is non-zero) is still not legitimate.
- [x]  Allow the user to submit the data.
- [x]  When the whole thing (totals of total) is 0/0 then what is show 0%.

**Comment by mpawlowski85** [comment]
I have tested this today but still unable to submit with 0 in denominator. I still get this message: 
![image](https://user-images.githubusercontent.com/26120371/53686632-b1421f00-3cf7-11e9-9511-d3dc4b8f9b01.png)

I have encountered another issue, that were not there before: 
- for a ratio indicator with 3 disaggregations, 
- I entered only 0 in male column and some numbers in the female column
- I hit save 
- the system does not calculate the line/row totals - this prevents the user from hitting save (hitting of the save button does not have any effect - the button is inactive).

![image](https://user-images.githubusercontent.com/26120371/53686714-a936af00-3cf8-11e9-943c-141312a5e161.png)


- I had to go and re-enter all of the numbers into all of the fields again - then the system calculated the line/row totals and let me save. 
- even then the line/column totals do not display on the screen.  

![image](https://user-images.githubusercontent.com/26120371/53686764-5ad5e000-3cf9-11e9-9486-cc599d2a357c.png)

Once I made all of the denominators equal to at least 1, the system allowed me to submit the report.

**Comment by mpawlowski85** [comment]
The test failed. 
I am able to submit a report, but now there is a problem with the Total Cumulative Progress. I did the following: 
1. fill in QPR 1 - various numbers
2. Accept QPR 1 on UNICEF side - all numbers are correct so far. 
3. The Total Cumulative Progress is calculated and displayed correctly. 
4. Fill in HR1 - various random numbers
5. Fill in QPR2 - fill in only zeroes and a single 1 in the denominator. 
6. Accept the report on UNICEF side. 

At this point Total Cumulative Progress becomes 0 for all indicators. I downloaded the XLS for QPR2 - it also shows 0 as total and Total Cumulative Progress.

**Comment by n1207n** [comment]
@mpawlowski85, this is correct behavior according to your spec for handling percentage indicators.

We set the indicator's total cumulative progress from latest accepted indicator report's achievement in reporting period if the indicator type is percentage. We even documented this in our Gitbook based on your PDF attachement.

https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/setting-calculation-methods-for-indicators#calculation-method-across-reporting-periods-ratio-indicator-type

https://waffle.io/unicef/etools-partner-reporting-portal/cards/5bbe94b0699120004fb0633d

![Screen Shot 2019-03-04 at 10.48.32 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206454f76b7191a379ef0c2f59415c4cbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ee04a57a1103460e571356e0a.png)

**Comment by mpawlowski85** [comment]
@n1207n  - sorry - you are completely right. It clicked now. 
This card is passed now. 
@ntrncic, @robertavram can we deploy this to PROD? 
I don't expect any data migration impact, as the organizations simply refrained from submitting the reports.
