### ISSUE TITLE
Allow multiple Attachments in SR and QPR's

### ISSUE THREAD

**Issue by brandinalexander** [unicef/etools-partner-reporting-portal#1088]
When submitting reports, create option to for the user to click "Add Attachments" to create additional fields where more attachments can be uploaded. 

----
**Trello Ticket:**
https://trello.com/c/Umy8fMAT/29-add-attachment

**Comment by chachra** [comment]
From Marcin: Lets stick with 3 attachments. The fields will be called: 
FACE Form: 
Other Attachment: 
Other Attachment:

It would be useful to have some metadata with those attachments as well. These would be: 
Source: "PRP"
Document type: "FACE" or "Other"

**Comment by n1207n** [comment]
Backend APIs are done for this ticket. I need to write unit test cases in the meantime, but frontend work can be started.

* ListCreate API: `/api/unicef/<WORKSPACE_ID>/progress-reports/<PROGRESS_REPORT_ID>/attachments/`
  - Supports GET for listing and POST for uploading a new attachment

* Detail API: `/api/unicef/<WORKSPACE_ID>/progress-reports/<PROGRESS_REPORT_ID>/attachments/<ATTACHMENT_ID>`
  - Supports GET for detail, PUT for updating an existing attachment, and DELETE for deleting attachment

POST and PUT methods require multipart-data request format, but existing Polymer code should already do this for you.

**Comment by n1207n** [comment]
The required fields for POST and PUT methods are really `path` and `type`.

`type` can either be `FACE` or `Other`. `path` is the field name for uploading file data.

You can upload 1 FACE type and 2 Other type attachments to a ProgressReport, totaling 3.
