### ISSUE TITLE
Include Information Icons

### ISSUE THREAD

**Issue by brandinalexander** [unicef/etools-partner-reporting-portal#1089]
Include information icons to explain various functions in the system.

----
**Trello Ticket:**
https://trello.com/c/8zRnxzhd/24-include-information-icons

**Comment by kasialanecka** [comment]
@brandinalexander Please check, but I believe this ticket is archived in Trello?

**Comment by brandinalexander** [comment]
@kasialanecka - Confirmed - will close.
