### ISSUE TITLE
Allow IP progress reports and Cluster indicator reports to be refreshed against the current state of the PD / LLO / reportables / locations

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#1094]
So.... our suggestion is:

- adding a button to progress report in IP.
- adding a button to indicator report in cluster.

Assuming PD syncs are happening fine these will create new indicator reports, delete any inactive ones, add locations, remove location reports.

Only allow for draft reports.

Warn the user: "new indicator reports and new locations will be added. Any indicator reports or locations that have been removed, data could be lost. Are you sure?"

**technical details**

![unadjustednonraw_thumb_4cad](https://user-images.githubusercontent.com/73096/53919193-18284680-401e-11e9-851f-2e9525dd2ff1.jpg)

**Comment by n1207n** [comment]
Our approach is to delete all IndicatorReport and IndicatorLocationData for ProgressReport and regenerate them based on current state of ProgrammeDocument, and it will not call PD sync task.
