### ISSUE TITLE
A signal is needed for any Indicator Report being filed

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#111]
Primarily apply the right math then to update the IR total field (represents progress across locations for that IR / reporting period) and also the Reportable total field (which represents progress for that indicator as a whole).

**Comment by chachra** [comment]
@n1207n please update ticket description per our discussions.

**Comment by n1207n** [comment]
I believe this is done as we merged disaggregation branches. Reportable total is done as IndicatorReport post_save signal.
