### ISSUE TITLE
Standarize report statuses

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#114]
Currently it's either `1`, `'Sub'` or `'Submitted'` which breaks the `<report-status>` component.

Also, within `<report-status>`:

```js
status: Number,
```

conflicts with:

```js
switch (status) {
  case 1:
  case 'Sub':
    return 'success';
```

**Comment by rkrupinski** [comment]
I suggest mapping statuses to integers / lowercase strings.

**Comment by lkolacz** [comment]
It's always 3 char.. where the first one is upper! This is backend standard in this project.. 
we can make a "big" update on backend to change it to have always lower...

**Comment by rkrupinski** [comment]
As per discussion with @chachra , we may end up writing a front-end middleware to convert ids to strings on the fly.

**Comment by chachra** [comment]
Choices I am fine with id or string or whatever is needed. of course if its a db entry then id is integer. If its a ChoiceField anything is fine.

**Comment by n1207n** [comment]
Unresponsive issue for long time... Closing this.
