### ISSUE TITLE
As data is being entered, totals are calculated in the frontend itself

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#119]
See https://projects.invisionapp.com/share/RDBE0T04F#/screens/238647670 and next few screens.

The math is always just sum (irrespective of calculation method since that doesn't apply at individual location level).

As user enters the subtotals and total of totals should all auto-calculate. Basically any level lower than the one user is reporting on should be auto-calculated.

No calculations will happen when user is entering data without any disaggregation (no checkboxes chosen or shown).

In ratio/percentage case division needs to happen of sum of numerator and denominator.

**validations**
for quantity:
* must be a positive rational number						
* must have no more than 4 decimal places						

for ratio/percentage:
* numerator and denominator must both be positive whole numbers						
* denominator can not be 0, unless is the numerator is 0 in which case the value calculation should be 0						
* if a percentage, show calculation as a percentage						
* if a ratio type is selected, show calculation as a number to the nearest 2nd decimal place

**Comment by chachra** [comment]
@kasfaw can you confirm to what decimal point for ratio should we store/show?

**Comment by kasfaw** [comment]
@chachra @rkrupinski we should store up to 2 decimal points

**Comment by chachra** [comment]
Technical details / spec: https://docs.google.com/document/d/13bY_rFSeXIfHUYxrUSJEsil2UqzH6GJKcRQ9jQVk2-U/edit?ts=59cb659b#

**Comment by rkrupinski** [comment]
One known bug remains: #346
