### ISSUE TITLE
check update - PD report status

### ISSUE THREAD

**Issue by kasialanecka** [unicef/etools-partner-reporting-portal#122]
From comment in Invision (PMP):
The report status needs to show as well the status based on UNICEF action in PMP. Proposed approach is:
- Overdue: red
- Submitted: orange
- Accepted: green
- Sent back to partner: red
- Due: grey
- Nothing due: no colour

https://invis.io/RDBE0T04F#/234383580_Reporting-IP-01_Hover

**Comment by lkolacz** [comment]
branch name `feature-PD-report-status-#122`
