### ISSUE TITLE
User should be able to select a response plan and see it in header as well

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#134]
In header in addition to country/intervention in cluster reporting user should see the selected response plan as well with a change link.

Clicking change will bring user to https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/237399449 . Also changing country will bring user to this screen.

User has to select and then process to dashboard for cluster reporting.

Since we want to permalink response plan id will end up in URL as well, but assuming by the time this task is done we have that routing logic in place already.

**Technical Design**
Add a ResponsePlan model to the 'core' app with appropriate fields etc. based on mockups. Only a GET request is needed filterable by country/intervention id.

Frontend implementation depends on #135

**Comment by n1207n** [comment]
@chachra, from our standup discussion today:

@lkolacz wants to get clarification on showing location column in Response plan list when the user is choosing Response plan. On the cluster reporting web page, we are already in one intervention which denotes country. Our understanding is that we show Response Plans for current country the user is interacting with. With that in mind, when we go to Response Plan select page, showing locations may seem wrong.

Let me know the rationale behind showing location columns that may have other countries although the user came from current intervention they are in cluster reporting.

**Comment by chachra** [comment]
@lkolacz please have fake data generate 3 RP's per country.
