### ISSUE TITLE
Implement TokenAuthentication

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#143]
In order to solve CSRF token requirement from Polymer, we need to drop SessionAuthentication and use TokenAuthentication only.

Until this is done, any "unsafe" HTTP request methods need to get CSRF token from cookie and set request header "X-CSRFToken"

**Comment by chachra** [comment]
@robertavram thoughts from your end on this?

**Comment by robertavram** [comment]
@chachra we're still working on the approach on this... basicauth for now should be ok.. I'll let you know asap on the token stuff

**Comment by chachra** [comment]
Closing this out since we're going with session auth for now for the interface
