### ISSUE TITLE
Create fake data for the rest of Indicator type & Finishing other Disaggregator classes

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#147]
Update fake data generator to generate a set of all possible combinatoric data entries for Ratio, Percent.

Implement the rest of BaseDisaggregator subclasses for all indicator types (2) and their calculation/display methods.

Update IndicatorLocationData PUT request API to accept multiple data to update at a time, if possible to do in this ticket easily.

**Comment by chachra** [comment]
@n1207n is this a dupe / already taken care of?

**Comment by chachra** [comment]
dupe.
