### ISSUE TITLE
Location is only incomplete if no data has been entered for a location

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#156]
Seems like currently its showing incomplete when user has reported at disagg level < as configured in indicator.

It potentially is doable in the frontend per @rkrupinski - but best to have the backend return this as a flag per indicator location data.

Need it when getting indicator data and for the PUT request to return it as well.

Also please check if "draft" flag is being set correctly... that should be set if any data (locations, LL output state/narrative, report narrative etc. has been filled in).

**technical notes**
In real-life case when crontab in #45 is created - db field for json is not nullable. So #45 should create it empty, and that is our flag that data has not been entered (false value in python).

**Comment by chachra** [comment]
@lkolacz shows in started state.... have you done any work on this yet? If not I am requesting @n1207n to take over to unblock @rkrupinski

**Comment by rkrupinski** [comment]
@n1207n @chachra Adding this to https://github.com/unicef/etools-partner-reporting-portal/pull/172.

**Comment by rkrupinski** [comment]
@n1207n One more thing - need to also return the `is_complete` flag in the response to the `PUT` request (when editing disaggregations for location).

**Comment by rkrupinski** [comment]
@n1207n Done: https://github.com/unicef/etools-partner-reporting-portal/pull/193

**Comment by n1207n** [comment]
Thanks for merging and having @lkolacz to add `is_complete` flag to PUT request API. Will close this issue.
