### ISSUE TITLE
Support multiple (1, 2, 3 or more...) indicator location data's be uploaded in one PUT request

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#158]
We need to support being able to submit multiple indicator location data's in one PUT request. Each of them could be for:

+ different indicators
+ different locations
+ different reporting periods
+ different disaggregation levels.

Think current JSON input doesn't make any assumptions hence in the backend each of the indicator location data's coming in can be processed individually in one transaction and then respond back as per usual.

One current use-case for this is reporting towards the cluster and the unicef targets in one go: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016138

**technical design**
Frontend / API will take a list of objects. Serializer would need many = True.

**Comment by n1207n** [comment]
Seems there is no use case for this at this time. Closing this.
