### ISSUE TITLE
Level 2 & 3 disaggregation (fake) data.

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#160]
Currently, generating fake data yields one PD with 2 indicator reports each, with 2 locations each. All locations have a maximum number of disaggregations of `1`. Could we please make our fake data scripts generate all levels? That would greatly improve testing & debugging.

**Comment by lkolacz** [comment]
common branch `feature-level-2-3-disaggregation-fake-data-#160`
