### ISSUE TITLE
Multiple calculation methods needed for quantity indicator type

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#161]
https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533792

For quantity add 2 calculation methods (each with sum, avg, max options like right now). The methods should be named:
* Calculation method across locations
* Calculation method across reporting periods

@n1207n says the fields are being added in https://github.com/unicef/etools-partner-reporting-portal/tree/feature-indicator-types-and-calculation-methods-147 - but we need these exposed in the create indicator.

@lkolacz @ErinOC please make sure that the indicator type and calculation method are not editable in the UI or API as well.

**Comment by lkolacz** [comment]
common branch for this is `feature-multiple-calculation-#161` based on #133 witch contain 147
