### ISSUE TITLE
Partner has to select calculation methods before they are able to report on a Progress report for a PD in IP reporting* Calculation method across locations * Calculation method across reporting periods

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#162]
Since calculation methods are not defined in PD in PMP anymore partner in PRP has to select the calculation methods before they are able to report towards progress of that PD and its indicators.

They will have to do so for each indicator in the PD report. So if any indicator in the PD doesn't have one, we should prompt partner for it, before they can proceed. **Once set this cannot be changed**.

The selections are:
* Calculation method across locations
* Calculation method across reporting periods

**Comment by chachra** [comment]
@kasialanecka needs mockup, not urgent.

**Comment by kasialanecka** [comment]
My suggestion: https://invis.io/RDBE0T04F#/242576554_Reporting-IP-Enter-Data_Select-Calclulation_Method

**Comment by kasfaw** [comment]
linked to #214
