### ISSUE TITLE
Allow user to enter and view percentage / ratio

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#163]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/238716263

User has to enter 2 values per cell.

Some spec details and validations are here: https://docs.google.com/spreadsheets/d/14lbalO2NlNdxDk03ShXy19TAZjXBESYZglHmENW3nDI/edit#gid=1382039906

**technical notes**

This is only when indicator type is percentage or ratio. Should we store the calculated value differently in the db itself? no transformation of data needed then when reading it I guess?

**Comment by rkrupinski** [comment]
@chachra @kasialanecka 

Regarding the mockup - what's this:

![?](https://lh4.googleusercontent.com/tUhC11RD2_fpYeK-BmIZkZZyXBk-0aJYau4lVkXP4IhTIDOBGPUJqFhVwt8_gV6bYNY3uz8jSFtzeM8=w1717-h887 "?")

**Comment by rkrupinski** [comment]
@n1207n How to I distinguish between value, percentage & ratio data?

**Comment by chachra** [comment]
@rkrupinski ignore the top right display for now per your question.

@n1207n Please add indicator type (quantity or percentage/ratio) and also the display type (Percentage or Ratio).

**Comment by n1207n** [comment]
I feel we can replace display type with calculation method, if we expose both indicator type and calculation method. However, the problem may come up if Reportable and IndicatorReport has different calculation methods at their level.

**Comment by chachra** [comment]
#148 should be merged first after @ErinOC review. Waiting on @n1207n backend code to support this indicator type.
