### ISSUE TITLE
Freeze indicator disaggregations in the location data capture

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#164]
disagg_lookup_map and disagg_choice_lookup_map specifically may need to be frozen at the Indicator Report level, that the backend sends to the frontend. So it would be captured when the IR is created for a specific reporting period as the disaggs etc. existed when it was created.

All of this would not be needed if indicators and specifically their disaggregations were never to be edited, once created or being used.... but guessing this is not ideal/desirable?

The main driver for this is the fact that the indicator in PMP or cluster reporting could have been edited in the following ways:
* disaggregation choice string could have been edited
* new disaggregation choice could have been added or deleted
* new disaggregation could have been added or deleted

The proposal is to freeze the data when the indicator report/indicator location data's are being created. See #45 where we plan to do that on a regular basis.

**technical notes**
No frontend changes needed at all since frontend would be agnostic to this.

The values coming back in the PUT request from the frontend will now need to be validated against the frozen disagg id's etc. and not what exists in the db at that point of time.

**open issue**

Freeze calculation method as well? I think calculation methods should never be editable.

**Comment by kasfaw** [comment]
@chachra assuming linked to #244

**Comment by n1207n** [comment]
Disaggregation and its choices are assumed to be locked when Reportable is created. We can only change calculation methods on them.

We do have a separate ticket for locking the disaggregation values to be edited, but that is a separate topic. Closing this.
