### ISSUE TITLE
Be able to edit an indicator in cluster reporting for cluster objective, cluster activity or partner project or non-cluster partner activity

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#168]
Followup to #133 task.

Be able to edit an indicator in cluster reporting for cluster objective, cluster activity or partner project or non-cluster partner activity

Needs mockup for it @kasialanecka (user should not be able to edit indicator type or calculation method or display type). Everything else should be fine to edit. So a followup of this one: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533792

**Comment by kasialanecka** [comment]
@kasfaw can I prepare those mockups? I'm not sure if the calculation method is something that can be edit or not? I think that there was a discussion about that with unicef?

**Comment by kasfaw** [comment]
@kasialanecka please go ahead. calculation method should not be editable in cluster.

**Comment by n1207n** [comment]
We now have edit button for cluster indicators. Closing.
