### ISSUE TITLE
Mockup changes suggested to simplify results entry in cluster reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#174]
Some thoughts/idea I have to simplify the reporting / interface quiet a bit in cluster reporting for entering results.

* Add 2 tabs, first one (default) being "draft/due reports" and other one being "submitted reports" in https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232071188 , can remove that checkbox filter then completely.
* In both tabs then in the list view, change the interface (each row component) to be like the row component in https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233039723 to the first screen the user sees itself which is https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232071188 (don't need 2 components / views for looking at an indicator report then).
* Then one all locations for an indicator report is "green" (like in https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233039728 ) then a button appears next to it saying "submit report" (at indicator report level). Till then its un-clickable.
* The "draft/due reports" tab can have 2 buttons as well, export / import which will export all draft/due reports (the "template") and import once filled in... if say user had 3 indicator reports due and uploaded data for all 3 and their locations, then all 3 would move to "draft" (with green checkboxes in each location). User then simply has to "submit" each report and they are done.
* The submitted reports tab can have "export" button as well which exports what user sees or filtered if they chose that.
* should add export to individual indicator report opened view as well? https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233039733

If we do above then literally only new UI idea we're adding is a "submit" button on indicator report and everything else from IP reporting is re-used and also the interfaces are less and simplified I feel.

By doing above we'll end up re-using lot of IP reporting components in the frontend. Moreover this screen https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233039721 and 4 other screens after it won't be needed at all.

All other interactions of the enter data modal, disaggs etc. remains unchanged of course.

**Comment by kasfaw** [comment]
@chachra my comments. generally agreeing with all your points.

- Add 2 tabs, first one (default) being "draft/due reports" and other one being "submitted reports" in https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232071188, can remove that checkbox filter then completely. _**agreed. that might even be more intuitive to see.**_

- In both tabs then in the list view, change the interface (each row component) to be like the row component in https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233039723 to the first screen the user sees itself which is https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232071188 (don't need 2 components / views for looking at an indicator report then). _**agreed**_

- Then one all locations for an indicator report is "green" (like in https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233039728 ) then a button appears next to it saying "submit report" (at indicator report level). Till then its un-clickable. _**agreed**_

- The "draft/due reports" tab can have 2 buttons as well, export / import which will export all draft/due reports (the "template") and import once filled in... if say user had 3 indicator reports due and uploaded data for all 3 and their locations, then all 3 would move to "draft" (with green checkboxes in each location). User then simply has to "submit" each report and they are done. _**agreed. it would be very straightforward as well. only open question to address (maybe unrelated?) is UX around multiple indicator+location tabs**_

- The submitted reports tab can have "export" button as well which exports what user sees or filtered if they chose that. _**agreed**_

- should add export to individual indicator report opened view as well? https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233039733 _**absolutely. this might even be most commonly used.**_

**Comment by kasialanecka** [comment]
@chachra Made the change, hopefully in the way you had on mind: https://invis.io/EDBIM0Y8M#/243476913_Data_Entry_01_02_Sug_01

I wasn't sure if it still should be a table or a card view. Second thing: in PRP new design looks like this: https://invis.io/RDBE0T04F#/238646329_Reporting-IP-Enter-Data_04_Copy_5 but i decided to add above info about dates/period, status, draft label and submit button (I think I should have add Partner's name as well?). I spent some time here iterating how this component's header (with submit button + toggle + indicator title) should look like, not to make it hard to read, not sure if I've made it. In expand mode there should be also place to view narrative, I suggest to put this below the table with data. 

Issue here: what happens if we have the indicator report not submitted for e.g. 2 periods? I mean - will this report be imported and exported 2 times (we don't have date filter on these screens, maybe there should be one, so only e.g. the newest one could appear on the screen)?

**Comment by chachra** [comment]
@kasialanecka this looks fantastic!

Yes should include partner name (if any), will make it clearer.

There is a lot of data... so yes its a bit hard to read, no way around it I guess.

If 2 indicator reports then yes it should appear twice for now, no issues there.

Looks good from my end! Can present tomorrow... @kasfaw can review as well.

**Comment by chachra** [comment]
@kasialanecka please link up the new 2 screens https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/243476913 in the nav and can move old ones to deprecated section or remove completely from invision. accepting this ticket.
