### ISSUE TITLE
Minor UI Changes

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#177]
- [x] Would be good when no data being returned because of filter in results screen of Progress report, to put some message? https://www.evernote.com/l/AAWR__JWXC1O_K0KQPx2wrNGfR4m2PxCfQI

- [x] There are some minor labels change and  a missing Column on the “Programme Document” List of PDs here: https://www.evernote.com/l/AAVNlqcQ85dDO7PU9a2enYULzvUFhYnLffQ -The Labels after CSO Contribution should read: UNICEF Cash, UNICEF Supplies, Planned Budget (do not display the percentage here). Then the next column should be  “$ Cash Transfers to Date (%)” and it should display the Actual Disbursement and the percentage in brackets.

- [x] Cluster reporting date pickers should have the green color in them (not blue) (this is kinda done in `create-partner-activity-#222`)

- [x] Center the select response plan screen in cluster reporting interface. currently its kind of to the left, makes it look broken?

- [x] Column change on PD list view: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016130/comments/83411796

- [x] Rename/remove save button: https://projects.invisionapp.com/share/RDBE0T04F#/screens/238646874/comments/83030821

- [x] Modify content in "Show PD/SSFA ToR Details" modal: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016133/comments/81159393

- [x] ~~Keep PD details from IP Reporting and PMP  aligned (more details may be required from @kasialanecka ): https://projects.invisionapp.com/share/RDBE0T04F#/screens/231338351/comments/82047876~~ 

- [x] Move "Indicator" below "Progress Reports" in IP Reporting left nav: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016144/comments/83414381

- [x] Place expand icons on the left throughout (to be consistent with rest of eTools): https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016144/comments/83896374

- [x] Target/progress values for % indicator types should have "%" appended to the value (ie: Target: 30%): https://projects.invisionapp.com/share/RDBE0T04F#/screens/231337947/comments/83833354

- [x] ~~Rename to: "Total progress in all locations": https://projects.invisionapp.com/share/RDBE0T04F#/screens/231337947/comments/81256615~~

- [x] ~~Text alignment on indicator details drop down: https://projects.invisionapp.com/share/RDBE0T04F#/screens/231337947/comments/83473356~~

- [x] Change text in yellow box: https://projects.invisionapp.com/share/RDBE0T04F#/screens/238646320/comments/83415905

- [x] Remove text from back button: https://projects.invisionapp.com/share/RDBE0T04F#/screens/238716263/comments/82760678

- [x] Rename "Unicef" to "UNICEF" - example here: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016138/comments/82284246

- [x] Move location progress a bit up to compact: https://www.evernote.com/l/AAXi9TMZEnlIxoYN_NZDTvacLCh84iL4iFc

- [x] ~~CO ref # is not shown / reflected in the CO details screen~~

- [x] Add name of Partner to both Draft/Due and Submitted tabs of Report section

- [x] UI style changes as shown in below attachment for all things starting from the notification card and above (details on header settings attached too)
![reporting-ip-enter-data_04 copy 5](https://user-images.githubusercontent.com/11070629/28092062-1c22a13e-6660-11e7-94e2-bfbd429b27a0.png)
[header_guide.pdf](https://github.com/unicef/etools-partner-reporting-portal/files/1256742/header_guide.pdf)

- [x] When no data comes back table pagination looks like this - https://www.evernote.com/l/AAVa06tOljVAOZA_LgPm2H76CxTbYazan_8 - also sometimes shows before data is loaded into a table.

**Comment by rkrupinski** [comment]
@chachra PD lacks "Planned Budget" information.

**Comment by dfryta** [comment]
@rkrupinski Added budget, funds_received_to_date and funds_received_to_date_percentage to PD serializer

**Comment by rkrupinski** [comment]
One more thing @dfryta - please, divide `funds_received_to_date_percentage` by `100`.

**Comment by rkrupinski** [comment]
@chachra 

> Place expand icons on the left throughout (to be consistent with rest of eTools):

I recall discussing this w/ @kasfaw but not sure what the output from that discussion was. The thing is, we're using their (Unicef's) component, `etools-data-table`, which has the row expansion feature baked in.

Here's what we can do:
1. Ignore it 💥 
2. Write a custom component 🐸 
3. Fork `etools-data-table`, make it configurable & submit a PR 🤔

**Comment by kasfaw** [comment]
@rkrupinski In the spirit of reusing components I would hold off until PMP component changes and use that when available. Thoughts @chachra ?

**Comment by rkrupinski** [comment]
@kasfaw Given there's no location filter on this screen, does https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016130/comments/83411796 still stand?
