### ISSUE TITLE
Design changes to revisit post-MVP

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#179]
- [ ] "Enter Data" button should not be raised: https://projects.invisionapp.com/share/RDBE0T04F#/screens/238646874/comments/82755625
- [ ] Status icons on a report: https://projects.invisionapp.com/share/RDBE0T04F#/screens/238646329/comments/82759039
- [ ] Distinct background color/text for absolute total cell: https://projects.invisionapp.com/share/RDBE0T04F#/screens/238647670/comments/82755801
- [ ] UI style changes as shown in below attachement for all things below the rejection feedback section
![reporting-ip-enter-data_04 copy 5](https://user-images.githubusercontent.com/11070629/28092062-1c22a13e-6660-11e7-94e2-bfbd429b27a0.png)

**Comment by n1207n** [comment]
Seemed irrelevant now as IP reporting is close to code completion. May re-evaluate later and take appropriate action in the future. Closing this.
