### ISSUE TITLE
Polymer unit test cases

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#181]
I feel we need to resume adding testing effort on Polymer again at some point. Django codebase is getting a good testing coverage and I hope to see the same thing in Polymer side as well.

**Comment by n1207n** [comment]
This is a huge issue for us now. We need to discuss this soon.

**Comment by chachra** [comment]
@rkrupinski can you add comment as to what exists and what level of coverage can easily be added or should be at all? tx.

**Comment by rkrupinski** [comment]
We've got no unit tests at the time of writing.

Here's an example of how Unicef folks do it:

https://github.com/unicef-polymer/etools-content-panel/blob/master/test/etools-content-panel_test.html

The higher coverage we'd like to add, the more effort it's gonna require (mocking ajax, etc) but testing in general should be pretty straightforward with https://github.com/Polymer/web-component-tester
