### ISSUE TITLE
Be able to submit a progress report

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#182]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/231677538

Can view everything and last button below is SUBMIT that should be a simple flag set (via the API) to mark this report as submitted.

**technical note**
Validation in the API needs to be:
* that all locations for all indicators have been submitted (irrespective of level)
* Cannot resubmit a report that is in submitted state (can re-submit something that has been rejected or in draft etc. of course)

**Comment by lkolacz** [comment]
backed is done for this part in branch ended with -#32
