### ISSUE TITLE
Handle cluster activity indicator progress calculation based on child partner indicator progress

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#184]
Cluster activity indicator progress should be calculated based on any reports against it (if any) but all children indicators

Relevant in cluster reporting, but can be implemented generically

- [ ] calculation of progress on CA indicator is the sum of all progress for child partner indicators

- [ ] @chachra backend mod to update CA indicator progress after PA indicator submission is accepted or sent back by an IMO

- [ ] @chachra separate endpoint to display progress by unique children location progress

- [ ] @rkrupinski on this mockup mockup: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533942 - come up with new component design to show multiple locations for each CA indicator similar to attached image
![screen shot 2017-08-23 at 1 05 12 pm](https://user-images.githubusercontent.com/11070629/29635970-bfb68382-8803-11e7-92ec-1ff40579f16e.png)

From #356

Per our discussion, once the PD recalculation upon IndicatorBlueprint changes is done, the Reportable instance may need to adjust its total based on its parent-child relationship.

This may require the refactoring on post_save signal on IndicatorReport for calculating Reportable totals and some conditions to check its children for getting a correct total value from.

**Comment by kasfaw** [comment]
@chachra few points from discussion ive captured:
- view target set by imo on the cluster activity indicator AND the sum of all targets set by partners for that cluster activity indicator
- progress on a cluster activity indicator always autocalculated based on collective partner reports for indicator linked to the cluster activity indicator
- imo can submit a report on behalf of a partner

**Comment by kasfaw** [comment]
@chachra should we close this issue since cluster activity indicators will be manually reported by IMOs in PRP

**Comment by dfryta** [comment]
Checked all comments - what is status of this issue?

**Comment by kasfaw** [comment]
@dfryta lets discuss in next sprint.
