### ISSUE TITLE
Allow partners to report on an indicator ad-hoc / on-demand

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#186]
Should a partner be permitted to submit an “ad-hoc” report on an indicator (outside of their usual 
reporting requirement)?

A: Would be good if this were possible, especially to account for sudden emergencies that result in the need to add/revise indicators at the emergency evolves.

**Comment by n1207n** [comment]
Now this is confirmed via Progress report types (QPR, HR, and SR)

Closing this as the feature set is implemented.
