### ISSUE TITLE
Results section in Cluster Reporting interface

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#189]
Mockups https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/243476913 and next screen (submitted reports tab).

This is the place partners come to report on their indicators. There are 2 tabs, first one being "draft/due reports" which is the default one. The other one is submitted (or accepted) reports.

Please use assumptions from IP reporting here, in best manner.

Everything within the open/close indicator reporting component should work exactly like in IP reporting. If outer wrapper interface cannot be re-used lets copy from IP and develop the new one here (they can look different for now). Other than project and cluster please add "partner" as well in the first row of the indicator report component.

The "Submit" button appears only for indicator reports that are not submitted or accepted state (the first tab basically). It should be disabled if all indicator location data's are not filled in. If they are then it appears enabled, clicking it should ask for confirmation from user and the allow submission. After this technically that report should vanish from this list (success message / toast message maybe?) and appear in submitted reports section now.

Since there can be many indicator reports, there needs to be pagination as well.

**Technical Notes**
We need an API that returns indicator reports list and allows pagination and filtering on it. I think the endpoint exists and might need some tweaks to support the filters that are here? cluster, project, partner, indicator etc.

Indicator report list API should also support "limit" since we can use it on dashboard as well then for first 5-10 or something: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232073629

We need a IR submit API endpoint potentially (similar to progress report submission in IP reporting, except in this case user is submitting the IR.... please make sure that endpoint actually marks IR's as "submitted" as well.). Submit should only work if all location data's are in place (json is non-empty... Silin has put in check for this in another PR).

**Comment by rkrupinski** [comment]
This kinda requires https://github.com/unicef/etools-partner-reporting-portal/pull/172, https://github.com/unicef/etools-partner-reporting-portal/pull/151 & https://github.com/unicef/etools-partner-reporting-portal/pull/144 being in `develop`.

**Comment by ErinOC** [comment]
@rkrupinski I'll try to address your remaining comments in #134 today so we can get that ticket (which included #151) merged. If there's further delay, you can branch off feature-response-plan-#134 (I've been keeping it up to date with develop).

**Comment by rkrupinski** [comment]
So far I branched of https://github.com/unicef/etools-partner-reporting-portal/pull/172
