### ISSUE TITLE
Indicator management for partner activities

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#191]
If partner is doing a cluster defined activity then can only edit `locations` `target` and `baseline`
https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533041

If a custom activity is added then partner can add their own indicators per usual. https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533047

https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533040

**Comment by chachra** [comment]
@eglital is this already done? If yes, please close this ticket...

**Comment by eglital** [comment]
Part of it is done, a part about editing moved to its own ticket #200
