### ISSUE TITLE
Enable partners to create activities (linked to cluster activity and custom ones as well) and then activity lists in response parameters and my planned action sections

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#192]
Mockups for creation: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533036 and next few screens. Creation components already in place.

List views (ideally will use the same API endpoint). The response parameters > partners > activities is for all partners.

my planned action > activities is for this logged-in partner itself: https://invis.io/EDBIM0Y8M#/232534042_Emergency-PP_Overview_02_Copy_6

https://invis.io/EDBIM0Y8M#/232533039_Emergency_-_MC_-_Activities

Needed backend:
- [ ] /partner/responsePlanId/partner-activity-list - for all activities (filtering by partner, project, status, location, only-customs/all)
- [x] /partner/partner-activity-details/activityId/ - for single activity
- [x] something to get all activities by cluster Id (probably just add a filter to /partner/partner-activity-list/ ?? not working as it is now)
- [x] check create activity endpoint: custom one seems to be working, but in GET /partner/partner-activity-list/ newly added activities dont come associated with any cluster, also dont have start/end time; create by cluster activity gives a 400 error that it doesn't find cluster activity with that id
- [x] not exactly sure but what's needed for this screen: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533047 and this: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533049
edit: at least for now I will be using the same indicator progress screen that it's being used for cluster activities, partner projects etc, even if it's not exactly like in mockups, so this seems to be working as it is
- [x] while creating new activity regardless of what status is chosen, it always ends up added as 'ongoing'. probably related: newly created activities don't have their start and end date set. (in seeded data all this info is in reportables array)
- [x] in individual activity api result, CO ref number is needed

Frontend make sure....
- [x] remove progress tab from activity details.
- [x] In projects/activities.html responsePlanID is not set hence call fails.

derived from cluster activity:
- [x] derived from cluster activity: If baseline / target not entered flag it. https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533040
- [x] cannot add new indicators.
- [x] cannot edit frequency of reporting of the indicators, since they are set by IMO.
separate ticket: #200 

custom activity:
- [x] can add new indicators

**Adding indicators** now is not working, but it's logged in separate ticket #376 and not related to this issue (and on that branch I already fixed frontend part, needs backend work).

**Technical notes**
If partner selects a cluster defined activity then the partner activity should FK to it (the cluster activity instance).

Moreover since the indicators are coming from cluster activity ones, system should auto-create the indicators and have the respective cluster activity indicator be its "parent".

Moreover since cluster activities could get new indicators, if any is added then partner activities that are linked to the cluster defined activity should automagically get that new indicator as well via a post-save signal etc.

**Comment by kasfaw** [comment]
@chachra assuming this is done but will verify with @dfryta and @rkrupinski in next sprint

**Comment by chachra** [comment]
Component is in place, emits an event and the activity details in the event details. Then it needs to be POSTed to an API endpoint.

**Comment by eglital** [comment]
@chachra is there already an API endpoint to list all activities?

**Comment by chachra** [comment]
there might be, but maybe not... I'll need to work with you on it to determine.... branch off dashboard-refact-#364 for now @eglital

**Comment by eglital** [comment]
okay, i couldnt find one, I assume it should be something like /partners/responsePlanId/partner-activity-list/ based on the projects list in the same section? I will start just by building static components

**Comment by chachra** [comment]
I'll put one together asap if I don't find it.

**Comment by eglital** [comment]
also I couldn't find an api endpoint to get all activities by cluster id, this one is currently used: /api/cluster/clusterId/cluster-activity-list/ which I dont think is right because it uses not clusterId but responsePlanId in django views

**Comment by chachra** [comment]
@eglital remove progress tab from activity details.

**Comment by chachra** [comment]
@eglital /api/partner/39/partner-activity/4323/ gets you single activity... please hook this up under response params and my planned action, both.

**Comment by eglital** [comment]
@chachra should 'Add indicator' be available only coming from 'My Planned Action'>Activities>Indicators or also coming from 'Response Parameters'>Partners>Activities>Indicators?
