### ISSUE TITLE
Indicator list be able to filter them in IP reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#20]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016144

Filters as in mockups at the top. "Show active PDs only" will only show indicators that belong to an active PD for this partner.

**Comment by n1207n** [comment]
Additional work:
* Backend support for `Show active PDs only`
* Frontend change to include new `checkbox-filter` Polymer component to support `Show active PDs only`
