### ISSUE TITLE
Ability to Edit Indicators

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#200]
A user with ability to edit an indicator (permissions task here #295), she/he should only be able to edit the `baseline`, `target`, `means_of_verification`, `assumption` and `partner`

In partner activities derived from cluster activities cannot edit frequency of reporting of the indicators, since they are set by IMO.

If partner is doing a cluster defined activity then can only edit locations target and baseline
https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533041

Sample screens:
https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/252229720
https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533041

**great to have:** If the start_date > TODAY all fields can be editted

**Comment by kasfaw** [comment]
@chachra happy to this here. This came up in standup today and wasnt sure if we had covered it. (Obviously) strong need for partner to indicate location they report for a cluster activity indicator

**Comment by n1207n** [comment]
Cluster indicators are now editable. Closing this.
