### ISSUE TITLE
Bug: Partners/Planned Action project list: the filters component interferes with query string

### ISSUE THREAD

**Issue by ErinOC** [unicef/etools-partner-reporting-portal#209]
I encountered this in #199 and am making a separate ticket because I have not figured out a solution yet and don't want to block merge.

Dropdown filters used for projects lists are messing up the pagination query string.

To reproduce: 
Uncomment project-status-filter or cluster-location-filter in:
response-parameters/partners/filter.html or planned-action/projects/filter.html
Go to a URL with a page number, e.g. cluster-reporting/plan/139/planned-action/projects?page_size=10&page=3
The page will show 3 for a moment and then change to 1.

**Comment by n1207n** [comment]
I think all of our filters are currently implemented up to date, therefore this may have been fixed. Closing this.
