### ISSUE TITLE
IP Reporting: Partner able to indicate when they are submitting their final report

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#213]
- [ ]  prior to report submission, Partner can indicate (via checkbox?) that this is their final report

- [ ]  report status for a final report should be "Met result as planned" or "Constrained (partially met results" (checkout screenshot)
![image](https://user-images.githubusercontent.com/11070629/28880332-b8bb6ce2-7772-11e7-9cdb-e7b5157990ae.png)

**Comment by n1207n** [comment]
We now have is_final flag from backend to frontend. Closing this.
