### ISSUE TITLE
IP Reporting: Calculation Method Interface and Recalculations

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#214]
- [ ] Separate tab under the PD screen for selecting calculation methods as shown in table below (https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016132) 

PD output/ SSFA expected result and Indicator | Calculation method across locations | Calculation method across reporting periods
-- | -- | --
PD output1:
Indicator 1.1 | Sum☐   Max ☒ Avg☐ | Sum☐ Max ☒ Avg☐
Indicator 1.2 | Sum☒   Max ☐ Avg☐ | Sum☐ Max ☐ Avg☒
Indicator 1.3 | Sum☒   Max ☐ Avg☐ | Sum☐ Max ☐ Avg☒
PD output2:
Indicator 2.1 | Sum☒   Max ☐ Avg☐ | Sum☐   Max ☐ Avg☒
Indicator 2.2 | Sum☒   Max ☐ Avg☐ | Sum☐   Max ☐ Avg☒
  |   |  

- [ ] default calculation methods to Sum

- [ ] if an indicator has `editable == true`, then calculation method should not be editable in IP Reporting by anyone
- [ ] On selection of a different calculation method, prompt the user with the following confirmation message: "Please make sure the calculation methods for your indicators are properly configured. Changing calculation methods would recalculate progress reports for your indicators!"
- [ ] prior to a user finalizing a modification to a calculation, a confirmation prompt should show up: "You are about to change the calculation method. UNICEF may ask you to resubmit past reports and the calculation of overall progress will change. Do you want to continue?"

- [ ] if a calculation method is modified, figures dependent on calculation methods are recalculated (ie achievement across location, achievement across reporting period) - the status of previous reports will remain the same

- [ ] if a calculation method is modified, both authorized officer from the partner and the UNICEF focal points are notified

**Comment by rkrupinski** [comment]
@chachra @dfryta 

Open questions:

1) In `/api/unicef/<workspace_id>/programme-document/indicators/`, how do I access the output data per indicator? `object_id`, `ref_num`?
2) `/api/unicef/<workspace_id>/programme-document/indicators/` is paginated - do we want to paginate the table too? If so, we're gonna have to sort indicators (query parameter?) by output to prevent outputs from appearing randomly on different pagination pages. Even if we do that, still a list of indicators for one output can span multiple pages if it's long enough. One option would be to set `page_size` to `99999` to bypass pagination (I didn't say that).
3) We can techically reuse the `/api/unicef/<workspace_id>/programme-document/indicators/` endpoint here as it provides all the require information, still we need a way to edit it. How about `PATCH` `/api/unicef/<workspace_id>/programme-document/indicators/<indicator_id>/`?

**Comment by chachra** [comment]
@kasfaw we do need to offer ratio / percentage as options to the user as well when unit choice is percent. For number sum, avg, max still makes sense of course. For percent what should we default to? percentage? Think so... lmk.

**Comment by kasfaw** [comment]
@chachra only calculation method since percent/ratio is selected in PMP by UNICEF. As for default calc method for % type, default should be avg (not sum).
