### ISSUE TITLE
IndicatorReport list API filter for due and overdue status

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#217]
From the cluster portal dashboard mockup, the first card view shows a list of upcoming and overdue indicator reports.

We could leverage the same API endpoint for grabbing a list of IndicatorReports. However, I believe there is currently no filter for grabbing indicator reports by specified status flags.

One question I have for this issue is how to grab upcoming indicator reports. Do we want to grab indicator reports that are due in a week? A month? There needs to be a time slot to determine what indicator reports are upcoming.

**Comment by chachra** [comment]
Think it shows upcoming / due indicator reports sorted by time or something for that partner or imo who is logged in, so requires user based filtering.

#190 has other cluster dashboard ideas.

**Comment by kasfaw** [comment]
@n1207n assuming this is addressed?

**Comment by n1207n** [comment]
Closing.
