### ISSUE TITLE
List of all PD's paginated by their report's due date

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#22]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016130

Pagination should work. Ignore filtering etc. for this task. Name of PD, report status, due data, draft status and appropriate link should work.

**Comment by chachra** [comment]
/country/$id/pd/ ---- list of all PD's. I know in the mockups the tab is called "PD reports" its a bit mis-leading. Made a comment there @kasialanecka

/country/$id/pd/$id/overview/ is 1 report overview

/country/$id/pd/$id/reports/ is list of reports for that pd

/country/$id/pd/$id/reports/$id/data/ is single report data tab
/country/$id/pd/$id/reports/$id/narrative/ is single report narrative tab
/country/$id/pd/$id/reports/$id/review-submit/ is single report review+submit tab only for non-submitted reports.

**Comment by lkolacz** [comment]
btw.. branch name `feature-pd-list-#22`

**Comment by lkolacz** [comment]
btw -> the pagination will be done on filtering ...

**Comment by rkrupinski** [comment]
@chachra According to @kasialanecka , there are changes planned to how budget is displayed on a list of PDs. Do we wan't to put this issue on hold until then, or maybe merge it and apply the changes directly on develop / some other, dedicated feature branch?

cc @lkolacz

**Comment by chachra** [comment]
Yep. Please open a separate ticket for it @rkrupinski - definitely don't want to delay merging this in once PR is reviewed.
