### ISSUE TITLE
Be able to create a partner activity

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#222]
2 modes:
* https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533037
* https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533038

When choosing add from cluster activity this new activity should be linked then to the parent cluster activity and it should get the same set of reportables / indicators as the parent activity does. Even those indicators should be linked to parent indicators that are associated with the cluster activity.

If they create a custom activity then its not related to cluster.

**technical notes**
Please see data model for the parent / child relationships between activity and indicators.

**Comment by rkrupinski** [comment]
@n1207n Branch: 'create-partner-activity-#222'

**Comment by rkrupinski** [comment]
@n1207n I'm gonna need a couple of things:

1) The endpoint itself
2) Request payload structure (including 2 "modes")
3) Possible values (+being able to get them from the API in some cases) for:`cluster`, `activity`, `partner_project`, `status`, `co_ref_no` and `location` dropdowns.

**Comment by n1207n** [comment]
@rkrupinski, API is ready for creating PartnerActivity object with 2 separate modes.

url goes `/api/partner/<response_plan_id_here>/create-partner-activity/<create_mode_here>`

create_mode url argument can be `cluster` or `custom`.

cluster for adding from cluster activity. custom for adding from cluster objective.

Sample request payload for cluster mode:
----------------------------------------------------------------------------------------
`{"cluster": 11891, "cluster_activity": 5221, "partner": 1772, "project": 1822, "start_date": "2017-01-29", "end_date": "2017-05-31", "status": "Ong"}`

Sample request payload for custom mode:
----------------------------------------------------------------------------------------
`{"cluster": 11891, "cluster_objective": 4071, "partner": 1772, "project": 1822, "start_date": "2017-01-29", "end_date": "2017-05-31", "title": "TEST", "status": "Ong"}`

----------------------------------------------------------------------------------------
The difference is between above payloads is that cluster mode needs `cluster_activity` id. custom mode needs `cluster_objective` id and `title`. The other fields are used equally in both modes.

Thankfully, Leszek has created all necessary APIs for grabbing possible values for each field.

cluster: `/api/cluster/cluster-list/<response_plan_id_here>`
cluster: `/api/cluster/cluster-list/<response_plan_id_here>`
cluster: `/api/cluster/cluster-list/<response_plan_id_here>`
cluster: `/api/cluster/cluster-list/<response_plan_id_here>`

**Comment by rkrupinski** [comment]
@n1207n Why does the payload include `partner` && `project` instead of just `partner_project`?

**Comment by rkrupinski** [comment]
@n1207n Also, the `custom` payload lacks `locations`.

**Comment by n1207n** [comment]
@rkrupinski, the mockup reflects some old fields that are no longer relevant. location field is not necessary at this point. 

`partner` is needed for validation purposes in order to make sure `project` exists under `partner`. Same goes to `cluster` & `cluster_activity` or `cluster_objective`.

**Comment by rkrupinski** [comment]
@n1207n Alrighty then.

**Comment by rkrupinski** [comment]
@n1207n Actually... I get the `cluster` -> `cluster_activity` part. I'm currently fetching activities for cluster upon selecting one, out of which one can then choose. If the above is what we want, I'm gonna need a way to fetch projects parameterized by partner id.
