### ISSUE TITLE
Refinements to #199 (Response Parameters and Planned Actions sections)

### ISSUE THREAD

**Issue by ErinOC** [unicef/etools-partner-reporting-portal#225]
Rafal left a few code review comments on things that do work but should be refactored for maintainability and/or speed:

1) Creation modals in #199 handling redirection after save:
"Doesn't this component do too much? Simply changing the routing will break it. I'd make it emit an event upon success which can be then handled by its parent component (or one of its parents)."

2) Data for overview pages are retrieved as a one-off Ajax call and not stored
"Wouldn't we rather store this data to have something to show right away when this page is navigated to another time? Just an idea. See App.Reducers.ProgrammeDocumentReports for details (reports are grouped by PD)."

3) I'm changing the class for the submenu (clusters/partners) to highlight appropriately based on the URL. There's got to be a better way to handle it, but I was stuck on that for awhile so that was a workaround.

4) Changing the background color of the datepicker (Rafal and I used different datepicker components, so I'll wait until he's merged in #133 and make mine consistent)

**Comment by chachra** [comment]
@eglital can you review quickly and see if anything relevant or needs to happen or all ok? If yes, please close.

**Comment by eglital** [comment]
@chachra I think at least No1 and 2 are not done, they probably could be done, I am not sure how needed it is, maybe Rafal could comment on this since they were his comments in the first place

**Comment by n1207n** [comment]
Closing.
