### ISSUE TITLE
Add 'frequency of reporting' to partner projects list and details API

### ISSUE THREAD

**Issue by ErinOC** [unicef/etools-partner-reporting-portal#226]
https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233065458

The mockups call for the frequency of reporting, but that value is not provided by the API.  There had been some confusion about this, but the creation form does include a frequency of reporting field, so the backend will have that information.

The endpoints are are partner-project-list and partner-project-details.

**Comment by dfryta** [comment]
Do we have some list of possible values? Daily, Weekly, Monthly or this should be string value?

**Comment by lkolacz** [comment]
@dfryta Are You looking for this?  core.common -> `FREQUENCY_LEVEL`

**Comment by dfryta** [comment]
Yup, thanks.
