### ISSUE TITLE
Minor UX changes

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#229]
- [x] In cluster reporting > results when opening an indicator report and clicking "enter data". When submit is pressed that Indicator report row closes. Behavior should be to keep it open and update the data in the open row itself.

- [x] Change default ordering in the API to return latest objects first... this way creating a new CO, project etc. is at the top when user creates it.

- [x] show spinner / loading progress bar in big empty white space on the right? Shows when going to any nav item for the first time. Seems like nothing will load or a bug/js error happened. 
![show spinner loading progress bar in big empty white space](https://user-images.githubusercontent.com/73096/29048003-4ea35ca6-7b83-11e7-8940-ce3cdf2ccc21.gif)

**Comment by rkrupinski** [comment]
OMG, this was tricky. Fix pushed to develop.

**Comment by rkrupinski** [comment]
Pushed the loading indicator directly to `develop`.
