### ISSUE TITLE
Be able to filter the list of PD's in IP reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#23]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016130

See filters up top. "Draft only" will show half done / completed (but started) PD reports for this partner. Some filters might be multi-select.

**Comment by chachra** [comment]
Depends on #22

**Comment by lkolacz** [comment]
common branch `feature-filter-pd-list-#23 `

**Comment by rkrupinski** [comment]
@chachra I recall us discussing how filters should work during the demo call. The two TBD items were:

* should filters be real-time (do we get rid of the "Apply filters" button)?
* should we show them all at once or do we want to do it the way PMP does?

Have we reached an agreement here?

cc @kasialanecka

**Comment by chachra** [comment]
@rkrupinski - http://www.material-ui.com/#/components/date-picker see "inline examples". not a strong preference but to me modal seems overkill when someone is trying to run analytics or quick filtering of the data. even pressing "ok/cancel" seems overkill, they selected the date, close the dialog and mark that as selected!!
