### ISSUE TITLE
API throws a 500 after adding a new 'co' indicator

### ISSUE THREAD

**Issue by ErinOC** [unicef/etools-partner-reporting-portal#236]
The API at /api/indicator/co/ worked.  Then I added an indicator using the Add Indicator button, and I started getting 500 errors.  When I added a try/except around the problematic part below, the API worked again and I could see that my newly-created indicator appeared in the list.

If you need to use the UI for this, it is currently available on the hook-up-indicator-button-#221 branch. Note that you'll need to comment out the location field validation in indicator-modal.html (the dropdown is currently empty) before you can submit the form. 

Relevant part of the 500 response:

TypeError at /api/indicator/co/
float() argument must be a string or a number

Request Method: GET
Request URL: http://localhost:8080/api/indicator/co/
...
File "/code/django_api/apps/indicator/models.py" in progress_percentage
  181.             percentage = (self.achieved['c'] - float(self.baseline)) / (float(self.target) - float(self.baseline))

Exception Type: TypeError at /api/indicator/co/
Exception Value: float() argument must be a string or a number

**Comment by ErinOC** [comment]
@chachra Ignore what I said above about the branch.  feature-add-indicators-to-detail-tabs-#220 is the branch to view this issue now.

**Comment by chachra** [comment]
@kasfaw Can you re-validate / replicate / close this ticket out... old...

**Comment by kasfaw** [comment]
Can't replicate. Closing out.
