### ISSUE TITLE
Tests script for django_api failures every time

### ISSUE THREAD

**Issue by nemd** [unicef/etools-partner-reporting-portal#241]
Currently for djano_api pipeline we have tests in place but it seems that there is something wrong with those tests - it failures each time. 

``python /code/manage.py test --settings=django_api.settings.test --parallel``

p.s. failed tests are not causing image not to being built.

**Comment by n1207n** [comment]
Re-posting from slack:

In `develop` branch, can you figure out why codefresh Django pipeline cannot find `ENV` environment variable entry?

The django_api pipeline definitely has `ENV` environment variable. I deleted composition_variables from django codefresh yml file and still not working.

Should we try renaming `ENV` to something else and maybe it would work?

Anyways if you figure out `ENV` not getting issue then Django pipeline should start doing unit tests again. I fixed all Django unit test cases so codefresh build should be successful.

Thanks in advance!
