### ISSUE TITLE
Cluster: Include ability to submit status for each indicator report

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#243]
- [ ] include status similar to this mockup below each indicator partner submits a report on (plus narrative textbox) : https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233039728

- [ ] keep both field optional 

- [ ] include "No Status" as a selection option and selected by default

@rkrupinski i've updated this.

**Comment by rkrupinski** [comment]
@kasfaw I'm not sure how this would work. Can we discuss this during standup?

**Comment by kasfaw** [comment]
@rkrupinski for sure. is there a particular part I can clarify more?

**Comment by rkrupinski** [comment]
Every. Single. One. :)

**Comment by kasfaw** [comment]
ok :) lets walk through in the stand up then!

**Comment by rkrupinski** [comment]
Branch: `cluster-submit-status-for-report-#243`

**Comment by kasialanecka** [comment]
Link to the screen: https://invis.io/EDBIM0Y8M#/243476913_Data_Entry_01_02_Sug_01

**Comment by rkrupinski** [comment]
What's missing:

* 3-char code for the "No status" status
* api for submitting status / narrative assessment (see https://github.com/unicef/etools-partner-reporting-portal/issues/264)

Open questions:
* For PD reports, do we want to include the "No status" option (and default to it) as well?

@dfryta @kasfaw

**Comment by kasfaw** [comment]
@rkrupinski "no status" not needed for pd reports
