### ISSUE TITLE
Cluster: Change in Disaggregation Selection

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#244]
Editing or deleting disaggregations is not allowed, hence this task just shows list of disaggregations and way to create them.

Also given simple nature, no filtering needed for now for list view.

- [ ] IMO should be able to view and add disaggregations for each response plan as shown here: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/247376565

- [ ] There is validation for duplicate disaggregation names when adding https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/247376566 (potential both client and server side validation needed)

- [ ] When adding an indicator, disaggregation selection should be a drop down with the list of disaggregations available from Cluster Response Parameters. Selection will display the disaggregation groups. https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/247376564

**Technical notes**

http://127.0.0.1:8080/api/indicator/response-plan/6/disaggregations/ - returns list of disaggregations and values.

Can send a POST request to http://127.0.0.1:8080/api/indicator/response-plan/6/disaggregations/ (6 is response plan id)

{
    "active": true,
    "response_plan": 3,
    "name": "test 2",
    "choices": [{"value": "1-2", "active": true}, {"value": "1-2", "active": true}, {"value": "1-2", "active": true}]
}

**Comment by n1207n** [comment]
~ Technical notes ~

1. Data model changes to Disaggregation and DisaggregationValue models to be linked under ResponsePlan. (For IP-Reporting, it's TBD. We may wanna keep the legacy models if deemed)

2. We need a new backend REST API for grabbing disaggregation info when creating cluster indicator.

3. Frontend changes to create a dedicated tab page for Disaggregation for Response plan. ADD DISAGGREAGTION modal. Lastly, a change to ADD INDICATOR in cluster portal for disaggregation.

**Comment by chachra** [comment]
@eglital backend all in place. I stubbed out the disaggregation tab as well (clone of cluster objective for now). It needs its own elements, no filtering and only creation/list view (no edit needed). with pagination ideally, not 100% needed since its not going to be long list. Eg. url locally (your codes / id's might be different): http://127.0.0.1:8080/app/AO/cluster-reporting/plan/1/response-parameters/clusters/disaggregations
