### ISSUE TITLE
Locations features for PRP

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#248]
- [x] Investigate and repurpose locations model from eTools

- [x] Investigate and choose mapping tool for use in analysis tab

- [x] Intervention should have many CartoDBTable and GatewayType and Locations

- [x] Add numeric admin_level field in gateway model and include in django admin interface for location type creation (dropdown limited to 1-10)

@chachra had a call with @n1207n and thought best to dedicate time to look into this

linked to #265 

~ Notes from requirements session with Silin/Kidus ~

* Restrictions to place on Carto datasets:
  * Need the following columns: pcode & name of location, (optional) pcode of parent location,
 (optional if parent pcode not added) Name if parent dataset
  * Following dataset column names are standard to the following
    * **name:** name of location 
    * **pcode:** pcode of location
    *  **parent_pcode:** pcode of location
  * Shape files should have a verified set of location data (polygon or point locations)
  * **Import should fail if above restrictions are not met**
* Updates of existing locations (typical “real life” scenarios)
  * Name of a location changes
    * Check pcode
    * If name is different, archive current location
    * Import location with new name from carto
  * Location is removed
    * Filter location by intervention & cartodbtable
    * Compare pcodes between new carto dataset and filtered locations
    * Archive locations with pcodes ONLY existing in the locations list
  * New pcode is added
    * Check if pcode exists 
    * If not, add it
* Validations to incorporate in all creation and updates
  * Always update everything except for name and pcode 
  * Only 1 unique ACTIVE pcode per intervention
  * If  parent pcode exists, validate if that pcode exists and is not archived in the parent cartodbtable

To check on:
* Carto api account might need to be organization-enabled to utilize DatasetManager

**Comment by n1207n** [comment]
For possible Polymer component to render a map with polygon: https://github.com/prtksxna/leaflet-map-component

**Comment by kasfaw** [comment]
@n1207n can you update status of this issue?

**Comment by n1207n** [comment]
PR #277 can be merged to get all the model changes. But, CartoDB sync branch has not been updated yet.

**Comment by kasfaw** [comment]
@n1207n seems like there is a conflict on the branch 

<<<<<<< refactor-location-features-248
    GatewayTypeFactory,
    CartoDBTableFactory,
=======
    PersonFactory,
>>>>>>> develop
