### ISSUE TITLE
Integrate with new access / identity management solution

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#25]
This solution should allow partners and unicef staff (IMO / PO's etc.) to login to PRP.

Details TBD.

**Comment by chachra** [comment]
@robertavram @ewheeler - any status update on this front?

**Comment by n1207n** [comment]
Think we can close this as ID management spec is in progress and we have AD in place on PRP codebase. We are going to create a new ticket for ID management anyways.
