### ISSUE TITLE
IP Reporting: Generate PDF of Annex C Part 2 for Submitted Progress Reports

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#256]
Clicking "Export" link in the below mockup should generate PDF of Annex C Part 2.

Mockup: https://projects.invisionapp.com/share/RDBE0T04F#/screens/231338351
Template: https://docs.google.com/document/d/1k1Q7S9GQ-Rx8_X_kykfxxucu2Nz9RTCiQUTnQqNfT_A/edit# 
JSON Schema from PMP: https://docs.google.com/document/d/1bvUAmNn8PbcWky8c7QWPaud-HRwvzOhvScA1nu2yFbo/edit
Data Mockup: https://www.lucidchart.com/documents/edit/a2252dd9-afde-4cf0-8dcd-2e3579cf44b5#
Example document: https://drive.google.com/open?id=0B8ZakJ9uPDhhUGFZUVpXSmU1TFk 

**Technical note**
API endpoint is needed the frontend can call for a specific progress report id.

Example: /api/progress-report/56/annex-C-export-PDF/

Please review github.com/unicef/etools and what PDF libraries are used to get started to put this in place asap / start dev. work. Even if 100% of the data is not there, lets please get the basic format / data PRP has in place to get this done.

Since only totals are in this export for a progress report for a reporting period, it basically is the total in the indicatorReport model or total {} key in the data of location data, as the case may be.

**Comment by dfryta** [comment]
Couple questions here:

1. JSON Schema from PMP - what is use of this? Data for PDF is not stored in DB?
2. Data Mockup - I do not have privileges to show this I think - it redirects me to LucidChart dashboard.

I did a etools review and reportlab was used there. I'll use exactly same here, starting from blank PDF template and then ask couple more questions about data itself.

**Comment by dfryta** [comment]
Oh... there are also django-easy-pdf and xhtml2pdf! Will choose whatever suits best.

**Comment by kasfaw** [comment]
Hey @dfryta - you can ignore the data model link. It was a precursor for buildings out the JSON spec

The first page of the PDF is coming mostly from PMP (a separate system in eTools). I built the json spec so that UNICEF can serve as an API to collect data we need for each programme document. 

I believe we plan to store all of this in PRP db (is that correct @n1207n ?) 

Let me know if you have anymore questions!

**Comment by dfryta** [comment]
@rkrupinski `feature-generate-pdf-#256`

**Comment by dfryta** [comment]
@kasfaw So, I've analyzed this feature and if data for PDF comes from external project we have to build this in safe way (to avoid possible http timeouts).

My idea discussed with Rafał is API endpoint (as you requested) that will return dynamic link (with hash) to generated PDF. If PDF is ready, we will return it with 200 status code. If not, 404 (or any other) status appears. Hash link is valid only till first download.

This approach will eliminate possible timeouts (in case of 3rd party API failure or long response time) and provide best user feedback (Rafał can prepare "in progress" icon or anything else).

Let me know if you are OK with such a solution or I should do it in quick mode believing that all data will be in PRP db.

**Comment by chachra** [comment]
Lets not confuse this task with #17 or with any API PMP needs to implement (filed in etools repo).

**Comment by chachra** [comment]
django-easy-pdf and xhtml2pdf are fine... please use what etools already uses unless these are better or new.

**Comment by kasfaw** [comment]
@chachra @dfryta correct, pdf should be generated in real time

**Comment by dfryta** [comment]
Yup, added same pdf now. Now preparing this magic table ;-) Tomorrow should be done.

**Comment by dfryta** [comment]
@kasfaw Could you please describe second section data. It seems like data is looped by Programme Outputs*, that might have n indicators (rows). Is this correct?

**Comment by kasfaw** [comment]
@dfryta yes, there are n indicators per output (called lower level outputs in prp i believe) and there are n outputs per report

**Comment by dfryta** [comment]
[report.pdf](https://github.com/unicef/etools-partner-reporting-portal/files/1229536/report.pdf)
@kasfaw Please take a look on PDF and let me know if this looks good. I will update with real values tomorrow. Thanks!

**Comment by kasfaw** [comment]
looks good @dfryta ! Do you mind adding 2 outputs and 3 indicators per output to see how multiple values show up?

**Comment by kasfaw** [comment]
Super @dfryta ! One last feedback. On page 2, overall status and narrative columns should be 1 per output (not indicator)

**Comment by dfryta** [comment]
Got it! Thanks for review!
[report_3.pdf](https://github.com/unicef/etools-partner-reporting-portal/files/1229683/report_3.pdf)

**Comment by kasfaw** [comment]
One more fix @dfryta :) Narrative assessment column (the last column) is also 1 per output

**Comment by kasfaw** [comment]
hey @dfryta 2 (hopefully last) changes after reviewing this with unicef:

- the page for the 2nd table should be in landscape orientation 
- Narrative assessment column (the last column) is also 1 per output

i will also send you live examples we can use for the demo

**Comment by dfryta** [comment]
@kasfaw there will be a problem with landscape orientation with only one page. Is this super important?

**Comment by kasfaw** [comment]
@dfryta no not an issue. we should keep all pages in landscape in this case.

**Comment by dfryta** [comment]
Awesome! I can do this ;)

**Comment by dfryta** [comment]
@chachra @kasfaw PDF is completed. Since lack of relations, all partner information are hardcoded as we talked Kidus. 

Please review and let me know if I should make any other enhancements. If is OK now, we can close this issue.

[report.pdf](https://github.com/unicef/etools-partner-reporting-portal/files/1232573/report.pdf)

**Comment by rkrupinski** [comment]
Moving to CR.

**Comment by chachra** [comment]
Lets make sure we've tested with 2-3 outputs and few indicators... more complex PD basically. Other than that looks great.

**Comment by dfryta** [comment]
@rkrupinski I found issue with pdf link. It seems we provide wrong ID. Let us talk tomorrow.

**Comment by dfryta** [comment]
@rkrupinski still open - link for export should use ProgressReport ID not Indicator ID. Let talk tomorrow.
