### ISSUE TITLE
Allow user to view profile and logout with the top right dropdown

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#26]
UI can be similar to how eTools does it: 
![dashboard](https://user-images.githubusercontent.com/73096/31073560-4f1cf8b0-a764-11e7-917c-a410672ddcc2.png)

- Will kick user to login screen if user clicks logout.

- If they click "profile" then can show in a modal, basic profile details like name, email, and their "group" (role) in the PRP project.

- Edit profile not needed.

- Please test / make sure working for both cluster and IP reporting.

**technical notes**
To show the profile users profile details will be available via an API

- /api/account/user-profile/

- api/account/user-logout/

- Please call a reset action on the redux store as well.

- Etools uses this component: https://github.com/unicef-polymer/etools-profile-dropdown

**Comment by chachra** [comment]
@kasfaw can you please validate/review this ticket.

**Comment by chachra** [comment]
@eglital branch for this is user-profile-logout-26 and has the API's ready to integrate with.

**Comment by kasfaw** [comment]
@chachra makes sense. Lets go with modal on profile since that is how rest of etools has it.
