### ISSUE TITLE
ProgrammeDocument data model update

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#260]
In preparation for PD sync API from PMP, we need to evaluate current database attributes before integrating with PMP.

Kidus pointed out that there are some fields to be removed due to irrelevancy.

1. Remove `response_to_HRP` and `administrative_level` fields

2. Make `unicef_officers`, `unicef_focal_point`, `partner_focal_point` fields to be able to save multiple values. (PostgreSQL ArrayField)

3. Add any missing fields from this JSON spec: https://docs.google.com/document/d/1bvUAmNn8PbcWky8c7QWPaud-HRwvzOhvScA1nu2yFbo/edit

**Comment by dfryta** [comment]
unicef_focal_point and partner_focal_point already exist. Will update their type to ArrayField.

**Comment by dfryta** [comment]
From JSON spec, officers, focal_points stores more information:
`"auth_officer": [{
        "name": "john smith",
        "title": "chairman",
        "phone_num": "+1-251-111-5555",
        "email": "abc @org.com"
      },
      {
        "name": "jane scott",
        "title": "president",
        "phone_num": "+1-251-555-1111",
        "email": "xyc @org.com"
      }
]`
Do we want to rebuild current model and  switch ArrayField into M2M fields? Or store only name?

**Comment by dfryta** [comment]
@kasfaw we are also missing org_name, org_acnym and currencies. Shall I add them also?

**Comment by kasfaw** [comment]
yes. Please add anything missing from the JSON spec.

**Comment by kasfaw** [comment]
@dfryta on auth_officer  and focal_points, we would need all fields (for pdf export you built here #256) rebuilding might make sense

**Comment by dfryta** [comment]
@rkrupinski please update frontend after changes. Focal points are now objects Person (name, title, phone_number and email). You should have them already in API response.

![etools-partner-reporting-portal.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599ea4b9f8cd181455aa3f82/125516c66e82c728ace21e0d46ed80952c8e90e49fe8ad57aa58e2d93b43377c3b10aa2577c8f327ad567a0d4d435cec03070511afbd9b21b4b33423dc5408b8d16e597d953c14acb88b1dba06bc27894997aaaec81d9ebc6278bec1da0d2c1417198ef55c30a09d4ac059ff42e64c57a1017b.png)

**Comment by dfryta** [comment]
@kasfaw Done from my side.
