### ISSUE TITLE
Response Parameters / My Planned Action routing glitch

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#262]
There's one irritating side effect of how routing is implemented within `Response Parameters` & `My Planned Action` trees. Since part of the routing is done asynchronously and scheduled tasks are not cancelled upon navigating away, we end up redirecting to pages that don't exist:

See:

https://drive.google.com/file/d/0BxDYQDDFAykYdzBkTDlCQ3d3SDQ/view?usp=sharing

and:

https://drive.google.com/file/d/0BxDYQDDFAykYRmdSdGM4QjgzNlU/view?usp=sharing

**Comment by kasfaw** [comment]
doesnt seem to be issue anymore?
