### ISSUE TITLE
CartoDB sync command and a first complete dev DB dump

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#265]
The goal for this ticket is to create a management command which would load data from CartoDB API as well as creating a first dev-purpose full db dump in order to reduce fake data task time.

This is the key preparation to Indicator Import/Export and upcoming Cluster Analysis features.

~ Technical notes ~
1. Re-enable GIS database fields and sync any missing database fields from PMP.
2. Install cartodb Python package and create a management command to sync Location data for existing countries.
3. Create a full db dump with fake data and CartoDB location data and share with the rest of the team.

**Comment by n1207n** [comment]
Blocked until #248 is done and merged.

**Comment by kasfaw** [comment]
@n1207n see my comment on #248 - can you update if still blocked?

**Comment by n1207n** [comment]
Updating CartoDB sync command with model changes from #277 is not a huge task. However, we need some CartoDB test dataset in order to test out the sync command. This is kinda blocker for this issue.

**Comment by kasfaw** [comment]
cool @n1207n  - ive put location datasets for 3 countries (Haiti, Pakistan, Mali) in clusterprp.carto.com
