### ISSUE TITLE
Differences between indicator reports on Results screens in edit and view mode (Cluster)

### ISSUE THREAD

**Issue by kasialanecka** [unicef/etools-partner-reporting-portal#268]
**# Draft/Due Reports** - this is a screen where Partner can enter data and submit a report

The whole screen contains:
- **buttons for export/import**

Each indicator report contains:
- **report status with due date**
- reporting period
- project title
- activity title
- **submit button / draft label**
- indicator title with target, total progress, achievement in reporting period
- new area **in edit mode** with: overall status, narrative assessment and attachment (waiting for confirmation which UI to follow)
- location tabs **with ability to enter data** - label above tabs added

**# Submitted reports** - this is a screen where Partner can view submitted reports

The whole screen contains:
- **button for export all reports**

Each indicator report contains:
- **submission date**
- reporting period
- project title
- activity title
- **export button**
- indicator title with target, total progress, achievement in reporting period
- new area **in view mode** with: overall status, narrative assessment and attachment (waiting for confirmation which UI to follow)
- location tabs **in view mode** - label above tabs added

@kasfaw please confirm the list, differences are marked

**Comment by kasfaw** [comment]
@kasialanecka @rkrupinski all good. export button should be exporting according to applied filters fyi.

**Comment by rkrupinski** [comment]
Requires #243

**Comment by kasfaw** [comment]
@rkrupinski assuming not blocked anymore?

**Comment by rkrupinski** [comment]
@kasfaw  Kinda blocked until #243 is merged. I'm simply gonna merge it to my branch locally for now.

**Comment by kasfaw** [comment]
Ok. Sounds good.

**Comment by rkrupinski** [comment]
The export button part requires #256

**Comment by rkrupinski** [comment]
@dfryta Can we export a single report yet?

**Comment by dfryta** [comment]
@rkrupinski added partner_activity and fixed project field also. Single report export will be in #256

**Comment by dfryta** [comment]
Team, I was able to fix Cluster filtering #289 and added filtering excel generation #88 plus also added possibility to export only one indicator as requested in #268. All changes are on #88 branch.

**Comment by rkrupinski** [comment]
@kasfaw Closing this as all the outstanding items (e.g. exporting) are being tracked in separate tickets.
