### ISSUE TITLE
Cluster Reporting: Ability to import from excel template

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#269]
Breaking out import and export tasks.

Related to: https://github.com/unicef/etools-partner-reporting-portal/issues/88

Specifications here: https://docs.google.com/spreadsheets/d/1JhM7yqcSJtRE6iGJGSuObEOadhk6Y0r6RRQupee4mXQ/edit#gid=0

**Comment by dfryta** [comment]
Thanks!

**Comment by chachra** [comment]
@dfryta this is being moved to post v1.0, so future task.

**Comment by dfryta** [comment]
Sounds good, thanks!

**Comment by n1207n** [comment]
Think this is implemented and was tracked as a new ticket sometimes in the past. Closing.
