### ISSUE TITLE
Test interface in low bandwidth situations

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#275]
Can leverage Chrome network tab to simulate.

- [ ]

**Comment by eglital** [comment]
@chachra what exactly speed should I test it on? 1 Mb/s or even lower than that?

**Comment by eglital** [comment]
there is also fast 3G or slow 3G options

**Comment by n1207n** [comment]
@eglital, it's safe to assume that some of the field officers may have 3G-like connections. Test both of the connections to start with.

**Comment by chachra** [comment]
@eglital what Silin said. Don't spend a ton of time on this, just some initial testing / results if you can present.

@rkrupinski one thing am noticing is in low bandwidth its better if all the clicks (tabs and such) loaded frontend resources immediately and only data loading (api calls) took time. I know you had mentioned loading one section and time was optimized so initial load is faster, but curious how to best handle.

@n1207n the polymer build task... will that have a positive impact here as well?

**Comment by rkrupinski** [comment]
@chachra It's always initial load time vs. post-action (click, etc) load time. Given the app will be used in the field, I'd rather load the top-level routes asynchronously, as we do now. I'm open to suggestions though.

**Comment by chachra** [comment]
Sure. Question is waiting for initial load to be slow and then clicking around be quicker is better or what we have currently. On the airplane slow internet loading everything to give me quicker clicking around seemed better (desktop / native app experience).

Anyways just food for thought for now... how easy is it to achieve?

**Comment by rkrupinski** [comment]
Easy. The question is whether we'd actually like to achieve it. I'd say no. Based on current best practices (which in turn emerged out of popular use cases), lazy-loading routes is the way to go.

**Comment by eglital** [comment]
So I understood things will change here, but the thing that is really noticeable with slower speed:
if you are in response parameters (clusters or partners), change Cluster filter and then navigate between clusters-partners etc, first it loads the full list, only then cluster filter at top right appears and list loads again with now correct info

**Comment by eglital** [comment]
Some initial testing as talked about.
**Fast 3G, cluster reporting:**
Initial loading to get response plan selection screen - 20sec, after selecting the plan, 17sec to load dashboard, after that 11sec to load response parameters, going between tabs is fairly quick - 1-2sec, results tab takes about 5sec to load, filtering is quick - 1-2sec. After changing the workspace takes about 25sec to get response plan selection screen.
**Slow 3G, cluster reporting:**
Initial loading to get response plan selection screen - 1.2min, after selecting the plan, 45sec to load dashboard, after that 35sec to load response parameters, going between tabs first time - 5-8sec, results tab takes about 12sec to load, filtering - 3-5sec. After changing the workspace takes about 1.3min to get response plan selection screen.
**Fast 3G, ip reporting:**
24sec to load overview, programme documents loaded in 8sec, filtering is quick -1-2sec, progress reports - 7sec, filtering is quick - 1-2sec, indicators - 7sec
**Slow 3G, ip reporting:**
1.4min to load overview, programme documents loaded in 25sec, filtering is -3-4sec, progress reports - 20sec, filtering - 4-5sec, indicators - 27sec
