### ISSUE TITLE
Email notifications from PRP

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#276]
- [x] Notify partner via email when progress report or indicator reporting is accepted or sent back

- [x] Notify new user when they are added to the system with PRP link.

When the status of a progress report changes to either `accepted` (for PR only) or `sent_back` (for IR or PR) an email should be sent to the `officer_programme_documents` with the email template below:

**If accepted**
> Dear {name of `officer_programme_documents`},
>
> Your progress report {url to progress report} for {`pd_ref_title`} has been Accepted by UNICEF.
>
> Best Regards,
> Partner Reporting Portal

**If Sent Back**
> Dear {name of `officer_programme_documents`},
>
> Your progress report {url to progress report} for {`pd_ref_title`} has been Sent Back for Revision by UNICEF. Please make the necessary changes and resubmit this report.
>
> Best Regards,
> Partner Reporting Portal

**Technical note**
Can be done as a django signal. The status of a progress report will flip for the most part because of PRP syncing the report status from PMP.

**Comment by sethgold8** [comment]
@n1207n it is still relevant

**Comment by sethgold8** [comment]
Let's add 

- [ ] progress report or indicator reporting  submitted
