### ISSUE TITLE
Cluster Analysis: group reported locations by the same admin level in filter

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#278]
When an IMO views the list of reported locations on the below screens, the list of locations should be grouped by the same admin level. This would require **adding a admin selection dropdown** and logic to determine, group and calculate progress at a specific admin level dynamically.

- [ ] make default `Location Type` filter Admin 1
- [ ] https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533939
- [ ] https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/247611383

This would effect both Cluster and IP reporting in PRP.

**Comment by chachra** [comment]
Dupe / not relevant per new specs on cluster analysis.
