### ISSUE TITLE
Single PD, "Details" tab screen in IP reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#28]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016131

User can see Details of a PD at /pd/$id/overview/

**Comment by lkolacz** [comment]
@ErinOC common branch for this task is `feature-Single-PD-#28`
when I start working on it I will give You more details like endpoint url and what data does it contain.

**Comment by lkolacz** [comment]
@ErinOC ... You should except from me fields like:
```
        fields = (
            'id',
            'agreement',
            'document_type',
            'reference_number',
            'title',
            'unicef_office',
            'unicef_focal_point',
            'partner_focal_point',
            'response_to_HRP',
            'start_date',
            'end_date',
            'population_focus',
        )
```
I'll be more specific by giving You url and JSON response in a next comment ;-) (when I'll be done with it)

**Comment by lkolacz** [comment]
@ErinOC 
for just now the url looks like this 
`http://localhost:8080/api/unicef/programme-document/details/111/`
and will return JSON for pk = 111
```
{
    "id": 111,
    "agreement": "JOR/PCA20172",
    "document_type": "Programme Document",
    "reference_number": "reference_number_2",
    "title": "programme_document_2",
    "unicef_office": "JCO country programme 2",
    "unicef_focal_point": "Abdallah Yakhola 2",
    "partner_focal_point": "Hanin Odeh 2",
    "response_to_HRP": "response_to_HRP2",
    "start_date": "2017-05-24",
    "end_date": "2017-08-02",
    "population_focus": "Population 2"
}
```
this url will change because I remember that Sumit what's to have urls that contain country intervention os something .. I need to check :)

**Comment by adamtlord** [comment]
@rkrupinski This may not be complete, but I'm at the point of needing feedback, please.

**Comment by adamtlord** [comment]
This was resolved in https://github.com/unicef/etools-partner-reporting-portal/pull/66
