### ISSUE TITLE
Feature - A public API endpoint for Cluster indicator list

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#285]
For the incoming PMP<->PRP integration process, PRP needs to expose a new private API for PMP to consume regarding cluster indicator info.

This API endpoint needs a Cluster ID in the URL pattern to return a list of Cluster indicators in that Cluster.

This API endpoint needs to be able to accept filtering by the followings as GET parameters:
* Reportable ID

Sample API response payload:
```
[{
    "id": 123,
    "title": "My Indicator 123",
    "baseline": 34,
    "target": 123,
    "means_of_verification": "My means of verification",
    "locations": ["pcode1", "pcode2", "pcode3"],
    "disaggregation": [
        {
           "name":"Age" ,
           "values": ['0-1','1-2']
        },
        {
           "name":"Gender" ,
           "values": ['M','F','O']
        },
    ],
}]
```

**Comment by chachra** [comment]
@robertavram does this work? If yes, then this is the API format that should get you the information (and more) back.

/api/indicator/ca/?clusters=1

ca = cluster objective (co, pp, pa, llo being other valid options). clusters=1 filters the data... then the results are list of reportables, with blueprint and all disaggregation information in them as well.


`{
            "id": 2,
            "target": "5000",
            "baseline": "0",
            "blueprint": {
                "id": 2,
                "title": "quantity_indicator_1",
                "unit": "number",
                "display_type": "number",
                "calculation_formula_across_periods": "max",
                "calculation_formula_across_locations": "sum"
            },
            "ref_num": "",
            "achieved": {
                "c": 2894,
                "d": 1,
                "v": 2894
            },
            "progress_percentage": 0.5788,
            "content_type_name": "cluster objective",
            "content_object_title": "1 - workspace_0 2017 Humanitarian Response Plan - WASH CO",
            "object_id": 2,
            "disaggregations": [
                {
                    "id": 6,
                    "name": "height",
                    "active": true,
                    "response_plan": 1,
                    "choices": [
                        {
                            "id": 23,
                            "value": "tall",
                            "active": true
                        },
                        {
                            "id": 24,
                            "value": "medium",
                            "active": true
                        },
                        {
                            "id": 25,
                            "value": "short",
                            "active": true
                        },
                        {
                            "id": 26,
                            "value": "extrashort",
                            "active": true
                        }
                    ]
                }
            ]
        },`
