### ISSUE TITLE
Filtering issues with Results list

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#289]
used the following to test: https://etools-test.unicef.org/app/PK/cluster-reporting/plan/33/results/draft?page_size=10&page=1&cluster=66 @dfryta let me know if any other observed issues exist

- [x] list of locations not reflective of available locations in indicator reports (eg: location_0 and location_1 available for an quantity_indicator_67 but only location_200 available for selection in filter)

- [x] selecting an indicator does not filter list properly (eg: filtered by quantity_indicator_67, but no results show)

- [x] project filter has no available options for filtering

- [x] partner filter has no available options for filtering

**Comment by rkrupinski** [comment]
@kasfaw @dfryta 

For the following permalink:

`/app/PK/cluster-reporting/plan/33/results/draft?page_size=10&page=1&cluster=66`

the request url is:

`/api/cluster/33/cluster-indicators-list/?page_size=10&page=1&cluster=66&submitted=0`

Does the url and the query string parameters match the api?

**Comment by dfryta** [comment]
I'm fixing this in #88. All filters need to be rebuild.

**Comment by dfryta** [comment]
All filters fixed. Next step - proper filters dropbox content.

**Comment by dfryta** [comment]
@rkrupinski @kasfaw In #88 Created new endpoint for list of cluster indicators:
`api/cluster/<response_plan_id>/cluster-indicators-locations/`
Old one was pointing response plan locations.

**Comment by rkrupinski** [comment]
On it

**Comment by chachra** [comment]
Is this ticket done?

**Comment by rkrupinski** [comment]
Yep, I guess. Just tested everything.

**Comment by chachra** [comment]
cool.
