### ISSUE TITLE
API url changes / misc. other

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#291]
- [ ] one of the fields is called "outputs" when it really is indicators
- [ ] the name of the API's might not be the best as well, so re-clarify / change in frontend as well.

- [x] Progress Reports : This view should show you all progress reports belongs to logged partner.  All API urls are based on location ID rather then partner ID Example: `api/unicef/<location_id>/progress-reports/`

- [x] Programme Documents:  When you go to Reports page, it should show you all Progress Reports assigned to given PD. Instead we hit: 
`api/indicator/programme-document/details/<pd_id>/reports/ `
That returns Indicator Reports not Progress Reports

- [x]  Programme Documents: Details Url is wrong. It points to Indicator Report `/api/indicator/programmedocument/details/<pd_id>/reports/<report_id>/ `

- [x] Rename IndicatorListCreateAPIView and make it extend just List view since its just list not creation at all.

- [x] Rename ClusterIndicatorsListAPIView to reflect what it actually returns which is IndicatorReport's in the cluster context.

**Comment by dfryta** [comment]
1. Progress Reports 
This view should show you all progress reports belongs to logged partner. 
All API urls are based on location ID rather then partner ID Example: `api/unicef/<location_id>/progress-reports/`

2. Programme Documents
 When you go to Reports page, it should show you all Progress Reports assigned to given PD. Instead we hit: 
`api/indicator/programme-document/details/<pd_id>/reports/ `
That returns Indicator Reports not Progress Reports

3. Programme Documents
Details Url is wrong. It points to Indicator Report `/api/indicator/programmedocument/details/<pd_id>/reports/<report_id>/ `

**Comment by kasfaw** [comment]
bundled dariusz comment and task #235 into one checklist above for ease of tracking. closing #235

**Comment by dfryta** [comment]
At IP Portal change:
[] remove PD Location from PD tab, rename PD Location filter to Location in PR and Indicator tabs
[] create API endpoint for getting all indicators for PDs
[] assign above endpoint for Indicator tab
[] create API endpoint for getting all indicator locations for PDs
[] assign above endpoint for Indicator / PR tab in Location filter

**Comment by dfryta** [comment]
@rkrupinski endpoints for getting filters data:
- `/api/unicef/<workspace_id>/programme-document/indicators/`
- `/api/unicef/<workspace_id>/programme-document/locations/`
