### ISSUE TITLE
IP Reporting: Permission specifications for roles and interpreting them in the frontend and backend API's

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#294]
IP Authorized Officer -   This is the person we have added in PMP as Authorized Officer (as per PCA). This person should have the permissions to view/add/edit/import/export data and submit reports in PRP

IP Editor -            This person can view/add/edit/import/export reports in PRP but cannot submit reports

IP Viewer -          This person can only view and export data from PRP

Available Actions  | IP Authorized Officer | IP Editor | IP Viewer
-- | -- | -- | --
[View Progress Report](https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016132) | x  | x  | x 
[Go to Draft of Progress Report](https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016132)  | x  | x  | x
[Enter Data for a Progress Report](https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016132)  | x  | x  | 
[Download Annex C Part A PDF of a Submitted Progress Report](https://projects.invisionapp.com/share/RDBE0T04F#/screens/231338351)  | x  | x  | x
[Show PD/SSFA Details](https://projects.invisionapp.com/share/RDBE0T04F#/screens/231338351)  | x  | x  | x
[Save a Draft/Sent Back Progress Report](https://projects.invisionapp.com/share/RDBE0T04F#/screens/231338349)  | x  | x  | 
[Download Annex C Part A PDF of a Draft Progress Report](https://projects.invisionapp.com/share/RDBE0T04F#/screens/231677538)  | x  | x  | 
[Upload a Draft/Sent Back Progress Report (when feature available)](https://projects.invisionapp.com/share/RDBE0T04F#/screens/231677538)  | x  | x  | 
[Submit a Draft/Sent Back Progress Report (when feature available)](https://projects.invisionapp.com/share/RDBE0T04F#/screens/231677538)  | x  |   | 
[Change the Calculation Method for a Programme Document](https://github.com/unicef/etools-partner-reporting-portal/issues/214)  | x  | x  |

**Comment by chachra** [comment]
@kasfaw can we followup on status of this. Its been outstanding for a while.... it'll be a challenge doing too many if/else customizations if this matrix is made too complex for MVP.

**Comment by rkrupinski** [comment]
@chachra @kasfaw Looking at the matrix, the permission levels are roughly:

Can view < Can also edit < Can also submit

Implementation-wise, storing a role instead of a super-granular set of booleans seems like a better idea, at first glance.

**Comment by chachra** [comment]
My worry is if it gets complicated over time. If it won't be an issue, then all good I guess... 3 roles and frontend interprets them appropriately. In short-term this can work...

In backend usually permission checks (not group checks) are done..... hence to me permissions seemed like the best thing to align on and make sure back/frontend are not interpreting groups differently if it makes sense.

**Comment by rkrupinski** [comment]
>  make sure back/frontend are not interpreting groups differently if it makes sense

👍
