### ISSUE TITLE
Cluster UI  logic to respect role / permissions of user logged in.

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#295]
Define specific permissions of an IMO and Partner user in a response plan similar to #294 

IMO profile user can:
- [x] create cluster objective and its indicators, for their cluster only... other cluster choices should be hidden
- [x] create cluster activity and its indicators for their cluster only, other cluster choices should be hidden
- [x] submit or enter data on any indicator report
- [ ] ~~send back an accepted indicator report (submitted reports in cluster reporting at automatically accepted)~~ tracked in #397 
- [x] if viewing data in another response plan whose clusters are not in "imo_clusters" in their profile then don't show any buttons to add co / add ca or buttons to submit or accept indicator reports. they are in a sense a viewer in those response plans.
- [x] Should not see the "my planned action" tab in the left hand nav.

Partner editor can
- [x] Cannot add new cluster objectives or its indicators or cluster activities or their indicators etc.
- [x] can enter data for indicator reports belonging to their partner only.

Partner authorized officer can
- [x] all above for partner editor
- [x] can submit their reports only. cannot submit reports that do not belong to their own partner.
- [x] Create partner projects or partner activities and indicators for them. Partner editor should not be able to. So hide those create buttons from editors and only show for authorized officers.

Partner viewer
- [x] can view all the data

**Comment by chachra** [comment]
@kasfaw should we take a first stab at it and have business owners review/approve asap? I think high-level IMO, Partner Authorized Officer, Partner Editor, Viewer (could be partner or agency or...)

So in effect only 1 new role as such, would be good to align IP and Cluster a bit, for both backend and front-end ease.

**Comment by kasfaw** [comment]
@chachra gavin and Jean in NYC this week to do this. Maybe dup effort? I can reach out if they need help. Their current thinking is having an IMO and Partner Editor group but can foresee need for a group (CC?) that has Django admin rights to set up response plan etc (that can be directly configed in Django admin)

**Comment by rkrupinski** [comment]
> send back an accepted indicator report

@chachra I don't recall any UI for sending reports back.

**Comment by rkrupinski** [comment]
> IMO profile user can:
> - submit or enter data on any indicator report
> - [...]
> - if viewing data in another response plan whose clusters are not in "imo_clusters" in their profile then don't show any buttons to add co / add ca or buttons to submit or accept indicator reports. they are in a sense a viewer in those response plans.

@chachra Doesn't that boil down to:

"can only edit & submit indicator reports **for their cluster only**"?
