### ISSUE TITLE
Change Fields in Interventions

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#297]
Current Interventions model has components of a programme document. This model is a specification of a PRP workspace and should be similar to eTools' country model: https://github.com/unicef/etools/blob/master/EquiTrack/users/models.py

Suggest we do the following:
- [x] remove all fields except for `title` and `country_code`
- [x] make `country_code` multiselect
- [x] add `business_area_code` field (similar to etools)
- [x] add map configuration fields (similar to /EquiTrack/users/models.py): `latitude` `longitude` `initial_zoom`

**Comment by chachra** [comment]
We went with adding Country model, same as etools so country_code, business_area_code field, llatitude longitude initial_zoom are on that model.

Workspace has now many countries and many locations, and we'll validate that these locations belong to the countries. Cool ?

Also made Cartodbtable point to Country, so 1 country can have many of them?

**Comment by kasfaw** [comment]
@chachra great on all fronts!
