### ISSUE TITLE
Be able to enter progress report narrative section

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#30]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016143

PUT request will update the data. Allowed only if progress report is NOT IN submitted status.

Ignore file upload for this task. To be done in #130

Lower level output narrative is captured here: #79 - not to be confused with this task.

**Comment by lkolacz** [comment]
branch name `feature-narrative-section-#30`
