### ISSUE TITLE
Reassociation between Location and Reportable

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#301]
- [x] remove `location` from `reportable`

- [x] add FK to multiple `location` in `reportable`

**Comment by n1207n** [comment]
@kasfaw, if you're referring one Reportable having many Locations, this relationship is already captured by having reportable Foreignkey field in Location model.

If you're referring Reportable <-> Location should be Many-To-Many field, then I can make a change for real quick.

**Comment by n1207n** [comment]
I checked the latest data model and it seems Many-to-Many field. I have made a DB migration change. Will make a PR now.

**Comment by kasfaw** [comment]
@n1207n yes it should be M2M. This should be defined on the reportable model and not in the locations model. 

Perhaps @chachra can explain further?
