### ISSUE TITLE
Be able to see PD / SSFA TOR details in a modal while entering report data

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#31]
When viewing a progress report, clicking the "Show PD/SSFA ToR Details" button should result in a modal with details as shown here: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016133

**Comment by chachra** [comment]
@robertavram thoughts on this? https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016133/comments/81058448

CC @mpawlowski85

**Comment by kasfaw** [comment]
@robertavram @mpawlowski85 @ewheeler Mind confirming our open question here?

**Comment by mpawlowski85** [comment]
The ability for the IP to download the PD attachment is a business requirement. It is a joint reference document that should be available for the Implementing Partner to view.

**Comment by kasfaw** [comment]
Thanks for confirming @mpawlowski85

**Comment by chachra** [comment]
This task is done, #83 tracks the file issue.
