### ISSUE TITLE
Generating the location_admin_refs field

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#311]
** Maybe location_admin_refs belong in `Location` model...tbd**

If we had 3 locations: LocA , LocB and LocC 
* LocA has `p_code='123ABC'` and `gateway = {title: 'Region', admin_level: 1, parent: Null)
* LocB has `p_code='328BAD'` and `gateway = {title: 'County', admin_level: 2, parent: FK(LocA))
* LocC has `p_code='836WHO'` and `gateway = {title: 'City', admin_level: 3, parent: FK(LocB))

Then the `location_admin_refs` field of each location would look like:
* LocA: `{"adm1": {"name": "LocA", "pcode": "123ABC"},"adm2": {"name": "", "pcode": ""},"adm3": {"name": "", "pcode": ""},"adm4": {"name": "", "pcode": ""},"adm5": {"name": "", "pcode": ""}}`
* LocB: `{"adm1": {"name": "LocA", "pcode": "123ABC"},"adm2": {"name": "LocB", "pcode": "328BAD"},"adm3": {"name": "", "pcode": ""},"adm4": {"name": "", "pcode": ""},"adm5": {"name": "", "pcode": ""}}`
* LocC: `{"adm1": {"name": "LocA", "pcode": "123ABC"},"adm2": {"name": "LocB", "pcode": "328BAD"},"adm3": {"name": "LocC", "pcode": "836WHO"},"adm4": {"name": "", "pcode": ""},"adm5": {"name": "", "pcode": ""}}`

**Comment by dfryta** [comment]
@chachra why we have to add this field? Cannot we just simply use Location parent relations?

**Comment by chachra** [comment]
@dfryta not a question for me...

**Comment by dfryta** [comment]
So I will do my way then ;-)
