### ISSUE TITLE
The information within "Narrative" section (progress report) is not persisted.

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#312]
`PUT` `http://localhost:8080/api/indicator/indicator-data/<report_id>/` `200`

**Comment by kasfaw** [comment]
@chachra still not persisting for me.

**Comment by rkrupinski** [comment]
That hasn't been fixed, afaik.

**Comment by dfryta** [comment]
No wonder is not working, since these fields are connected to PR not Indicator, heh.

**Comment by dfryta** [comment]
Fixed. Please use `/api/unicef/<workspace_id>/progress-reports/<progress_report_id>/update/` PUT endpoint

**Comment by rkrupinski** [comment]
Done.
