### ISSUE TITLE
Setup celery worker in docker-compose and on docker cloud

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#315]
For CartoDB sync function, it needs to have a running celery worker instance. Currently, the docker-compose setup doesn't start celery worker although it has the celery and redis containers.

We may have to set up Procfile and systemd startup service when django_api container starts.

**Comment by kasfaw** [comment]
@n1207n just heads up that cartodb syncing should always be a manual action (not automated). not sure if this is related to it...

**Comment by chachra** [comment]
Correct. This is just so celery is up, not actual sync. That happens when carto entries are made in dB.
