### ISSUE TITLE
Reportable Total update when IndicatorReport status is Accepted

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#316]
When the `overall_status=Accepted` for an `IndicatorReport`, update the `total` of the associated `Reportable` based on the calculation method.

**This may simply require simply modifying the `recalculate_reportable_total` receiver and adding a condition that `reportable_total` is only recalculated if `overall_status=Accepted` for the IndicatorReport

**Comment by chachra** [comment]
@kasfaw this is being done now both when being sent back and accepted.

2 followup questions:
- can you clarify what "total cumulative progress:" is meant to show on indicator lists... We're currently showing the progresso on that indicator/reportable when user is viewing it (irrespective of reporting period).
- should we add a "accepted reports" tab in cluster reporting? submitted/due can handle sent back ones just fine I think... although interface for comment from IMO etc. how to handle... not sure I wanna add a "sent back reports" tab as well?

**Comment by kasfaw** [comment]
@chachra 
* "total coumulative progress" is the Reportable's `total` field for that indicator
