### ISSUE TITLE
FE for Disaggregation Selection

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#324]
related to #244

**Comment by chachra** [comment]
@eglital make sure to merge in develop into this branch so you don't have a ton of merge conflicts. can do compose down and up --build again and re-generate the fake data. tx.

**Comment by chachra** [comment]
@eglital which branch is your code in... since "user" is missing, I can add it to api in that branch. Please lmk...

**Comment by chachra** [comment]
remove user column for now... doesn't seem critical in a sense. I'll open a separate ticket for logging purpose to track which user created some of these models like objective, disagg etc. as well.
