### ISSUE TITLE
Misc. IP reporting testing bugs

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#331]
- [x] In all progress report lists, accepted progress reports should not show "enter data" but "view report" (just like submitted ones). https://www.evernote.com/l/AAVpjLfyDItMH676L7uG6m5uSh1NhB78LdA

- [x] Going to progress report edit url when report has been submitted or accepted should redirect to the url for viewing the report.

- [x] Sent back message newlines should be respected in the frontend. Currently lays it out in 1 line on frontend: https://www.evernote.com/l/AAVYuD6IoM1FyLe1e3malqHfk5Sm2Ag2Rg8
- [x] Autosave on progress report fields does not work, including: overall status selection, narrative fields, ~~and all fields in the OTHER INFO fields~~ (tracked in #312)
- [x] Filters on "Reporting on Results" tab of Progress report do not work!
- [x] No validation on Progress Report Submission: all fields should be filled out (status, narrative, other info fields, and indicators - only exception is that indicators with LLO status of Met or No Progress are not required to have data entered.

- [x] Selecting location in progress report filtering seems to return a ton more results than there are reports! Seems a distinct() or something is needed? https://www.evernote.com/l/AAVvcdtJ6YRHk71GN3dDF6eIs_9NdB5uIc8

- [x] Due date filtering on progress report tab might not be what we want it to be. In code.     `def get_due_date(self, queryset, name, value):
        return queryset.filter(due_date=value)`

- [x] Indicators list should be showing list of UNIQUE reportables: http://prp.tivixlabs.com/app/MY/ip-reporting/indicators?page_size=10&page=1&pds=11

- [x] Indicators List not aligned with mockup: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016144
- [x] Progress Reports lists not displaying statuses and icons for Accepted and Sent Back: https://www.evernote.com/shard/s659/sh/2ea18d7e-b30b-41c9-8a96-0c6072411d8a/c3326e3b8dc7efe7ccae6dcb7447e47c AND https://www.evernote.com/shard/s659/sh/fa2c4966-c909-4fb7-b603-7a23918ef790/ea1a2be9624f1b86d29806054b8cf192
- [x] Links in Indicators list should go to PD overview page: https://www.evernote.com/shard/s659/sh/1d032e96-03c8-4656-9aec-94509c78e9da/17889471ff914feb043ee1f4e52fca48
- [x] minor Overview page changes: https://www.evernote.com/shard/s659/sh/b532ed19-9cb6-4e40-a414-4f4cc913b560/7ebd7f226b77005d393e54532c494773

- [x] minor PD list changes: https://www.evernote.com/shard/s659/sh/721793d4-11bd-41f9-a422-a57f0622aec4/94626ef1cd02ed3cf70fa906111455db

- [x] Programme Document details missing Document Type: https://www.evernote.com/shard/s659/sh/ce8baf6c-33c3-4b79-85c6-4e300b59722a/7c44e3d84cc589066f1fdae09176e8d2 AND https://www.evernote.com/shard/s659/nl/177263020/de6afbac-43dd-49d4-976a-027b71ab3140

- [x] Null indicator data should NOT show up as '0'...maybe as '-'? https://www.evernote.com/shard/s659/sh/673b9ef9-1b70-4098-8094-4fdab7cc5a06/44682acd3aba30055b29fafd5fac11ac

- [x] ~~Check if Draft marker works in progress reports lists:~~ https://www.evernote.com/shard/s659/sh/64c108fa-941e-4135-b713-ef84b7e2dfca/7fa9a1ee1649b92d25d0d66c1116327b AND https://www.evernote.com/shard/s659/sh/da7a1202-b9ec-4962-8904-0b39b2ca2de1/9e4dc4df0153e3a39d6d4ac8c94536a2
Reports on both screens have the `is_draft` flag set to `false`. 

- [x] Order Progress Reports list by Due Date (Descending order): http://prp.tivixlabs.com/app/MY/ip-reporting/pd/11/view/reports?page_size=10&page=1 AND http://prp.tivixlabs.com/app/MY/ip-reporting/progress-reports/

- [x] Annex C PDF missing currencies: https://www.evernote.com/shard/s659/sh/b0498303-94dd-4b67-beb7-7bc53a2f3a9a/597f94a44b43d29111117ea251a8e720

- [x] Need to filter Indicators list by Active PDs (this means showing reportables associated to Programme Documents with status='Active'): https://www.evernote.com/shard/s659/sh/4641fb6b-b499-40e8-b514-bb1c47bd3c24/5455b3afe7a79c0e93a84a07184bf36a

- [x] Report Status fields for progress report lists incorrect: https://www.evernote.com/shard/s659/nl/177263020/27dc6fb0-55ea-4ba0-a870-4fa173421b05 AND https://www.evernote.com/shard/s659/nl/177263020/b74eca64-9798-4ece-9b73-1cbb1f18fb91
- [x] Rename "Export" to "Download Annex C Part A": https://www.evernote.com/shard/s659/sh/b0498303-94dd-4b67-beb7-7bc53a2f3a9a/597f94a44b43d29111117ea251a8e720
- [x] Style changes in Calc Method screen: https://www.evernote.com/shard/s659/sh/a31069cf-6814-4cda-bb7b-7b32c52e31c6/098c533d1c7335de2f9c979442c9cb49

**Comment by chachra** [comment]
@kasfaw please add more based on your testing on test site today.

**Comment by kasfaw** [comment]
@chachra will do. Putting IP reporting through the wringer today

**Comment by chachra** [comment]
@kasfaw question for you / file if you know resolution unless already filed: https://www.evernote.com/l/AAXzSrrSZ9FLtLUEbbVSz6MVo5pkCa_Oqu4

**Comment by kasfaw** [comment]
@chachra if there was no manual entry then it should be blank not 0

**Comment by chachra** [comment]
@kasfaw Report Status fields for progress report lists incorrect: https://www.evernote.com/shard/s659/sh/4641fb6b-b499-40e8-b514-bb1c47bd3c24/5455b3afe7a79c0e93a84a07184bf36a AND https://www.evernote.com/shard/s659/sh/4641fb6b-b499-40e8-b514-bb1c47bd3c24/5455b3afe7a79c0e93a84a07184bf36a - both same links ?

**Comment by chachra** [comment]
@kasfaw can you send in right link for this... seems for other enhancement (fixed) - " Annex C PDF missing currencies: https://www.evernote.com/shard/s659/sh/b0498303-94dd-4b67-beb7-7bc53a2f3a9a/597f94a44b43d29111117ea251a8e720"

**Comment by kasfaw** [comment]
@chachra sorry here you go https://www.evernote.com/shard/s659/sh/ee310ae6-7dc2-46ff-a011-ca2b96497335/9fa1f69a24238fbbb6b24091f7a4f8ba

**Comment by chachra** [comment]
@rkrupinski filtering in progress report: http://127.0.0.1:8080/api/unicef/37/progress-reports/1608/?page=1&llo=3407&location=583 works now... but filtering really applies only to indicator_reports key and only returns appropriate indicator reports. Location filtering works fine. PD output filtering keeps showing åll PD outputs. I know why since programme_document is still returning all of them.... any way to fix it / show only one selected? It'll be tough to do on backend.... but lmk. tx.

**Comment by kasfaw** [comment]
@chachra @rkrupinski need to do the following on the Overview page tweak: https://www.evernote.com/shard/s659/sh/617226a5-e814-4fab-8fd1-670b761ba790/4e6fe218f56f1a347d53e8ec91bde444

**Comment by rkrupinski** [comment]
@chachra 

Changed https://github.com/unicef/etools-partner-reporting-portal/commit/9bf1f6f01733d74c35a85479e80f050cfddb4e72#diff-83174f4644ccf27a75dc04183a53c9a0 to https://github.com/unicef/etools-partner-reporting-portal/commit/ad3a0acd2aff8e3ec2fb831cf55c7fe7c435c397. Not sure whether the ordering is correct though.

**Comment by chachra** [comment]
you combined both of them? If thats what task asked for... I assumed just showing cso type if its present was the requirement.

**Comment by rkrupinski** [comment]
@chachra @kasfaw 

Than apparently, none of is sure what the requirements are :) The commit prior to mine looks liked it aimed (incorrectly, but hey!) at combining these two.

**Comment by chachra** [comment]
I thought the 2nd arg was "default" or fallback value. But maybe I mis-interpreted. anyways its a minor bug, we'll get to it.

**Comment by rkrupinski** [comment]
@kasfaw What do we actually display here? https://www.evernote.com/shard/s659/sh/617226a5-e814-4fab-8fd1-670b761ba790/4e6fe218f56f1a347d53e8ec91bde444

**Comment by kasfaw** [comment]
@rkrupinski displaying a concat of 'type' and 'cso_type' ... so a government partner would show just "government" and a CSO with cso_type=national would show "National CSO"

**Comment by dfryta** [comment]
@rkrupinski Backend ready for https://www.evernote.com/shard/s659/sh/721793d4-11bd-41f9-a422-a57f0622aec4/94626ef1cd02ed3cf70fa906111455db

**Comment by dfryta** [comment]
@rkrupinski About wrong statuses on PR and PD filtering, here are proper values: https://github.com/unicef/etools-partner-reporting-portal/blob/develop/django_api/django_api/apps/core/common.py#L102

**Comment by rkrupinski** [comment]
@dfryta https://github.com/unicef/etools-partner-reporting-portal/commit/9b6ba08c1f7558bc6f81c7684ff451908f10c9de

👍 Thanks

**Comment by dfryta** [comment]
@kasfaw ```No validation on Progress Report Submission: all fields should be filled out (status, narrative, other info fields, and indicators - only exception is that indicators with LLO status of Met or No Progress are not required to have data entered.```
- Is it possible to have status as No Status on IP side? What is default state?
- if status in Met or No Progress, we should skip all validation?

**Comment by kasfaw** [comment]
@dfryta 
> Is it possible to have status as No Status on IP side? What is default state?
There should be no “No Status” option. No default. 
> if status in Met or No Progress, we should skip all validation?
Correct. Skip all validation on all indicator reports related to that LLO

**Comment by dfryta** [comment]
@kasfaw Last thing are partner_contribution_to_date, challenges_in_the_reporting_period, proposed_way_forward are always required? They do not belong to indicator but to PR.

**Comment by kasfaw** [comment]
@dfryta correct. Those fields are required when submitting a PR
