### ISSUE TITLE
Indicator "editable" flag is missing

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#333]
Add `editable` (Boolean) flag to indicators in:

`/api/unicef/<workspace_id>/programme-document/<pd_id>/calculation-methods/`

**Comment by rkrupinski** [comment]
@chachra 

Please, revert https://github.com/unicef/etools-partner-reporting-portal/commit/67e385f71feaadb520a068070bc1ab1dcdcb62fa once you're done.

**Comment by chachra** [comment]
still needed? sorry not sure of what this ticket is asking?

**Comment by rkrupinski** [comment]
We made (hardcoded) all calculation methods editable. If that's the way we want it then this is no longer needed.
