### ISSUE TITLE
Allow users to "Sign In" just via email address

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#337]
This assumes the users have already been setup with a random username, password and email address. Assigned to appropriate group (role) for permissions.

Once this has been done any user can come to PRP, enter their email address on login screen. They will then be emailed a "magic link" which they can click to then login. Either way even email is not in the system let them know "If this is a valid email address, please check your email for instructions to Sign In".

If link is valid user will click and be logged in, otherwise show them the email address input with an error ("Unable to login, invalid token, please try again").

If user goes to /login and they are already logged in (can GET their profile successfully then redirect to /app)

**technical notes**

- On /login Put a "email address" input box (validate its an email) and a submit button.

- POST this email address to the backend (to /api/account/auth/get-token/ ). If its an existing user the backend will send out an email with magic link. (on local dev can do tail -f /var/log/uwsgi.ini to see console email and get token)

- Link in the email will be pointing to a Polymer route say /login-token/?token=snj5h34u3 show a progress indicator potentially - Take this token and POST is to a API endpoint ( /api/account/auth/login-with-token/ ), if successful then redirect the user to /app/ otherwise show error.

Some libs/links to leverage:
- https://github.com/aaronn/django-rest-framework-passwordless
- https://medium.com/aaronn/passwordless-auth-for-django-rest-framework-3a3de5204860

**Comment by chachra** [comment]
@eglital pressing enter key should submit the form.

When user sees, Sign in with email

If this is a valid email address, please check your email for instructions to Sign In. Maybe add a "try another email" link which shows them login box again?

The email address is not validated at all ?? /get-token/ should never be called if its not validated in frontend anyway... standard polymer/component validation? Backend will respond with {"email":["Enter a valid email address."]}, error should be handled and user not shown that message unless backend says 200 response anyway.

http://127.0.0.1:8080/app/login-token/?token=045856 doesn't call a POST to login the user yet?

**Comment by eglital** [comment]
@chachra I think front end validation works, if you enter just some text or numbers that's not an email and click submit, underline becomes red, and post request doesn't send. If it's an email, then doesn't matter if it's in our system or not, it shows user the message to check the email.
I can do those other couple things today

**Comment by eglital** [comment]
@chachra just to clarify: if an email is the right format and passes front end validation, the user gets the message 'If this is a valid email address, please check your email for instructions to Sign In.' regardless if from the server I get 200 or 400 right? This is what I understood initially.. Or do I inform the user that this email wasn't in the system and they should try another one?

**Comment by chachra** [comment]
'If this is a valid email address, please check your email for instructions to Sign In.'  is sufficient I think.

**Comment by eglital** [comment]
ok, and then I am adding 'try another email' with email input below that message so if the user knows that he made a mistake or doesn't get an email he can enter a new one without refreshing the page, right?

**Comment by chachra** [comment]
Correct. Right now user is kind of stuck, has to reload page since there are no links etc. there.
