### ISSUE TITLE
Be able to view the data for a output+indicator+location of a PD report

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#34]
Like in https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016134

This is a *re-usable component* and hence should be designed / implemented carefully. "Output" here is really the "Reportable" from the data model, hence this is a view of showing an instance of an IndicatorReport for a Reportable in the context of a PD report (in the future cluster reporting there is no PD reports, hence this should be thought of as reusable component).

When user clicks the arrow in right of the indicator it should uncollapse and show the "location tabs" and within each the disaggregation data of the indicator.

These components will be re-used in PRP when viewing a report and also in PMP implementations later on.

If one location is done another is pending, then at indicator level its shown as pending as well (red "!").

**Comment by chachra** [comment]
@n1207n This would require the API endpoint /indicator/$idX/ind-reports/$idY/

**Comment by n1207n** [comment]
@chachra, yeah definitely. #21 is the prerequisite for this issue.

**Comment by chachra** [comment]
@n1207n am thinking if the API will even be needed or #21 related work will be enough for this task. In this case just like in #21 user opens indicator and we show them data for all locations (in tabs). No past data, just latest one.... so I think no additional backend work here. Thoughts?

**Comment by chachra** [comment]
Got merged into with #35 potentially. Dupe and closing.
