### ISSUE TITLE
Cluster Testing Bugs

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#342]
- [x] Dashboard data is empty for both partner and IMO
- [x] All Cluster filter dropdowns are blank: (example) https://www.evernote.com/shard/s659/sh/617226a5-e814-4fab-8fd1-670b761ba790/4e6fe218f56f1a347d53e8ec91bde444
- [x] Cluster Objectives list: CO Ref # column should be much narrower as typical value will be no more than 6 characters long. Cluster Objectives title should be the widest
- [x] Cluster Objectives Overview: show full name for frequency of reporting: https://www.evernote.com/shard/s659/sh/acf17b38-73e9-48b9-92ad-88058015b04c/f147a5a81a99a20e28881661d27f5539
- [x] Add Cluster Objective: cluster selection dropdown empty https://www.evernote.com/shard/s659/sh/ce8c7006-4b33-4944-806d-d95ef4ddfa9b/e8ad41beaf6eb2163106fae7f4d830c4
- [x] All "Add Indicator" modals have empty Location dropdowns
- [x] Add Cluster Activity: cluster selection dropdown empty https://www.evernote.com/shard/s659/sh/7d55bda3-bd7f-4be9-ad18-dda84ecbba06/b7769b38dad67e720f01f17175ad2cfa
- [x] Cluster Activity Details: minor fixes https://www.evernote.com/shard/s659/sh/5ac6ff7f-3083-4f47-99e4-4f1c8ef1c266/a75e3b3969d0d34c163e338174c8d36a
- [x] Indicator lists in CO and CA show PD/SSFA ref # columns: https://www.evernote.com/shard/s659/sh/a21ba446-f79f-4b73-bb13-42b5918659ee/9fc9a4e02934f9fa4b8d912b914bb226
- [x] Partner Projects List not populating in both Response Parameters>Partners and My Planned Action>Projects
- [x] Results: Cluster filter dropdown empty for both Draft/Due and Submitted
- [x] Results: indicators not filtered by `status="Due" or "Overdue"` in Draft/Due tab https://www.evernote.com/shard/s659/sh/3bd7f7a9-20de-4c27-9064-b9b84c09a43a/87fee34b88096616034ff11f368a43f8

**Comment by rkrupinski** [comment]
> All Cluster filter dropdowns are blank

@dfryta @chachra Dropdowns require data formatted in the manner below:

```json
[
  {
    "id": 1,
    "title": "lorem ipsum"
  },
  {
    "id": 2,
    "title": "dolor sit amet"
  }
]
```

**Comment by rkrupinski** [comment]
> Indicator lists in CO and CA show PD/SSFA ref # columns: 

@dfryta Both `/api/indicator/co/` & `/api/indicator/ca/` return items with the field `ref_num` which may not be what we want since it's always an empty string. Pease confirm.

**Comment by rkrupinski** [comment]
> Results: indicators not filtered by status="Due" or "Overdue" in Draft/Due tab

@dfryta Whether they are or not, the url seems to be correct:

`/api/cluster/3/cluster-indicator-reports-list/?page_size=10&page=1&submitted=0`

**Comment by rkrupinski** [comment]
> Cluster Activity Details: minor fixes

@dfryta Need `cluster_title` (currently only `co_cluster_title` is present) in:

`/api/cluster/cluster-activity/<activity_id>/`

**Comment by n1207n** [comment]
> Dashboard data is empty for both partner and IMO

I don't see Polymer calling Cluster Dashboard API. Even if I choose a specific Cluster on the top-right dropdown, the dashboard API is not being called. It could be that Polymer is not fetching data, thus empty Dashboard UI is presented.

**Comment by rkrupinski** [comment]
@n1207n Polymer is fetching data when it obtains a url. The url is only created when certain fields on the model are assigned. Cluster id is one of those fields. No cluster id === no http request.

* `GET /api/cluster/<RESPONSE_PLAN_ID>/<CLUSTER_ID>/cluster-dashboard/`
* `GET /api/cluster/<RESPONSE_PLAN_ID>/<CLUSTER_ID>/partner-dashboard/`

cc @chachra

**Comment by chachra** [comment]
@rkrupinski we're aware and I will work on a fix tomorrow, ignore dashboard stuff for today.

**Comment by rkrupinski** [comment]
> Activities tab is blank (shows "TODO") in both Response Parameters>Partners and My Planned Action>Activities

@chachra @kasialanecka Is this handled in a separate ticket? Could someone point me to mockups, please?

**Comment by kasialanecka** [comment]
@rkrupinski you mean these?

https://invis.io/EDBIM0Y8M#/232534042_Emergency-PP_Overview_02_Copy_6

https://invis.io/EDBIM0Y8M#/232533039_Emergency_-_MC_-_Activities

**Comment by rkrupinski** [comment]
@dfryta Please close when

> Results: indicators not filtered by status="Due" or "Overdue" in Draft/Due tab 

done.
