### ISSUE TITLE
Add indicator modal, don't allow same disagg to be selected more than once

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#349]
https://www.evernote.com/l/AAU7V4IEAmRD7r2JBPWEZDqeyAIpx6PNnaU

**Comment by eglital** [comment]
@chachra the validation is done after you click save, the same selections will be underlined red and save will not go through. That was easier at the time to do then disabling certain fields on already rendered dropdowns or doing check after each selection. But I can change that if that's what prefered

**Comment by chachra** [comment]
oh ok. cool then. can close this out!
