### ISSUE TITLE
Be able to enter data for an indicator+location in a PD report filing in a modal

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#35]
See https://projects.invisionapp.com/share/RDBE0T04F#/screens/238647670 and next few screens.

data is not auto-saved.....

Once user clicks save, modal closes and data is shown in the read-only components below for that indicator+location. If user entered all the data then green checkmark appears, otherwise remains a red "!". https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016142

Clear clears the data. Saving will make an API call. Entering partial data is not allowed. User can report at lower disagg level and thats allowed of course (checkboxes at top: https://projects.invisionapp.com/share/RDBE0T04F#/screens/238646320 ). Message shows when reporting at lower level than what the indicator (reportable) has been configured at/as.

If changing to higher or lower disagg, can get a warning message as well: https://projects.invisionapp.com/share/RDBE0T04F#/screens/238646326

**Technical design**

Please build upon work in https://github.com/unicef/etools-partner-reporting-portal/issues/72

The JSON structure is being used for the "view only" tables already. Similar logic should be used to construct the forms here as well, except instead of TD its a INPUT component being used.

It'd be good to create a copy the redux element / store for the data being edited.  If user cancels modal out, then delete this copy. If user is making changes then the data in this copy in redux is being modified. If user makes changes and/or presses save then PUT the data back to backend and on success copy it back to the original redux store/key, so underlying tables and logic of complete/incomplete etc. will auto-update.

If the user checks / unchecks any disaggregation checkboxes, other than the warning the frontend will have the regenerate the disaggregation data structure with all the possible key combinations *for that level* and set them to empty data.

Please look at this as well if it helps in implementation: http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/paper-datatable/editable.html

**Comment by chachra** [comment]
One of the feedbacks is can keep the modal but enter data in more of a matrix. One idea was to use this library: http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/paper-datatable/editable.html

**Comment by chachra** [comment]
@n1207n can finish off more validation, actual math (sum/avg etc.) in this ticket.

**Comment by n1207n** [comment]
@rkrupinski Here is the proposed API url: /api/indicator/indicator-location-data-entries/
