### ISSUE TITLE
Calc methods in indicator reports

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#351]
Both on IP Reporting and Cluster Reporting, the list of indicator report should indicate the calculation methods across locations and reporting periods should be displayed for the indicator reports. Specifically these screens:

- [ ] https://projects.invisionapp.com/share/RDBE0T04F#/screens/231338349
- [ ] https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/243476913
- [ ] https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/250848101

**Comment by rkrupinski** [comment]
Any guidelines regarding how this would look?

**Comment by chachra** [comment]
not really... lets just use the across locations when indicator report and across reports when showing an single indicator I think? Adding Dariusz in case backend change / additional data needed. tx.

**Comment by dfryta** [comment]
@rkrupinski please review and let me know if you need my help here. Thanks!
