### ISSUE TITLE
A way to reconcile Reportable's recalculated total from its child Reportable instances

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#356]
Per our discussion, once the PD recalculation upon IndicatorBlueprint changes is done, the Reportable instance may need to adjust its total based on its parent-child relationship.

This may require the refactoring on post_save signal on IndicatorReport for calculating Reportable totals and some conditions to check its children for getting a correct total value from.

**Comment by chachra** [comment]
dupe of #184
