### ISSUE TITLE
Allow user impersonation for superusers

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#361]
https://github.com/arteria/django-hijack

**Comment by chachra** [comment]
@robertavram @ewheeler assuming this is ok... can block it on production, but will be super helpful in testing. Any other suggestion than one mentioned?

**Comment by n1207n** [comment]
IMO admin can do anything cluster user can do at the moment. Closing this but we may have to dig a bit on API permissions.
