### ISSUE TITLE
Polymer upgrade to 1.9.3?

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#362]
https://github.com/Polymer/polymer/releases/tag/v1.9.3

Something to look into for perf/features/stability

**Comment by rkrupinski** [comment]
The version specified in `bower.json` is `^1.8.1` which basically means `1.<latest minor>.<latest patch>`. I'm currently on `1.11.0`.

**Comment by chachra** [comment]
So can close this? Can you update bower.json?

**Comment by rkrupinski** [comment]
I'd say can close without updating anything.
