### ISSUE TITLE
Cluster dashboard backend refactor and any frontend changes

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#364]
Currently the serialization of data is happening against a Cluster, instead of ResponsePlan.

Make all necessary changes and more DRY code and frontend changes so it is fully working E2E for partner and IMO

**Frontend items to address:**
- [x] initial load of dashboard doesn't load data (not pass in any cluster_id basically)
- [x] Refreshing screen when a cluster is selected, loses that selection
- [x] constrained indicator reports should link to reportable/indicator
- [x] constrained indicator report should show progress based on reportable.achived numbers.
- [x] empty box put "no results" etc.

**Backend items to address:**
- [ ] Make sure Indicators by Progress Status are indicator counts, not indicator report counts

**Comment by chachra** [comment]
@rkrupinski Code should be in place in branch to solve the FE issues here.

**Comment by rkrupinski** [comment]
@chachra In `/api/cluster/3/cluster-indicator-reports-list/?page_size=10&page=1&cluster=7&submitted=0` (and all the other places where we filter by cluster) pls change the `cluster` param be `cluster_id`. I think I also saw `clusterId` somewhere.

**Comment by rkrupinski** [comment]
> constrained indicator report should show progress based on reportable.achived numbers.

@chachra given

```json
"achieved": {
  "c": 1086.5,
  "d": 1,
  "v": 2397.5
},
```

How do I interpret that?

**Comment by rkrupinski** [comment]
> constrained indicator reports should link to reportable/indicator

@chachra Linked, yet `/api/cluster/<cluster_id>/cluster-indicator-reports-list/?indicator=<indicator_id>&submitted=1` returns no results. A data integrity issue?

**Comment by rkrupinski** [comment]
Frontend work is complete.
