### ISSUE TITLE
Be able to enter unicef and cluster data in a modal for a output+indicator+location

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#37]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016138

Similar to #35. 2X the amount of data is entered.

The backend API call should be structured in a way ideally that it supports in the future adding another funding entity (say other than unicef)?

**Comment by kasfaw** [comment]
@chachra can we walk through this one together tomorrow? a few questions that UNICEF brought up:
- how will this accommodate for mismatched reporting periods between cluster and IP reporting?
- what will a partner see if reporting from cluster? (will they be able to report for unicef and cluster at the same time?)
- if a progress report is rejected by unicef, what happens to the cluster indicator that's included in that report? is the IMO going to see it as draft? 
- is the unicef component of the report being calculated in any way on the cluster side (ie analysis)?

**Comment by kasfaw** [comment]
dup of #155
