### ISSUE TITLE
Misc. cluster reporting changes

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#376]
Span both frontend and backend.

Bolded are for backend help needed

- [x] **Add cluster activity cluster objective ref Nr are blank.** (cluster titles are fine) Should it just be removed from creation?

- [x] Remove CO ref # column from /clusters/objectives - CO list.

- [x] is CO ref # needed in activities list ?

- [x] **Remove CO Ref # and frequency of reporting in cluster objective creation.**
egle: I did the front end part of it and made them not to be required on the back end, not sure what else should be done on the backend

- [x] In add indicator no locations available ?

- [x] move links to the details of anything to the left side of the tables (except PD reporting, link to the report should be on the left)

- [x] in Response Parameters > Clusters > Activity after doing 'Add Cluster Activity' adds created activity in cluster objectives instead

- [x] 'Add Indicator' doesn't work (nothing happens)

- [x] add new project > remove frequency of reporting. also on view/list page etc.

- [x]  in 'My Planned Actions' > 'Projects' > individual project > 'Activities' it shows the same 10 activities no matter what page you are on (even on the last one that should show only 4 (21-24) activities it still shows same 10)

- [x] Lot of duplicate calls are made in places because of observer data change. Put debounce in a few places where it makes sense.

- [x] Response parameters > Partners: location dropdown is not searchable.

- [x] **In activities table status is not shown on all activities because from the back end it comes like 'g', 'n', '0' instead of regular 3-letter codes (only fake data ones, the newly created ones work fine).**

- [x] Response parameters > Partners > Activities and My planned actions > Activities most filters are not working (back end problem)

- [x] **in Projects Locations is always blank (always an empty array from the back end)**

- [x] no start and end date in activity overview

- [x] adding two indicators in a row doesn't work without first refreshing the page

**Comment by eglital** [comment]
@chachra regarding no1: will cluster objectives be assigned Co Ref# on the back end automatically or will they just not have it?

**Comment by eglital** [comment]
@chachra  I reported as many bugs as I found and finished fixing up the ones I was able to. I did some backend changes as well so please review them, I am not that familiar with django yet. Only a few backend tasks left, if you have some time it would be great to finish it up and merge.
