### ISSUE TITLE
Add cypress/automated front end tests

### ISSUE THREAD

**Issue by eglital** [unicef/etools-partner-reporting-portal#378]
Debatable on how to chunk up the tests etc. But there is data dependency usually present / assumptions on data for any test to run and succeed.

Each test can start assuming a blank db or minimal data in the db, unless there is dependency between tests, which there might be in some cases.

**General**

- [x] Be able to login into django admin interface onboard 4 new users in django admin with imo, partner viewer, partner editor, partner authorized officer roles and checking for appropriate error conditions etc.

**Cluster reporting:**

- [x] Cluster reporting: be able to login to django admin interface as an IMO and be able to create a new workspace, response plan (2), cluster (2 per cluster).

- [ ]  Be able to login into django admin, create a new partner, associate it with a cluster. Create a new user and assign to this partner. Have this user then be able to login and be able to select a the appropriate response plan, select it, be able to see dashboard, response parameters etc.

- [ ] Build on top of previous test state: be able to create a project, a custom activity, a partner activity associated with cluster, be able to add indicators to the project and custom activity then as well.

- [ ] Build on top of previous test state: After some time be able to come and then report on the activity indicators (2 partners ideally for same indicator).

- [ ] Build on top of previous test state: have IMO for that cluster login and be able to view indicator progress that takes into account both reports and applies the right across reports accumulation of progress to that indicator (eg. sum or max etc.)

- [ ] Build on top of previous test state: Be able to see appropriate data / changes then to the dashboard and analysis section as well.

**IP reporting:**

- [ ] Login as partner viewer and be able to see partner details, see workspaces in dropdown that partner is associated with. See partner details and list of PD's and any report in draft should not be viewable and any submitted or accepted report should be.

- [ ] Login as partner editor and be able to do lot of things in above test. But then be able to view the draft report and add data to one or more indicators in LLO's.

- [ ] Build on top of previous test state: login as a partner authorized officer and be able to do above test case. Additionally to entering data, can then review and see the submit button and submit it. Also should be able to go to PD > calculation methods and be able to change and save them.

- [ ] A test case to enter data for 2 PD reports (same PD).

- [ ] Accept a PD report in PMP and run a test in PRP that it appears as accepted. "send back the other PD report" and test in PRP that it appears sent back with message. Test that it can be then re-submitted.

- [ ] Verify that the indicator made progress with appropriate amount after the the progress report (and its underlying indicator reports) have been accepted.

**Comment by eglital** [comment]
@chachra in here: 

> Be able to login into django admin, create a new partner, associate it with a cluster. Create a new user and assign to this partner. Have this user then be able to login and be able to select a the appropriate response plan, select it, be able to see dashboard, response parameters etc.

create a new user and assign to partner - what group the user should belong to? or doesn't matter?

**Comment by chachra** [comment]
@eglital doesn't matter.... can do even "viewer" role, should be same test. Tx.

**Comment by n1207n** [comment]
Closing this to move the conversation to other ticket.
