### ISSUE TITLE
Scaffold route structure

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#38]
With empty templates to have navigation in place.

**Comment by chachra** [comment]
Country id in url would be good.

http://prp/<country_id>/...... including even PD url's etc. which technically don't need the country_id because the id's are unique in the db.

**Comment by chachra** [comment]
@rkrupinski since you're working on routes some thoughts / clarifications from my end.

/country/<id>/pd/  ---- list of all PD's. I know in the mockups the tab is called "PD reports" its a bit mis-leading. Made a comment there @kasialanecka 

/country/<id>/pd/<id>/overview/ is 1 report overview

/country/<id>/pd/<id>/reports/ is list of reports for that pd

/country/<id>/pd/<id>/reports/<id>/data/ is single report data tab
/country/<id>/pd/<id>/reports/<id>/narrative/ is single report narrative tab
/country/<id>/pd/<id>/reports/<id>/review-submit/ is single report review+submit tab only for non-submitted reports.

Whether to do reports or report or pd or pds (plural or singular) will leave to you. We should be consistent I guess here and in the API's as well. @n1207n @lkolacz

**Comment by rkrupinski** [comment]
I'd say that's a pd-specific change.
