### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by eglital** [unicef/etools-partner-reporting-portal#388]
- [x]  go to response params > clusters, then click response parameters > partners. Click back on clusters.... notice url is /clusters/projects when it should be /clusters/objectives ~~---- please check other such issues in other places of the UI as well please.~~

- [ ] ---- please check other such issues in other places of the UI as well please.

- [x] clicking on any open tab second time (and all times after) removes query parameters from url.

- [x] Response Parameters > Partners > Activities go to second or any further page, then click on individual activity, 'page' in query parameters doesn't change back to 1, that causes errors in indicators tab. The same issue happens across the site, page in url needs to change back to 1, when clicking between tabs.

**Comment by chachra** [comment]
any updates on LOE / questions / debugging on this?

**Comment by rkrupinski** [comment]
Can't assess LOE right away. Historically, routing's always been a huge pain.
