### ISSUE TITLE
Cluster reporting: some columns should be sortable

### ISSUE THREAD

**Issue by eglital** [unicef/etools-partner-reporting-portal#392]
Sortable columns:

**Response parameters**
- [x] Objectives List - cluster, cluster objective title
- [x] Cluster Activities List - cluster, cluster objective title, cluster activity
- [x] Projects - title, cluster, status, partner
- [x] Activities - title, status, partner, cluster activity

**My Planned Action**
- [x] Projects - title, cluster, status
- [x] Activities - title, status, cluster activity

**Comment by chachra** [comment]
@eglital what will it take to do on frontend? PMP does it already... if you can make the frontend changes along with adding it as query params to the url as needed / possible then backend changes can follow.

Make columns that are directly coming from the db sortable, those are the easiest / low hanging fruit. Thanks.

These are all you captured from that spreadsheet? Think in partner project/activity might want the same, no?

Response plan sorting is where? we don't show them in list.... other than selecting one, even there won't be ton of them, so don't see use-case for sorting.

**Comment by eglital** [comment]
@chachra in the spreadsheet partner project/activity columns are not mentioned that need to be sorted. If we do it in response parameters, I guess we can include it there as well. Up to you
