### ISSUE TITLE
Cluster reporting: editing objects

### ISSUE THREAD

**Issue by eglital** [unicef/etools-partner-reporting-portal#393]
what fields are editable after an arrow

**I would add edit buttons on the details screens rather than pollute the list views** - except for indicators since those don't have a detail screen of their own.

**_Frontend_**
**Response parameters**
- [x] Cluster Objective >  Edit  => Title only
- [x] Cluster Activity >  Edit  => Title only
- [x] Objective Information > Cluster Objective Indicators > Edit each indicator
- [x] Cluster Activity information > Cluster Activity Indicators > Edit each indicator

**My planned action**
- [x] Project details > Edit => pretty much all the fields are editable. Title , Locations, Clusters, start date, end date, status, total budget, funding source, description, additional information
- [x] Activities list > Edit activity (no radio button like in create... 2 separate modal components depending on activity type) => for cluster activity: partner project, start date, end date, status. for custom activity: title, partner project, start date, end date, status
- [x] Project Information - Project indicators > Edit under each indicator
- [x] Activity Information - activity indicators > Edit under each indicator [ONLY IF they are custom indicators]

If indicator is allowed to be edited. Following fields can be edited: title, means of verification, measurement specifications, freq of reporting, baseline, target, locations. Cannot change disaggregations.

_**Backend**_
!! /api/indicator/ needs to include more things in results to be able to prepopulate editing data. Missing fields: means of verification, measurement specifications, frequency of reporting, locations.

**Response parameters**
- [ ] Cluster Objective >  Edit  => Title only
- [ ] Cluster Activity >  Edit  => Title only
- [ ] Objective Information > Cluster Objective Indicators > Edit each indicator
- [ ] Cluster Activity information > Cluster Activity Indicators > Edit each indicator

**My planned action**
- [ ] Project details > Edit => pretty much all the fields are editable. Title , Locations, Clusters, start date, end date, status, total budget, funding source, description, additional information
- [ ] Activities list > Edit activity (no radio button like in create... 2 separate modal components depending on activity type) => for cluster activity: partner project, start date, end date, status. for custom activity: title, partner project, start date, end date, status
- [ ] Project Information - Project indicators > Edit under each indicator
- [ ] Activity Information - activity indicators > Edit under each indicator [ONLY IF they are custom indicators]

The logic for **who can edit** something is exactly same as who can create that thing for the most part.

Who can edit...  | IMO | Authorized Officer | Editor | Viewer
-- | -- | -- | -- | --
Cluster Objective | x (only if the cluster for this is in the imo_clusters of the logged-in user | | |
Cluster Objective > Indicator | x (only if the cluster for the CO this indicator belongs to is in the imo_clusters of the logged-in user | | |
Cluster Activity | x (only if the cluster for this is in the imo_clusters of the logged-in user | | |
Cluster Activity > indicator | x (only if the cluster for the CO this indicator's activity belongs to is in the imo_clusters of the logged-in user | | |
Partner Project | | x (only if the project's partner id = user's partner id) | |
Partner Project > Indicator |  | x (only if the project's partner id this indicator belongs to = user's partner id) | |
Partner Activity | | x (only if the partner activity's partner id = user's partner id)  | |
Partner Activity > indicator | |  x (only if the partner activity's partner id this indicator belongs to = user's partner id **AND** this the partner activities cluster_activity is null (meaning it was a custom activity)) | |

related to #200

**Comment by chachra** [comment]
@eglital cluster objective and cluster activity will need their own edit as well?

Added "ONLY IF they are custom indicators" to on point in ticket.

Anything else we're missing.... ? Disaggs don't have edit, so thats fine.

**Comment by chachra** [comment]
Don't think changing cluster should be allowed for any of these... or changing the "cluster indicator" for activity indicator (when it inherits from cluster indicator) etc. Lets detail out these edge cases in ticket description above as well.

**Comment by eglital** [comment]
@chachra based on what I understood from the spreadsheet - cluster activity, partner activity, project plus all indicators need to be editable? It would be great if you can write down details on what should be editable in each case because I couldn't understand that from the spreadsheet and it's a bit confusing to me. It would be much easier to continue with this task if we had clear list plus edge cases.

**Comment by eglital** [comment]
@chachra so far I added UI for editing cluster activity, partner activity and project. Still dont know what should be editable in each case, plus I need back end for those. I also need info for permissions of these.
I didnt start indicator editing, if you can detail out what needs to be editable for each type of indicator, that would be great. Need back end as well. Plus permissions.
Thanks!

**Comment by chachra** [comment]
@eglital I have added in good detail what all can be edited from where and by whom in a table. Please lmk if you have any questions. Backend is missing I u/s, but assume you can make a PATCH request with validated data back to backend.

**Comment by chachra** [comment]
@eglital it got missed in spec in previous task but since you're in frontend permissions if you could please disable "add" for disaggregations for non-IMO users. Thanks.

**Comment by eglital** [comment]
@chachra thanks for all the details, much more clear now! I will add the permissions for 'add disaggregation' as well

**Comment by eglital** [comment]
@chachra I finished most of the frontend but I will need to double check everything once backend is in place

**Comment by chachra** [comment]
@eglital cluster activity edit works... but frontend doesn't refresh the data store. Please check, something minor am guessing. Refreshing screen shows new edited title.
