### ISSUE TITLE
Cluster reporting: changes to Response Plan 

### ISSUE THREAD

**Issue by eglital** [unicef/etools-partner-reporting-portal#394]
**Response Plan**
- [ ] Add Country to the Response Plan model and to the UI
- [ ] Add filter by 'Type of Response Plan', 'Start Date', 'End Date', 'Country'
- [ ] Add search by 'keyword'

**Comment by chachra** [comment]
Response plan belongs to workspace which belongs to countries. hence RP can belong to countries I guess... so yes.

where would all this keyword search / sorting etc. be added ? on the screen selecting response plan? for one country don't see there being many hence not sure I see utility of it.

**Comment by eglital** [comment]
If there is never gonna be too many response plans to select from I don't think filters or search are needed either..

**Comment by n1207n** [comment]
We now have workspace filter on Response plan UI. Closing this.
