### ISSUE TITLE
Cluster reporting: modifications to indicator creation

### ISSUE THREAD

**Issue by eglital** [unicef/etools-partner-reporting-portal#395]
For all indicators:
- [ ]  add 'Reporting Method' (dropdown single select - Cumulative or Period, default Cumulative), remove 'Calculation method across locations' and Calculation method across reporting periods', add 'Numerator' and 'Denominator' - both numerical fields by default blank (both not required), add 'Start Date of Reporting'

For 'Add Cluster Objective Indicator' and 'Add Project Indicator':
- [ ] remove Location

For 'Add Cluster Activity Indicator':
- [ ] add 'Admin Level' (choices: Admin 0, Admin 1, Admin 2, Admin 3, Admin 4, Admin 5 (from Carto DB)), Location should be Multi-select dropdown - Dependent on the admin level chosen

**Comment by chachra** [comment]
Please don't work on this ticket for now @eglital tx.
