### ISSUE TITLE
Misc. UX issues

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#402]
- [ ] ~~Put link to main object on the left and anything else on the extreme right? Applies to progress report list in IP reporting for example.~~ moved to #421

- [x] Put pagination controls on top of each table view as well ?

- [x] Cluster reporting: in partner activity list views (both in my planned action and response parameters) add cluster activity and cluster objective columns? and a 'custom' checkmark (if custom=true) column?

- [x] Success toast on saving calculation methods in IP reporting

- [x] Error toast anytime a 500 error happens by the backend.

- [x] Filters load partially, making UI awkward. Eg. in cluster reporting > results, filters load piecemeal. Would wanna probably show loading indicator and only show once all data has loaded successfully?

- [x] When partner is logged in clicking on cluster reporting > reports should have them selected by default.

- [x] Prefill partner in analysis, when available

- [x] Export is broken because of partner activity title issue: https://etools-test.unicef.org/api/cluster/4/cluster-indicator-reports-list/export-for-analysis/?page_size=10&page=1&submitted=0

- [ ] ~~Need Admin level and pcode in location dropdowns everywhere. Can look at how PMP does it.~~ Moved to #421

**Comment by rkrupinski** [comment]
> Filters load partially, making UI awkward. Eg. in cluster reporting > results, filters load piecemeal. Would wanna probably show loading indicator and only show once all data has loaded successfully?

Or make the APIs faster? 😉

**Comment by rkrupinski** [comment]
> When partner is logged in clicking on cluster reporting > reports should have them selected by default.

@chachra Can we close #401 then?

**Comment by rkrupinski** [comment]
> Need Admin level and pcode in location dropdowns everywhere. Can look at how PMP does it.

@chachra Based on how filters currently work, it would be best to have the formatting done by django.

**Comment by dfryta** [comment]
Export issue fixed on develop.

**Comment by rkrupinski** [comment]
Merged develop to `misc-ux-issues-#402`.

**Comment by rkrupinski** [comment]
> Put link to main object on the left and anything else on the extreme right? Applies to progress report list in IP reporting for example.

@chachra Not sure whether I understand correctly.

**Comment by rkrupinski** [comment]
Closing & merging this as is. Remaining stuff moved to #421
