### ISSUE TITLE
Misc. bugs

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#412]
- [x] {"unit":["\"ratio\" is not a valid choice."]} When adding an indicator.

- [x] Partner dropdown duplicates appear.

- [x] Duplicates appear in indicator dropdown as well.

- [x] Sending back report impacts multiple reports for some reason.

**Comment by sethgold8** [comment]
Send back report is still not working so moved it to #550

Everything else is good so closing out :) - Seth
