### ISSUE TITLE
Capturing cluster spreadsheet feedback action items

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#415]
https://docs.google.com/spreadsheets/d/1rhwxi0UFER1vbhpO7qng8mwFqv9C0zrasU65bHLa0_4/edit#gid=1025865473

- [x] No documents needed for response plan for now, so response plan list we can remove the open/close toggle. Use some other component to display them... just radio buttons selection screen now.

- [x] Change in response plan selection to "Select Response Plan <workspace_name>" since we;'re showing response plans for a workspace always.

- [x] Change results to "reporting results" in left nav.
- [x] Make cluster objective title and cluster in objective list sortable. -> handled in ticket #392  
- [x] Add a link to the activity from single project > project activities tab > in the list. Both in response params and my planned action. In each it'll link to the project in response params or my planned action respectively. -> some weird issue, link is correct, works if you open it in new tab but not in the same window... not sure how to fix it
- [x] Remove locations from project creation and edit. Backend might still require them, will change that too.
- [x] In response plan list if IMO user add a link to django admin to response plan list screen. /api/admin/core/responseplan/ saying "Response Plan Admin". Can make it a button with a gear icon if appropriate. Add to top right of screen, right aligned with "select response plan...."

- [x] Validate start date / end data are valid in the frontend start being < end always.

- [x] Add an "in-need" to indicator modal (optional field) and send to backend as a variable on creation and edit. This is just like baseline and target fields from a validation perspective.

- [x] Make baseline / target optional in indicator edit/create.

- [x] Make total budget, funding source, description and additional information on project not be mandatory.

- [x] ~`405` when `PATCH`ing `/api/indicator/cluster-indicator/`~ Changed to `PUT`.

### ❗️ Moved to #439:

 - [ ] In create indicator modal add some helper text

- [ ] In partner activity add we should only ask for partner project? why ask for cluster at all?

-  [ ] Add a date to CO, CA, PP, PA lists.

- [ ] Add a "go back to PRP" in top right of django admin template.

- [ ] Add a new "Cluster Coordinator" role that is cluster reporting specific role that allows this person/user to view all the data. The IMO continues to be the one who can edit/create etc. in the system.

- [ ] Create a IMO group or django admin permissions so they can create users, edit response plans etc.

**Comment by chachra** [comment]
@eglital the top 7-8 tasks can be done quickly by you in frontend. Build on top of your edit branch if you'd like, might be best. I'll handle the rest on backend or with Rafal then next week. Tx.

**Comment by eglital** [comment]
@chachra 

> Add an "in-need" to indicator modal (optional field) and send to backend as a variable on creation and edit.

Is this a text field?

**Comment by eglital** [comment]
@chachra 

> Add a date to CO, CA, PP, PA lists.

What kind of date? cluster objectives and activities don't have dates, and projects and partner activities are already displaying start and end dates

**Comment by rkrupinski** [comment]
> In create indicator modal add some helper text

Any particular helper text?

**Comment by rkrupinski** [comment]
> Add an "in-need" to indicator modal (optional field) and send to backend as a variable on creation and edit. This is just like baseline and target fields from a validation perspective.

@dfryta I added "In need" field to both add & edit indicator modals. Field name in request payload is `"in_need"`. Given this has to match target & baseline validation-wise, the field type (`"number"`) remains the same. Lmk if that's correct.

P.S. I noticed that we're getting `405` when `PATCH`ing `/api/indicator/cluster-indicator/`. Added that to the ticket.

**Comment by rkrupinski** [comment]
> Add a date to CO, CA, PP, PA lists.

@dfryta Whatever `a date` means, we need to add it to:

* `/api/cluster/<response_plan_id>/cluster-objective-list/`
* `/api/cluster/<response_plan_id>/cluster-activity-list/`
* `/api/partner/<response_plan_id>/partner-project-list/`
* `/api/partner/<response_plan_id>/partner-activity-list/`

**Comment by dfryta** [comment]
@chachra based on @rkrupinski request - what kind of date we are interested to? Start and end date? Update date?
