### ISSUE TITLE
Export PDF and XLS of various things in IP reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#417]
Specification below.

[1709 PRP IP export  print revised.docx](https://github.com/unicef/etools-partner-reporting-portal/files/1475769/1709.PRP.IP.export.print.revised.docx)

**Technical Note**
See below API endpoints needed. Many have same serializer to be used, some return one object, others return more.

1. /api/unicef/W-ID/programme-document/?status=Sig%2CAct%2CSus&format=xls/pdf (and any other filters) ..... should this be extension of existing endpoint then?
2. /api/unicef/W-ID/progress-reports/642/?format=pdf (and any other filters) ..... should this be extension of existing endpoint then?
3. /api/unicef/W-ID/progress-reports/R-ID/annex-C-export-PDF/ (already exists in code)
4. /api/unicef/W-ID/progress-reports/R-ID/annex-C-export-data-XLS/ (new)
5. /api/unicef/W-ID/programme-document/PD-ID/reports/?format=xls/pdf (and any other filters) ..... should this be extension of existing endpoint then?
6. /api/unicef/181/progress-reports/?format=xls (and any other filters) ...... should this be extension of existing endpoint then?
7. /api/unicef/181/programme-document/indicators/?format=xls/pdf (and any other filters) ...... should this be extension of existing endpoint then?

**Comment by n1207n** [comment]
Detailed specs from Change request docs:

1. Programme Documents page - PDF & Excel
* Export in excel programme document (PD) information as filtered on PD page
* https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016130
2. PD progress report page - PDF
* https://projects.invisionapp.com/share/RDBE0T04F#/screens/238646874
* Data fields for export:
  * IP name
  * Country
  * PD Reference Number
  * PD Title
  * PD Reporting Period
  * PD report status
  * PD report due date
  * PD report submission date      	
  * PD output Title
  * PD output progress status
  * PD output narrative assessment
  * PD Indicator Title
  * PD indicator type
  * PD UNICEF Indicator Target
  * Calculation method across location
  * Calculation method across reporting period
  * Previous location progress
  * Location admin level 1
  * Admin level 1 Pcode
  * Location admin level 2
  * Admin level 2 Pcode
  * Location admin level 3 (as many levels as set in workspace)
  * Admin level 3 Pcode
  * Value by disaggregation groups including all sub totals
  * Achievement in reporting period (total across all locations)
  * Total cumulative progress
  * (Cluster) Indicator Target
  * (Cluster) previous location progress
  * (Cluster) value by disaggregation groups including all sub totals
  * (Cluster) achievement in reporting period (total across all locations)
  * (Cluster) total cumulative progress
  * Partner contribution to date
  * Funds received to date
  * Challenges/bottlenecks in the reporting period
  * Proposed way forward
  * Submitted by
  * Attachment

3. PD progress report (Annex C part 2) - PDF
* Same data fields as #2 above.
4. PD progress report data( Annex C part 2 + disaggregated data) - Excel
* Same data fields as #2 above.
5. Progress reports page (multiple PDs) - PDF & Excel
* https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016132
* Same data fields as #2 above.
6. PD progress data (multiple PDs reports, multiple periods) - Excel
* https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016132
* Same data fields as #2 above.

7. Indicators page - PDF & Excel
* Data fields for excel export for Indicator page based on data filtered on screen.
* 5.1 Export indicator data in excel
  * PD Reference Number
  * Last reporting period
  * PD report submission date      	
  * PD output Title
  * PD output progress status
  * PD output narrative assessment
  * PD Indicator Title
  * PD UNICEF Indicator Target
  * Previous location progress
  * Location admin level 1
  * Admin level 1 Pcode
  * Location admin level 2
  * Admin level 2 Pcode
  * Location admin level 3 (as many levels as set in workspace)
  * Admin level 3 Pcode
  * Value by disaggregation groups including all sub totals
  * Achievement in reporting period (total across all locations)
  * Total cumulative progress
  * (Cluster) Indicator Target
  * (Cluster) previous location progress
  * (Cluster) value by disaggregation groups including all sub totals
  * (Cluster) achievement in reporting period (total across all locations)
  * (Cluster) total cumulative progress

**Comment by mjaworski** [comment]
Excel and CSV are used interchangeably, is the export meant to be a `.csv` file using excel dialect or an `.xlsx` file, or both options should be available?

**Comment by mjaworski** [comment]
Work ongoing on https://github.com/unicef/etools-partner-reporting-portal/tree/417-exports-in-IP-reporting

For the most part extending existing endpoints.

**Comment by sethgold8** [comment]
add 2 Export buttons for XLS and PDF
