### ISSUE TITLE
Analysis in Cluster Reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#427]
Requires a bit of a redo.

Analysis in Cluster Reporting

Questions you wanna answers

1. Which clusters are present in which locations
2. Which organizations are present in which locations
3. Which activities are in which locations
4. Add a cluster_partner_type and make it default to following based on partner type
    1. Bilateral / Multilateral → International NGO
    2. CSO + International → International NGO
    3. CSO + * (other) → National NGO
    4. UN Agency → UN Agency
    5. Government → Government

Detailed requirements captured in the spreadsheet: https://docs.google.com/spreadsheets/d/1rhwxi0UFER1vbhpO7qng8mwFqv9C0zrasU65bHLa0_4/edit#gid=979285202

**Comment by chachra** [comment]
@kasialanecka Please see this mockup as an illustration. Please ask questions...

Examples for visuals:

https://www.humanitarianresponse.info/system/files/documents/files/3w_overview_partners_31_august.pdf

**Comment by chachra** [comment]
@kasialanecka Please see this mockup as an illustration. Please ask questions...

![IMG_0518.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ca8dffc9b0d720006675c4/125516c66e82c728ace21e0d46c1b9bd1cd2d6f8d7abf301b44fff9e2c4533317346f6737383bb7bba122857560c4fa941585646f9fe8f2ca4b02e6c981e5ab38532022d8c6853beb2901eb70bbb258a4e86bfb88244c7e93c27f5c6.jpg)

Examples for visuals/reports:
https://www.humanitarianresponse.info/system/files/documents/files/3w_overview_partners_31_august.pdf

https://www.humanitarianresponse.info/system/files/documents/files/wos_response_july_2017_170919.pdf

**Comment by kasialanecka** [comment]
progress by indicator - are we showing all indicators or only activity indicators?

**Comment by kasialanecka** [comment]
@chachra https://invis.io/EDBIM0Y8M#/265873598_Analysis_Cluster_New_01
3 screens (1 + 2nd with hovers and 3rd with different types of indicator boxes (depending of type filtered)

**Comment by chachra** [comment]
Looks great @kasialanecka - let me review in detail today....

**Comment by chachra** [comment]
@kasialanecka assuming you've made the edits to mockups today Kasia, please review with @rkrupinski to gather any feedback or issues he flags. tx.

**Comment by kasialanecka** [comment]
@chachra hope I've done all required changes, please check

**Comment by kasialanecka** [comment]
@chachra  Rafał's feedback:
- map - specification, how this map should work, is needed (e.g. what if 2 different locations will be filtered, what about legend if only one location will be filtered)
- a lot of information hidden on hover, these are all additional filters and maybe better idea is not to hide it?

**Comment by rkrupinski** [comment]
Kasia was faster, yet I'm still gonna submit my feedback:

> My only concerns are:
> 
> * How would the map work? Actually, in what format will the map data arrive (coords vs actual shapes)? How interactive does it need to be? Google vs leaflet?
> * Aren't we trying to put too much stuff inside tooltips/rollovers?

**Comment by chachra** [comment]
@kasialanecka looks really good to me.

**Comment by chachra** [comment]
@rkrupinski Map works simply to show shapes of polygons. Leaflet is way to go I think. Interaction we need is simply hover over see number and list of partners.

The data from backend will send you "buckets" (ranges 1-5, 5-10 etc...) and colors for each to use or frontend can hardcode those colors. darker is highest bucket, lightest = lowest bucket.

Agree on tooltips, but should be manageable I think...

**Comment by rkrupinski** [comment]
The locations. How are we gonna send areas -> locations -> sublocations from the backend?

**Comment by n1207n** [comment]
From Dec 1st, 2017 docs:

Layout is divided by two tabs (you can see them below filters): Operational Presence and Indicators. Prototype is interactive, so you can switch between screens by clicking on these tabs.

**Comment by chachra** [comment]
#436 and #437 capture all the details now. Closing this ticket.
