### ISSUE TITLE
Do a check on report submission in IP Reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#428]
Upon submission of the report - the email of the person submitting the report should be checked against the email of the authorized officer assigned to the PCA that is connected to that PD. If the emails are the same, then the report is submitted. If the emails are different, then there is a pop up that ask the user to select which Authorized Officer is the user submitting the report on behalf of. The user can choose only 1 and submit.

**Comment by rkrupinski** [comment]
@dfryta Submitter's email is available in profile data. Is the authorized officer's email exposed somewhere? I'd rather perform the check prior to actually trying to submit the report, unless of course we consider emails sensitive data and don't want to expose them.

**Comment by rkrupinski** [comment]
@chachra @dfryta Is `the authorized officer assigned to the PCA that is connected to that PD` what's exposed as `PD` -> `unicef_officers`?

**Comment by dfryta** [comment]
@rkrupinski Programme Documents endpoint holds this data already:

`http://localhost:8080/api/unicef/<programme_document_id>/programme-document/`

Response:

```{
            "id": "15206",
            "external_id": "33",
            "agreement": "JRF PCA 12 (2013-01",
            "reference_number": "JRF PCA 12-PD 2-2015",
            ...
            "unicef_officers": [
                {
                    "name": "Evrim Sahib",
                    "title": "Officer",
                    "email": "evrimm@gmail.com",
                    "phone_number": "3473938878"
                }
            ]
        },
       ...
```

**Comment by sethgold8** [comment]
moved to ticket #454
