### ISSUE TITLE
Ability to sort columns on some tables in IP reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#430]
See cluster reporting sorting ticket: https://github.com/unicef/etools-partner-reporting-portal/issues/392

Support sorting by columns that quick/easy in pd list, progress reports list, and within "progress reports" tab of a PD.

**Extra credit (if possible)**
Allow sorting by progress in indicators table in IP reporting.

**Comment by rkrupinski** [comment]
@dfryta The Polymer part pushed to `ip-reporting-changes-#377`.

**Comment by sethgold8** [comment]
#done and duplicate ticket
