### ISSUE TITLE
IP Reporting change requests

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#434]
- [ ] 1> In the “Progress Report “page there must be an ability to export the page to display all reports and statuses, raw data from within the reports and also must be able to print PDF.

- [ ] 2> The need to include a “demo indicator table” in the Calculation Method Tab. Using an indicator as an example, the demo indicator table will enable the IP to see how the change of the calculation method for the sample indicator impacts progress reported across locations and reporting periods. This could provide an initial response to the challenge of setting the calculation method in a screen that is separate to the data entry screen.

- [ ] 3> Upon submission of the report - the email of the person submitting the report should be checked against the email of the authorized officer assigned to the PCA that is connected to that PD. If the emails are the same, then the report is submitted. If the emails are different, then there is a pop up that ask the user to select which Authorized Officer is the user submitting the report on behalf of. The user can choose only 1 and submit.

- [x] 4> In "Progress report" he default view must be overdue, send back and the next due report, but the partner should have the ability to select a view to show all reports.

- [x] 5> ~Ability to sort the columns on the Progress report page. Covered in #430?~

- [ ] 6> Add drilldown (expand the section) on the Progress report list page, the information should be the same as the PD details.

- [ ] 7> Add Locations to the PD Details page (add location SS)

- [ ] 8> Add Location filter to the Programme Document list Page.

- [x] 9> In Indicators list Page - the PD Status filter should be defaulted to "Active"   	

- [ ] 10> Ability for a partner to rate a final report

- [ ]  11> Add a new column in the table (“Programme Documents” and “Progress Reports” pages) called “Report number”, where the report number is generated automatically. The last quarterly progress report (QPR) on the list should be called “final” QPR. The numbering of the reports will depend on the report type, e.g. Special reports would be SR1, Humanitarian will be HR1. The numbers will be generated at the time when the report is generated.

**Comment by rkrupinski** [comment]
Open questions:
## 4:
1. Is preselecting a couple of values in a multi-choice filter enough?

**Comment by chachra** [comment]
broken into multiple tickets already. closing this.
