### ISSUE TITLE
Integration with OCHA API’s (RPM / OPS / FTS)

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#435]
The goal of such an integration is to enable IMO’s to be able to pull in cluster structure from OCHA RPM. Additionally for partners to be able to pull in project information from OPS and FTS.

Misc. items:
* If a cluster has been setup to sync with with OCHA RPM then it will pull in the clusters plans (one overall HRP or Flash Appeal plan) on a regular (say daily or weekly) basis from RPM directly.
* Project Status (from OPS): ongoing | planned | completed – ‘cancelled’ is missing as an option but this is something you would not put at the setting up of a project, so OK. But it is something that should sync if/when the status is changed in FTS.
* Total Budget (from FTS): should pull ‘required funding” from FTS. FTS has a history of amendments in its records, i.e. a partner may ask donors for more money later down the line (this is normal) and will want to update the Total Budget (in FTS). If this was amended in FTS, it should appear (sync) to eTools PRP.

Funding Source: 
* FTS data should also feature in the analysis section of PRP. In the analysis view we should be able to see a chart that shows % funded. The chart in our Analysis tab should show option 2 below.
 
* Often we see a simple percent funded, i.e. 100*(committed + paid)/required funding (as a percentage, with actual values in dollars below):
![pasted image 0](https://user-images.githubusercontent.com/3138217/34818321-c8d4aca0-f6fd-11e7-80f7-fece89a6a36b.png)

* What we need is to split the green bar above into two to show how much is committed and how much is paid (commitments don’t always turn into payments and so ‘paid’ is the only source of certainty, hence the wish to separate.  (still a percentage, with actual values in dollars below).

In the list of projects (so later in the workflow, after creation) partners should be able to select a project, and view the info created for a project, HOWEVER here’s the added feature:

* There should be an “add more detail” button.

* On clicking the button, it brings up a table that requires completion or updating if completed already.

* The information from OPS and FTS will appear as per the API sync. This can only be editable (for now) in OPS or FTS, i.e. to be view only in PRP To have a two-way sync would be ideal (thoughts Anwar or Mark?)

* The additional information (as per the ‘No’ entries in the file https://tinyurl.com/y9gcy5ee) should be editable in PRP.

* We also need an “add custom field” for any peculiar, additional information needed. Which could be clicked twice to add two fields - this might be a number/value or text.
Depending on the country, the new OPS might be in place. To accommodate both old and new OPS systems we will have to integrate with both since some countries will not be using new OPS anytime soon.

**Comment by sethgold8** [comment]
#duplicate moving to complete
