### ISSUE TITLE
Cluster Analysis: Operational Presence

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#436]
Detailed documentation: https://unicef.gitbook.io/prp/product-end-user-documentation/cluster-reporting/analysis-of-results

https://invis.io/EDBIM0Y8M#/265873598_Analysis_Cluster_New_01

Here we have an overview of operational presence, we can see which Clusters and Partners are working in a country. Operational Presence Table is not paginated now and can be exported, the area of a table is scrollable (vertically and horizontally in case of a larger number of sectors to show). 

Tooltips available on hover are shown on this mockup (there’s no interaction between them, one tooltip per hover):
https://invis.io/EDBIM0Y8M#/265873599_Analysis_Cluster_New_01_Hovers

**Comment by rkrupinski** [comment]
Open questions:

1. From the documentation: "Operational Presence Map [...] Zoom in/out capabilities will be there as well.". This will depend on the granularity of the actual data.

**Comment by sethgold8** [comment]
- [ ] hover on ma

**Comment by sethgold8** [comment]
Hover on Map needs to be done but everything else is good.
