### ISSUE TITLE
Cluster Analysis: Indicators tab and functionality

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#437]
Detailed documentation: https://unicef.gitbook.io/prp/product-end-user-documentation/cluster-reporting/analysis-of-results

https://invis.io/EDBIM0Y8M#/266599953_Analysis_Cluster_New_01_02

Indicators are grouped into cards with green headers, which provide information about what type of indicator we are looking at., e.g.: Cluster Activity as a header means that below (inside this card) we can see Cluster Activity Indicators. 

Gray bar with title of an indicator is collapsible. In collapsed state we can quickly see progress against target (green progress bar with %) and against People in need (PiN, orange progress bar with %). In uncollapsed state we can see detailed information with charts.

Tooltips available on hover are shown on this screen (the behavior is the same, one tooltip per hover, no interaction between tooltips):
https://invis.io/EDBIM0Y8M#/266599955_Analysis_Cluster_New_01_02_Hovers

Other types of indicators (Cluster Objective Indicators, Project Objective Indicators and Activity Indicators) are shown here:
https://invis.io/EDBIM0Y8M#/265873600_Analysis_Cluster_New_02

In filters area we have a filter called "Indicator Type" and this is a single select, so only one type of indicator will be displayed on the screen in Indicators tab.

**Comment by sethgold8** [comment]
when @rkrupinski  is back, Sillin and him need to go through everything to help him review

**Comment by sethgold8** [comment]
@rkrupinski 

- [ ] Chart missing for Current progress null for http://prp.tivixlabs.com/app/GA/cluster-reporting/plan/246/analysis/indicators?loc_type=1&page=1

![Screen Shot 2018-03-19 at 2.03.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455fa6b7191a37af112284f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44ae54456a11a3166e0722431.png)

- [ ] Partner by status should not be 'On_track'. It should be 'On track'. Same with 'No_progress' and 'No_status'

![Screen Shot 2018-03-19 at 2.08.15 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455fa6b7191a37af112234f5e5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44ae54456a3103764ee702431.png)

- [ ] hover feature on Indicator tab for Current Progress by Partner, Partner by Status, current progress by location not working

**Comment by rkrupinski** [comment]
@sethgold8 

> Chart missing for Current progress

Can't render chart when there's no data. Discussed this w/ @n1207n and that should not occur in real-life scenarios.

> hover feature on Indicator tab for Current Progress by Partner, Partner by Status, current progress by location not working

Tooltips in general are missing within "Indicators" tab due to some backend work required. We've decided to postpone them in order to merge analysis asap (due to its size). cc @chachra

**Comment by sethgold8** [comment]
@rafal

Can we change the null to another polymer component. If not, can we have the text read: "No data for Current Progress by Location yet."

I've moved hover feature to a new ticket for #560 and assigned to @n1207n

**Comment by sethgold8** [comment]
- [ ] partner type filter is not working on backend
- [ ]location filters are not working on backend 
- [ ] Green bar needs to change based on the Indicator Type Filter. Use Content_Type Field @rkrupinski 
![Screen Shot 2018-04-11 at 3.04.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f26b7191a37bf1122f4f5b5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19f41c95df448e54551a7163166ef762431.png)

**Comment by sethgold8** [comment]
- [ ] Getting 500 error from Location filter

![Screen Shot 2018-04-16 at 2.03.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f56b7191a37af112284f5a565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df448e84c57a2153160e4772431.png)

**Comment by n1207n** [comment]
I can't seem to reproduce this issue on staging as both IMO and AO. We'll create a new ticket if the issue arises as undiscovered edge case or breaking changes.

Advise to close this issue.
