### ISSUE TITLE
If same email address of a focal point or authorized officer comes from another PD in another workspace, add that workspace to that user.

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#441]
Sync related.

**Comment by mjaworski** [comment]
`Add default permissions of say reader and unusable password.`

**Comment by chachra** [comment]
agree on unusable password. Their role might have to be authorized user? please see what kind of users PMP sends, or maybe they are all AO's?

**Comment by chachra** [comment]
Is there PR for this @maciej-jaworski ?

**Comment by chachra** [comment]
ok found https://github.com/unicef/etools-partner-reporting-portal/pull/467 - Added #441 to its title.

**Comment by sethgold8** [comment]
#blocked by PMP data sync

**Comment by chachra** [comment]
Is this done @maciej-jaworski and was dupe?

**Comment by maciej-jaworski** [comment]
Yup, should be done.

**Comment by sethgold8** [comment]
In django admin, I made a new user the Focal point for a PD and their workspace in django admin did not update

**Comment by maciej-jaworski** [comment]
@sethgold8 afaik this was regarding PMP sync, so not something that could be verified through django admin

**Comment by sethgold8** [comment]
#Maciej triple checked ;)
