### ISSUE TITLE
Upgrade all Django/Python packages

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#442]
Update most important ones, like Django, DRF etc.

amqp (1.4.9) - Latest: 2.2.2 [wheel]
asn1crypto (0.23.0) - Latest: 0.24.0 [wheel]
astroid (1.5.2) - Latest: 1.6.0 [wheel]
azure-storage (0.20.0) - Latest: 0.36.0 [wheel]
Babel (2.5.1) - Latest: 2.5.3 [wheel]
billiard (3.3.0.23) - Latest: 3.5.0.3 [wheel]
carto (1.1.0) - Latest: 1.1.2 [sdist]
celery (3.1.25) - Latest: 4.1.0 [wheel]
certifi (2017.7.27.1) - Latest: 2017.11.5 [wheel]
cffi (1.11.2) - Latest: 1.11.4 [wheel]
cryptography (2.1.2) - Latest: 2.1.4 [wheel]
decorator (4.1.2) - Latest: 4.2.1 [wheel]
Django (1.11.5) - Latest: 2.0.1 [wheel]
django-celery (3.2.1) - Latest: 3.2.2 [sdist]
django-debug-toolbar (1.7) - Latest: 1.9.1 [wheel]
django-extensions (1.7.7) - Latest: 1.9.9 [wheel]
django-filter (1.0.4) - Latest: 1.1.0 [wheel]
django-leaflet (0.19.0) - Latest: 0.23.0 [sdist]
django-model-utils (2.6.1) - Latest: 3.1.1 [wheel]
django-mptt (0.8.6) - Latest: 0.9.0 [wheel]
django-storages-redux (1.3.1) - Latest: 1.3.3 [wheel]
django-suit (0.2.21) - Latest: 0.2.25 [sdist]
djangorestframework (3.6.4) - Latest: 3.7.7 [wheel]
factory-boy (2.8.1) - Latest: 2.9.2 [wheel]
Faker (0.8.6) - Latest: 0.8.9 [wheel]
flake8 (2.5.4) - Latest: 3.5.0 [wheel]
future (0.15.2) - Latest: 0.16.0 [sdist]
html5lib (1.0b8) - Latest: 1.0.1 [wheel]
ipdb (0.8.1) - Latest: 0.10.3 [sdist]
isort (4.2.5) - Latest: 4.2.15 [wheel]
jedi (0.11.0) - Latest: 0.11.1 [wheel]
Jinja2 (2.9.6) - Latest: 2.10 [wheel]
kombu (3.0.37) - Latest: 4.1.0 [wheel]
openpyxl (2.4.8) - Latest: 2.4.9 [sdist]
paramiko (2.3.1) - Latest: 2.4.0 [wheel]
parso (0.1.0) - Latest: 0.1.1 [wheel]
pexpect (4.2.1) - Latest: 4.3.1 [wheel]
Pillow (4.3.0) - Latest: 5.0.0 [wheel]
psycopg2 (2.7.3.1) - Latest: 2.7.3.2 [wheel]
pyasn1 (0.3.7) - Latest: 0.4.2 [wheel]
pyflakes (1.0.0) - Latest: 1.6.0 [wheel]
pylint (1.7.1) - Latest: 1.8.1 [wheel]
PyNaCl (1.1.2) - Latest: 1.2.1 [wheel]
python-json-logger (0.1.7) - Latest: 0.1.8 [wheel]
setuptools (36.5.0) - Latest: 38.4.0 [wheel]
simplejson (3.11.1) - Latest: 3.13.2 [sdist]
text-unidecode (1.0) - Latest: 1.1 [wheel]
tornado (4.5.2) - Latest: 4.5.3 [sdist]

**Comment by n1207n** [comment]
Closing this as PyPi packages are not compatible with Django 2.0 yet.
