### ISSUE TITLE
In frontend set Title

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#444]
If on login then "Sign In | PRP"
If in IP Reporting "IP Reporting | PRP"
If in Cluster Reporting "Cluster Reporting | PRP"

For any other edge case (if any) just PRP is fine. Django admin has its title set already, so no change needed there.

**Comment by rkrupinski** [comment]
https://github.com/unicef/etools-partner-reporting-portal/pull/445
