### ISSUE TITLE
Misc. IP reporting changes from change requests doc. round 2

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#448]
- [x] 1> Display of the text on the blue bar must be changed from the actual name of PD Output to as per the text displayed in PMP. Call the label on blue thing "SSFA expected result". Eg. PD output be: "Enhanced knowledge in targeted communities for improved IYCF practices for children under-2 years" - https://www.evernote.com/l/AAVpeZdjS35CcLW4BRR6Dt4BVa3MhTOhaI8 #frontend

- [x] 14> PD/SSFA Ref no must be the first column on the Progress Report page. The 2nd should be the Reports name (cf. table below 13, replacing the “view report” or “enter data” field). #frontend
- [x] 15> come up with a solution mock up to make it clear to the user the existence of the calculation method tab, as currently this is a hidden feature that nobody will know about.
![final_from_unicef_cr-003_prp_-_misc__ip_reporting_changes_-_specification_-_google_docs](https://user-images.githubusercontent.com/73096/36514680-6fce94a2-172a-11e8-949d-da386085487c.png)

- [x] 16> User must have an ability to add one file attachment to the reports. Add a one-off API endpoint to make this upload, and make sure the GET request exposes the upload as well. #backend #frontend

- [x] 18> Remove 'Due Date' and 'Show Only Due Report' from Progress Reports in IP

![Screen Shot 2018-02-16 at 5.40.58 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455f56b7191a37df1162b4f5a575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df742e34952a7123562ef712431.png)

**Comment by chachra** [comment]
updated post-meeting with more details.

**Comment by rkrupinski** [comment]
@kasialanecka Is 6 mocked up?

**Comment by kasialanecka** [comment]
@rkrupinski I believe we don't have. I can prepare one.

**Comment by sethgold8** [comment]
Closed, everything is working good :) - Seth

These are moved to #537

 3> Include Signed/Active/Ended/Closed/Suspended/Terminated PDs

Signed or Closed PD’s would not be reported on, just displayed. Partner must be able to report on Active, Ended, Suspended & Terminated.

(Please REMOVE "draft" status) in PRP so partner can report on them. 'Draft' is still showing.

8> If PD is not active then in PMP we cannot "send back the report" even. Restrict in PRP API. #backend

 19> In case the PD is terminated or suspended in middle of the agreement then the final report must be moved to the end / suspended date of the contract and the other pending reports for the rest of the months must no longer be due
