### ISSUE TITLE
Create Progress Report and associated Indicator reports on a regular basis based on PD settings for that partner

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#45]
Based on reporting frequency required create indicator reports, their indicator location data's and progress report (IP reporting only) instances. They will not contain any data (but should probably have the correct JSON structure we have put in place for disaggregations), till the partner user enters the data for that time period.

The reports, location datas and progress reports should only be created at the end of the reporting period. So for example if reporting is monthly, and last IR is at June 3, 2017 then new one should get created for June 4-July 3, 2017 (assuming cron ran on July4). Something similar to this logic, please document in detail in the code as this might change a bit.

There are different reporting periods that need to be supported including some that are specific dates as well.

This can be achieved via a cron or celery-beat. A technical discussion will be helpful to determine best approach.

**technical design**
Please design this as a Django management command please for now.

Keep #164 in mind.

Please do a quick technical evaluation and ask any questions before any extended coding.

Don't create IndicatorReport if its Reportable belongs to ClusterActivity.

**Comment by chachra** [comment]
@robertavram what is your thoughts on implementing this type of functionality?

**Comment by chachra** [comment]
CC @kasfaw

**Comment by robertavram** [comment]
@chachra this sounds good.. one quick question though...  the benefit of creating the report prior to the data being entered.. is it to be able to show which reports were not completed?

**Comment by chachra** [comment]
@robertavram Thanks. Yes the intent is then all actions in the UI are to modify / add data (PUT requests) and yes to show list of pending reports since at a given point there could be multiple for same indicator.

Hence user never has to come in and "create" a report... its all there for them for the right time periods and they just have to enter data and submit it etc.

**Comment by chachra** [comment]
@lkolacz please start work on this asap as your next task. Do a technical analysis and ask any open questions as well. tx.

**Comment by chachra** [comment]
Or if @n1207n maybe you can take this task on?

**Comment by lkolacz** [comment]
branch for this task `feature-cronjob-create-end-period#45`

**Comment by n1207n** [comment]
The branch has no work so far as it is even with develop branch. I could take a stab after some other branches to work on.

**Comment by n1207n** [comment]
Technical architecture design is due.

**Comment by n1207n** [comment]
Hi @lkolacz, I'll be taking over this task given the complexity of it. If you have any code committed, please push those to contribute.

Thanks!

**Comment by chachra** [comment]
@n1207n can you please test this on IP reporting side. Open a bug, if its an issue.

**Comment by n1207n** [comment]
IP reporting side confirms the successfully generated reports. new ProgressReports showed up in the UI.
