### ISSUE TITLE
Email/user check on submission of Report - IP

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#454]
Upon submission of the report - the email of the person submitting the report should be checked against the email of the authorized officer assigned to the PCA that is connected to that PD. If the emails are the same, then the report is submitted. If the emails are different, then there is a pop up that ask the user to select which Authorized Officer is the user submitting the report on behalf of. The user can choose only 1 and submit.

![Screen Shot 2018-02-07 at 5.28.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f46b7191a37df110234f5b575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df743e14856a71b3765e3722431.png)

**Technical notes**
Make sure authorized officer is being synced, think it is. I'd say expose in API emails? Not a security issue I think since this is a partner user logged in already. If this users email is not on that list of id's only then does this modal pop up.

Can change the report submit endpoint to always expect a "submitting on behalf" email or focal point id (not sure its stored in a model). In many cases it'll be same as logged in user and in other it won't (when they select user from dropdown).

Also note they are not selecting a "django user" from dropdown technically. Since these focal points may have never logged in and I don't think we create users for them. Please check that though.

**Comment by sethgold8** [comment]
![Screen Shot 2018-02-07 at 5.28.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f46b7191a37df110234f5b575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df743e14856a71b3765e3722431.png)

**Comment by marcindo** [comment]
How exactly this situation can be reproduced? I'm getting ```
TypeError at /api/unicef/1/progress-reports/59/submit/
unsupported operand type(s) for +: 'NoneType' and 'str'
```
When I try to submit some existing report. Also the user email should be compared to list of users stored in `partner_focal_point` field on programme document?
:

**Comment by maciej-jaworski** [comment]
@marcindo fixed this issue directly on develop

**Comment by marcindo** [comment]
Frontend work is partially done in: ` feature-email-check-report-submission-454` Modal is always displayed, and only ui is added with minimum logic as I'm not sure about final implementation

**Comment by sethgold8** [comment]
@marcindo let @maciej-jaworski know what you need

**Comment by maciej-jaworski** [comment]
Technical note - `submitted_by` is an FK to `account.User` model, while `partner_focal_points` is a M2M relation to `unicef.Person` so some logic will be added to double check that User for given Person exists.

I'll also add another field to save the user that actually triggered the report submission, since keeping track of that is potentially useful in the future.

**Comment by maciej-jaworski** [comment]
Commited my changes in the feature-email-check-report-submission-454
Payload needs to contain `submitted_by_email` for those users

**Comment by marcindo** [comment]
Frontend looks done to me, but still getting error even after submitted_by_email is sent along

**Comment by maciej-jaworski** [comment]
Fixed the issue

**Comment by sethgold8** [comment]
@marcindo bringing this ticket back from delivered. If you click 'cancel' from the modal, then the submit button stops working. It should have opened the modal again. X button looks just fine.

Can you change the name format to be "$Name [$title]"

**Comment by marcindo** [comment]
@sethgold8 this is done in staging
