### ISSUE TITLE
Location filter on PD List and locations on Details Page

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#455]
- [x] Add Locations to the PD Details page

![Screen Shot 2018-02-07 at 5.31.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f46b7191a37df1112a4f5a565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df743e14856a21a3167e3702431.png)

 

- [x] Add Location filter (allowed to select multiple) to the Programme Document list Page

![Screen Shot 2018-02-07 at 5.32.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f46b7191a37df111294f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29841c95df743e14856a3123162e2732431.png)

**Comment by sethgold8** [comment]
Add Locations to the PD Details page

![Screen Shot 2018-02-07 at 5.31.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f46b7191a37df1112a4f5a565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df743e14856a21a3167e3702431.png)

 Add Location filter to the Programme Document list Page
![Screen Shot 2018-02-07 at 5.32.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f46b7191a37df111294f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29841c95df743e14856a3123162e2732431.png)

**Comment by marcindo** [comment]
Added very basic UI for location on details page in branch ```feature-locations-on-pd-details-locations-filter-455``` but further integrations will be needed as I don't see locations appearing in serializer
For the moment I copied over the locations filter from reports, but it doesn't work, as id/endpoint used to aggregate locations is incorrect. I'm blocked on this on and need separate endpoint for PDs

**Comment by maciej-jaworski** [comment]
@marcindo please confirm
You need:
- locations added to the programme document list endpoint
- a source endpoint for locations filter choices

**Comment by marcindo** [comment]
yes, and I believe single programme document model itself needs locations field to be displayed on details view

**Comment by chachra** [comment]
a source endpoint for locations filter choices - should exist I think, do check.

pd filtering on locations, needs to support multiple.

Does locations exist on our PD model?

**Comment by maciej-jaworski** [comment]
@chachra no, not directly, either related through workspace -> countries, etc or through indicator report down to location level

**Comment by marcindo** [comment]
@maciej-jaworski 
- I've got the multiple filter on programme document list, but endpoint itself needs to be updated to use multiple filter
- still waiting for location field be added to programme document serializer. Looks like frontend is only using list endpoint to display details

**Comment by maciej-jaworski** [comment]
@marcindo Adjusted the filters and added locations to PD list endpoint
