### ISSUE TITLE
Different overall status choices for IP partner on Final Report

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#456]
- [x] Rate a final report

 ![Screen Shot 2018-02-07 at 5.38.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f46b7191a37df111234f5e585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df743e14856ad11306be1732431.png)

**Technical Notes**
If progress report has final flag set to true then show 2 choices for overall status instead of 4. Met results as planned and constrained.

Open question: re-use the "met" and "constrained" statuses or create new on in db model?

- [x]  When viewing a final report that is submitted, Right now it just says 'Met' or 'Constrained'. The text should say ' Met results as planned' or 'Constrained (partially met result)'.  @marcindo 

![Screen Shot 2018-02-20 at 3.07.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f36b7191a37bf1122c4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df742e04b5da41b3467e2752431.png)

**Comment by sethgold8** [comment]
![Screen Shot 2018-02-07 at 5.38.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f46b7191a37df111234f5e585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df743e14856ad11306be1732431.png)

**Comment by maciej-jaworski** [comment]
work on  456-status-choices-for-final-report

**Comment by maciej-jaworski** [comment]
Frontend choices seem to be hardcoded in https://github.com/unicef/etools-partner-reporting-portal/blob/develop/polymer/src/elements/reportable-meta.html#L45

**Comment by maciej-jaworski** [comment]
Opened PR with backend changes
@marcindo  Frontend needs to adjust displayed choices based on progress_report `is_final` field

**Comment by marcindo** [comment]
Frontend part is done in  #468 as I had 'is_final' flag already defined there, so this one is good to merge

**Comment by sethgold8** [comment]
moving this ticket back to code review @marcindo . When viewing a final report that is submitted, the text should say ' Met results as planned' or 'Constrained (partially met result)'. Right now it just says 'Met' or 'Constrained'

![Screen Shot 2018-02-20 at 3.07.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f36b7191a37bf1122c4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df742e04b5da41b3467e2752431.png)

**Comment by sethgold8** [comment]
[ ] - downloading the doc after submitting a final report does not work
@n1207n

**Comment by marcindo** [comment]
@seth what do you mean by doc? How can I check it on staging, cause locally, after submitting  final report I can download annex, and both exports if that's what you mean

**Comment by marcindo** [comment]
@sethgold8  Document issue is unrelated, it just doesn't work, I created separate ticket for it #523, other  point is in PR

**Comment by sethgold8** [comment]
#works good as long as the 'overall status' is supposed to be different for Final Reports and Other Reports. Will close after this is confirmed - Seth
