### ISSUE TITLE
Put restrictions on PD reporting based on PD status

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#459]
Signed or Closed PD’s would not be reported on (restrict in API, throw error if anyone tries to submit report for a signed/closed PD), just displayed. No new reports to be generated for ended, suspended etc. (see tasks.py) New reports only generated for active PD's. Once document is closed, no action in PRP. #backend 

#frontend - a little frontend task is to hide submit button if PD is signed or closed. Hide review & submit tab as well in this case actually, easier, since button is on there. Above the tabs maybe put a warning message saying "PD is $status$ hence you cannot submit this report".

This edge case will only happen when a PD goes to closed/signed state and the progress report was generated in the past when it was active.

Additionally If PD is not active then in PMP we cannot "send back the report" even. Restrict in PRP API that enables this.

**Technical note**
Mostly backend task, with one frontend thing.

New reports are generated here, make sure logic complies with above: https://github.com/unicef/etools-partner-reporting-portal/blob/a7a246ce4b4074efcaa90fca161ebcd52041e328/django_api/django_api/apps/core/tasks.py#L65

Send back is review API: https://github.com/unicef/etools-partner-reporting-portal/blob/develop/django_api/django_api/apps/unicef/views.py#L578

**Comment by mjaworski** [comment]
`process_period_reports` only runs on `ProgrammeDocument.objects.filter(status=PD_STATUS.active)` so only API validation change is needed.

**Comment by mjaworski** [comment]
@marcindo please work on 459-pd-reporting-restrictions-based-on-status branch

**Comment by mjaworski** [comment]
`This edge case will only happen when a PD goes to closed/signed state and the progress report was generated in the past when it was active.` Shouldn't PD status change delete / hide those progress reports?

**Comment by marcindo** [comment]
@chachra @mjaworski frontend part is done and pushed to this branch, I've used existing logic to hide `review 'n' submit` tab and simply added next case there for pd status

**Comment by maciej-jaworski** [comment]
@marcindo Sure the correct branch was used? I dont see any commits / polymer updates in the diff

**Comment by marcindo** [comment]
@maciej-jaworski forgot to push apparently, please check now
