### ISSUE TITLE
Indicator type filter in Cluster reporting > Reporting results

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#465]
Add a “indicator type” dropdown in cluster reporting > reporting results, so indicator reports are easier to find.

**Comment by n1207n** [comment]
Once the backend filter is ready for indicator type, @marcindo can implement a filterbox to utilize the filter in UI.

**Comment by marcindo** [comment]
List of indicator types should be hardcoded on frontend or downloaded as separate request, like cluster types? New filter is added and operates on indicator_type field, but doesn't have choices defined yet. Branch feature-indicator-type-filter-cr-reporting-results-465

**Comment by n1207n** [comment]
We shouldn't hardcode in frontend and the backend should be the single source of truth. The filter options for indicator type will be provided in Django API documentation. Also, I'll provide a list of filter options in this issue for you to refer.

**Comment by n1207n** [comment]
I added indicator_type filter on IndicatorReportsListAPIView which is responsible for data on Reporting results page.

At the moment, the backend API only returns PartnerActivity/PartnerProject related IndicatorReports. So I added GET parameter to handle that.

`indicator_type` GET parameter accepts a string value of: `partner_activity` or `partner_project`

E.g) http://localhost:8080/api/cluster/2/cluster-indicator-reports-list/?page_size=10&page=1&submitted=0&indicator_type=partner_activity

E.g) http://localhost:8080/api/cluster/2/cluster-indicator-reports-list/?page_size=10&page=1&submitted=0&indicator_type=partner_project

**Comment by marcindo** [comment]
@n1207n we still need some GET endpoint to fetch label-value pairs for filter choices

**Comment by chachra** [comment]
status?
