### ISSUE TITLE
Django object-level permission for IMO to create/edit Partner projects + activities

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#471]
Django object-level permissions for ticket #466

**Comment by n1207n** [comment]
At this moment, Django-REST-Framework's permission classes are sufficient enough. Django-guardian seems overkill. Will replicate what etools Github repo has done for permission classes and customize for cluster matrix.

**Comment by n1207n** [comment]
Closing this as this may be overkill and not needed.
