### ISSUE TITLE
Searching by Report Type

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#473]
![36057271-f3600d78-0dc0-11e8-9c5a-60e7285836fc.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46bbc2ca76d5d1fedea4b910f20da0907e1e6a232d07f36621d4e670f21b78540e4248ac145f5d4cf9f18a2df0e52e6c981c49b28b380c30d43703a9b0d149b702ef2088498ce5bd8f4cc0e13f20e08d884d380c190acbae0361ffc412820db459eb5f57a7193766e77e307a47901971286d6534e6.png)

**Comment by sethgold8** [comment]
@maciej-jaworski backend should be simple, can you do it?

**Comment by maciej-jaworski** [comment]
Backend done on branch 473-search-by-report-type, still needs frontend integration.
As mentioned in PR works the same as existing `status` filter

**Comment by marcindo** [comment]
Frontend done
