### ISSUE TITLE
Continuos Load in IP Reporting on Indicators and PD list page

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#488]
Filter Box needs to load data from backend

```
indicators?pd_statuses=Act&page_size=10&page=1:45 Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
(anonymous) @ indicators?pd_statuses=Act&page_size=10&page=1:45
```

![Screen Shot 2018-02-20 at 5.22.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f36b7191a37df110294f5b585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29b41c95df742e04a53a51a3e61ee772431.png)

**Comment by rkrupinski** [comment]
@sethgold8 The error above has nothing to do with filters - ignore it.

Speaking of filters...

Some of the load data asynchronously; in this particular case it's:

- Location
- PD

When the data arrives for those filters, they consider themselves loaded and notify the parent (filters container) about the fact. When the number of loaded filters matches the total number of registered filters, the loader is removed.

Here's the thing though - the asynchronous filter only considers itself loaded when the collection of options fetched from the backend is not empty. In our case either location or pd filter gets an empty collection.

Is this a real-life scenario (which we need to account for) or just a bug?
