### ISSUE TITLE
Reduce Padding Significantly in filter components

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#502]
Filter components have a lot of padding between elements and around them in general.

Reduce padding there, but anywhere in the application as well where it makes sense, to fit more information on the screen.

**Comment by marcindo** [comment]
@sethgold8 right now padding in filters is 25px, you want me to reduce it how much? To 15px, 10px?

**Comment by marcindo** [comment]
Also we have a lot of padding, which usually is based around 25, sometimes 24, 15, 16px  and sometimes just rems. I think that unifying those and using smaller padding is desirable but what guidelines should we follow?

**Comment by kasialanecka** [comment]
@sethgold8 @marcindo I would suggest 15px in Filters for a box, margin between inputs 15px as well. For the rest of the app - 24px between cards as we have now, as I remember, is from uncief quidelines.

**Comment by sethgold8** [comment]
#worksgood :) - Seth and Kasia
