### ISSUE TITLE
Hide pagination controls in tables everywhere if 5 or less results in the table?

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#508]
Looks weird to have the controls with less data.

![cluster_reporting___prp](https://user-images.githubusercontent.com/73096/36763681-d9e2eeda-1bdd-11e8-95ce-49ef326d6ebc.png)

**Comment by marcindo** [comment]
I believe it only makes sense to edit etools component, otherwise this task will take a lot of work, so I opened PR there https://github.com/unicef-polymer/etools-data-table/pull/29

**Comment by marcindo** [comment]
Pr was merged, so new version of data-table already supports it in staging

**Comment by sethgold8** [comment]
tested. good to go :)
