### ISSUE TITLE
In edge cases display_type is not passed to backend on indicator create leading to 500 error.

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#510]
Its tough to re-create sometimes. Refresh screen etc. Gives 500 error.

I had baseline > target, got 400 error, then fixed it and then get this. It can be tricky to replicate, but happens with consistency sometimes.

![cluster_reporting___prp](https://user-images.githubusercontent.com/73096/36765674-42832a82-1be7-11e8-9e44-0aba7b860bd1.png)

**Comment by marcindo** [comment]
For the record, this was happening when modal was canceled and opened again, displayType and type didn't refresh properly

**Comment by sethgold8** [comment]
#worksnow -Seth
