### ISSUE TITLE
Harmonize the icons that appear on indicator report rows in cluster and IP reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#513]
In cluster:
- extra icon that shows due/overdue. This is fine.

In both cluster and IP when looking at an indicator report row:
- [x]  big icon that seems is getting linked with due/overdue hence 2 red icons always. This icon was supposed to show if this all location data for this indicator report has been entered by the user.

![Screen Shot 2018-04-16 at 10.13.50 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f56b7191a379ef0c2a52415a4ebc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f349e24455a5133567e570326e0a.png)

- [ ] Show incomplete in IP does not work also. Locations have been entered and this Report is 'Due'; not 'Overdue'.

![Screen Shot 2018-04-16 at 10.51.00 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f56b7191a379ef0c2e50415f4ebc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e24455a5123466e0763f6e0a.png)

**Comment by marcindo** [comment]
@chachra  I believe I'd need separate field on the endpoint to mark that, there is can_submit but it has more checks than just locations completed

**Comment by momimomo** [comment]
Fixed, changed 
```<report-status
                        status="[[data.report_status]]"
                        no-label>
                    </report-status>```

to `status="[[data.overall_status]]"` in `cluster-report.html`

**Comment by sethgold8** [comment]
@momimomo 

- [ ] For IP, Icon should be green if data is filled out. (Photo below refers to both). It does not have to do with due/overdue
- [ ] Also if it is filled out, it should not be shown when user asks for ‘show incomplete only’


![Screen Shot 2018-04-18 at 11.51.23 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a379ee0c2e50415d4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e54d52ac123663e170336e0a.png)

**Comment by momimomo** [comment]
In cluster I was able to fix it easily because all the data is received in one request, and the desired fields are there.

In this case we need additional field which should be calculated in backend by checking if every`is_complete` in `disaggregations.indicator_location_data` is true for a given lower level output. Then it should available in `lower_level_output.indicator_report[x]` also as `is_complete` Boolean. 

Right now there is no way to calculate the icons, because the data regarding the locations isn't available until dropdown is clicked.

**Comment by maciej-jaworski** [comment]
Delivered API improvement directly on develop.

**Comment by sethgold8** [comment]
#looks good. 

I noticed if I entered data and then change the # to 0, it marks it with a green check...but am going to assume that would be ok if the user entered the data 0. Onward and upward.
