### ISSUE TITLE
Drilldown (Showing Reports) in Dual reporting for Cluster Indicators and Unicef Indicators

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#517]
- [ ] 17> On the indicators page, in the drill down if the indicator has cluster then the 2 tables must display the current cluster and UNICEF reports, If the indicator has only UNICEF indicator then the tables must display the current and previous progress reports, the overall status + narrative must be removed in both the scenarios.

**Comment by chachra** [comment]
not needed anymore per discussions, simple solution put in place.
