### ISSUE TITLE
Unable to download progress report attachment on staging

### ISSUE THREAD

**Issue by marcindo** [unicef/etools-partner-reporting-portal#523]
On staging, after adding attachment to progress report, user is not able to download upload file. Looks like the link is ok, but file is just not there. It works well on local build

**Comment by maciej-jaworski** [comment]
#481 takes priority, but just a note - the issue is that the url returned from backend is relative (because staging doesn't use external storage) so the request gets forwarded to frontend and it doesn't know what to do with the url

**Comment by maciej-jaworski** [comment]
Backend returns the proper link now but frontend treats it as a frontend url and hijacks the route.
Informed @marcindo on the issue.

**Comment by sethgold8** [comment]
getting this blank screen and no download

![Screen Shot 2018-03-16 at 10.10.45 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f56b7191a379ef0c2a51415b4bbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e04c5ca113316be670356e0a.png)

**Comment by maciej-jaworski** [comment]
Why am I assigned again, when this is 100% on the frontend side.

**Comment by rkrupinski** [comment]
I wish I could test that. Staging's got no data.

**Comment by rkrupinski** [comment]
> It works well on local build

Actually, it doesn't and never did. It only "worked" when you viewed the app from `localhost` and the attachment was served from `127.0.0.1`. Upon clicking DOWNLOAD, the host got changed from `localhost` to `127.0.0.1` which prevented polymer routing from picking up the change.

A dumb question - would that be possible to host attachments on a subdomain?

**Comment by maciej-jaworski** [comment]
Finally was able to set up S3 for staging, seems last time I tried AWS was having some issues, just my luck.

Older attachments won't work since they are still stored locally but everything else should now work fine.

**Comment by sethgold8** [comment]
@maciej-jaworski just want to make some notes since I know this will change as we move to production (with Microsoft Azure Service) and away from AWS. When downloading the image it creates a URL which works. Would be good to have a traditional download so it saves to my desktop instead of browser opening image. Also we need to make sure the URL is signed URL so that it is a safe public url.

Since this will change during production, i don't think we need to go overkill and make all of these now, but it will be needed for production. 

Opening a new ticket for file storage

**Comment by maciej-jaworski** [comment]
Azure and AWS can be used interchangeably (see https://github.com/unicef/etools-partner-reporting-portal/blob/develop/django_api/django_api/settings/base.py#L417).

In my testing AWS URLs have been signed, have not tested Azure.
