### ISSUE TITLE
Allow running the bundled version of the polymer app (+ the api, of course).

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#53]

**Comment by rkrupinski** [comment]
Any progress here? The codebase is growing rapidly.

**Comment by rkrupinski** [comment]
@n1207n ?

**Comment by chachra** [comment]
Lets review how other eTools codebases have done it (on dockerfile or dev or both)

https://github.com/unicef/etools-partnership-management#run-application

https://github.com/unicef/etools-partnership-management/blob/master/Dockerfile

Can you document here @rkrupinski how you're doing this on dev. currently or will if you were not using docker at all? I have to think its a simple build command and then we serve off bundled folder via node server like in other eTools repos afaik.

**Comment by rkrupinski** [comment]
I currently don't do it. The only thing I make sure of is that the app bundles (linters/minification/import resolving passes without errors). My concern is that port clash will occur when running node server outside of docker + the API within. I may be mistaken though. If that's the case, we only need a port to run node server on in order to talk with the api seamlessly.

**Comment by rkrupinski** [comment]
@n1207n Any progress here?

**Comment by n1207n** [comment]
It's halted at the moment to focus on Location/CartoDB syncing and other APIs work. :(

**Comment by chachra** [comment]
@robertavram thoughts on this task from your previous experience? How best to take polymer code and make it optimized for production deploy? Tx

**Comment by robertavram** [comment]
we have addressed this... we build manually (gulp) and then run a different fab command that runs the application from the built container...
fab devup_built on etools-infra

**Comment by chachra** [comment]
@n1207n can you please help in getting this live please? Whatever changes on docker cloud or otherwise need to happen for it? Tx.

**Comment by n1207n** [comment]
I tried doubling `max_old_space_size` size but it failed quickly. I assume my laptop memory couldn't take that size, as doubling that amount was 4GB.

```
Killed
polymer_1     | npm ERR! code ELIFECYCLE
polymer_1     | npm ERR! errno 137
polymer_1     | npm ERR! polymer-starter-kit-custom-build@0.0.0 bundle: `node --max_old_space_size=4096 ./node_modules/gulp/bin/gulp`
polymer_1     | npm ERR! Exit status 137
polymer_1     | npm ERR! 
polymer_1     | npm ERR! Failed at the polymer-starter-kit-custom-build@0.0.0 bundle script 'node --max_old_space_size=4096 ./node_modules/gulp/bin/gulp'.
```
