### ISSUE TITLE
Make all fields in partner sync work properly. ...partner type date last accessed, address, phone , number, email are not appropriately synced.

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#535]

**Comment by n1207n** [comment]
Rob from etools repo said he's gonna take a look at it now. Stay tuned.

**Comment by n1207n** [comment]
Rob closed the issue on etools, assuring API is good. This confirms the data on staging is not verbose and our syncing has been working well.

Closing this.
