### ISSUE TITLE
Update Fields for Adding a Project

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#536]
- [ ] add project and  show more details when adding a project https://projects.invisionapp.com/d/main#/console/13398823/279786970/preview
https://projects.invisionapp.com/d/main#/console/13398823/279786971/preview

- [ ] project details with 'Show more details' https://projects.invisionapp.com/d/main#/console/13398823/279786972/preview
https://projects.invisionapp.com/d/main#/console/13398823/281180875/preview
- [ ]  edit project with edit 'show more details'
https://projects.invisionapp.com/d/main#/console/13398823/279786975/preview
https://projects.invisionapp.com/d/main#/console/13398823/279786984/preview

**Comment by sethgold8** [comment]
@maciej-jaworski this is regarding custom, not OCHA

**Comment by sethgold8** [comment]
https://www.dropbox.com/sh/85j18mgg90sfdfj/AADnUKBn0rUbVXrpnuRVf9WBa/OPS%2C%20FTS%2C%20RPM%20(API%20materials)?dl=0&preview=Additional+information+fields+needed+for+financial+reporting.xlsx

**Comment by marcindo** [comment]
Just the display of the fields is sitting on  `536-update-fields-for-adding-project` branch

**Comment by maciej-jaworski** [comment]
Should `Funding gap` be calculated automatically based on `Funding Requirements` and sum of all individual funding fields?

**Comment by sethgold8** [comment]
waiting on confirmation from Gavin in the specs (bc he mentioned something about Funding Paid). 

I believe it should be Funding Gap = 100 *(Funding Received/Funding Requirements). I will let you know once he confirms.

**Comment by maciej-jaworski** [comment]
<img width="745" alt="screen shot 2018-04-09 at 08 56 30" src="https://user-images.githubusercontent.com/1492815/38483642-014fd2ec-3bd4-11e8-9eb9-2cb3480420c4.png">
Some fields are mocked up as choicefields, is there a source for available choices?

**Comment by maciej-jaworski** [comment]
Think most of the work on my part is done, @momimomo reach out if you run into any issues.

**Comment by momimomo** [comment]
Changes requested by Unicef on callin on Thu, 12 for location of custom fields pushed to the PR for this branch. Funding gap and other fields are working after changing some keys.

**Comment by maciej-jaworski** [comment]
Fields such as agency name / type are mocked as choicefields, where do we get the choices for 'em?

**Comment by sethgold8** [comment]
@momimomo 
- [ ] When user clicks 'edit' they should go directly to the indicator where they can edit. Right not we are asking the Partner, if it's from OCHA, or Custom.

![Screen Shot 2018-04-18 at 10.49.45 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a379ef0c2f58415b4bbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b49c259f349e54d52a71a3162ee72326e0a.png)

Just have it edit the indicator details. Hopefully this is a quick fix.

![Screen Shot 2018-04-18 at 10.53.21 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a379ef0c2e52415d4fbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e54d52a0123560e675306e0a.png)

**Comment by momimomo** [comment]
Edit changed.

However, I don't think I understand the problem that the 0s affect the funding gap in OCHA... 

It works properly when defining custom project, but ocha projects don't have funding requirements after import as of now, only `total budget`. If `currentRequestedFunds` are the same as `Required Funding`, then they are not passed through in API. I can see them in project details while connecting to ocha, but in project details in our API, im getting always `required_funding` as null @maciej-jaworski . 

That's why it's displayed as 0. If it's edited as a custom afterwards, all values are calculated properly. So if the field will be passed, funding gap should be also working fine too.

**Comment by maciej-jaworski** [comment]
Change the default to 'N/A' or '---' anyway, putting 0 in there is confusing and suggest data is available.

**Comment by momimomo** [comment]
Done.

**Comment by momimomo** [comment]
so if errors are displayed it's only issue in backend.

**Comment by sethgold8** [comment]
@momimomo yes please make 'additional info' optional. Also if I'm going to re-edit 'total budget' and 'funding source' can we have them as '---'. This way if I edit other details, I am not forced to enter something that might be incorrect.

**Comment by momimomo** [comment]
You mean in the editable form? Let's clear that on standup, but the Funding gap will be recalculated based on other fields even if data for it is sent, and should be displaying properly in project details.

**Comment by sethgold8** [comment]
@momimomo let's make total budget, additional info, funding source not mandatory

**Comment by sethgold8** [comment]
@maciej-jaworski we are curious if we're getting all the data here. It just seems weird OCHA would have all of this data but not 'Funding Source' or 'Total Budget'. Can we double check?

cc @momimomo @n1207n

![Screen Shot 2018-04-23 at 10.05.15 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a379ef0c2b54415e4bbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e54855a7123165ef75346e0a.png)

**Comment by maciej-jaworski** [comment]
Funding source and budget are dependant on FTS data availability.

**Comment by sethgold8** [comment]
@maciej-jaworski let's make total budget, additional info, funding source not mandatory for Projects from OCHA. The reason is if someone pulls a project and wants to edit one of those fields, they will not be able to if they don't have the correct data for all. If this is an issue since it contradicts with 'Custom Projects' and those being mandatory, then please leave as is.

**Comment by momimomo** [comment]
We're still waiting for options to select in dropdowns @maciej-jaworski mentioned 16 posts earlier: https://user-images.githubusercontent.com/1492815/38483642-014fd2ec-3bd4-11e8-9eb9-2cb3480420c4.png

**Comment by momimomo** [comment]
Changed `name of funding agency` to string input.

**Comment by sethgold8** [comment]
working :)
