### ISSUE TITLE
Import/Export Template for Indicator Reports

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#538]
- [ ] Import needs to function the same as an upload file @rkrupinski . This should be the same file format as the export (csv).

- [ ] We need to hide import function in 'submitted tab' @rkrupinski 

![Screen Shot 2018-04-04 at 3.38.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f76b7191a37bf111234f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df449e94554a11b3060e0722431.png)

- [ ] current bug when exporting indicators. It's trying to grab partner activity from Cluster activity, but cluster activity might not have been adopted yet
![Screen Shot 2018-04-04 at 3.38.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f76b7191a37bf111234f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df449e94554a1123760ee7e2431.png)

----

For the task below on downloading template, do not do. Might not be necessary so leaving it here just in case - Seth

- [ ] way for user to download the template file; which can then be re imported/uploaded @rkrupinski

**Comment by maciej-jaworski** [comment]
Import feature was done by @dfryta, reassinging to him since he's back. Also added frontend dev since changes there are mentioned.

**Comment by dfryta** [comment]
- hide import function in 'submitted tab' (@rkrupinski frontend work)
- for import doc, there should only be 1 tab. Right now there are tabs for dissagregations (yes if you are using normal export and this is correct. It was required feature to split disaggregations to possible combinations to avoid super wide empty columns in most cases. There is also `cluster-indicator-reports-list/export-for-analysis/` that merges everything into one tab.
- yes, but AFIK it was never done - basic idea of whole import/upload was possibility to edit data by user directly in excel and upload it back.

@chachra might know more here, since my knowledge might be obsolete

**Comment by rkrupinski** [comment]
- [x] hide import function in 'submitted tab'

**Comment by sethgold8** [comment]
@dfryta great regarding tabs. We will leave as is to avoid super wide empty columns, unless they ask us to switch. Removing from task list above

**Comment by dfryta** [comment]
This task is related to #269 and #88. Please confirm if specification is still same.

**Comment by sethgold8** [comment]
@dfryta So I'm thinking all we need is import and export. Export can download everything. Partner can use that that template (the export they just downloaded) to enter any data and import (upload) back into the system. 

So let's say I'm a partner. I download the template and It should include multiple rows with indicators, locations etc and data on targets, in-need, baseline (where available in PRP). 

The only thing that should be blank (no data) should be the column that the partner can report on (dissagreggations). If it's already been reported then it will be there. 

If they have not stated targets in PRP then that column might have no data and could also be filled to be imported. 

The original #269 and #88 should be the same and an example here https://docs.google.com/spreadsheets/d/1q5KdU2dRckCEqsJB5pVC3ZLmDMzZDeT8-kK1F3Tn_mA/edit?usp=sharing

cc @chachra

**Comment by dfryta** [comment]
```So I'm thinking all we need is import and export. Export can download everything. Partner can use that that template (the export they just downloaded) to enter any data and import (upload) back into the system.```
You messed import with export but overall is OK. User Imports data from platform and Exports to platform.
```So let's say I'm a partner. I download the template and It should include multiple rows with indicators, locations etc and data on targets, in-need, baseline (where available in PRP).```
That is correct.
```The only thing that should be blank (no data) should be the column that the partner can report on (dissagreggations). If it's already been reported then it will be there.```
Errr... I don't get it. User always import all data :-)
```If they have not stated targets in PRP then that column might have no data and could also be filled to be imported.```
AFAIK only disaggregations data must be uploaded.
```The original #269 and #88 should be the same and an example here ```
Import is already done (normal Import (seperated by tabs) and Import for Analysis (all data in one tab). Export was never done and AFAIK it should be done only from Import file (seperated by tabs).

HOWEVER, please confirm format and data didn't change for past 7 months.
- isn't baseline and target are also under locations now? Old format do not include these. -- - 
- how about 'In need' field that was added some time ago? etc.

@chachra please confirm if I should start doing this ticket

**Comment by sethgold8** [comment]
@dfryta Baseline and Target can be set at the indicator level. They can also be set at the location level by the partner. The Clusters section goes into more detail https://docs.google.com/document/d/1y_uypqOqj-NSEVedk1aN10zIGADhe1u5COdqYnbqQF8/edit?ts=5acbec07#heading=h.h7et8x99ph . I will be updating it into Gitbook as well also after Gavin confirmation. That spec is the most up to date though of everything

In-Need is optional for quantity indicators. Imo can set In-need for the indicator level and Partner can set for location. (This is in the indicators section as well in the specifications)

**Comment by sethgold8** [comment]
@dfryta spoke with @chachra earlier. Yes if you have bandwidth can you please move forward with the ticket.

**Comment by dfryta** [comment]
@rkrupinski please:
- [] change Export to Import
- [] add Export button (file chooser) that points to `'^(?P<response_plan_id>\d+)/cluster-indicator-reports/import/`

**Comment by sethgold8** [comment]
- { ] we need to figure out a way to make sure partner does not enter data for other partners

**Comment by dfryta** [comment]
@sethgold8 I cannot recreate this locally. How did you get indicators from OCHA?

**Comment by dfryta** [comment]
I cannot recreate #1. Please open new ticket if happens again.

**Comment by n1207n** [comment]
@dfryta,

Based on the staging data, Libya 2018 response plan from OCHA seems to have some OCHA indicators. (In case you wanna replicate this locally)

In staging ,we were able to produce 500 error when exporting indicators in Reporting results tab in 2 different cases:

1. In Iraq 2018 response plan, we encountered this error:
```
AttributeError at /api/cluster/115/cluster-indicator-reports/export/
'NoneType' object has no attribute 'id'

537: /code/django_api/apps/cluster/export_indicators.py in export_data
              if not self.fill_sheet(disaggregation_types): 

250: /code/django_api/apps/cluster/export_indicators.py in fill_sheet
                    column=37).value = cluster_objective.id

```

2. In Libya 2018 response plan (where OCHA imported indicators exist), we encountered this error:
```
AttributeError at /api/cluster/133/cluster-indicator-reports/export/
'NoneType' object has no attribute 'partner_activities'

537: /code/django_api/apps/cluster/export_indicators.py in export_data
            if not self.fill_sheet(disaggregation_types): ...

140: /code/django_api/apps/cluster/export_indicators.py in fill_sheet
                partner_activity = cluster_objective.cluster_activities.first().partner_activities.first() 
```

In `fill_sheet` method, you are trying to grab cluster_objective, cluster_activity, partner_activity, and partner_project from each IndicatorReport object in self.indicators.

```
cluster_objective = indicator.reportable.cluster_objectives.first()
cluster_activity = indicator.reportable.cluster_activities.first()
partner_project = indicator.reportable.partner_projects.first()
partner_activity = indicator.reportable.partner_activities.first()
```

This is not correct way of getting each cluster object. Above code is using GenericRelation object. Any of those cluster objects can be null if you use above method.  Depending on what GenericForeignKey in Reportable is pointing to, you need to grab each cluster object correctly.

Check the reportable's content_object with `isinstance` and grab cluster objects properly via its foreignkey objects.

**Comment by dfryta** [comment]
@n1207n let's talk on daily, since I cannot reproduce this locally.

**Comment by sethgold8** [comment]
In Iraq 2018 as admin_imo
app/IRQ/cluster-reporting/plan/115/results/draft?page_size=10&page=1&indicator=4413

![Screen Shot 2018-05-21 at 10.24.56 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a379ef0c2955415a48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e74457a7153062ee77306e0a.png)

Libya 2018 as admin_imo
app/LBY/cluster-reporting/plan/133/results/draft?page_size=10&page=1&indicator=4418

![Screen Shot 2018-05-21 at 10.10.32 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a379ef0c2a51415c4cbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e74457a7153f64ee71316e0a.png)

**Comment by sethgold8** [comment]
@dfryta 

On **staging** in Iraq 2018 as imo /IRQ/cluster-reporting/plan/152/results/draft?page_size=10&page=1&indicator=6544  generated template and then entered new data in 'Short' and 'Tall' column. Also tried doing all 3 with 'Total' but received this error.

![Screen Shot 2018-05-25 at 4.59.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f66b7191a37cf117224f5e5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ce34457ad10366ae7722431.png)

![Screen Shot 2018-05-25 at 5.00.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f66b7191a37df1122b4f5a585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44ce34457ad103e6bef7f2431.png)

I am unable to to test for indicators from OCHA as we are not getting those at the moment. There must be a change from OChAs end but I imagine there might be some issues with import/export of OCHA indicators too (since there was previously)

When I downloaded with data and edited the data, and re-uploaded it did work.

**Comment by sethgold8** [comment]
@dfryta any update? We were able to get OCHA indicators for Libya 2018 as Admin_IMO. Received this error message when trying to generate export template

![Screen Shot 2018-05-29 at 5.32.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456fa6b7191a37df111294f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ce74955a010326bee732431.png)

**Comment by sethgold8** [comment]
@dfryta spoke with @chachra. We should not allow Partner/IMO to upload partial data for a specific indicator

**Comment by sethgold8** [comment]
Need to make sure location id text is plain text on Google Sheets. Google Sheets saves it in a different format.

**Comment by dfryta** [comment]
Done.

**Comment by sethgold8** [comment]
- [ ] Once an indicator is submitted, it should not change (unless it is sent back).  Right now IMO or Partner are able to change submitted indicators when they import the template

- [ ] For both Percent Indicators and Ratio Indicators, Google Sheets sometimes perceives a single digit number as a data and then throwing an error. Can we have the format default to no dates for those columns? Am open to suggestions in solving this. 

For example, it thinks 5/5 is May 5.
![Screen Shot 2018-06-07 at 11.45.33 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f46b7191a379ee0c2f54415c4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e94954a61b3763e472376e0a.png)

- [ ]  When user alters Disaggregation Subtotal (2 different disaggregations added together) data it has a confusing error message. Disaggregation Subtotal should not be changed so we should make sure the users knows this with validation saying: "Please import only disaggregation data"

Example here where the user changed the Gender + Height disaggregation subtotal. 

![Screen Shot 2018-06-07 at 2.17.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f46b7191a37af1132c4f5e5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df443e54c56a4103765ef712431.png)

**Comment by sethgold8** [comment]
Technical notes: please use the san submit metafield @dfryta

**Comment by dfryta** [comment]
Done (excluding Google Sheets). Please check.

**Comment by sethgold8** [comment]
both work good :). Let's discuss potential solutions like error validation message regarding google sheets assuming its date (day/month) at our standup
