### ISSUE TITLE
Integrate with RPM for Response Plan Sync [ Cluster Objectives and Cluster Activities and Associated Indicators ]

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#539]

**Comment by maciej-jaworski** [comment]
- Importing happens into an existing workspace
- GET Response Plans by single / multiple countries (get from workspace)
- Use OCHA provided cluster names
- Endpoint to import POST-ed plan id

**Comment by maciej-jaworski** [comment]
@marcindo From the frontend POV this is done, 2 new endpoints.
To create custom response plan:
`/api/core/workspace/<workspace_id>/response-plan/create/`

For imports:
`/api/ocha/response-plans/workspace/<workspace_id>/`
- GET gets you a list for current workspace
- POST-ing a `plan` parameter triggers an import

There will be an update to finalize RP import, but completely transparent to the frontend.

**Comment by maciej-jaworski** [comment]
Do we want to make it so that a plan can only be imported once - hide already imported plans from choices in the modal and block a repeated import on the backend?

@chachra @sethgold8

**Comment by sethgold8** [comment]
yes only import once @maciej-jaworski .

 No we do not want to hide imported plans from choices in the modal.

Yes block repeated import on the backend. Throw an error so the frontend can catch it

**Comment by sethgold8** [comment]
@maciej-jaworski looks good when selecting the RP. Went through a few but didn't see any cluster objectives but not sure if that's just bc the data isn't missing. Is there a specific few RP's I should test

**Comment by maciej-jaworski** [comment]
A lot of them come up empty, when testing plans for Palestine (PSE) seemed to be the most complete.

**Comment by sethgold8** [comment]
We are getting Clusters, but not the Objectives or Activities.


![Screen Shot 2018-03-28 at 4.42.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fb6b7191a37cf116294f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df449e34555a2113367ef7e2431.png)

 Also we cannot test Palestine because it is not coming up with any response plans

![Screen Shot 2018-03-28 at 4.44.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fb6b7191a37cf1162f4f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df449e34555a3123763e2772431.png)

**Comment by maciej-jaworski** [comment]
You had palestine setup with SOP country code, which doesnt even seem to be a valid country code.
valid code for palestine is PSE

**Comment by maciej-jaworski** [comment]
@chachra @sethgold8 
About 50% of the time I tested this, the request timed out, the other half was usually cutting it close at around 50s
I've changed the code to only save response plan in the request and then trigger background task to get objectives and activities. 
This works really well, small improvement would be to add some small info text / box with something like `Response plan saved, it may take a couple of minutes to synchronize Objectives and Activities`

**Comment by sethgold8** [comment]
#works good w/ PSE :)

**Comment by maciej-jaworski** [comment]
@sethgold8 They are imported correctly, reason those are broken in the UI are changes by @n1207n mentioned in #568

**Comment by sethgold8** [comment]
@maciej-jaworski will push this forward after we get the whole loop successfully on CHAD and Libya
