### ISSUE TITLE
All labels in the interface should be translation proof for the future

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#54]
Potentially sufficient solution: https://github.com/PolymerElements/app-localize-behavior

**Comment by chachra** [comment]
LOE / evaluation of this? please add "technical note" in the description @rkrupinski . @robertavram thoughts on how eTools has done this?

**Comment by rkrupinski** [comment]
The frontend part of it should be pretty straightforward given there's https://github.com/PolymerElements/app-localize-behavior and assuming that it works as described. In some cases (e.g. error messages) we display contents of the API response unchanged.

**Comment by chachra** [comment]
Asked Adrian for feedback.

**Comment by adi130987** [comment]
@chachra I have not tried `app-localize-behavior` yet. Another option would be this element https://www.webcomponents.org/element/ebidel/i18n-msg/elements/i18n-msg.

I would use `Polymer.AppLocalizeBehavior`, it has all the functionality needed for internationalization, it has caching and you can have parameters in translated messages (https://formatjs.io/guides/message-syntax/).
