### ISSUE TITLE
Integrate with New OPS for Cluster Projects and Partner Activites Sync + Custom Project Creation

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#540]

**Comment by maciej-jaworski** [comment]
<img width="753" alt="screen shot 2018-03-20 at 12 01 44" src="https://user-images.githubusercontent.com/1492815/37650880-9d4032a8-2c36-11e8-801b-f85bf52e0b59.png">

Fields like status and additional information don't seem to be coming from OCHA.

**Comment by maciej-jaworski** [comment]
For custom project I assume available clusters should be a subset of response plan clusters.

**Comment by maciej-jaworski** [comment]
<img width="752" alt="screen shot 2018-03-21 at 12 51 44" src="https://user-images.githubusercontent.com/1492815/37708382-ba52676e-2d06-11e8-8e17-6454b0d2675a.png">

https://projects.invisionapp.com/d/main#/console/13398823/279786970/preview

Theres no place to select / create partner in this form. Backend **doesn't allow project creation with no partner**. Do we want to:

1. Add partner selection / creation on the frontend
2. Change backend schema

cc @chachra @sethgold8

**Comment by maciej-jaworski** [comment]
Should we allow creation of projects with dates in the past?
