### ISSUE TITLE
baseline, target, in- need save in json field

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#547]
https://unicef.gitbook.io/prp/product-end-user-documentation/cluster-reporting/cluster-indicators

**Comment by sethgold8** [comment]
- [ ] Frontend does not see edit button on Partner Activity indicator list. Partner needs to edit Locations for reports to be generated. We think this is only on Partner Activity adopted from Cluster Activity

![screen_shot_2018-03-28_at_3.39.46_pm.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46fb978826878d969ce1b0579b0fa0c5710b77206456fb147191dc7bf111224f5b5921ec1c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df449e34a5da0143060e3732431.png)

- [ ] For Ratio and Percent Indicator: Baseline + Target not showing 
- [ ] For Ratio and Percent Indicator: Against Target Indicator and Against In-Need % not working

![screen_shot_2018-03-28_at_3.38.53_pm.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46fb978826878d969ce1b0579b0fa0c5710b77206456fb147191dc7bf111234f5a5c21ec1c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df449e34a5da01a3467ee7f2431.png)

**Comment by chachra** [comment]
@n1207n The indicator response only has percentage_progress, just like in analysis we need 2 fields returned not just one.

**Comment by chachra** [comment]
@n1207n when target is 200%, filed a report with 20%, shows progress percent 105263.11 and "achieved" is being reported as {c: 20000000, d: 600, v: 120}. Seems like a bug, can you please test? Thanks.
