### ISSUE TITLE
Data model changes

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#55]
+ Add docstrings to each model
+ PartnerProject - change location to locations
+ Indicator - add frequency of reporting to it
+ active flag on disaggregation on blueprint
+ move disagg and disagg options on reportable model to separate models than jsonfield. reportable -> disaggregation -> disaggregation values (this is https://www.evernote.com/l/AAXVTEhv0TBKqbVZ3PqK6QWKv73sVHGu2_o not the data associated with it... thats in IndLocationData of course)

**Comment by chachra** [comment]
@lkolacz please do on new branch. There are probably more things as well, this is a WIP task. Tx.

**Comment by lkolacz** [comment]
branch for this task `feature-data-model-changes-#55`

**Comment by lkolacz** [comment]
@chachra not sure about this part..
`active flag on disaggregation on blueprint`
You want to have a boolean field `active` for `IndicatorBlueprint` model?.. 
Please bring me more details about this part.
Thx!

**Comment by lkolacz** [comment]
@chachra I am confused in this part:
```
move disagg and disagg options on reportable model to separate models than jsonfield. reportable -> disaggregation -> disaggregation values (this is https://www.evernote.com/l/AAXVTEhv0TBKqbVZ3PqK6QWKv73sVHGu2_o not the data associated with it... thats in IndLocationData of course)
```
more less draft of the above idea will be something like this (I guess):
```
--- a/django_api/django_api/apps/indicator/models.py
+++ b/django_api/django_api/apps/indicator/models.py
@@ -42,6 +42,14 @@ class IndicatorBlueprint(TimeStampedModel):
         super(IndicatorBlueprint, self).save(*args, **kwargs)
 
 
+class Disaggregation(TimeStampedModel):
+    by = models.CharField(max_length=255, null=True, blank=True)
+    group = JSONField(null=True)
+
+    def __str__(self):
+        return "Disaggregation <pk:%s>" % self.id
+
+
 class Reportable(TimeStampedModel):
     target = models.CharField(max_length=255, null=True, blank=True)
     baseline = models.CharField(max_length=255, null=True, blank=True)
@@ -55,7 +63,7 @@ class Reportable(TimeStampedModel):
 
     # variable disaggregation's that may be present in the work plan
     # this can only be present if the indicatorBlueprint has dissagregatable = true
-    disaggregation_logic = JSONField(null=True)
+    disaggregation = models.ForeignKey(IndicatorBlueprint, null=True, related_name="reportables")
```
correct me please .. bring more Your thoughts to me please :)

**Comment by chachra** [comment]
@lkolacz "disaggregation values" == new model, not a JSONField. please change that.

Also Disaggregation should have fk to Reportable (Reportable can have MANY Disaggregations which can have MANY disaggregation values). See mockups for it.

active flag should be added to both Disagg and DisaggValues model per your previous comment. Thanks!
