### ISSUE TITLE
Future Potential Enhancements for Analysis

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#554]
Future Potential Enhancements
- [ ] Option to export for each component - chart, map, etc.
- [ ]  Cluster icons on map
- [ ] HRP/Country/emergency name is not mentioned on the page title - its in the top right bar, but can be added if it's confusing in the future.

**Comment by n1207n** [comment]
There has not been new additions to Cluster analysis features. Closing this as irrelevant but we may create a new ticket if needed.
