### ISSUE TITLE
Adding/Editing Projects and Indicators as Partner + IMO

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#559]
- [x] adding a project as partner creating 500 bug

```
TypeError at /api/partner/250/partner-project-list/
Got a `TypeError` when calling `PartnerProject.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `PartnerProject.objects.create()`. You may need to make the field read-only, or override the PartnerProjectSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 916, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 392, in create
    obj = self.model(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 572, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'funding_source' is an invalid keyword argument for this function
```
![Screen Shot 2018-03-22 at 3.29.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f16b7191a37bf110224f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae64852ac13356aef742431.png)

- [x] Funding source not saving when editing project for imo and partner

![Screen Shot 2018-03-22 at 3.31.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f16b7191a37bf1112a4f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae64852ad10356be57f2431.png)

- [x] editing a project as IMO has a 400 error so user cannot move forward.

- [x] Make sure we call `check_progress_values` in Cluster indicator serializer update method.

- [x] getting errors adding a cluster activity. Polymer needs to update.
![Screen Shot 2018-03-22 at 4.24.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f16b7191a37cf1102f4f5a565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44ae64b54a512316be4772431.png)

- [x]  Still seeing Cluster not populating when you create a Cluster Activity

![Screen Shot 2018-04-04 at 4.11.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f76b7191a37cf1132a4f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df449e94556a3133261e5702431.png)

**Comment by maciej-jaworski** [comment]
Adding @momimomo for the frontend bugs.

**Comment by maciej-jaworski** [comment]
Fixed all the backend issues.

For project creation / edit errors are not displayed in the UI, meaning #511 is not completed everywhere.

> editing a project as IMO has a 400 error so user cannot move forward
This is almost fixed - fixed the serializer issue, but on the backend it is verified that the partner belongs to on of IMOs clusters before performing update, on the frontend it seems edit button is always displayed.

**Comment by maciej-jaworski** [comment]
<img width="1421" alt="screen shot 2018-04-18 at 10 55 57" src="https://user-images.githubusercontent.com/1492815/38921891-1d469240-42f7-11e8-8462-3467bcb7f5b8.png">
Works fine here.

**Comment by sethgold8** [comment]
Moved adding an activity as imo has 500 error to a different ticket
