### ISSUE TITLE
Filter for PD status not working

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#561]
![Screen Shot 2018-03-22 at 5.03.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f16b7191a37df112284f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae64b56a1133160e2732431.png)

**Comment by rkrupinski** [comment]
Indeed, there was a bug. It is now fixed on staging.
