### ISSUE TITLE
Cannot add cluster objective

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#568]
{cluster_title: ["This field is required."], error_codes: {cluster_title: ["required"]}}
cluster_title
:
["This field is required."]
error_codes
:
{cluster_title: ["required"]

**Comment by n1207n** [comment]
Direct commit to develop branch and merged develop into `feature-indicator-modal-changes-546` as well. Should be fixed.

**Comment by sethgold8** [comment]
- [ ] We are naming the Cluster Objective, by what Cluster it is in

**Comment by n1207n** [comment]
I only made change so that CO and CA can be created from UI. There have been changes to how cluster imported name is used instead of provided CO and/or CA title from OCHA integration. I think @maciej-jaworski may have answer to this. Otherwise, I can try to change API serializer to use CA/CO title again.

**Comment by sethgold8** [comment]
@maciej-jaworski have you see this?

**Comment by maciej-jaworski** [comment]
My cluster title changes have been done in a rather transparent way to the frontend.

Cluster title has been broken in this commit:
https://github.com/unicef/etools-partner-reporting-portal/commit/04f8a30e26d2b1ef158122cf2f173784d8918196#diff-592e9832fdb580dbb8e945ed8a62c34f

As to why the title edit isn't working I don't know, but unlikely this was any of my changes.

**Comment by sethgold8** [comment]
@maciej-jaworski 2 checkboxes above work good now :)

- [ ] Still seeing Cluster not populating when you create a Cluster Activity

![Screen Shot 2018-04-04 at 4.11.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f76b7191a37cf1132a4f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df449e94556a11a3e62e07e2431.png)
