### ISSUE TITLE
Misc. UX issues

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#569]
- [x] Shows this message even when no disaggs in the indicator "If one or more disaggregation box is unchecked, the reporting table will be simplified however the report will not be in line with the disaggregation agreed in the PD/SSFA."

- [x] Show labels as "data key" wherever tables are shown in the interface, at least in cluster reporting.

**Comment by rkrupinski** [comment]
Branch: `feature-indicator-modal-changes-546`

**Comment by rkrupinski** [comment]
> Show labels as "data key" wherever tables are shown in the interface, at least in cluster reporting.

@n1207n Is it possible to return labels along with `indicator_location_data`, `disagg_lookup_map`, etc?

**Comment by n1207n** [comment]
@rkrupinski,

I added a new field called `labels` as object where it has all 3 labels: `label`, `numerator_label`, and `denominator_label`

![Screen Shot 2018-03-30 at 11.14.39 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206457f36b7191a379ee0c2a55415c47bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e34956a7153f66e1743e6e0a.png)
