### ISSUE TITLE
Add Amendments to PD details

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#575]
- [x] Just the 'Amendment' component

https://projects.invisionapp.com/d/main#/console/13273014/277346578/preview

**Comment by rkrupinski** [comment]
Branch: `amendments-#575`

**Comment by rkrupinski** [comment]
@n1207n The `Amendments` field in django admin accepts JSON. I assumed the following structure:

```json
[{ "types": "lorem, ipsum", "signed_date": "12-Jun-2018" }, { "types": "dolor sit amet", "signed_date": "24-Jun-2018" }]
```

**Comment by sethgold8** [comment]
Small items. Let's do a quick test on Wednesday at our standup, but overall looks good.
- [ ]  make Results have a capital R
- [ ] add lines at the bottom of the Row so it matches invision line

![Screen Shot 2018-04-16 at 11.14.39 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f56b7191a379ee0c2a55415c47bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e24455a6153f62e570336e0a.png)

**Comment by rkrupinski** [comment]
> make Results have a capital R

Whatever's returned from the api, gets displayed.
