### ISSUE TITLE
When Partner sending information to IMO about an indicator, we should include a link to the specific indicator for more context

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#577]
- [x] add  partner users name, email, partner name, indicator, project, plan to the modal and message received by the IMO.

- [x] Include all locations this indicator modal has. Can include a url to : response parameters > partners > activities > activity > indicators tab

Example email text:

Dear Jean Mege,

TPM DELOITTE HASKINS AND SELLS LLP has accepted your request for a Monitoring/Verifcation visit to Implementing Partner BAHAR ORGANIZATION BAHAR DERNEGI.

Please click this link for additional information https://etools.unicef.org/users/api/changecountry/?country=10&next=/tpm/visits/19/details

Thank you.

**Comment by sethgold8** [comment]
- [ ] Let's include a confirmation after message sent saying 'Message sent' so the partner knows it went through cc @maciej-jaworski

**Comment by maciej-jaworski** [comment]
Done with my part. Confirmation is a frontend task.

**Comment by sethgold8** [comment]
#greatjob :)
