### ISSUE TITLE
pd details not matching in PMP and PRP

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#580]
Need to dig deeper on this. This might have been changed in django admin

![unnamed.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51fb2876ddb02def112d580c5e4bac41515d41fbff8e29a0a42062c80d55b98e30063e937f03a6aa8317b500bf22894683b0bc8e4ac9ea3537aa.jpg)

![unnamed-1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46fd9a94228f86adc2b8fd0fe64de29b234324676b5ee17e2886e570ec472b5259561dad44585f4dfefc8e2da1b43a62964e49bc8f3900299f7744eeaa880dbe09b0218e4d87bfba8c4cc5eb3924ee99c2.jpg)

**Comment by maciej-jaworski** [comment]
For whatever reason original importer code saved `cso_budget` as `budget`.
Fixed `budget` to be sum of `cso_budget` and `unicef_budget`

**Comment by maciej-jaworski** [comment]
Separate values for `UNICEF Supplies` and `UNICEF cash` don't seem to be available in eTools API output. So all is saved under UNICEF cash in PRP.

**Comment by sethgold8** [comment]
#moved details to 580
