### ISSUE TITLE
Only secure origins happen. Javascript error happens when trying to edit + save a ratio indicator as a partner.

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#581]
![Screen Shot 2018-04-05 at 4.16.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f66b7191a37cf1132d4f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df449e84a55a6173161ee7f2431.png)

**Comment by rkrupinski** [comment]
The error occurs due to an attempt to register a service worker on a non-secure (`http`) origin.

https://github.com/unicef/etools-partner-reporting-portal/blob/4b4d37e7c6377d1b8f665895ade04264e128ce65/polymer/index.html#L94

Can ignore. Closing.
