### ISSUE TITLE
Allow IMO to add/edit indicators for Partner Project or Partner Activity

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#584]

**Comment by rkrupinski** [comment]
> Editing an activity as IMO does not work

`PATCH`: `http://prp.tivixlabs.com/api/partner/10/update-partner-activity/41/` -> `404`

**Comment by n1207n** [comment]
After some investigations, this likely happened from fake data issue. Somehow, there are partner activities without partner project instance.

**Comment by sethgold8** [comment]
Moving forward :). This was a fake data issue.
