### ISSUE TITLE
'Add Project' Missing From My Planned Action for Partner + Unable to 'add Cluster' when trying to add an activity

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#586]
- [ ]![Screen Shot 2018-04-10 at 11.01.26 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ee0c2b50415d48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e24e5da7163f6be773376e0a.png)

- [x] Unable to 'add Cluster' when trying to add an activity
![Screen Shot 2018-04-10 at 1.05.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379f1122e4f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19f41c95df448e24455a3173766e6722431.png)

**Comment by momimomo** [comment]
Permissions for Adding Project fixed, but let's make sure we are clear on that:

in Response Parameters -> Projects:
[add project] should be visible for:
-IMO

in My Planned Action:
[add project] should be visible for:
-authorized officer (ao)
-partner editor (pe)

I will merge permission fixes with 563&536 before standup.

As for the other bug, I think it's unrelated to the first one.

**Comment by momimomo** [comment]
Clusters can't be imported in other places too...  I'm getting empty array as a response from backend. @maciej-jaworski

**Comment by maciej-jaworski** [comment]
<img width="1108" alt="screen shot 2018-04-11 at 11 00 49" src="https://user-images.githubusercontent.com/1492815/38606907-a19c942a-3d77-11e8-9c75-c3f604cc354d.png">

@momimomo not sure whats the issue with your local setup, in staging, where Seth tested this clusters are returned fine from the backend but frontend still doesnt display them properly

**Comment by momimomo** [comment]
Ok, will move to this one after 536 then.

**Comment by momimomo** [comment]
should adding activity from cluster activities be available forusers other than than IMO? The clusters are not available, because like I said, even in Django admin it's not possible to assign AO to IMO clusters (hence there are no shown). Maybe this option should be disabled?

**Comment by momimomo** [comment]
Never mind, I changed it for clusters curently in redux state, so there would be no differences in permissions.

**Comment by sethgold8** [comment]
#worksgood. Pushing through
