### ISSUE TITLE
Rebuilding unit test cases

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#592]
Bringing existing Django unit test cases back alive to enable coverage testing again.

Once unit test cases are back to normal, we need to identify which Django APIs/functionalities are not covered in testing.

We need to bring up coverage test rate to 75% or higher.

**Comment by n1207n** [comment]
One thought on how to speed up unit test cases is that our BaseTestCase class triggers generate_fake_data method every time its subclass gets instantiated to run tests.  It may be possible to have a class static attribute on BaseTestCase so that generate_fake_data method will be called once only.

If that's not possible then we may have to do dirty work where we create a flag in test DB or django cache something to prevent generate_fake_data method to run once. :(

**Comment by n1207n** [comment]
For the progress I have made on this ticket, I have attempted to fix unit test cases from cluster app and indicator app. There is one unit test in indicator app that I have not been able to fix it yet. :(

core, unicef, and partner Django apps still have commented out unit test cases. I think account app doesn't need to be tested since we rely on django-allauth and AD stuffs. ocha Django app is what Maciej has created and I saw his unit test cases.

**Comment by maciej-jaworski** [comment]
It was in setUp, which is run before every test not even every time `every time its subclass gets instantiated` moving it to setUpClass sped up test execution almost 4x (2046.908s > 568.384s)

**Comment by maciej-jaworski** [comment]
Found a way to only run fake data once rather cleanly - [introduced a custom test runner](https://github.com/unicef/etools-partner-reporting-portal/commit/33914dd8b3c00e43a64fbf8fb26876413d285a1f) that creates fake data after database setup, now we're down to:
`Ran 50 tests in 12.601s`

This doesn't include time it takes to run fakedata but it's still a major improvement.
@n1207n review the linked commit, some changes to `BaseAPITestCase`.

**Comment by n1207n** [comment]
AWESOME! 50 tests in 12 seconds is ideal for our current CI process. The fakedata function with quantity=1 usually takes under 60 seconds. There are few test cases in indicators that require fakedata quantity around 3~4 due to disaggregation data validations. Even still, the fake data should not take too much time.

Great work on test performance. Now we need to start enabling unit test classes and do coverage test at once :D

**Comment by maciej-jaworski** [comment]
FYI: Total I timed is 5 minutes when fakedata generates disaggregations and 3 minutes without them.

**Comment by n1207n** [comment]
@maciej-jaworski,

I am disabling unit test runner for django_api so that staging can get dual reporting groundwork tasks.

For some reasons, codefresh CI is having 15 min timeout since django test command is taking too long to run. I checked out locally and for me it's stuck at test db creation.

Somehow, the test runner is not running (or idling) any tests after test db is created. :(
