### ISSUE TITLE
Integrate with Active Directory via Oauth for user login

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#595]
See PR here for how to integrate, once session is set no change in how we do things. Keep the current login method we have, simply add a "login via Active Directory" button to login page additionally which will trigger the Oauth flow.

https://github.com/unicef/etools/pull/1235

**Comment by n1207n** [comment]
I was able to setup AD integration locally, but I need a UNICEF credentials to test out successful login attempt at the moment. Need to ping Rob on this.

**Comment by sethgold8** [comment]
works wohoo! :)
