### ISSUE TITLE
Indicators Showing Up Multiple times in 'Indicator Filter' in Reporting Results

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#599]
Makes it hard for the user to find the specific indicator

![Screen Shot 2018-04-17 at 10.02.06 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a379ef0c2b53415f48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e2445da0153762e676336e0a.png)

**Comment by n1207n** [comment]
Updated backend API serializer to distinguish from Cluster Activity on same naming now

![Screen Shot 2018-04-20 at 3.48.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f36b7191a37bf116234f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe34b51a1153266ef772431.png)
