### ISSUE TITLE
Project Filter Not working in Reporting Results: The same indicator is appearing as listed in Project Filter. It's not even in that specific Project.

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#600]
I'm assuming it's a filter issue with the 'Project Filter'

You can see the same indicator appears despite the specific project filter changes:

![Screen Shot 2018-04-17 at 10.05.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a379ef0c2b54415e48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e2445da1133766e07f306e0a.png)

![Screen Shot 2018-04-17 at 10.05.37 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a379ef0c2b54415c49bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e2445da1133462e3713f6e0a.png)

The indicator is not even in that specific project. This is probably correct, just showing the photo to illustrate that the filter probably is not working

![Screen Shot 2018-04-17 at 10.09.26 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a379ef0c2b58415d48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e2445da113346be670356e0a.png)

**Comment by n1207n** [comment]
So, that `quantity_indicator_3` indicator is a ClusterObjective indicator generated by fake data script.

Since the UI needs to be able to return all Indicator Reports regardless of their indicator type, the partner project filter is basically returning any ClusterObjective indicator where it has association to PartnerProject filter.

ClusterObjective does not require PartnerProject to be created. Think of that partner project filter as reverse lookup.

**Comment by sethgold8** [comment]
Here is actually better examples i think. (Not removing the top one because your comment specifically reacts to it.)

![Screen Shot 2018-04-25 at 3.28.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a37bf110234f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29a41c95df44fe74450a010346be2732431.png)

![Screen Shot 2018-04-25 at 3.28.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a37bf110234f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44fe74450a0173660e3732431.png)

**Comment by n1207n** [comment]
I have stated that this is not a bug many times. But if @chachra can clarify, that would be great.
