### ISSUE TITLE
Humanitarian Reports (HR) in IP Reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#602]
Spec: https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/progress-reports/humanitarian-reports-hr

There will be a followup ticket since this sets the ground work for dual reporting soon after.

- [x] #backend This report does not include PD output rating or narrative assessment of progress and there is no “other info" tab in the user interface for this report. The tab in the PD report page called “Reporting on Results” must be renamed to “Reporting on Indicators”.
- [x] #frontend for above (just hide those fields if report type is HR).
- [x] #frontend if HR then instead of showing accepted show "Received" in the frontend for that state.
- [x] #frontend Change "Reporting on results" tab to "Reporting on indicators" if HR.
- [x] HR’s status can be set to “Received” (accepted) when this report is submit, and the underlying cluster specific indicator report (if any) would be set to Received as well (Cluster Reporting status to be renamed from current “accepted” to “received” as well).
- [x] #backend There is no workflow following the submission by the IP to UNICEF and Cluster. 

**Technical notes**
In the backend submission of these reports should make them go directly to "accepted". In the UI though if its HR everywhere to show "Received" instead. Same in Cluster reporting UI as well, change accepted to received everywhere.

Since for SR's we've already made in the backend narrative and rating optional, in this POST request for HR's since we don't use these, its good. But please make sure that QPR's still require it for each LLO coming from the frontend and then those getting pushed to the IR's.

"received" is just a frontend change.

**Comment by n1207n** [comment]
Creating a new branch from `feature-dual-reporting-sr-611`

It will be named `feature-dual-reporting-hr-602`

**Comment by n1207n** [comment]
Now HR report type progress report can be submitted without "Other info" values and IndicatorReport-level narratives and overall status.

All the HR progress report needs are all IndicatorLocationData filled and submitting as partner focal point user.

![Screen Shot 2018-04-24 at 3.12.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f76b7191a37bf113294f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df44fe74d5da4133462e17f2431.png)

**Comment by n1207n** [comment]
@chachra,

For HR progress report, do all of its indicator reports need to have narrative assessment and overall status fields filled out before submitting?

**Comment by sethgold8** [comment]
@chachra can as user submit no data for HR? Since there is only 'received for HR' should the partner be able to submit a report without adding any data? Is this acceptable or do we want them to at least enter some data (regardless of whatever it is) before submitting 

cc @n1207n @rkrupinski

**Comment by sethgold8** [comment]
@rkrupinski 

- [ ] HR Report status should be 'Received'. Right now it is accepted.

![Screen Shot 2018-05-02 at 10.08.25 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454f16b7191a379ef0c2b59415d4bbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e44f5da41a3e60ee713f6e0a.png)

**Comment by chachra** [comment]
What is the rejection reason?
