### ISSUE TITLE
When pulling projects from OCHA, we have partners that do not belong

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#607]
- [ ] Anguila 2018 and Caritas show when pulling projects for CHAD 2018. They do not belong (I believe since they should apply to different workspace).

![Screen Shot 2018-04-19 at 3.57.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fa6b7191a37bf1172c4f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44fe04a5dac14376bef732431.png)

Also @maciej-jaworski does CHAD have partners? @n1207n and I tried to add Partners for CHAD from PMP but there were none? I realize this would be on PMP, but would be good for clarification. 

cc @chachra

**Comment by maciej-jaworski** [comment]
Partners are filtered based on clusters, I've manually added those partners to be able to test something, I don't think this is a bug.

**Comment by sethgold8** [comment]
kk pushing forward
