### ISSUE TITLE
Special Reports (SR) in IP reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#611]
SR is a type of report already in the system.

- [x] Report generator to generate HR's (fake)
- [x] Add new API for POST
- [ ] frontend changes to handle when user clicks on SR (view and edit mode depending on submission status).

Documentation: https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/progress-reports/special-reports-sr

**Technical notes**
- Clean new POST endpoint. GET can remain the same probably.
- add (optional) narrative field to the Progress Report model #backend
- re-use existing attachment field on PR. Already exists.
- Some fields on progress report may need to be marked optional like start date, end date, proposed_way_forward, contr to date, etc. But **please** make sure that then the API endpoints for the normal (that qpr/hr will use) are not effected and still enforce the required fields.

**Comment by n1207n** [comment]
I updated fake data script so that each PD lasts a year, and generating 4 QPRs and 12 HRs evenly.

![Screen Shot 2018-04-23 at 3.08.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a37bf112234f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe44f54a7113565e3742431.png)

**Comment by n1207n** [comment]
@chachra, does this ticket also cover the report generator generating SR reports?

**Comment by n1207n** [comment]
I heavily modified report generator celery task to handle QPR, HR, and SR generation properly. It's idempotent now. ;)

![Screen Shot 2018-04-23 at 5.34.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a37df1112f4f5d5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe44e55a41b3461e0752431.png)

**Comment by n1207n** [comment]
New API under new URL is now ready for submitting SR progress report. It does check for narrative and attachment fields to be required.

At the moment, Due/Overdue report status checker celery task is broken due to changes from SR. I'll take a look tomorrow.
