### ISSUE TITLE
Sync all report periods/due dates with PMP: QPR, HR, SR

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#612]
Update pmp PD sync.

**Comment by n1207n** [comment]
Just checked with PMP PD sync API. They don't seem to have updated reporting periods field for each report type yet.

I see that is_high_frequency field is now available. We need to put that into our PD sync task.

**Comment by robertavram** [comment]
QPR and HR are now under `reporting_requirements` field.. as `report_type` same structure (`due_date`, `start_date`, `end_date`, + `report_type`)

SR will be a new field called `special_reports` will include a list of objects with the properties `due_date` and `description`

**Comment by chachra** [comment]
Waiting on special_reports from PMP. @robertavram

**Comment by sethgold8** [comment]
@robertavram any update on special_reports field?

**Comment by robertavram** [comment]
Done!

**Comment by sethgold8** [comment]
Much appreciated @robertavram !

**Comment by sethgold8** [comment]
working good :)
