### ISSUE TITLE
Progress report layout changes (as part of dual reporting CR)

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#613]
Please do this task before doing any SR, HR work.

For existing reports do the following:

- [x] Remove review & submit tab from the progress report completely
- [x] Enter data for "$reference_number" now instead of title.
- [x] the reference number is a link now, which will open the modal that currently is opened by the "SHOW PD/SSFA TOR DETAILS" (remove this button hence)
- [x] Put the "SUBMIT" button at the top irrespective of which of the 2 tabs the user is in. Show/hide logic for that button still applies, meaning should not show for accepted, submitted reports of course.

See first screenshot for details. Don't change anything else even if mockup has slight different words (like xls export button) without discussing internally. https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/progress-reports/standard-quarterly-progress-reports-qpr

**Comment by sethgold8** [comment]
good to go ;)
