### ISSUE TITLE
In QPR being able to pull data for HF indicators

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#615]
QPR contains all 3 kinds of indicators.

For HF indicators (cluster or non-cluster) there will now be an additional option to "pull data" It'll open a modal showing user which HR's (whose end dates fall within reporting period of this QPR) data will be pulled from and it basically just pre-fills the tables (for all locations of that IR).

**there is no dual reporting** or cluster tabs in a QPR.

Spec: https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/progress-reports/standard-quarterly-progress-reports-qpr#reporting-on-high-frequency-humanitarian-response-indicators

- [x] In POST requests will then apply the "across locations" formula for each location in the QPR, find the ILD's in the IR's for those HR's for those locations and apply the formula and the populate the QPR's IR's ILd's for those locations then with the totals.

**technical notes**
- may only be able to pull totals since HR's data may not be at same disagg level?
- Add a boolean to IR's serializer called "has_high_frequency_reports". If false then no "pull data" option (this would always be false for the PD regular indicators). In some cases for HF indicators as well it could be false since no HR was submitted/received yet.

**Comment by rkrupinski** [comment]
@chachra / @n1207n Is this ready to work on?

**Comment by n1207n** [comment]
1. Fix the query for data hf pull
2. Add a field called is_unicef_hf_indicator boolean in reporting default=False
3. update fake data to randomly put CAI ID when we generate LLO indicator, make sure one CAI ID per partner
4. add a post step to update all Reportables if they have cai id to mark is_unicef_hf_indicator flag
5. Make sure IndicatorReports for Reportable with is_unicef_hf_indicator flag are the only ones generated for HR
6. when pulling HF data, filter IndicatorReport with UNICEF reporting entity only and sum it up by locations.

**Comment by chachra** [comment]
Some modifications here.

- Don't need to put reporting start/end data in modal title if not easy.
- Keep indicator name in modal if easy, if not can remove.
- the data returned is not per location, so modal doesn't need to have location.
- Remove Location progress thing since data is not per location
- add a column in the table called "Total Progress" and show a number there the API sends back.
- API needs to send back report name HR1, HR2 etc.

**Comment by n1207n** [comment]
The REST API is ready for GET and POST methods:

```
GET /api/unicef/73/progress-reports/468/indicators/16922/pull/
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "id": 474,
        "report_name": "HR3",
        "start_date": "01-Mar-2018",
        "end_date": "31-Mar-2018",
        "due_date": "31-Mar-2018",
        "report_location_total": {
            "c": 3102.0,
            "v": 3102.0,
            "d": 1
        }
    },
    {
        "id": 473,
        "report_name": "HR2",
        "start_date": "01-Feb-2018",
        "end_date": "28-Feb-2018",
        "due_date": "28-Feb-2018",
        "report_location_total": {
            "c": 2225.5,
            "v": 2225.5,
            "d": 1
        }
    },
    {
        "id": 472,
        "report_name": "HR1",
        "start_date": "01-Jan-2018",
        "end_date": "31-Jan-2018",
        "due_date": "31-Jan-2018",
        "report_location_total": {
            "c": 2845.25,
            "v": 2845.25,
            "d": 1
        }
    }
]
```

**Comment by chachra** [comment]
@kasialanecka please see previous comment I made in "Some modifications here." and in the spec as well. If you can update the mockup and put it in gitbook and the spec doc. Thanks!

**Comment by n1207n** [comment]
@kasialanecka,

we think it'll be so tedious to pull data per location level, therefore we designed the backend API to pull data per indicator report level.

I think we should put `PULL DATA` link at the indicator report row UI instead.

cc'ing @momimomo ^

**Comment by n1207n** [comment]
Currently, a display logic for PULL DATA link in Polymer is to target QPR report type. This happens for both dual-reporting LLO Indicator QPR reports and LLO Indicator that has no HR reports generated yet.

I think that's because IR serializer does not have `has_high_frequency_reports` field yet. Once this is implemented then, this should be all handled.

**Comment by sethgold8** [comment]
Working good :)
