### ISSUE TITLE
Model changes for dual reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#616]
- [x] Add a parent field on IndicatorReport model
- [x] Add a new ReportingEntity model
- [x] Add a fk from IR to ReportingEntity model (should be required fk I think).
- [x] Add ca_indicator_used_by_reporting_entity fk self-referential fk

**Comment by n1207n** [comment]
Creating a new branch from `feature-dual-reporting-hr-602`

It will be named `feature-dual-reporting-model-changes-616`
