### ISSUE TITLE
Set up HTTPS for staging to get AD redirection working

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#620]
Rob asks us to set up HTTPS for the staging environment in order to get AD redirection working properly

**Comment by maciej-jaworski** [comment]
For let's encrypt we'd need persistent storage (it needs to store account info, etc locally). Most instructions on how to set it instruct to link underlying storage, which we don't have access to in docker cloud. Could of course develop some workaround (like storing it encrypted on S3 or sth) but hardly seems worthwhile when docker cloud is shutting down in less than a month.

**Comment by n1207n** [comment]
My opinion is to have a docker image/container for letsencrypt so that we can still use it on docker cloud and Rancher OS later on when Docker cloud is shutdown in less than a month. Because technically in docker cloud, we can re-use existing docker volume for containers no matter how many times we deploy (e.g postgres container in PRP)

I would consult with Michal Kopacki to come up with the letsencrypt docker container setup, which can be run in docker cloud for now and later on for whatever platform we are gonna use.

@chachra

**Comment by maciej-jaworski** [comment]
Skipped my mind that volumes are semi-acceptable to work around this, will try it out.

**Comment by maciej-jaworski** [comment]
It's done, no PR since had to work directly on develop, but changes can be seen in the nginx_proxy directory.
