### ISSUE TITLE
400 error: AO not appearing when trying to submit a report on their behalf

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#622]
![Screen Shot 2018-04-23 at 4.47.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a37cf1162c4f5c575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe44f52a7103063ee722431.png)

**Comment by momimomo** [comment]
locally I reproduced the error only as an AO, and the response from backend is:
![Screen Shot 2018-04-24 at 13.50.54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f76b7191a379ec0c2e51415a4abe5d4a1f06a3a3dc78e2a436628f5458bbd96e0a74c53b18ffb9871fbf08b8258c4982b4ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5cf34ce04f55a21b3765f43b.png).

On staging I can't see any errors as an AO.

as an IMO I can't reproduce this issue neither on staging nor on dev.

**Comment by maciej-jaworski** [comment]
this is correct behaviour, this error triggers  display of the modal

**Comment by momimomo** [comment]
ok, but if the user is an AO, it shouldn't trigger modal for assigning other users? That's why the dropdown is empty from my understanding, as this situation shouldn't occur.

**Comment by maciej-jaworski** [comment]
user needs to be an AO for this particular PD not AO in general

**Comment by momimomo** [comment]
Seems fixed, but can't test it locally. Will be testing tomorrow on staging to not disrupt too much today.

**Comment by momimomo** [comment]
Fixed and on staging.
