### ISSUE TITLE
Should not be able to submit  a QPR report if data is not entered

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#626]
![Screen Shot 2018-04-25 at 12.12.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a379ed0c2a53415e47bc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e54b5da21a3f62e274356e0a.png)

**Comment by momimomo** [comment]
From what I understood from the errors I got while testing, the only condition is selecting "Met" or "Constrained" in all PD outputs for that report, not the completion of data for each indicator. Will change It with Maciej tomorrow if that's not the expected result.

**Comment by sethgold8** [comment]
@Silin Can you confirm on what needs to be filled out (or not filled out)
before submission? I think this was decided before I joined.

**Comment by n1207n** [comment]
My memory serves the progress report submission like this.

For ProgressReport to be submitted, there are following validations the backend needs to perform:
1. All indicator location data in the progress report via its indicator reports need to be entered.
2. Other info tab information (except attachment being optional) need to be entered.
3. The progress report has not been submitted before has been sent back from PMP.

However, I looked at ProgressReportSubmitAPIView and it seems we only perform validation #1 if indicator report's overall status is either met or no progress. I think this may be the only exception we have. I have to think we do this according to ip reporting spec, so this may not be issue at all.

It's just that when this progress report is submitted, all of its indicator reports were met or no progress.

**Comment by sethgold8** [comment]
@momimomo lets go with what Silin commented above

**Comment by sethgold8** [comment]
Everything looks good @momimomo except

- [ ] when I remove 'Other Info' and go to "review and submit' it lets me submit. I removed the data but it does not save and I can see the old data there

![Screen Shot 2018-04-26 at 11.33.56 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f56b7191a379ee0c2852415a48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e54a53a3143566e171336e0a.png)

-

**Comment by maciej-jaworski** [comment]
Changed endpoint to accept empty strings.

**Comment by sethgold8** [comment]
works good :)
