### ISSUE TITLE
Add a splash screen for AD Login

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#627]
Have text showing: 

"Account created. Please wait 1-2 business days for your admin to approve you. If it has been longer then 1-2 business days, please email X to get you approved. "

**Comment by maciej-jaworski** [comment]
Don't think there's any backend work required here, just display this when user profile
/api/account/user-profile/ request returns empty `groups`.

**Comment by momimomo** [comment]
Sure, are there any mockups? What should be the style for the notification - If it's a popup, should it have a green or blue title? Or should it be just a plain centered text?

**Comment by momimomo** [comment]
Im just going with centered plain text for now.

**Comment by sethgold8** [comment]
works good, just waiting on correct email to add for the user to message before pushing through
