### ISSUE TITLE
When user logs out of AD, they should need to log back in before they get access to PRP again

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#633]
RIght now I can log out. I don't need to log back in after.

**Comment by sethgold8** [comment]
@robertavram AD seems to remember user's browser has logged in. It does not force them to login again after a deliberate log out. Is there a way to delete AD session when I log out in django. If not, is there a time out to ask the user to log back in after a specific time has passed? cc @n1207n

**Comment by n1207n** [comment]
Revisiting back here. This is technically a typical feature of single sign-on. AD system controls when to expire the user's session, and we don't have that control in PRP. Therefore, this should no longer be marked as issue.
