### ISSUE TITLE
Map not centered in Analysis

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#635]
When I am in Location: Admin 2 ; the map does not show any available locations because it is not centered.
![Screen Shot 2018-04-30 at 10.09.23 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276457f36b7191a379ef0c2b58415d4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f349e44d5ca317306ae574336e0a.png);

When I scroll up, it works fine

![Screen Shot 2018-04-30 at 10.11.59 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276457f36b7191a379ef0c2a50415a47bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f349e44d5ca316346ae272316e0a.png)

**Comment by sethgold8** [comment]
@rkrupinski  cannot test...experiencing secure origin issue that is marked for #643

**Comment by rkrupinski** [comment]
This is unrelated.

**Comment by sethgold8** [comment]
Map is still not always centered. On this photo, it locations were initially working, after 2nd time refreshing, locations are not showing and it is not centered.

![Screen Shot 2018-05-18 at 2.05.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a37af1122e4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44de74a52a11a3e61e6762431.png)

![Screen Shot 2018-05-18 at 2.05.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a37af1122e4f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de74a52a2123667e37f2431.png)

**Comment by rkrupinski** [comment]
@sethgold8 I'm gonna need a combination of workspace / response plan / admin level for which we have location geometry on staging.

**Comment by sethgold8** [comment]
have seen it not centered but tested with SIlin today and am pushing through...worked fine :)
