### ISSUE TITLE
Must not let other partners enter enter data via import/export for indicators that don't belong to them

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#636]

**Comment by dfryta** [comment]
@sethgold8 How about IMO? Are they allowed to do this for partner?

**Comment by n1207n** [comment]
@dfryta,

IMO can impersonate as a Partner, so IMO user should be able to do everything that a Partner can do. So I would argue that even IMO user can do an importing/exporting indicators for that specific Partner.

IMO user should not be allowed to import/export indicators that the partner does not handle.

**Comment by chachra** [comment]
IMO should be allowed to report on any data that any of the partners in that cluster are allowed to report to. So thats the broad strokes. If any of the data being uploaded does not belong to that cluster then it should error out that entire upload (atomic).

**Comment by n1207n** [comment]
Taking over this ticket as well. Some linting issues to fix and needs to add IMO user support for this.

**Comment by sethgold8** [comment]
@n1207n not sure the best way to test this? Do we throw an error if they try to export indicators that do not belong to them (the partner)? Or do we throw the error if they try to upload data for indicators that don't belong to them. 

I suggest validation error when trying to export with message that "Partner can only export indicators that they can report on ". 

Right now I am receiving this error but assuming it's just because import/export is not fully complete yet

![Screen Shot 2018-05-22 at 11.07.48 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f16b7191a379ee0c2b56415b46bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e64d54a6163462ee7f356e0a.png)

**Comment by n1207n** [comment]
Could be that import/export functionality itself is not complete. I only fixed the linting issues and added IMO support for importing indicator report data up to my best knowledge.

I guess I have to re-assign this ticket to Dariusz since he may be still working on import/export feature.

**Comment by sethgold8** [comment]
pushing this back as would like to test after import/export is Accepted.

**Comment by sethgold8** [comment]
working good :)
