### ISSUE TITLE
Dual reporting frontend changes

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#638]
Frontend task for #629 - please make changes for this on dual-reporting-backend-for-reporting-629 branch itself.

Review cluster reporting specs. Everything under https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/progress-reports

**For this task to start focus on cluster reporting side ONLY*** (since no progress report overhead... but code / frontend logic for data entry and display should be same for IP as well): https://unicef.gitbook.io/prp/product-end-user-documentation/cluster-reporting/reporting-on-results/reporting-to-unicef

**Steps to get data into right place.** Please use incognito window to save time (IMO and AO):

- Run fab up. Make sure reporting entity model and data for it (2 entries) appears in django admin. cluster & unicef.

- login as IMO
- create a new cluster activity
- create a couple of new indicators for this new activity. Also add 2-3 locations to each of these indicators.
- Make a note of the ID's of these **CAI's (ClusterActivity Indicator)**.

- now login as a AO
- create a new partner activity that derives from the above created new PA.
- make sure indicators got cloned/adopted as well.
- Edit the couple of PAI's now add 2-3 of locations. For analysis etc. to work (ideally) make them the SAME locations as a PAI (created above, so that in-need and baseline area already set for these). If you don't make them the same locations, no big deal, does not affect this tickets work.

Now if report generator has generated reports for the PAI, go to django admin and go to Reportable. Choose "lower level output" in content type filter on the left. Go to last page in pagination and see if you can choose  quantity indicator for lower_level_output_0. Click on it, and in `Ca indicator used by reporting entity` select the **CAI id (noted above)**.
- Do same for another LLO indicator and associate the other **CAI indicator id**.

Now go ahead and delete **all progress reports** in django admin as well (quickly) for the PD that you chose reportables for above.

Note: Make sure in periodic tasks in djcelery - add a periodic task for process_period_reports , give it a name, enabled, for every 1 minute interval and save.

Index the ILD's by location and then by reporting entity.
![assets%2F-KzwqgC7O0kW5EDlHvvK%2F-LAWg-O_lUlN1LvZuuCK%2F-LAWhfdFo-da2KFuvXXY%2FData_Entry_01_02_Sug_01_02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ca8dffc9b0d720006675c4/125516c66e82c728ace21e0d46e98789269690ecddcff268be4ae1930a1108232233f60e5489cb3ea9693e53294232dd260f423b93a5ec77d8b74036e0194e9eaa785d02db4160cbe0d44bc95ea774da4dfec0f9cc24a881282791ffde0b6f717046cdbd145aa09824c85a9928a41a3aa4125963e4642a6e07d6412f79382334a1eeda5ed4d368a7ef102c50c1b0e5ff1612a87eddc00f76615349b63870e45c0ed63dc10c2d1ff9bfd6fc1f46091b03c8e9c1dbbdeadd3171265557.png)

- [] Print function should also reflect for dual reporting tabs on disaggregation table indexed by location and reporting entity too.

Enter data modal (same on cluster reporting side of course as well when its dual reporting for that location and IR). The PUT request should be made to the ILD that is the is_master_location_data marked as True:
![assets%2F-KzwqgC7O0kW5EDlHvvK%2F-LAWe30zunKHgZEeE0Kc%2F-LAWePAeUu1woi-KT2_4%2FReporting-IP-Enter-Data_02_V3_03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ca8dffc9b0d720006675c4/125516c66e82c728ace21e0d46e98789269690ecddcff268be4ae1930a1108232233f60e5489cb3ea9693e53294232dd260d5c44b6bcd750dee15605df290b9682785d02db4160cbede26eea64ff21cc10dcabc7ee4eafec282791e9da0f615c4141d7a8404cc0843e961ca309fc3904e0425963e419507f28941d6730792764f4a68a05c3976ab6bf187c00c0e0b1fa1514a82fd9c209716a575ead2c35b704489572da172609b4e89db7420e1a1413ccecc9dab8edde33742c451b50c722e84056.png)

** API changes for entering IndicatorReport location data on dual reporting **
New API request payload to `http://localhost:8082/api/indicator/indicator-location-data-entries/`

The key fields to your attentions are:
* `is_master_location_data`
* `percentage_allocated`
* `reporting_entity_percentage_map`

By default, `reporting_entity_percentage_map` field is optional to accommodate both dual reporting and regular reporting.

If you include `reporting_entity_percentage_map` field, then dual reporting data split will happen in the backend. The format should be a list of objects including `title` and `percentage` keys:

`"reporting_entity_percentage_map":[{"title": "UNICEF", "percentage": 0.3}]`

`percentage_allocated` should always be `"1.0"`

If you call PUT request on this API with IndicatorLocationData including `is_master_location_data` == false, then API will throw 400 error.

```
curl -vX PUT http://localhost:8082/api/indicator/indicator-location-data-entries/ --cookie "csrftoken=gNLz1r13q6FVSHaweyg03HYxvJdlc74TwmJCd4CTrVkql8746i0qbuk9wwjzyT8P; sessionid=v0q57cdhqsrukhdadx2h1i81bk52fent" -H "x-csrftoken: gNLz1r13q6FVSHaweyg03HYxvJdlc74TwmJCd4CTrVkql8746i0qbuk9wwjzyT8P" -H "Content-Type: application/json" -d '{"id":59774,"indicator_report":12441,"location":{"id":146,"title":"location_1","latitude":null,"longitude":null,"p_code":"wAznx-1","admin_level":"2"},"display_type":"number","disaggregation":{"()":{"c":0,"d":0,"v":0},"(104,)":{"c":null,"d":null,"v":50},"(103,)":{"c":null,"d":null,"v":500},"(102,)":{"c":null,"d":null,"v":500}},"num_disaggregation":1,"level_reported":1,"disaggregation_reported_on":[24],"location_progress":{"c":0,"d":0,"v":0},"previous_location_progress":null,"is_complete":false,"is_master_location_data":true,"reporting_entity":{"id":1,"title":"UNICEF"},"reporting_entity_percentage_map":[{"title": "UNICEF", "percentage": 0.3}]}'
```

**Comment by n1207n** [comment]
Fake data script now automates one LLO indicator report for dual reporting purposes.

1. Do the git pull and restart the docker-compose. Run fake data by `fab fixtures:1`

2. Go into django_api shell_plus.

3. Run following commands:
```
a = Reportable.objects.filter(ca_indicator_used_by_reporting_entity__isnull=False).first()

b = PartnerActivity.objects.filter(
  cluster_activity=a.ca_indicator_used_by_reporting_entity.content_object,
  partner=a.content_object.cp_output.programme_document.partner
).first()

b = b.reportables.first()

ProgressReport.objects.filter(programme_document__title__icontains="_0").delete()

b.indicator_reports.all().delete()
````

**After a minute run below:**

```
ProgressReport.objects.filter(programme_document__title__icontains="_0").delete()
````

Then you'll find QuantityIndicator in lowerleveloutput_0 in programme_document_0 dual reporting ready!

**Comment by sethgold8** [comment]
working good :)
