### ISSUE TITLE
Partner sync is broken (we are not getting all the partners from all the workspaces).

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#639]
We do create partners when getting PD's from those workspaces, but we might be missing partners completely because of the former.

- [x] We should only create 1 partner for the same Partner vendor number

- [x] NOT NEEDED ANYMORE: We should add a field to say where we received partner from - basically the unicef business area code.

- [x] Add OCHA external id as optional field on the Partner model

- [x] Add a optional id field (like external id) called ocha_external_id to the Partner model. Enforce uniqueness of this id on the model if any entered. Many / most will be empty/null.

**Comment by dfryta** [comment]
@sethgold8 
`we should only create 1 partner for the same Partner vendor number` - are you sure we don't have this already? Please check: https://github.com/unicef/etools-partner-reporting-portal/blob/develop/django_api/django_api/apps/partner/tasks.py#L21

`We should add a field to say where we received partner from - basically the unicef business area code.` - not sure if I understand. `business_area_code` is a `Workspace` field. We are sync partners only from PMP, so what exactly we want to store it?

**Comment by chachra** [comment]
@dfryta former might be true, please double check though. @robertavram can you clarify on #2 Dariusz is raising, since I think you had mentioned this on our call. Tx

**Comment by dfryta** [comment]
I confirm that 1. and 3. are already done.

@robertavram please let me know what need to be done in case of second point. Thanks!

**Comment by chachra** [comment]
@dfryta ignore #2. Added a quick #4 as well.

**Comment by robertavram** [comment]
https://github.com/unicef/etools/pull/1476/files 
new partner sync by business area code...

**Comment by sethgold8** [comment]
@dfryta can we start using the new api Rob mentioned above on partner sync branch

**Comment by dfryta** [comment]
@sethgold8 Sure, let me check this new endpoint. Connected with #644

**Comment by dfryta** [comment]
Done in #644.

**Comment by sethgold8** [comment]
working good :)
