### ISSUE TITLE
Should not be able to add the wrong Partner to a Project

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#640]
**Technical Notes**
#Frontend - pass in PRP partner ID back to backend when getting list of projects.

#Backend - Call OCHA as per usual (don't think they support partner filtering and that is fine, we'll do the filtering in-memory in PRP), when response comes back filter out projects that belong to the PRP partner id and return response. Filtering will be done for the ocha partner id in PRP. If ocha partner id is not set for this partner id sent by frontend, then well no need to call OCHA even, return a "blank response" (no projects).

**Requirement**

- [ ] Acting as an IMO:

 After a partner is selected, only show projects that the partner has registered to them in  OCHA's OPS/Projects Module pertaining to that workspace.

![Screen Shot 2018-05-01 at 5.41.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454f26b7191a37df1162a4f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ee34f54a31b346ae5752431.png)

- [ ] Acting as a partner: when you are adding Projects, only Only show projects that the partner has registered to them in  OCHA's OPS/Projects Module pertaining to that workspace.

**Comment by momimomo** [comment]
This is backend change first, then I'll change the endpoints / send ids with request.
Should we filter that based on ids used within the portal? I think this question was posted some time ago and got the response that filtering by name sounded like a bad idea.
@maciej-jaworski @n1207n

**Comment by rkrupinski** [comment]
Is the backend change mentioned above already in place?

**Comment by dfryta** [comment]
Copy of #701

**Comment by sethgold8** [comment]
Looks great. 

Only item is if I select a project from OCHA for a specific Partner, and then change the partner, It allows me to still save that project.

For example, I selected Action CONTRE LA FAIM, and choose ' Strengthening Nutrition Surveillance for appropriate emergency response.' Then I change the partner to ACTED, and was able to save ' Strengthening Nutrition Surveillance for appropriate emergency response.' for them.

![Screen Shot 2018-06-22 at 10.42.04 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f16b7191a379ef0c2f53415f4abc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e84b5dad103e62e177316e0a.png)

**Comment by sethgold8** [comment]
working good :)
