### ISSUE TITLE
For reports, Partner must enter data before allowed to submit

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#642]
Partner cannot just submit. We must validate that they are entering data before submission.

@momimomo let me know if this is backend and I should assign someone else

**Comment by momimomo** [comment]
Yes, this is mostly backend - after the changes, I'll add error box if it's not there yet to display proper error codes. Isn't it connected to last changes (allowing user to completely empty input fields in "Other Info")?

**Comment by n1207n** [comment]
Now, ProgressReport should not be submitted if all location data is not entered.

The API logic was using a wrong approach to check if IndicatorLocationData is empty. We recognize empty IndicatorLocationData if its `d` value is 0. This would be set to non-zero if the data was entered as number or ratio type.

![Screen Shot 2018-05-02 at 3.00.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454f16b7191a37bf1122b4f5e595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44ee3445da0103262e37e2431.png)

**Comment by sethgold8** [comment]
works :)
