### ISSUE TITLE
Matching Data for PMP and DjangoAdmin Partner Details

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#644]
There are some fields were the data does not sync for Partners in PMP and what we get in Django Admin/PD details. 

- [ ] In etools we have Alternate name with data. There is nothing showing in Alternate Title in django. Alternate Name is not showing on pd details in prp. 

- [ ] In Etools we have Core Values Last Assesment Date. In Django admin and PD details it says Date Last Assessed Against Core Values and nothing is showing for both.

- [ ]  In Etools we have Basis for Risk Rating. We are not getting Basis for Risk Rating in django admin and pd details

- [ ] In Etools and Django admin do not have 'Assessment Type'. It is in PD details but obviously no data shows

- [ ] In Etools we have Date of Report. This does not exist in django admin or pd details. We do have date of assesment in Django admin and PD details

**Comment by dfryta** [comment]
@sethgold8 could you please let me know where did you find these fields in PRP?
- there is no `Alternate name` field in  PRP PD model and in PMP API 
- there is no `Core Values Last Assesment Date` in PMP API and ` Date Last Assessed Against Core Values` in PRP PD model
- there is no 'Basis for Risk Rating` in PRP PD model and PMP API
- there is no `Assessment Type` in PRP PD model and PMP API
- there is no `date of assesment` in PRP PD admin panel (where did you find it?) and in PMP API

@sethgold8 Please let me know if @robertavram should add those fields in API and we should create this fields in PD model and then update sync task?

**Comment by chachra** [comment]
@dfryta - @robertavram will add these to the API quickly/asap, once done please add these new fields to our PD data model as well then and hook up all the way to the frontend of the PD details screen. Should be easy given fields are already there, api serializer would need an update. Thanks.

**Comment by robertavram** [comment]
what is "date of report"?

**Comment by dfryta** [comment]
@sethgold8 could you please answer @robertavram?

**Comment by sethgold8** [comment]
We are not seeing 'Date of Report' anymore in Etools PMP @robertavram @dfryta

**Comment by sethgold8** [comment]
@dfryta @robertavram we just renamed the ticket to **Partner Details**

We assume 'Date of Report' from risk rating in PMP Partner Details Page is Date of Assessment in PRP

![Screen Shot 2018-05-16 at 4.31.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a37cf1112a4f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44de44c56a01a3563e17f2431.png)

We don't see assessment type in PMP partner details so will drop that field. We will re-name Date of Assessment it to Date of Report.

- [ ] #backend task alternate name, last assessment date, core value assessment date to PMP partner serializer class. @dfryta 
- [ ] #backend task delete type of assessment field from partner model and make sure we import alternate title last assessment date and core values assessment date @dfryta 
- [ ] #frontend update partner details serializer to exclude type of assessment UI @momimomo 
- [ ] #frontend use last assessment date to date of assessment for partner detail UI and remove assessment type column in UI as well @momimomo

**Comment by momimomo** [comment]
I'm sorry, I don't really understand those changes... I haven't been working on this at all yet.

**Comment by dfryta** [comment]
Waiting for @robertavram. We are missing `alternate name` and `core value assessment date` in PMP API partner endpoint.

**Comment by robertavram** [comment]
hey @dfryta .. you can use `https://etools-demo.unicef.org/api/prp/v1/partners/?workspace=2130` that should have all the fields... you can discard all usage of the old partner endpoint

**Comment by dfryta** [comment]
@robertavram new endpoint is lack of `partner_type`, `cso_type`, `total_ct_cp`, `total_ct_cy` required by PRP Partner model. Is it possible to add those fields like in old endpoint?

**Comment by chachra** [comment]
@robertavram are these fields are going to be available or ??

**Comment by dfryta** [comment]
Created new ticket for missing fields: #699. Closing this one.

**Comment by sethgold8** [comment]
Basis For Risk Rating does not show in E Tools but we see it coming from PMP API.

Everything looks good. Pushing forward :)
