### ISSUE TITLE
Not able to 'confirm' and add Custom Response plan

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#645]
IMO can ad a 'Custom' New Response Plan. After they click the radio button though, they cannot hit the 'confirm' button and hence move forward.

![Screen Shot 2018-05-02 at 4.20.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454f16b7191a37cf1102b4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44ee24d56a7143667e67f2431.png)

**Comment by momimomo** [comment]
Fixed.

**Comment by sethgold8** [comment]
working :)
