### ISSUE TITLE
Bar chart against in-need.

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#647]
It is currently showing target/in-need as a %; it should be calculating achievement/in-need.

If it is backend, please assign to Maciej

**Comment by momimomo** [comment]
Seems like a back-end change, in the response from API the `total_against_in_need` is 0 for all indicators even as they have `total_against_target`, so there might be a bug.

**Comment by momimomo** [comment]
now cant test against_in_need, as there is different logic for switching between users or lack of data? `total_against_target` works.

**Comment by momimomo** [comment]
locally both working fine.

**Comment by sethgold8** [comment]
great, will test today or tomorrow

**Comment by sethgold8** [comment]
@momimomo pushing this ticket back. It still shows target/In need.

If it we're achieved / in need, the % would be 0 since there is nothing entered for 'achieved'.
![Screen Shot 2018-05-18 at 10.31.23 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a379ef0c2850415d4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e74b53a014336be074316e0a.png)

**Comment by momimomo** [comment]
This is back-end ticket. There are no calculations on frontend. Endpoints are hooked correctly.

**Comment by sethgold8** [comment]
Working good :)
