### ISSUE TITLE
Handling Locking of location of ILD's

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#651]
- [x] When a cluster indicator report is submitted (hence accepted) all ILD's of all locations of the IR and its children will be marked as locked.

- [x] When a progress report with dual reporting IR's is submitted then all ILD's of all locations that are in the PD ONLY, will be marked locked (both parent and child IR's).

- [x] If Cluster sends back a indicator report then... ?

- [x] Hide Enter data button for each location if is_locked attribute is true

**Comment by sethgold8** [comment]
On IP can't send report back

**Comment by sethgold8** [comment]
lock if indicator report on cluster side sent; unlock if it is sent back

**Comment by n1207n** [comment]
I may have to delegate hiding `Enter data` Polymer button logic to @rkrupinski. Current polymer logic to show/hide that button requires far more effort for me to figure out.

**Comment by n1207n** [comment]
** Techincal notes for frontend **
IndicatorLocationData object now exposes `is_locked` attribute. In the indicator-details.html, we need to hide `Enter data` button for each location if `is_locked` attribute is true.

**Comment by sethgold8** [comment]
working :)
