### ISSUE TITLE
Accomadate for dual reporting cluster HF indicators in data import/export in cluster side

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#653]
Export of the template when iterating IR's and it has children then include the children's ILD's as well.

No "%" stuff will happen in import/export since user will be entering data explicitly for all the IR's and ILD's always in excel.

**Comment by sethgold8** [comment]
Need to add parent indicator

**Comment by sethgold8** [comment]
- [ ] When a filter is applied before Generate Upload Template, we don't get any data in any of the rows. Using Micronesia 2017 HR- WASH Cluster Partner. app/FM/cluster-reporting/plan/6/results/draft?page_size=10&page=1&location=19

![Screen Shot 2018-06-07 at 1.59.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f46b7191a379f117224f5a585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df443e54d50a7123466e7712431.png)

**Comment by dfryta** [comment]
Location filter is broken. I will look into this.
Second issue - Quantity_Indicator_10 - works good. Please notice that Quantity_Indicator_1 comes from children indicator.

**Comment by dfryta** [comment]
Done. I've found two more issues - already resolved.

**Comment by sethgold8** [comment]
@dfryta 

- [ ] For the Unicef Indicators, it should have the same info of the Columns (Cluster, Partner Name, Cluster Objective, Activity, Response Plan)  from its Parent Cluster Indicator. The only thing different should be the disaggregation itself.

**Comment by n1207n** [comment]
@dfryta,

I notice that `IndicatorsXLSXReader` has `IndicatorLocationData` ORM filter check if self.partner exists: https://github.com/unicef/etools-partner-reporting-portal/blob/develop/django_api/django_api/apps/cluster/import_indicators.py#L59

For UNICEF-only rows, we need to skip this Validation process. Inside that `if` statement, have additional logic for this purpose:
* If `IndicatorReport` for `ild_id` does not have a parent, then throw the `does not belong to partner` error
* If `IndicatorReport` has a parent, then check the parent IndicatorReport's reportable's partner activity's partner. If this partner does not equal to `self.partner`, then throw the same error
* If above partners are matching, then skip to next step.

**Comment by dfryta** [comment]
Done. @n1207n please check if this is what you have requested.

**Comment by n1207n** [comment]
I think the condition structure looks great. Can we change the ORM for checking parent's partner to `indicator_report__parent__reportable__partner_activities__partner`?

PartnerActivity has direct link to Partner, and project foreignkey in PartnerActivity can be null.

With that change, this should look solid ;)

**Comment by dfryta** [comment]
Done. Thanks!

**Comment by sethgold8** [comment]
working good :)
