### ISSUE TITLE
Update Indicator list UI both in IP and cluster reporting to handle dual reporting indicator

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#654]
There are some discrepancies on dual reported indicators in Indicator list UI from both Cluster and IP reporting.

Here are the screenshots for entered data on IndicatorReport:
![Screen Shot 2018-05-10 at 1.05.30 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f36b7191a379f1122e4f5c5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ee84557ad123163ee762431.png)
![Screen Shot 2018-05-10 at 1.05.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f36b7191a379f1122e4f5c5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ee84557ad123163ee702431.png)

------------------------------------
Entering data and seeing them on respective IndicatorReports are fine as you have seen above. However from IP reporting's Indicators tab, 2 latest IndicatorReport data seem to show the total of totals only. Simply, the IP reporting Indicator detail UI component does not seem to render fully.

![Screen Shot 2018-05-10 at 1.05.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f36b7191a379f1122e4f5b5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ee84557ad123163ee752431.png)

This is the API response that IP reporting Indicator details UI gets.
![Screen Shot 2018-05-10 at 1.05.49 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f36b7191a379f1122e4f5b565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44ee84557ad123163ee712431.png)

---------------------------------------------------
Moreover, Indicator detail UI from Cluster shows the UNICEF copy of IndicatorReport data.

![Screen Shot 2018-05-10 at 1.06.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f36b7191a379f1122d4f5a585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ee84557ad123162e6712431.png)

Above screenshot shows that we are only showing a location data from whichever IndicatorReport comes first.

This happened because the IndicatorReport list API didn't return both parent/child IndicatorLocation data for both Cluster/IP reporting indicator list UI. And now, I fixed the API consumptions for both cluster/IP reporting apps. Now we need to group location data by location and reporting entities on those UIs too.

**Comment by n1207n** [comment]
Oh also, we need to make progress bar color for against target to green if indicator is dual reporting enabled in IP reporting. Same thing goes in cluster for blue color on this UI:
![Screen Shot 2018-05-14 at 4.50.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f76b7191a37cf1172b4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de24954ad113e62e77e2431.png)

Just like how we make green flag for LLO indicator report if it's dual reporting enabled, and vice versa for cluster.

**Comment by rkrupinski** [comment]
@n1207n This took a while to debug...

Regarding sparse disaggregation data being rendered: please check whether `id`s inside `disagg_lookup_map` match the ones used to construct disaggregation keys (`(X,Y,Z)`). I'm pretty sure they don't. The total of totals being rendered correctly is a side effect of it being insensitive to `id`s (it's just `()`). Before pulling your changes I had both matching and not matching sets of `disaggregation` and `disagg_lookup_map`.

**Comment by rkrupinski** [comment]
@n1207n Here's an item of a collection that `/api/unicef/<workspace_id>/programme-document/indicators/` returns. Can't use location data to alter progress bar color as this data is fetched lazily. Is `parent_indicator` or `parent_ir_id` what I should be looking at?

```json
{  
  "id":2706,
  "indicator_name":"ratio_indicator_0",
  "title":"ratio_indicator_0",
  "reportable":{  
    "id":161,
    "target":{  
      "d":35378,
      "v":13285
    },
    "baseline":{  
      "d":257,
      "v":195
    },
    "in_need":{  
      "d":51833,
      "v":38954
    },
    "blueprint":{  
      "id":161,
      "title":"ratio_indicator_0",
      "unit":"percentage",
      "display_type":"ratio",
      "calculation_formula_across_periods":"sum",
      "calculation_formula_across_locations":"sum"
    },
    "ref_num":"",
    "achieved":{  
      "c":0,
      "d":0,
      "v":0
    },
    "progress_percentage":-0.0,
    "content_type_key":"cluster.clusterobjective",
    "content_object_title":"11 - Austria 2017 HR - WASH CO",
    "object_id":6,
    "means_of_verification":null,
    "cs_dates":[  
      "01-Jan-2018",
      "24-Mar-2018",
      "15-May-2018"
    ],
    "frequency":"Wee",
    "pd_id":"",
    "disaggregations":[  
      {  
        "id":22,
        "name":"height",
        "active":true,
        "response_plan":6,
        "choices":[  
          {  
            "id":92,
            "value":"tall",
            "active":true
          },
          {  
            "id":93,
            "value":"medium",
            "active":true
          },
          {  
            "id":94,
            "value":"short",
            "active":true
          },
          {  
            "id":95,
            "value":"extrashort",
            "active":true
          }
        ]
      },
      {  
        "id":24,
        "name":"gender",
        "active":true,
        "response_plan":6,
        "choices":[  
          {  
            "id":102,
            "value":"male",
            "active":true
          },
          {  
            "id":103,
            "value":"female",
            "active":true
          },
          {  
            "id":104,
            "value":"other",
            "active":true
          }
        ]
      }
    ],
    "locations":[  
      {  
        "id":3420,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":34,
        "loc_type":5
      },
      {  
        "id":3419,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":33,
        "loc_type":5
      },
      {  
        "id":3418,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":32,
        "loc_type":5
      },
      {  
        "id":3417,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":31,
        "loc_type":5
      },
      {  
        "id":3416,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":30,
        "loc_type":5
      },
      {  
        "id":3415,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":29,
        "loc_type":5
      },
      {  
        "id":3414,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":28,
        "loc_type":4
      },
      {  
        "id":3413,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":27,
        "loc_type":3
      },
      {  
        "id":3412,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":36,
        "loc_type":5
      },
      {  
        "id":3411,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":35,
        "loc_type":5
      },
      {  
        "id":3410,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":26,
        "loc_type":2
      },
      {  
        "id":3409,
        "baseline":{  
          "d":1,
          "v":408
        },
        "in_need":{  
          "d":1,
          "v":35081
        },
        "target":{  
          "d":1,
          "v":2549
        },
        "location":25,
        "loc_type":1
      }
    ],
    "comments":null,
    "measurement_specifications":null,
    "start_date_of_reporting_period":null,
    "label":null,
    "numerator_label":null,
    "denominator_label":null,
    "cluster":6,
    "parent_indicator":null,
    "total_against_in_need":0.4996691849893832,
    "total_against_target":0.0,
    "ca_indicator_used_by_reporting_entity":null,
    "cluster_partner_indicator_reportable_id":null
  },
  "reporting_period":"01-May-2018 - 08-May-2018 ",
  "due_date":"23-May-2018",
  "submission_date":null,
  "frequency":"Mon",
  "total":{  
    "c":0,
    "d":0,
    "v":0
  },
  "remarks":null,
  "report_status":"Due",
  "overall_status":"NoS",
  "narrative_assessment":null,
  "sent_back_feedback":null,
  "review_date":null,
  "cluster":{  
    "id":6,
    "title":"WASH"
  },
  "cluster_id":6,
  "project":null,
  "partner":null,
  "partner_id":null,
  "partner_activity":null,
  "cluster_objective":{  
    "id":6,
    "title":"11 - Austria 2017 HR - WASH CO"
  },
  "cluster_activity":null,
  "is_draft":true,
  "can_submit":false,
  "time_period_start":"01-May-2018",
  "time_period_end":"08-May-2018",
  "is_complete":false,
  "parent_ir_id":null,
  "child_ir_ids":null
}
```

**Comment by n1207n** [comment]
@rkrupinski, I pulled `develop` branch, blew up my local environment, and ran the fake data again. It seemed the issue is gone now. Weird.

> Regarding sparse disaggregation data being rendered: please check whether ids inside disagg_lookup_map match the ones used to construct disaggregation keys ((X?,Y?,Z?)). I'm pretty sure they don't.

This is wrong. the keys for `disaggregation` in each `indicator_location_data` field are mapped to `disagg_choice_lookup_map`, not the `disaggregation_lookup_map`. They are totally different. I'm sure that's how we map the Polymer table UI values back in last year.

**Comment by n1207n** [comment]
@rkrupinski,

> Can't use location data to alter progress bar color as this data is fetched lazily. Is parent_indicator or parent_ir_id what I should be looking at?

Don't use `parent_indicator` field as that signifies the reportable is partner activity reportable. Use `child_ir_ids` or `parent_ir_id` to signify the reportable is dual-reporting enabled.

**Comment by rkrupinski** [comment]
@n1207n Okay, I found one more inconsistency that once removed seems to have fixed the issue. The `id`s within disaggregation keys seem to come (from django) sorted in ascending order. In polymer, we seem to purposefully reverse that order for some reason I'm unable to comprehend.

Take a peak at https://github.com/unicef/etools-partner-reporting-portal/commit/0707ee1ff43f7b291363e92a6452d88289b8dd4c

Please, tell me that this is the case and we indeed sort the ids ascendingly.

**Comment by n1207n** [comment]
@rkrupinski,

Let's hold off on this issue until tomorrow's meeting. We don't know their expectation on UX.

As far as disaggregatioj key entries, I concluded that your local environment may have gotten messy. Fake data script ensures all reportable share same disaggregation keys.

I couldn't replicate the issue on my environment so let's move on. Focus on other tickets assigned to you
