### ISSUE TITLE
Not filtering Cluster Objective

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#658]
![Screen Shot 2018-05-15 at 5.53.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f66b7191a37df117284f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44de54e57a5133466ee722431.png)

**Comment by n1207n** [comment]
I looked at backend code for filtering, and it seems the filter is not even working due to GET parameter argument is `clusters`, not `cluster_id`. Will work on it tomorrow.

**Comment by sethgold8** [comment]
working :)
