### ISSUE TITLE
Under Project Activities, project link is broken

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#662]
![Screen Shot 2018-05-16 at 10.32.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379ef0c2853415f4fbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e7495ca7163664ef75346e0a.png)

**Comment by n1207n** [comment]
@rkrupinski, Can you take a look at this one? Interestingly, project's activity links work in My planned actions, but not working in partner project's activity links from response parameter.

**Comment by sethgold8** [comment]
I noticed it was working when I went through 'My Planned Action'.

Going to Partners ---> Projects ---> Activities ---> Project activities is still not working.

**Comment by rkrupinski** [comment]
This does work now, trust me :) Something must have prevented the code from deploying to staging.

cc @nemd

**Comment by sethgold8** [comment]
Just tested again and still facing the same issue. I can show at our standup

Was admin_ao in Iraq
2018 app/IRQ/cluster-reporting/plan/115/response-parameters/partners/project/126/activities?page_size=10&page=1&project=126

**Comment by sethgold8** [comment]
working now :)
