### ISSUE TITLE
Title of Indicators should Wrap instead of ...

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#666]
If it's a long title, we cut it off with '...'. 

We should Wrap (examples below) it instead

![Screen Shot 2018-05-16 at 12.13.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379ed0c2a52415f47bc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e7495cac133261e774306e0a.png)

Example of Wrap: https://spreadsheeto.com/wrap-text-excel/

**Comment by momimomo** [comment]
This will be nearly impossible to implement given current complexity of this component.

How about adding labels on hover that contain the full title?
