### ISSUE TITLE
IMO and Partner Should not be able to edit title, label, etc (more in the ticket) for PAI derived from CAI

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#669]
Editing Partner Activity Indicator modal derived from CAI a  should only allow Partner to add new locations or editing targets on locations. This happens for both **Partner and IMO user**

Right now IMO can edit Title, Comments, measurement specifications, Frequency of reporting, date of report, start date of report, labels (all), baseline and target on PAI **even though they should be locked since they are derived from Cluster Activity**

**removed previous screen shot because it was the wrong one**

**Comment by momimomo** [comment]
I'm sorry, it was Rafał's component I think, it's going to take some time for me to go through all of it, so maybe let's assign him too.

**Comment by rkrupinski** [comment]
@sethgold8 The UI also lets IMOs add partner activities / indicators. How's that coherent?

cc @n1207n

**Comment by sethgold8** [comment]
@rkrupinski just the edit indicator modal of the photo attached above

**Comment by sethgold8** [comment]
@rkrupinski 

Partner should not be able to edit  'Baseline' and 'In Need'

![Screen Shot 2018-05-18 at 10.54.58 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a379ef0c2e55415a46bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e74b53a2123064e1723e6e0a.png)

**Comment by sethgold8** [comment]
working :)
