### ISSUE TITLE
Activities from OCHA not showing up. Objectives + Indicators from Old OPS might be missing too

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#672]
Previously we had these objectives (and indicators inside)

![Screen Shot 2018-05-16 at 2.27.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a37af1102c4f5d5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44de44d53a515306be77e2431.png)

Now we are missing them

![Screen Shot 2018-05-16 at 2.15.15 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a37af1132e4f5e5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44de44d53a5143f6ae1722431.png)

**Comment by sethgold8** [comment]
any thoughts update on this @maciej-jaworski ?

**Comment by maciej-jaworski** [comment]
@sethgold8 I do not have time to look into this.

**Comment by sethgold8** [comment]
@sethgold8 look into if we are getting activities. Check previous videos

**Comment by sethgold8** [comment]
I do not believe we are getting activities. Also not sure if we are getting objectives/indicators from the old ops cc @dfryta @n1207n

**Comment by n1207n** [comment]
Trying to import OCHA activities from Cameroon workspace now, based on what OCHA told us for any sample workspace to work with.

Getting these errors from celery (which I had to create Periodic task for each response plan :( sadly) :

```
[2018-05-31 17:47:12,238: ERROR/MainProcess] Task ocha.tasks.finish_response_plan_import[6284ecb7-72eb-4e25-9d15-19e362951b2f] raised unexpected: TypeError('string indices must be integers',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/django_api/apps/ocha/tasks.py", line 31, in finish_response_plan_import
    entities_response=plan_data, measurements_response=strategic_objectives_data
  File "/code/django_api/apps/ocha/imports/response_plan.py", line 45, in save_activities_and_objectives_for_response_plan
    s['planEntityIds'] for s in activity['value']['support']
  File "/code/django_api/apps/ocha/imports/response_plan.py", line 45, in <listcomp>
    s['planEntityIds'] for s in activity['value']['support']
TypeError: string indices must be integers
```

**Comment by sethgold8** [comment]
@dfryta 

Data From OCHA:

Libya 2018 should have Cluster Objectives and Indicators

Cameroon 2018 should have indicators and activities

**Comment by dfryta** [comment]
Cameroon 2018 has different response structure then rest of Response Plans. I was able to handle this, but still - list of ID is empty. TBD on meeting.

**Comment by dfryta** [comment]
Sean will check Cameroon data. Project preview is fixed. Ticket closed.

**Comment by sethgold8** [comment]
@dfryta has Sean given an update regarding Cameroon?
