### ISSUE TITLE
When pulling project from OCHA is not an option, do not show the 'custom' choice to add the project. Just have it directly enter the custom information

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#674]
- [x] When pulling project from OCHA is not an option, do not show the 'custom' choice. Just go there directly

- [x] Project list should only apply to specific Partner after the partner is selected

**Comment by rkrupinski** [comment]
@sethgold8 

> Project list should only apply to specific Partner after the partner is selected

Do you mean filtering the list of partner projects by partner name?

**Comment by sethgold8** [comment]
Yes. Once the Partner is selected, we should only show the projects that
pertain to that specific partner.

**Comment by rkrupinski** [comment]
@sethgold8 

> Yes. Once the Partner is selected, we should only show the projects that
pertain to that specific partner.

This seems to be working as we speak

**Comment by sethgold8** [comment]
The flow is
1. Select 'Custom'

![Screen Shot 2018-05-18 at 3.38.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a37bf111234f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de74556a51b3162e6702431.png)

2. Enter Custom Details.

![Screen Shot 2018-05-18 at 3.38.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a37bf111234f5d575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44de74556a6133e63e4772431.png)

Since we are not pulling from OCHA, there is no need to do the 1st 'Custom' Select. It should be 1 step instead of 2

**Comment by rkrupinski** [comment]
@sethgold8 @momimomo See https://github.com/unicef/etools-partner-reporting-portal/pull/677

**Comment by sethgold8** [comment]
working :)
