### ISSUE TITLE
UX for making it clear that a user needs to add locationsI for report generation in Cluster (Keep Open)

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#675]
Need to improve the UX so a user knows when reports are generated.

- [x] In the indicator list view (on all indicator list views be it CA, PA, CO, PP etc. Should show in all places in response parameters for IMO and only under "my planned action" lists if partner) at the top add a message if any indicator has no locations "Please make sure indicators have locations set for reports to be generated". Along with an exclamation mark next to "edit" link. Clicking edit or "!" will do same thing (open edit modal). If all indicators have locations then don't show any warnings.

![Screen Shot 2018-06-04 at 11.18.44 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f76b7191a379ee0c2a59415b4abc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f349e94c56a2173461ee75326e0a.png)

**Comment by sethgold8** [comment]
Still working on these.

After a Partner adopts a Cluster Activity, we open the 'edit' indicator modal to let Partner user know they need to add Location(s) so reports are generated.

![Screen Shot 2018-06-04 at 11.01.53 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f76b7191a379ee0c2b50415a4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e94c56a1153467e77e3f6e0a.png)

If user exits out of the Location Modal, and if no Locations have been added to a specific PAI,

**Comment by sethgold8** [comment]
Still working on these.

After a Partner adopts a Cluster Activity, we open the 'edit' indicator modal to let Partner user know they need to add Location(s) so reports are generated.

![Screen Shot 2018-06-04 at 11.01.53 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f76b7191a379ee0c2b50415a4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e94c56a1153467e77e3f6e0a.png)

If user exits out of the Location Modal, and if no Locations have been added to a specific PAI,

**Comment by chachra** [comment]
Please add this data in the relevant API calls and add another person to handle the frontend piece of it.

**Comment by n1207n** [comment]
Backend API for `/api/indicator/<INDICATOR_TYPE>/` has `locations` serializer field per each Reportable.

If `locations` field is empty for Reportable, then we should show above UI message.

**Comment by sethgold8** [comment]
@rkrupinski 

- [ ] Needs to work for all indicator list views: CA, CO, PP 

Right now its working well for adopted PAI

**Comment by rkrupinski** [comment]
@sethgold8 This does work for all the lists (in cluster-reporting) but my assumption was that this only makes sense if you're able to edit (given the warning message)

![screen shot 2018-06-08 at 09 14 22](https://user-images.githubusercontent.com/775177/41144206-6781ea44-6afc-11e8-9508-76db517df08e.png)

**Comment by sethgold8** [comment]
@rkrupinski it's working good as is :)

- [ ] let's not show the warning message for Cluster Activity Indicator list UI since we don't generate reports for CAI

**Comment by sethgold8** [comment]
working good :)
