### ISSUE TITLE
Misc Dashboard Issues

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#680]
- [x] Number of Due/Overdue Reports in dashboard # is different then the # in Reporting Results 
Says 188
![Screen Shot 2018-05-18 at 5.03.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a37df112284f5a5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44de7455da617376aef702431.png)

Only showing 31
![Screen Shot 2018-05-18 at 5.02.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a37df112294f5b5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de7455da6173364ee702431.png)

- [x] Remove see all partners link

**Comment by sethgold8** [comment]
I noticed no matter how many locations, disaggregations, everytime I submit a report, the 'Number of Due/Overdue Reports'  goes down by 18 for imo on iraq 2018. IRQ/cluster-reporting/plan/152/dashboard?page=1&cluster_id

**Comment by n1207n** [comment]
Number of Due/Overdue Reports reflects # of due/overdue indicator reports on Partner Activity indicators. Renaming the polymer label as such.

**Comment by sethgold8** [comment]
working good :)
