### ISSUE TITLE
Input box is disabled when clicking 'enter data' on locations with no disaggregation reported on

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#685]
I went to enter data and was unable to. Input is not enabled.

![Screen Shot 2018-05-21 at 4.27.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a37cf1102c4f5b5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44de84950a7163461e0772431.png)

**Comment by sethgold8** [comment]
@rkrupinski  as Partner:  Armenia  2017 HR - Wash Cluster Partner. In Workspace Armenia, programme_document_0

You can get to indicators here: app/AM/ip-reporting/pd/580/report/126/edit?page=1

**Comment by rkrupinski** [comment]
@n1207n 

This is related to #654.

Locations for which the problem occurs have `disaggregation_reported_on` with ids that don't match the ones within `disagg_lookup_map`. Also, when you check and uncheck again all the disaggregation checkboxes (`disaggregation_reported_on` is then built by polymer, thus matches `disagg_lookup_map`) you're unable to submit the data:

```json
{
  "non_field_errors": [
    "This IndicatorLocationData cannot be updated for dual-reporting: Use Cluster reporting entity IndicatorLocationData instance"
  ],
  "error_codes": {
    "non_field_errors": [
      "invalid"
    ]
  }
}
```

**Comment by n1207n** [comment]
I see now inputs are enabled on dual reporting data

**Comment by sethgold8** [comment]
Input box is working. 

Getting 500 error when trying to submit data. Pushing this through but opening a new ticket
