### ISSUE TITLE
Fake data issue: Make sure LLO indicators with dual reporting to have disaggregation from its cluster activity and not create its own.

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#686]
![Screen Shot 2018-05-21 at 4.53.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a37cf117284f5b5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de84953ad113467e07e2431.png)

**Comment by n1207n** [comment]
TODO: We need to re-run fake data script when staging is updated with this change.

**Comment by n1207n** [comment]
Fake data script is somehow broken. locally reproduced. Needs to fix that then we can test these issues again

**Comment by n1207n** [comment]
Turns out there was an additional manual step to do in order to generate dual reporting indicator reports. Will run that manual step once staging is deployed again. Then I'll close this.

**Comment by sethgold8** [comment]
working good :)
