### ISSUE TITLE
Title of projects in response parameters -> partner projects - add hover

### ISSUE THREAD

**Issue by momimomo** [unicef/etools-partner-reporting-portal#691]

**Comment by momimomo** [comment]
![Screen Shot 2018-05-23 at 09.26.42.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a378e60c2957415b4cbe5d4a1f06a3a3dc78e2a436628f5458bbd96e0a74c53b18ffb9871fbf08b8258c4982b4ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ff64de14957a310366af43b.png)

**Comment by sethgold8** [comment]
working good :)
