### ISSUE TITLE
In IP when in a QPR, Cluster Indicator top bar is blue as opposed to green

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#695]
Need a way to identify that it is a cluster indicator and make sure the bar is green

![Screen Shot 2018-05-23 at 5.07.51 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a37df1122c4f5a5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df44ce04f55a3153162ee762431.png)

Photo is wrong (can't update it now bc dual reporting is not available with fake data issue). The blue color needs to be green if indicator is dual reporting

**Comment by sethgold8** [comment]
check frontend to see if it has a flag to turn the color green

**Comment by n1207n** [comment]
Apparently, the backend work for this ticket is done already. Smart me from the past ;)

** Technical notes for frontend **
@rkrupinski,

IndicatorReport object has `is_related_to_cluster_reporting` attribute. Turn green color for IndicatorReport row in ProgressReport details page, *if the ProgressReport type is QPR and `is_related_to_cluster_reporting` is true when Polymer iterates each indicator_report object.

![Screen Shot 2018-05-30 at 10.55.31 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f36b7191a379ef0c2e54415c4fbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b49c259f349e64a55a61a3066e272376e0a.png)

**Comment by sethgold8** [comment]
working good :)
