### ISSUE TITLE
Missing fields in PMP Partner API

### ISSUE THREAD

**Issue by dfryta** [unicef/etools-partner-reporting-portal#699]
New partner endpoint `https://etools-demo.unicef.org/api/prp/v1/partners/?workspace=2130` is lack of `partner_type`, `cso_type`, `total_ct_cp`, `total_ct_cy`. Please add them to PMP API.

**Comment by sethgold8** [comment]
@robertavram do we have an update on this?

**Comment by robertavram** [comment]
Done!

**Comment by sethgold8** [comment]
thanks @robertavram :)

**Comment by sethgold8** [comment]
coming through :)
