### ISSUE TITLE
Add partner_id to projects imported from OCHA

### ISSUE THREAD

**Issue by momimomo** [unicef/etools-partner-reporting-portal#701]
Please add field `partner_id`allowing for filtering projects available at `/api/ocha/projects/response-plan/<id>/`. 

(current records from this endpoint: )
![Screen Shot 2018-05-28 at 15.58.05.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456fb6b7191a379ea0c2e59415f4bbe5d4a1f06a3a3dc78e2a436628f5458bbd96e0a74c53b18ffb9871fbf08b8258c4982b4ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ff34ae44457a3163765f43b.png)

Since we'll be filtering projects on the frontend, there shouldn't be a need for any further changes in the backend.

**Comment by momimomo** [comment]
This is related to #640

**Comment by dfryta** [comment]
We have added external_ocha_id to request and we did backend filtering. Ticket closed.
