### ISSUE TITLE
Hard Refresh after importing response plan

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#713]
-Once IMO adds a new response plan, they are not attached to the Cluster until there is a refresh. We should do a Hard Refresh as soon as a response plan is added

**Technical notes**
- [ ] Once Polymer finishes a REST API to add new response plan from https://prp.tivixlabs.com/api/ocha/response-plans/workspace/5/, do a hard refresh on a browser.

**Comment by rkrupinski** [comment]
From what I see, this works as expected:

![rp](https://user-images.githubusercontent.com/775177/41037208-dfc1ea10-6992-11e8-9616-526a04286672.gif)

**Comment by sethgold8** [comment]
We are not pulling the clusters here after repsonse plan is added until there is a hard refresh

![Screen Shot 2018-06-06 at 8.40.21 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f56b7191a370f1162b4f5d5e5edd3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df443e3445ca3133663e0732431.png)

**Comment by sethgold8** [comment]
working good :)
