### ISSUE TITLE
From indicators imported from OCHA (Nigeria 2018), we cannot edit and save COI

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#714]
![Screen Shot 2018-06-04 at 3.36.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f76b7191a37bf1112d4f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df443e04854ac143766e6712431.png)

link: app/NGA/cluster-reporting/plan/15/response-parameters/clusters/objective/100?page_size=10&page=1&cluster_id

**Comment by rkrupinski** [comment]
2 issues:

1. There were some validation edge-cases when a required json field was initialized with the value of `0` - this is now fixed
2. The error on the screenshot is a result of `loc_type` for some locations being `0`. We currently only support values from range `1..5`. How do we proceed?

![screen shot 2018-06-06 at 13 43 45](https://user-images.githubusercontent.com/775177/41036267-cedc4b94-698f-11e8-9253-d082cbc6c0f0.png)

cc @n1207n

**Comment by sethgold8** [comment]
@n1207n  Is the 0 coming from OCHA or are we setting it to 0.

**Comment by n1207n** [comment]
Digging through OCHA codes, it seems OCHA is returning admin_level 0 if it's country-level location.

Either we should start treating 0 as country admin level in PRP or we should save it as admin_level 1 when importing OCHA indicators.

**Comment by rkrupinski** [comment]
I'm fine w/ both. @sethgold8 ?

**Comment by sethgold8** [comment]
working good :)
