### ISSUE TITLE
Fixtures for all sync/ periodic tasks in PRP

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-partner-reporting-portal#718]
can we have a fixture file for all tasks in PRP so we can load it with 1 command rather than having to manually add all tasks by hand in admin.

@n1207n

**Comment by chachra** [comment]
Also update dev setup steps to manually load up this fixture maybe. Make sure its not initial data otherwise will keep overriding on deploy. Tx.

**Comment by n1207n** [comment]
Now we have Django fixtures json data for djcelery model instances. Fabric command is updated to loaddata on periodic_tasks as well.

Apparently, PD sync task can already iterate workspaces, so no change is made on there.

Report generator and Overdue report checker are running every minute. Partner, Workspace, and PD sync tasks are running every 2 hours.

**Comment by sethgold8** [comment]
pushing through
