### ISSUE TITLE
Use basic auth for all OCHA calls to avoid throttling

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#720]
Use credentials sent. Configure them in test/staging/prod envs.

Only needed for calls to the new v1/v2 endpoints.

**Comment by sethgold8** [comment]
@dfryta is this on staging? We may have to update k8s secret to include OCHA credentials

**Comment by dfryta** [comment]
@sethgold8 yes it is. You have to setup Environmental Variables: `OCHA_API_USER` and `OCHA_API_PASSWORD`. If they are not provided we do not use basic auth.

https://github.com/unicef/etools-partner-reporting-portal/blob/develop/django_api/django_api/settings/base.py#L460

**Comment by dfryta** [comment]
Sent email conversation.

**Comment by n1207n** [comment]
Staging k8s is now using OCHA credentials in Django settings and I can confirm. We can close this.
