### ISSUE TITLE
Admin trigger or endpoint for triggering a task on demand

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-partner-reporting-portal#721]
It would be very useful for testing if there was an admin button / endpoint that would trigger some of the tasks on demand... It would avoid having to set the synchronizers at unreasonable frequency during testing and would help when developing the integration.

Partner Sync
PD sync
Process Reporting Periods
Process Due Reports

It would be useful if the applicable ones can be called with a "business_area_code" parameter in order to process one workspace. Let me know if help is needed for this as it might not necessarily be in your scope.

**Comment by n1207n** [comment]
Hi @robertavram,

Would you like to have a Django management command for each of above periodic tasks? That might be more useful for you in terms of testing that involve data from any of above periodic tasks ;)

I'll prepare management commands today for above.

**Comment by n1207n** [comment]
I see. I just don't want to witness the APIs heavily abused to trigger celery perioidic tasks more than it is intended to call. Hence, I went with management command route.

I'll come up with a REST API for triggering periodic task with optional argument.

**Comment by robertavram** [comment]
yeah this api should probably only be accessible by superusers

**Comment by n1207n** [comment]
The API is now finish and the PR is open for review: https://github.com/unicef/etools-partner-reporting-portal/pull/723

A superuser should call a REST API at `/api/core/task-trigger` with the following GET parameters:
* `task_name`: celery task function python path (required)
* `business_area_code`: Optional argument for PD or Partner sync task

Here are some API payload examples:

```
Basic API payload:
GET http://localhost:8082/api/core/task-trigger/?task_name=indicator.tasks.process_due_reports

200 OK
{"task_name":"indicator.tasks.process_due_reports","status":"started"}

API payload with business_area_code:
GET http://localhost:8082/api/core/task-trigger/?task_name=unicef.tasks.process_programme_documents&business_area_code=2130

200 OK
{"task_name":"unicef.tasks.process_programme_documents","status":"started"}
```

Here are some validation errors you may encounter:
```
API payload:
GET http://localhost:8082/api/core/task-trigger/?task_name=unicef.tasks.process_programme_documents&business_area_code=ffds30

400 Bad Request
{"non_field_errors":["business_area_code must be digit only"],"error_codes":["invalid"]}

API payload:
GET http://localhost:8082/api/core/task-trigger/?task_name=unicef.tasks.process_programme_docu

400 Bad Request
{"non_field_errors":["No task is found with name: unicef.tasks.process_programme_docu"],"error_codes":["invalid"]}

API payload:
GET http://localhost:8082/api/core/task-trigger/

400 Bad Request
{"non_field_errors":["task_name is required"],"error_codes":["invalid"]}
```

The task is triggered asynchronously in celery worker instance.

**Comment by robertavram** [comment]
@n1207n you Rock 🎸

**Comment by n1207n** [comment]
@robertavram Have you taken a look at PR for this issue? Let me know if this is good to go and merge into develop. Then you shall have this API in your environment.

**Comment by sethgold8** [comment]
@robertavram circling back on this if you've had a chance to look at the PR (#723) for this ticket

**Comment by robertavram** [comment]
lgtm,
tests are failing though..

**Comment by n1207n** [comment]
Pushing this forward. We have a separate ticket to resolve unit test issues at once.
