### ISSUE TITLE
Update PD reporting date sync logic for HR

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#724]
Apparently, PMP PD sync API only sends due date for HR report type, and this is in alignment with documentation we have in gitbook.

A small change is needed to report generator for handling HR.

> For humanitarian response indicators that are UNICEF specific “high-frequency humanitarian response indicators”, the due date is defined by the user in PMP, and the start and end date of the reporting period are automatically assigned (start date: previous due date reporting period (or PD start date for first HR) + 1 day; end date: due date selected by the user).

**Comment by sethgold8** [comment]
working good :)
