### ISSUE TITLE
Add Cameroon Manually

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#726]

**Comment by n1207n** [comment]
Added manually via Django admin

**Comment by sethgold8** [comment]
@n1207n lets sync on this quick later. Not getting activities

**Comment by n1207n** [comment]
Hmm not sure how this ticket is rejected just because the activities are not coming up.

Shouldn't we mention this in that OCHA ticket?

**Comment by sethgold8** [comment]
pushing through
