### ISSUE TITLE
Special Reports (SR) should never be final

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#730]
![Screen Shot 2018-06-19 at 2.23.12 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fa6b7191a37af110284f5e5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df442e54956a011366aef7f2431.png)

**Comment by n1207n** [comment]
This is more of frontend ticket. Just don't use is_final flag on polymer

**Comment by sethgold8** [comment]
working good :)
