### ISSUE TITLE
Remove the amendment card if the PD doesn’t have any amendments.

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#732]
Don't show amendment card if no data

![Screen Shot 2018-06-19 at 2.26.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fa6b7191a37af1102d4f5b585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df442e54956a3133761e7732431.png)

**Comment by n1207n** [comment]
This is also frontend issue. Just don't show UI if amendment is empty.

**Comment by sethgold8** [comment]
Not sure if this is a fake data issue, but I am seeing Amendments Component with no data for programme_document_1 in Micronesia 2017 app/FM/ip-reporting/pd/4/view/details

![Screen Shot 2018-06-21 at 10.47.41 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f26b7191a379ef0c2f56415b4fbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e84b55a7103466ee77306e0a.png)

I noticed it was working for programme_document_0 in Micronesia 2017 app/FM/ip-reporting/pd/3/view/details

**Comment by sethgold8** [comment]
working good :)
