### ISSUE TITLE
Report Status and Report Type Filters are not working in Progress Reports. PD status filter not working in indicators Page

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#736]
- [ ] 
![Screen Shot 2018-06-19 at 3.17.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fa6b7191a37bf1132c4f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df442e54953a2143f6ae47f2431.png)

- [ ]
 ![Screen Shot 2018-06-19 at 3.17.06 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fa6b7191a37bf1132c4f5f595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df442e54953a21b3065e3772431.png)

- [ ] PD status filter not working on indicators Page

![Screen Shot 2018-06-19 at 3.23.31 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fa6b7191a37bf110284f5c5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df442e54952a4103667e5772431.png)

**Comment by rkrupinski** [comment]
After [a couple of changes](https://github.com/unicef/etools-partner-reporting-portal/commit/83282697e582e347dd3e1e8f73942c3cf54b2660), I'm unable to reproduce the bug. Let me know if you ran into any issues.

**Comment by sethgold8** [comment]
working good :)
