### ISSUE TITLE
Update report generator logic to handle HR progress report differently

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#737]
We need new Indicator reports for HR progress report to be handled differently based on indicator type (UNICEF HF or Cluster).

Right now, the report generator bundles new Indicator reports for all LLO indicators from PD into one HR progress report. This happens for each HR reporting requirement from PMP synced data.

However, LLO indicator that is marked as cluster indicator, should not use PMP HR reporting requirement, and use associated Cluster Indicator reporting requirement instead from cluster reporting.

Moreover, the indicator report for LLO cluster indicator should be grouped with UNICEF HF indicator reports if their reporting period is identical, otherwise should be put under a brand new HR progress report.

**Technical Notes**
- [ ] Generate Indicator reports first for creating ProgressReport instances if report type is HR
- [ ] When generating Indicator report for HR Progress Report, exclude cluster LLO indicators and add UNICEF HF indicator reports to HR progress report
- [ ] Iterate cluster LLO indicator separately and create Indicator report based on its LLO indicator's cluster activity reportable foreign key instance. Use this instance to look up frequency, start & end and due date in order to create cluster LLO indicator report
- [ ] Iterate each cluster LLO indicator report and compare UNICEF HR progress report's date info. If they are exactly matched, then assign cluster indicator report to UNICEF HR progress report. Otherwise, create a brand new HR progress report.

**Comment by sethgold8** [comment]
tested on Friday, good :)
