### ISSUE TITLE
Emails sent when when a report is sent back, submitted, accepted

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#739]
IP

1. Sent back - Email of the person submitting the report or authorized officer assigned to the PCA. Could be the same person.
2. Submitted- authorized officers and/or the focal points
3. Accepted - Email of the person submitting the report and authorized officer assigned to the PCA. Could be the same person.

Cluster

1. Sent back - Partner or Imo (whoever submitted the indicator report)
2. Submit - IMO
3. Accepted- Partner or Imo (whoever submitted the indicator report)

**Comment by KKaselkar** [comment]
@sethgold8  so we reopen this ticket during ID management ?
