### ISSUE TITLE
Indicator data tab for a submitted report (user is viewing)

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#74]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/231338351

One or more indicators (Reportables) showing. Expanding shows the indicator report and data for each location in that report for that progress/PD report.

Showing the table of data is to be done in #34

Filtering at the top will be handled in #33

#32 should follow this task (at a later time), since its a but more involved. I think for cleanliness it might be best to use different components, but same route? Can be decided.

For this task though route will probably be like /pd/$idX/report/$idY/data/

Backend API ----> /pd-report/$id/ should send back:
+ narrative of PD report
+ list of reportables (with their own narrative) etc. Happens to be the LL output name / id in this case, but could be other things (gfk) in future, so please take care.
+ nested in each reportable it should send back "indicators: [{
name: "indicator name",
id:,
}

PR -> indicator reports -> reportables -> LLoutputs

Take this data and group by LLoutput.id.

```
{
  // https://projects.invisionapp.com/share/RDBE0T04F#/screens/231338350
  partner_contribution_to_date:,
  funds_received_to_date:,
  challenges_in_the_reporting_period:,
  proposed_way_forward:,
  'outputs':
     [
         {
            id:
            name:    
            status: {remarks:, report_status:},  // backend can just read this from first indicator report associated with this output
            indicator_reports: 
                 [
                      {id:, indicator_name:, target:, achieved:},   // indicator_name can be indicator serialized or comes from blueprint
                      {id:, indicator_name:, target:, achieved:},    // target comes from Reportable
                      {id:, indicator_name:, target:, achieved:},   // achieved comes from IndicatorReport.total
                 ]
         },
         {
            id:
            name:  
            remarks:
            report_status:  
            indicator_reports: 
                 [
                      {id:, indicator_name:, target:, achieved:},   // indicator_name can be indicator serialized or comes from blueprint
                      {id:, indicator_name:, target:, achieved:},    // target comes from Reportable
                      {id:, indicator_name:, target:, achieved:},   // achieved comes from IndicatorReport.total
                 ]
         },
         {
            id:
            name:    
            remarks:
            report_status:
            indicator_reports: 
                 [
                      {id:, indicator_name:, target:, achieved:},   // indicator_name can be indicator serialized or comes from blueprint
                      {id:, indicator_name:, target:, achieved:},    // target comes from Reportable
                      {id:, indicator_name:, target:, achieved:},   // achieved comes from IndicatorReport.total
                 ]
         }
     ]
}
```

But NOT the actual data itself... that is in API in #21 and #34.

**Comment by lkolacz** [comment]
common branch name ```feature-Indicator-data-tab-submitted-report-viewing-#74```

**Comment by chachra** [comment]
Ignore the overall status and narrative assessment for now for this task. will open a new one.

**Comment by chachra** [comment]
@lkolacz updated description of issue more.
