### ISSUE TITLE
Date for Amendments should be DD MM YYY

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#740]
- [ ] Date for Amendments should be DD MM YYY. It should match PMP

![Screen Shot 2018-06-21 at 5.31.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f26b7191a37df1112a4f5d585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df442e74f52a1113664ef772431.png)

**Comment by rkrupinski** [comment]
We don't do any date formatting on the front-end. Whatever is returned from django, gets rendered.

cc @n1207n

**Comment by n1207n** [comment]
It turned out that date data in amendment JSON is not formatted to our standards. So we may have to change this at PD sync or something.

**Comment by n1207n** [comment]
Fixed directly. We have to resync PDs so that amendment dates will be formatted correctly before saving.

**Comment by KKaselkar** [comment]
@robertavram could you please redeploy the code so we can check in UNICEF test environment

**Comment by sethgold8** [comment]
confirmed :)
