### ISSUE TITLE
Display the latest or next due reports (QPR)

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#748]
System doesn’t display the latest or next due report for QPR. In the below example it displays the past 2 QPR’s but doesn’t display the next latest/due QPR, I did submit one of the QPR hence it shows accepted:

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/41859088-650d09b8-7869-11e8-9037-8bdf54e685e0.png)

![image](https://user-images.githubusercontent.com/32198614/41859099-6949aa2c-7869-11e8-8655-3f2e382f55f1.png)

**Comment by sethgold8** [comment]
@KKaselkar lets remove. We do not generate reports until they are due (July 25). It's not July yet, so has not yet been generated
