### ISSUE TITLE
Remove the Reports Link for Cluster Activity Indicators and also the Filter

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#750]
Let's leave this as blocked since waiting for confirmation from Gavin

Since we do not generate reports for CLuster Activity Indicators, we should we remove

 - [ ] 

1. Reports Link in Response Parameters for Cluster Activity Indicators

![Screen Shot 2018-06-26 at 5.53.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f56b7191a37df117284f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df54be14b55ac163f65e4772431.png)

 - [ ]

2. Filters Choices for Cluster Activity Indicators. The filter are still good, we just don't need the Cluster Activity Indicators to select

![Screen Shot 2018-06-26 at 5.53.12 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f56b7191a37df117284f5e5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df54be14b55ac163764e5762431.png)

**Comment by rkrupinski** [comment]
@n1207n How can I filter out cluster activity indicators from `/api/cluster/<response_plan_id>/cluster-reportable-simple-list/`? Adding `content_type_key` would help too.
