### ISSUE TITLE
Values missing on PRP overview page, need to be imported from PMP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#752]
IP PRP - > https://etools-test.unicef.org/app/IRQ/ip-reporting/overview/ 
Chrome browser
Country - > Iraq
Vendor Name - > AGENCY FOR TECHNICAL & EMERGENCY DEV.

Issue: On overview page the below highlighted values are missing:

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42094883-11ff56ea-7b7f-11e8-910e-249c1a45808c.png)
 
PMP Image:
![image](https://user-images.githubusercontent.com/32198614/42094910-21f31a96-7b7f-11e8-9b87-912e3c398c86.png)

**Comment by sethgold8** [comment]
@robertavram can you check to see if we are sending Basis for Risk Rating properly? We are receiving it for ( ACTION CONTRE LA FAIM ACF FRANCE) in Iraq, but not other partners.

All other fields we are getting proper

![Screen Shot 2018-06-29 at 4.47.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456fa6b7191a37cf1162c4f5a565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df54be24c53a5143566ef772431.png)

**Comment by robertavram** [comment]
added from PMP side.. @sethgold8  should we leave the ticket here until someone from your side confirms?

**Comment by sethgold8** [comment]
@robertavram   We confirm PMP PD sync returns Type of Assessment and Last assessment date. We can combine these two fields to fill: Basis for Risk Rating. Will push to delivered when live  cc @n1207n

**Comment by sethgold8** [comment]
Working in dev :)

![Screen Shot 2018-07-23 at 4.46.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a37cf1162d4f5b5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df549e2455ca2123364e4772431.png)

![Screen Shot 2018-07-23 at 4.46.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a37cf1162d4f5e575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e2455ca2113066e3742431.png)

**Comment by KKaselkar** [comment]
Can you please remove the highlighted date:

Screenshot from PRP:
![image](https://user-images.githubusercontent.com/32198614/45108952-1c75b480-b10c-11e8-92e6-474fa2b364b6.png)


Screenshot from PMP:

![image](https://user-images.githubusercontent.com/32198614/45109005-3ca57380-b10c-11e8-95c6-ee50c1f4d0ef.png)
