### ISSUE TITLE
HR displays as final report in PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#753]
etools-test environment
chrome browser
Partner: AGENCY FOR TECHNICAL & EMERGENCY DEV.

HR report displays final report in PRP

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42095676-4b219d46-7b81-11e8-92df-22ededf5e95f.png)

**Comment by sethgold8** [comment]
@KKaselkar HR has final reports

**Comment by sethgold8** [comment]
HR has final reports. Closing this ticket
