### ISSUE TITLE
Error when clicked on PDF link on indicators page

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#754]
IP PRP - > https://etools-test.unicef.org/
Chrome browser
Country - > Iraq
Vendor Name - > AGENCY FOR TECHNICAL & EMERGENCY DEV.

Error when clicked on PDF link on indicators page

**Comment by KKaselkar** [comment]
@robertavram  as per Seth this has been fixed in tivixlabs, so need to be redeployed in UNICEF environment

**Comment by sethgold8** [comment]
@KKaselkar please confirm if this is working now

**Comment by sethgold8** [comment]
@KKaselkar update on this? IF working, please close

**Comment by KKaselkar** [comment]
working fine
resolved
