### ISSUE TITLE
Incorrect sequence of list of indicators in PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#758]
IP PRP - > https://etools-test.unicef.org/
Chrome browser
Country - > Iraq
Vendor Name - > AGENCY FOR TECHNICAL & EMERGENCY DEV

Sequence of indicators is different in PMP and PRP.
PRP must align or show the same sequence of indicators as displayed in PMP.

**Comment by KKaselkar** [comment]
PMP screenshot:
![image](https://user-images.githubusercontent.com/32198614/42101352-df8d7c48-7b90-11e8-9568-fd2221fcc64a.png)


PRP screenshot:
![image](https://user-images.githubusercontent.com/32198614/42101364-e98f6f58-7b90-11e8-91c6-09bcb600397d.png)

**Comment by sethgold8** [comment]
@KKaselkar this requires significant amount of work. Not in requirements so will close it.

**Comment by KKaselkar** [comment]
@sethgold8  I had to provide a business case (need) to Rob. Will contact him on this issue .
