### ISSUE TITLE
Value of target doesnt display in PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#759]
IP PRP - > https://etools-test.unicef.org/
Chrome browser
Country - > Iraq
Vendor Name - > AGENCY FOR TECHNICAL & EMERGENCY DEV

Value of target is not displayed on any of the indicators except cluster indicators and system still calculates the progress of report against the target, Target values do not appear anywhere on the indicators.

**Comment by KKaselkar** [comment]
PMP screenshot:
![image](https://user-images.githubusercontent.com/32198614/42101487-32350f6a-7b91-11e8-931b-f3a94fa018d7.png)


PRP screenshot:

![image](https://user-images.githubusercontent.com/32198614/42101507-4267be28-7b91-11e8-9c60-c3d45a328a7e.png)


PMP progress page:

![image](https://user-images.githubusercontent.com/32198614/42101524-4ea72c32-7b91-11e8-83ef-3f9ebb8f5ccf.png)

**Comment by robertavram** [comment]
There was an update in the models, the serializers are returning the old target and baseline values... @n1207n I'll update the values.. but they will be json (the same structure you have currently in PRP) there will need to be an actiion from you after we update the serializers...

**Comment by robertavram** [comment]
@n1207n Targets and baseline fields were added, they are now json and resemble  PRP models. Also added nominator_label / denominator_labels. delivered in etools-demo to have for reference. you may need to update the pd synchronizer to use these values.

**Comment by sethgold8** [comment]
working :)
![Screen Shot 2018-07-23 at 4.38.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a37cf111234f5f585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df549e2455ca517366ae4762431.png)

**Comment by KKaselkar** [comment]
@sethgold8  targets do appear, will check the labels and update the ticket

**Comment by KKaselkar** [comment]
Value for targets dont appear for percentage and ratio indicators.
![image](https://user-images.githubusercontent.com/32198614/45109448-99edf480-b10d-11e8-983d-0d10dad6888f.png)


"label" still appears for quantity even though label field doesnt exists in PMP for quantity
