### ISSUE TITLE
Cluster objective indicator report submission by IMO

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#763]
Chrome browser, etools test environment, IMO role

IMO submitted a cluster objective indicator report.
"The IMO will be informed of this submission and you will not be able to make any changes on this report unless it is sent back to you. Are you sure you’d like to Submit this report?"

The same IMO can see the submitted report in submitted tab and click on the three dots and send back to the partner? but there isnt any partner involved in this report as this is a cluster objective indicator report.

system allows the same IMO to submit and send back his own report to himself

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42283910-e52d8c42-7f78-11e8-9e99-db7e4a9235ae.png)

**Comment by sethgold8** [comment]
@KKaselkar please include the error message you'd like us to share

**Comment by KKaselkar** [comment]
Message in the pop up to be updated when IMO submits the report: 
Are you sure you’d like to Submit this report? (Cancel / Continue)

**Comment by sethgold8** [comment]
@momimomo if IMO is submitting an Indicator Reprort, can we change the modal text to :
 
- [ ] Are you sure you’d like to Submit this report? (Cancel / Continue)

**Comment by sethgold8** [comment]
@momimomo on Etools test still seeing the old message

![Screen Shot 2018-07-23 at 12.11.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a379ed0c2a50415f4cbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e34e52a7133163e372326e0a.png)

**Comment by KKaselkar** [comment]
Message has been changed to " Are you sure you’d like to Submit this report? (Cancel / Continue)"
