### ISSUE TITLE
Export of project indicator report & cluster objective indicator report gives error

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#764]
Chrome browser, etools test environment, Iraq workspace, 

Partner role gets an error when clicked on the export button for the project indicator report and cluster objective indicator report is submitted.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42284713-5c39b142-7f7b-11e8-9cf4-899c75b155b3.png)
![image](https://user-images.githubusercontent.com/32198614/42284756-77b636a2-7f7b-11e8-873f-cbd7c5f06e2d.png)

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42284825-a9e455dc-7f7b-11e8-863e-7162f5e98dfe.png)

**Comment by sethgold8** [comment]
working on Tivix envornment

**Comment by KKaselkar** [comment]
@sethgold8  export link on the page in the above screenshot works when logged in as IMO but doesnt work when logged in as partner.
If its fixed in tivixlabs than please tag Rob and let him know to redeploy the code.

**Comment by sethgold8** [comment]
Just tagged you above @robertavram . Not sure it notifies you for updated comments so wanted to circle back to read Kunal's comment above

@KKaselkar can you close if this is working?

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/43219150-86f5a31a-9014-11e8-8693-3276d42975d1.png)

not working on demo prp

**Comment by n1207n** [comment]
The backend API for this currently allows IMO only to export. This should be easy fix as we just need to add Authorized officer to the permitted groups.

**Comment by KKaselkar** [comment]
getting an error with cluster member login

**Comment by sethgold8** [comment]
working fine for me. Can you include user, response plan and what you exported? Maybe a permissions issue

**Comment by KKaselkar** [comment]
opened another ticket 1041
