### ISSUE TITLE
Data Key error

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#765]
On both PRP IP and PRP cluster the data key must display the actual value of the labels entered and not the term "data key - [ ]" 

- [x] Change name from 'Data Key' to' Label'. For both IP and Cluster

- [x] We need to re-add Label for percent and ratio indicators with IP #frontend

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42285038-4bccd6d0-7f7c-11e8-904f-c04a497cddb4.png)

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42285064-5ef8d27c-7f7c-11e8-85dc-8c3acc43e357.png)

**Comment by sethgold8** [comment]
@momimomo 

Label (Data Key) can be found in Cluster
- [ ] Reporting Results in Cluster

![Screen Shot 2018-07-10 at 3.36.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f36b7191a37bf1112d4f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae34b51a7163667e4732431.png)


- [ ] 'Locations' edit in Cluster Activity Indicators

![Screen Shot 2018-07-10 at 3.36.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f36b7191a37bf1112d4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae34b51a016336be47f2431.png)


Label (Data Key) is not showing in IP currently.
- [ ] It should be for Percent and Ratio indicators in the

**Comment by momimomo** [comment]
Thanks!

**Comment by momimomo** [comment]
Changed those labels - let me know if I should look more into Percent and Radio indicators Data Key Label being hooked up properly - if there are steps to reproduce on staging please provide them as I'll be able to look if there is response from API or is it only frontend.

**Comment by momimomo** [comment]
All should be done and on staging!

**Comment by KKaselkar** [comment]
resolved.
