### ISSUE TITLE
Change the error message while adding same partner activity

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#766]
Chrome browser, Iraq workspace, etools test environment

Partner gets an error if tries to add the same activity for the same project, please change this error message to a user friendly error message.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42286629-8f02137a-7f81-11e8-9927-01e14f24f7e4.png)

**Comment by sethgold8** [comment]
@KKaselkar update with validation message please

**Comment by KKaselkar** [comment]
Error message to be updated:
Please note that below activity has already been added to this project

**Comment by sethgold8** [comment]
can we change the text to 

- [ ] Please note that below activity has already been added to this project

**Comment by KKaselkar** [comment]
Resolved, error message is updated
