### ISSUE TITLE
PD reports sync issue

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#767]
Chrome browser, etools test environment , Iraq workspace

created a PD in PMP demo environment https://etools-demo.unicef.org/pmp/interventions/395/details

, PD did appear in IP PRP but the reports dont appear in IP PRP

Aldo it takes 15-20 mins for the cluster indicators frequency requirements (for e.g. weekly or monthly) to appear on the reporting requirements card in PMP

**Comment by robertavram** [comment]
@ Silin we're getting an error on the PD sync. here's the trace:
```
[2018-07-05 13:30:08,699: ERROR/MainProcess] Task core.tasks.process_period_reports[5219d825-6560-4b22-87e8-aad960ff8b1c] raised unexpected: MultipleObjectsReturned('get() returned more than one Reportable -- it returned 2!',)
7/5/2018 9:30:08 AMTraceback (most recent call last):
7/5/2018 9:30:08 AM  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
7/5/2018 9:30:08 AM    R = retval = fun(*args, **kwargs)
7/5/2018 9:30:08 AM  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
7/5/2018 9:30:08 AM    return self.run(*args, **kwargs)
7/5/2018 9:30:08 AM  File "/code/django_api/apps/core/tasks.py", line 515, in process_period_reports
7/5/2018 9:30:08 AM    due_date
7/5/2018 9:30:08 AM  File "/code/django_api/apps/core/tasks.py", line 412, in create_ir_and_ilds_for_pr
7/5/2018 9:30:08 AM    pai_indicator = cai_indicator.children.get(partner_activities__partner=pd.partner)
7/5/2018 9:30:08 AM  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
7/5/2018 9:30:08 AM    return getattr(self.get_queryset(), name)(*args, **kwargs)
7/5/2018 9:30:08 AM  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 384, in get
7/5/2018 9:30:08 AM    (self.model._meta.object_name, num)
7/5/2018 9:30:08 AMindicator.models.MultipleObjectsReturned: get() returned more than one Reportable -- it returned 2!
```

**Comment by n1207n** [comment]
Are there any 2 LLO indicators from PD using same cluster activity indicator ID?

The only case letting this to happen is if you use same cluster indicator ID twice in PD indicators, which is illegal state in PRP. Dual reporting is meant to handle 1 parent and 1 child Indicator report relationship for data splitting purposes. In the meantime, we'll add a validation where the report generator would skip the dual reporting link if there are more than 2 PartnerActivity Indicator instances for 1 ClusterActivity indicator.

**Comment by KKaselkar** [comment]
@n1207n just wanted to provide you the screenshot of PMP which displays all the indicators added in the PD, you can see there are 2 different cluster indicators and 3 UNICEF indicators.
![image](https://user-images.githubusercontent.com/32198614/42394113-f85aee18-8126-11e8-8b72-6eab3809a656.png)

**Comment by sethgold8** [comment]
You can't use cluster activity indicator more then once in 1 PD since this is illegal in PRP for determining dual reporting link. This is the reason for report generator to cause error that Rob posted above.  For example, you can only add Number of stationary indicator once in this PD cc @KKaselkar @robertavram 

![Screen Shot 2018-07-09 at 4.54.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246454fa6b7191a37cf1172f4f5e565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29b41c95df54ae04555a01b3760e3772431.png)

**Comment by sethgold8** [comment]
discussed during call, #closing
