### ISSUE TITLE
Some initial Python 3 changes 

### ISSUE THREAD

**Issue by lkolacz** [unicef/etools-partner-reporting-portal#77]
think about removing 

from __future__ import absolute_import
Change __unicode__ to __str__ in models
Remove unnecessary params from super() method

**Acceptance criteria**
No major linting issues

Docker image for django_api switched to Python 3 base image?

**Comment by chachra** [comment]
Put a linter in place and make it part of CI process in CF?

**Comment by chachra** [comment]
Other than above task suggestions and linter, @n1207n lets make sure code is Python 3 compliant (think it mostly is?).

Switching to python 3 base image for django_api docker image would be key win / metric?
