### ISSUE TITLE
Remove start date in case of custom specific dates

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#773]
Chrome browser, etools test environment, Iraq workspace

Please remove the start date of reporting period when selected custom specific dates for frequency of reporting for all types of indicators in cluster. the below example is for cluster activity indicator.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42395319-7f74203c-812b-11e8-98fb-352b9a22a3d6.png)

**Comment by sethgold8** [comment]
@KKaselkar what is the purpose of removing it?

**Comment by sethgold8** [comment]
Custom Specific date relies on 'Start Date' in the indicator. Each date of Date of Report is used  to determine End date. 

- [ ] Can we change 'Date of Report'  to 'Due date of report'

**Comment by sethgold8** [comment]
confirmed :)
