### ISSUE TITLE
Dual reporting

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#774]
Chrome browser, etools test environment, Iraq workspace.

Created cluster activity reports with frequency of reporting as weekly (1st June 2018 is the start date),

Cluster indicator appears in PMP in PD.
Created HR reports in PMP for the same PD with reporting dates as 2 June to 8 June.

IP PRP displays the reports only for UNICEF indicators and not for cluster indicators.
system doesn't display the dual reporting window.

**Comment by sethgold8** [comment]
@KKaselkar how come you did not attach PD reference #,  photos, or links? This wastes time.  You need to be specific please.

**Comment by sethgold8** [comment]
@KKaselkar can you change the dates to match exactly and re-test.

**Comment by KKaselkar** [comment]
@sethgold8 locations were added and report was generated to Cluster PRP, the only issue is with the dates matching in both the systems, will retest and let you know

**Comment by KKaselkar** [comment]
Resolving the issue as this works
