### ISSUE TITLE
Partner Activity Indicator - created by IMO

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#784]
etools test environment, IMO role, IRAQ workspace

1) As an IMO I created cluster activity indicator and than adopted that indicator in partner activity indicator.

System doesnt allow to save the partner activity indicator as IMO needs to add the baseline at the cluster activity indicator level.

Baseline is already added for the same location and IMO again updates the baseline for the same location at cluster activity indicator level, but still it doesnt appear at partner activity indicator level , hence IMO is not able to save the partner activity indicator.

2) calculation method is percentage in the above scenario, inneed text box doesnt appear.
But at the partner indicator level system asks the IMO to enter inneed.

**Comment by KKaselkar** [comment]
https://etools-test.unicef.org/app/IRQ/cluster-reporting/plan/6/response-parameters/partners/activity/51/indicators?page_size=10&page=1

Partner Act Indicator by IMO
 
 
![image](https://user-images.githubusercontent.com/32198614/42699839-f716ca4a-868f-11e8-961d-ceecb3762e49.png)
![image](https://user-images.githubusercontent.com/32198614/42699846-fb48647a-868f-11e8-80fb-4933529ee497.png)


Cluster Act Indicator by IMO
![image](https://user-images.githubusercontent.com/32198614/42699852-00ce1796-8690-11e8-8fab-b7b9c21d70cd.png)

**Comment by sethgold8** [comment]
@KKaselkar 

- [ ] 1st part of this ticket is already in # . 
- [ ] 2nd part is not clear enough. Please rephrase and be specific with exact steps on how to reproduce

**Comment by sethgold8** [comment]
both of these tickets are in other tickets. Closing
