### ISSUE TITLE
Incorrect monthly reporting period

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#789]
1. Log into Cluster-PRP as IMO
2. Select a Response Plan
3. Go to Reponse Parameters -> Clusters -> OBJECTIVES tab
4. Click on a Cluster Objective
5. Go to CLUSTER OBJECTIVE INDICATORS tab
6. Click on ADD CLUSTER OBJECTIVE. Specify:
    a. Frequency of reporting = "Monthly"
    b. Start date of reporting period = "15 Jun 2018"

system displays incorrect monthly reporting dates:
The following Reporting Periods were created:
                15-Jun-2018 – 30-Jun-2018
                15-Jul-2018 – 31 Jul-2018

It would make more sense to have generated the following Reporting periods instead?
                15-Jun-2018 – 14-Jul-2018
                15-Jul-2018 – 14 Aug-2018

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42829794-2e171ef2-89b8-11e8-81dc-0842a64e6f51.png)


![image](https://user-images.githubusercontent.com/32198614/42829806-3209502a-89b8-11e8-9829-d32a27e22ce9.png)

**Comment by sethgold8** [comment]
@KKaselkar can you confirm, if user sets the start date for Monthly on May 15...Start date should be May 15 with end date June 14th and due date June 15. For next period start date should be June 15 with end date July 14th and due date July 15.

**Comment by KKaselkar** [comment]
Working now.
Issue is fixed on demo
