### ISSUE TITLE
Loading error when trying to save an indicator without 'Baseline'

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#791]
Browser:Chrome
Workspace:South Sudan
etools test

-Steps:
-Login as IMO.
-Go to Response Parameters -->Clusters ---> Activity Indicators
-Add Cluster activity indicator.
-Enter Title.
-Select Type- Percent or Ratio.
-Fill all the required fields.
-Click SAVE.
-User will be directed to list of indicators.
-Click on "Edit" option for the same indicator which was added last.
-Edit few of the fields.Delete the value populated in "Baseline".
-Click SAVE.

Results: The page freezes and shows "Loading data".Ideally it should display an error stating if Target is populated, baseline should also be populated.

**Comment by sethgold8** [comment]
working :)

**Comment by KKaselkar** [comment]
Issues resolved, no loading error anymore
