### ISSUE TITLE
Inneed field cannot be null- cluster activity indicatot

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#792]
Browser: Chrome
Workspace:South Sudan
etools test

Steps:
-Login as IMO.
-Go to Response Parameters -->Clusters ---> Activity Indicators
-Add Cluster activity indicator.
-Enter Title.
-Select Type- Percent
-Fill all the required fields.
-Add locations, Baseline and target in Locations Card.
-CLick SAVE.
-User will be directed to list of indicators.
-Click on "Locations" option for the Same indicator which was last created.
-Try editing the baseline.
-Click SAVE.

 Result: Error message is displayed that "In_need" field cannot be null.However "In Need" field is not present when type is "Percent" or "ratio"

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42834714-68635d3e-89c5-11e8-8da9-2e5a8a8654e2.png)


![image](https://user-images.githubusercontent.com/32198614/42834717-6cfe5c36-89c5-11e8-97af-262c9395b872.png)

**Comment by sethgold8** [comment]
- [ ] IMO unable to change and save baseline

**Comment by KKaselkar** [comment]
working fine now. Resolved
