### ISSUE TITLE
Add Error Validation if user does not add date for custom Response Plan

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#794]
Browser: Chrome
Workspace:South Sudan
etools test

Steps:
-Log in as IMO
-add a reponse plan from frontend.
-Select option Custom.
-Fill below details:       
Response Plan
Plan Type
Clusters
- Don't populate the start date and end date.
-Click SAVE.
 
Result: Error message is displayed and the page freezes and keeps on showing "Loading".Ideally a relevant error message should be displayed if start date and End date are mandatory.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42835284-6ce446d8-89c6-11e8-86b3-d6b78bdacec5.png)

**Comment by sethgold8** [comment]
![Screen Shot 2018-07-18 at 3.43.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455fb6b7191a37bf116284f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df54ae84856ac10356ae3712431.png)

**Comment by sethgold8** [comment]
- [ ] if start and end date are empty when creating custom response plan, through a frontend validation to prevent calling API @momimomo 
- [ ]  Make sure check start and end date before creating custom response plan @n1207n

**Comment by momimomo** [comment]
Hi, I don't see any front end date validation in PRP - in other modals, it's backend that's sending the error response along with 400 status. I'll update after backend change.

**Comment by n1207n** [comment]
Backend changes is in place and it's working. No frontend work is needed ;)

**Comment by sethgold8** [comment]
working :)

**Comment by KKaselkar** [comment]
Resolved, system gives error message to enter start and end date
