### ISSUE TITLE
Dashboard - constrained indicator

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#795]
1. Log into Cluster-PRP as IMO
2. Select Workspace = "Somalia".
3. Select Response Plan = "Water Sanitation in Somalia 2018 (FA)"
4. Go to Dashboard. 
5. Change Cluster filter from "All" to "Imported Type".

Constrained Indicator with Cluster = 'WASH" is listed under "List of constrained indicators". It shouldn't have since it is for Cluster = "WASH".

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42837199-615cb962-89cb-11e8-9319-33d2ae367c92.png)

![image](https://user-images.githubusercontent.com/32198614/42837214-66f69e24-89cb-11e8-9508-331993c41469.png)

**Comment by n1207n** [comment]
A couple of updates here:

1. We don't show Imported Type anymore. We map out cluster titles correspondingly, so this should no longer be issue.

2. Instead, I'm seeing `Imported` in Cluster column from List of constrained indicators rows. Based on the code, this should not happen though. I'm trying to redeploy polymer on dev environment to see if the changes are not deployed yet or something.

**Comment by sethgold8** [comment]
@KKaselkar can you please rephrase the specific issue? The top description is unclear

**Comment by KKaselkar** [comment]
@sethgold8  results displayed under constrained indicator section must be as per the filtered cluster selected in the cluster drop down list

**Comment by sethgold8** [comment]
Working now. In Food Security for admin_imo in IRAQ_2018, there are no constrained indicators. In Wash, you can see the constrained indicators

![Screen Shot 2018-11-13 at 4.55.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f06b7191a37cf1172e4f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e04853ad153e67ef752431.png)

![Screen Shot 2018-11-13 at 4.54.53 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f06b7191a37cf1172f4f5a5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e04853ad1b3064e0702431.png)

**Comment by KKaselkar** [comment]
another ticket is opened for constrained indicators not displaying on dashboard
