### ISSUE TITLE
Initial data modelings

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#8]
Create few Django model classes based on the diagrams.

**Comment by chachra** [comment]
![unicef humanitarian cluster portal kickoff - etools prp - data model](https://cloud.githubusercontent.com/assets/73096/25759968/8bb09076-3189-11e7-9b8a-5058449abc71.png)

Please implement based on updated attached.

There are models like indicator blueprint + reportable/applied indicator, indicator report and also blue ones (will sync from PMP in the future) that one can take from https://github.com/unicef/etools apps/models as well where appropriate.

**Comment by chachra** [comment]
Should be done (v1 merged) by EOD tomorrow (PST).
