### ISSUE TITLE
Partner name is not displayed in the project edit form

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#801]
Browser:Chrome
Workspcae:South Sudan
etools test environment

Steps:

-Login as a IMO.
-Go to Response Parameters--> Partners--->Projects
-Add a project.
-Fill all the required fields.
-Click SAVE.Project will be saved.
-Click on Edit Project.

Result: Partner name does not display on the field "Partner".However when user click on the dropdown the selected partner is displayed.

Ideally the name should be displayed in the field itself.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/43005314-7faae984-8c00-11e8-850a-cc52fc91790d.png)


![image](https://user-images.githubusercontent.com/32198614/43005322-8568433a-8c00-11e8-9d3f-ac372dde350d.png)

**Comment by n1207n** [comment]
The partner is actually being selected if you click that dropdown menu. We just need that dropdown UI to show default value if it has partner to it.

**Comment by KKaselkar** [comment]
@n1207 can you display the partner name as default value

**Comment by sethgold8** [comment]
working now

![Screen Shot 2018-11-07 at 1.53.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a379f117284f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ae74f52a2103f67e4722431.png)

**Comment by KKaselkar** [comment]
Issues resolved in dev
