### ISSUE TITLE
Editing disaggregations

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#804]
1. Log into Cluster-PRP as IMO
2. Select a Response Plan
3. Go to Reponse Parameters -> Clusters -> Disaggregations tab
4. Add 1 or 2 Disaggregations. SAVE.

User is not able to modify or edit the disaggregations.

Disaggregations must be editable if not used in any indicators

**Comment by sethgold8** [comment]
@KKaselkar Not a bug. We designed it this way so users would not do harm. They can do it in django admin
