### ISSUE TITLE
Generate Uploader Template error

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#810]
etools test environment
Browser:CHrome
Workspace:South Sudan

-Log in as an IMO.
-Click on "Generate Uploader Template".
-Go to Reporting results Tab.
-Spreadsheet will be downloaded.
- enter the data / report in the downloaded spreadsheet.
- click on import template and upload the file from the local machine.

Result: Error is displayed and report does not get uploaded.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/43012615-922a10e4-8c14-11e8-9733-515284ffbad5.png)

**Comment by sethgold8** [comment]
@KKaselkar which response plan, you will need to reproduce the exact issue

**Comment by KKaselkar** [comment]
Resolving this issue as it works well
