### ISSUE TITLE
Analysis tab - no indicator type and no graphical images

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#811]
etools test environment
Steps:
-Log in as IMO.
- Click on Analysis.
- Click on Indicators.
- Classification of indicators will be displayed.
-Click on the dropdown icon to expand the indicators.

Result: 
1. For some of the indicators Graphical images are not displayed 
2. Indicator Type is blank

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/43018010-236be4a4-8c26-11e8-909f-3ce3dd34634d.png)


![image](https://user-images.githubusercontent.com/32198614/43018015-2807d6bc-8c26-11e8-936e-0604570f35e9.png)

**Comment by sethgold8** [comment]
@KKaselkar location importer not ready

**Comment by KKaselkar** [comment]
@sethgold8  moving this ticket from backlog.
Identified as critical bug by business owner.
Analysis tab doesn't display any data on the screen for both operational presence and  indicator

**Comment by sethgold8** [comment]
@momimomo can you test the loading in analysis section on the Filter Box for workspace Syria in Demo and Dev environments. 

If you see infinite loading data, can you replicate in your machine and see the cause?

**Comment by momimomo** [comment]
There seems to be empty response from backend - Are you sure the data is avaialable? I it should be, please check the endpoint `api/cluster/cluster-analysis/<id>/indicators/` @n1207n

**Comment by n1207n** [comment]
Based on my inspection, that *loading data* loader keeps spinning if there is no partner data in cluster reporting. When I added partner activity and its indiator in one country, the analysis filter box UI loads fine. When I went to the country without any partner activity data, the analysis filter box UI has that hanging spinner. ccing @sethgold8

@momimomo, I think this has to do with how filter box polymer element is waiting on multiple promises, and it cannot resolve successfully if any of API calls made for each filter box returns an empty array data. If the API call returned an empty array, this should not block at all.

**Comment by n1207n** [comment]
@momimomo,

Possibly an origin of bug for this issue: https://github.com/unicef/etools-partner-reporting-portal/blob/develop/polymer/src/elements/filter-list.html#L178

Somehow, readyCount is not incremented when the API for filter box returned an empty data.

**Comment by n1207n** [comment]
@momimomo, actually the real culprit is probably `cluster-objective-filter-multi`

Assuming the response plan has clusters and locations from OCHA or via custom plan, cluster objective is the only one I could think of you have to create manually.

If you can take a look at that component and see if how empty array data affects the component itself.

![Screen Shot 2018-07-30 at 2.52.15 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246457f36b7191a37af117294f5e5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e84552a1163464ef732431.png)

**Comment by momimomo** [comment]
This component properly receives data and sets pending to false. Still looking into it!

**Comment by KKaselkar** [comment]
Not all the graphical images appear for the below mentioned indicators:
MB_ClustAct_2_15th Oct_Indi_1  
MB_ClustAct_15th Oct_Indi_2

**Comment by sethgold8** [comment]
If the indicator report is not submitted, Progress over time will not show anything

**Comment by KKaselkar** [comment]
Issues resolved on dev
