### ISSUE TITLE
Error is displayed twice

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#815]
etools test environment
1. Log into Cluster-PRP as IMO
2. Select a Response Plan
3. Go to Reponse Parameters -> Partners
4. Go to PROJECTS tab
5. Click on ADD PROJECT
6. Without populating any field, click on SAVE.

The list of errors are displayed twice.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/43021972-939b6300-8c33-11e8-8340-689401c3bca4.png)

**Comment by KKaselkar** [comment]
Error still exists
![image](https://user-images.githubusercontent.com/32198614/45109777-7f684b00-b10e-11e8-957d-1d51820a8ad1.png)

**Comment by sethgold8** [comment]
@KKaselkar The bug reported was for the error message repeating twice (as you can see in the first screenshot you posted). There is only 1 error message live (I have tested on Tivix environment and dev environment) and in the photo you posted.

cc @chachra

**Comment by KKaselkar** [comment]
Resolved, error is displayed once
