### ISSUE TITLE
Not able to add Cluster Objective Indicator

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#820]
etools demo environment
Iraq workspace
IMO role

Once click on save button for cluster objective indicator system keeps on loading and doesnt save the cluster objective indicator

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/43159588-bdbaca48-8f50-11e8-9617-5645739adede.png)

**Comment by sethgold8** [comment]
@KKaselkar 

- [ ] For New OPS, check  Libya  with Response Plan Libya 2018
- [ ] For Old OPS, check Afghanistan  with Response Afghanistan 2017

Keep in mind, when you import those response plans, it may take a few minutes for all the indicators to show up

**Comment by KKaselkar** [comment]
Working now, user is able to add cluster objective indicator
