### ISSUE TITLE
Cannot add cluster indicator in PMP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#821]
Demo PMP and PRP environment

When I select cluster while adding an indicator system throws an error.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/43219589-bce0f6d6-9015-11e8-8580-a839b502d204.png)

**Comment by sethgold8** [comment]
@ntrncic Etools demo PMP environment is not talking to the PRP DEMO environment. Can you configure Etools Demo to call our PRP Demo environment. 

cc @KKaselkar

**Comment by KKaselkar** [comment]
This is resolved.
