### ISSUE TITLE
Projects not showing after adding from OCHA

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#823]
As Partner (ADRA ADVENTIST DEVELOPMENT AND R AGENCY), we added a project successfully from OCHA. When we went to the list of projects, none we showing.

When Project is imported, somehow the Cluster is not associated with the project and the project list API cannot return the newly added project because Cluster link is missing.

**Comment by dfryta** [comment]
This one we need talk about. I will reach you Monday @sethgold8 since I have couple additional questions.

**Comment by dfryta** [comment]
I found an issue. It will be fixed soon - we are missing this relation at all.

**Comment by KKaselkar** [comment]
Working fine, resolved
