### ISSUE TITLE
When writing a Narrative for indicator, auto save should save after 2 seconds

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#832]
Add 2000 millisecond debounce delay to that text UI component

![Screen Shot 2018-08-01 at 11.21.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f26b7191a379ee0c2950415e48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f348e24c51a3143061e276366e0a.png)

**Comment by momimomo** [comment]
Hi, it seems it's already supplied with debounce - redux is updating as it should, 2000ms later.
![Screen Shot 2018-08-02 at 09.07.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f16b7191a378e60c2b56415c49be5d4a1f06a3a3dc78e2a436628f5458bbd96e0a74c53b18ffb9871fbf08b8258c4982b4ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5bf742e24b5da3163065f43b.png)

**Comment by momimomo** [comment]
This is from cluster.

**Comment by momimomo** [comment]
Can't seem to find that component then, but redux is updating with debounce already somehow...

**Comment by momimomo** [comment]
Found it! it was set to 400. Fixed.

**Comment by KKaselkar** [comment]
Resolved.
