### ISSUE TITLE
In xls export template when no data entered, leave blank instead of 0?

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#835]
Currently spreadsheet has 2 tabs, None (when no disagg) and another tab.

Totals are set to 0 by default, but if user were to upload the spreadsheet it'd be almost as if they reported 0's!

May be best to be blank. Its possible/doable since in the prp ui default is 0, but backend json structure knows when its default 0 versus user has intentionally reported a "0" progress.

**Comment by dfryta** [comment]
Copy of #918. To remove @sethgold8 ?
