### ISSUE TITLE
"Number of Due/Overdue Partner Activity Reports" on cluster dashboard is wrong.

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#840]
Number is wrong. Its mixing data across response plans because of wrong query in: https://github.com/unicef/etools-partner-reporting-portal/blob/c2146a5e306f5b0d1e3fd753c6f6718650ca84e9/django_api/django_api/apps/cluster/models.py#L117

Fix: similar to https://github.com/unicef/etools-partner-reporting-portal/commit/2b5e9a59decd4f6a269cea694e5ffcd0a5ef8fb7

**Comment by sethgold8** [comment]
working ; )
![Screen Shot 2018-10-31 at 4.14.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a37cf1132f4f5d575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24ae14f52a3143264e1742431.png)
![Screen Shot 2018-10-31 at 4.14.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a37cf1132f4f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24ae14f52a31b3766e2772431.png)

**Comment by KKaselkar** [comment]
Issue fixed for due/draft reports
