### ISSUE TITLE
OCHA plans are appearing twice ?

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#841]

**Comment by chachra** [comment]
![Screen Shot 2018-08-06 at 2.08.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ca8dffc9b0d720006675c4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f56b7191a37af112234f5d585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df548e44856a31b3062e67e2431.png)

**Comment by n1207n** [comment]
Should no longer be issue I think. Closing.
