### ISSUE TITLE
Filtering by partner on reporting results brings indicator reports for cluster objectives as well

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#846]
Should not be bringing in cluster objective indicator reports at all since it has nothing to do with partner.

**Comment by sethgold8** [comment]
If partner filter is used, grab Partner Activity and Partner Project indicators only @n1207n

**Comment by KKaselkar** [comment]
Partner filter is selected but the next drop down still displays cluster objective 
![image](https://user-images.githubusercontent.com/32198614/46972443-84fd6d00-d08c-11e8-803d-09e322fad0b6.png)

**Comment by sethgold8** [comment]
@groinder can you fix

- [ ] If Partner is Selected, hide 'Cluster Objective'

**Comment by sethgold8** [comment]
working :) 
![Screen Shot 2018-10-24 at 12.50.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f76b7191a379ed0c2e51415c4cbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f34fe14954a415326be576316e0a.png)

**Comment by KKaselkar** [comment]
Cannot add cluster objective indicators as button is not visible

![image](https://user-images.githubusercontent.com/32198614/47933648-85c73900-deab-11e8-8f2e-066839784871.png)


login: kunal_kaselkar@yahoo.com
demo.prp
Iraq workspace
