### ISSUE TITLE
Remove report status and due date columns from programme document list screen and add some other columns

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#85]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016130

Columns to be added:

![requesting_final_review_sign-off_--_ip_reporting_requirements___mockups_-_sumit_chachra_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/73096/26706011/e65b4dca-46ee-11e7-955a-ddbcde485fe2.png)

**Comment by kasialanecka** [comment]
I've added comment in Invision (No 18) with questions about the new view for this table. I'll update the view, but please check it before Rafal and Leszek will make those changes on their side.

**Comment by lkolacz** [comment]
common branch name: `feature-update-pd-list-columns-#85`
