### ISSUE TITLE
"List of my project activities" on partner dashboard does not respect cluster filter at the top

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#850]
- [x] Cluster filter at top is education but it shows nutrition etc. project activities as well for some reason. #Backend

![Screen Shot 2018-08-15 at 3.30.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f66b7191a37bf1112b4f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df54fe24a57a717376ae4702431.png)

- [ ] Clicking "see more" then resets the cluster filter at top right to 'All', it should not! #Frontend

![Screen Shot 2018-08-17 at 4.51.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f46b7191a37cf1172a4f5d575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df54fe4495cad133161ef7e2431.png)

**Comment by sethgold8** [comment]
![Screen Shot 2018-08-15 at 3.30.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f66b7191a37bf1112b4f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df54fe24a57a717376ae4702431.png)

**Comment by KKaselkar** [comment]
Issue resolved on dev
