### ISSUE TITLE
Weird gap in analysis ui

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#852]
https://www.evernote.com/l/AAVoBXrex7lPirI6EwweTBnc9wMQiyb76rs

**Comment by sethgold8** [comment]
not able to replicate so #closing

![Screen Shot 2018-08-15 at 3.26.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f66b7191a37bf1102d4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54fe24a57a4113660e0722431.png)

**Comment by sethgold8** [comment]
not able to replicate so #closing

![Screen Shot 2018-08-15 at 3.26.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f66b7191a37bf1102d4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54fe24a57a4113660e0722431.png)
