### ISSUE TITLE
Cluster reporting frequency not displayed in PMP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#859]
Cluster indicator reporting was set as weekly but in PMP it shows (0)
Cluster HR indicator is still displayed in the QPR in IP PRP.

Dev. prp environment.
Iraq workspace
PD : PCA 2016/04/PD2018437

**Comment by KKaselkar** [comment]
PMP
![image](https://user-images.githubusercontent.com/32198614/44465937-f967e280-a5ec-11e8-9f39-60405f5e94fb.png)

PRP
![image](https://user-images.githubusercontent.com/32198614/44466137-8dd24500-a5ed-11e8-8265-c23243f7bb49.png)

![image](https://user-images.githubusercontent.com/32198614/44466203-b5c1a880-a5ed-11e8-902c-2cd912825c87.png)

**Comment by KKaselkar** [comment]
@sethgold8  is there  any update on this? as we need to start testing dual reporting.
the error that I sent you on slack is below:
Processing PD: 437
[2018-08-21 15:36:38,576: WARNING/Worker-2] Cannot associate PartnerActivity to ClusterActivity for dual reporting - skipping link!
[2018-08-21 15:36:38,576: WARNING/Worker-2] Invalid ClusterActivity Reportable ID for dual reporting - skipping link!
[2018-08-21 15:36:38,735: WARNING/Worker-2] Processing PD: 436

**Comment by sethgold8** [comment]
@KKaselkar you need to recreate Dual Reporting indicator in PMP demo due to stale cluster activity indicators. 

For Dual reporting, reporting period needs to match. Look at the cluster reporting, create a Cluster Activity  indicator with frequency all lined up. Create Partner activity from the cluster activity, then go to pmp and create cluster indicator with a cluster activity indicator you created from PRP.

**Comment by KKaselkar** [comment]
@sethgold8  I had created new cluster indicators and used them in PMP,  but I can try again if you want .

**Comment by sethgold8** [comment]
@KKaselkar yes please do and let know steps after following the above comment

**Comment by sethgold8** [comment]
@KKaselkar have you tested again and confirmed? If so, can we close as I see Dual Reporting indicators have been generated and seen HR - Cluster (1) in PMP for other PDs.
