### ISSUE TITLE
Not able to submit SR

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#860]
Dev. prp environment.
Iraq workspace
PD : PCA 2016/04/PD2018437

attachment is added but  system says please add an attachment when submitting a SR, looks like its not accepting large files

Attachment uploaded in PRP doesnt appear in PMP

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/44475535-4b1b6780-a603-11e8-92f8-8f39785e7eab.png)

**Comment by sethgold8** [comment]
from @KKaselkar 
- [ ] cannot upload large files
- [ ] The attachment does not appear in PMP

**Comment by KKaselkar** [comment]
@sethgold8  this is not resolved

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46628259-fd06e880-cb0a-11e8-83a0-a4bca116bb75.png)
 resolved
