### ISSUE TITLE
Target is required even though value is added

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#861]
env: Dev (dev.partnerreportingportal.org)
Browser:Chrome
Workspace: South Sudan

Steps:
-Login as Partner.
-Go to My Planned Actions---> Add Project(OCHA or custom any)
-Update all the fields and click SAVE.
-Now create project indicator.
-Fill all the fields and click SAVE.
-Edit the project indicator.
-Click SAVE.

Result: Error message is displayed : target is required to create Indicator.Even though target was already updated.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/44588140-f1da4200-a782-11e8-8210-9cde8ad58041.png)

**Comment by sethgold8** [comment]
@KKaselkari see the error message and just tested twice and everything was working. Let's have you demo this live so I can see.

**Comment by KKaselkar** [comment]
working fine now .
