### ISSUE TITLE
Deleted indicator in PMP appears in PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#866]
PD number: IRQ/PCA2018245/PD2018441
dev.prp environment 
Iraq workspace
demo pmp environment

Add indicators to a PD (indicators can only be added when the PD is in draft status)

click on save button.

now delete an indicator from the PD click on save button.

change the PD status to signed and then active by adding additional details in the PD.

deleted indicator still displays on the change calculation page in IP PRP

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/44601638-1f3ae600-a7ab-11e8-8db6-731f86963d75.png)


![image](https://user-images.githubusercontent.com/32198614/44601681-409bd200-a7ab-11e8-80e6-2350978eba7b.png)

**Comment by chachra** [comment]
@n1207n this can be delivered now?

**Comment by KKaselkar** [comment]
deactivated indicator doesnt appear in IP PRP
