### ISSUE TITLE
Only high frequency humanitarian indicators in HR

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#867]
PD number: IRQ/PCA2018245/PD2018441
dev.prp environment 
Iraq workspace
demo pmp environment

HR reports must only display High Frequency humanitarian indicators marked in PMP and not all. 

QPR must display all types of indicators.

**Comment by KKaselkar** [comment]
PMP - 2 indicators in the below screenshot are not high frequency humanitarian indicators 
![image](https://user-images.githubusercontent.com/32198614/44601839-cb7ccc80-a7ab-11e8-8e99-c2fc02eaaf5a.png)

**Comment by chachra** [comment]
@KKaselkar which ones were HF? I think this field was added in PMP late in dev. @robertavram can you confirm its in the API?

**Comment by KKaselkar** [comment]
@chachra  there is a toggle in PMP which a user selects if the indicator is high frequency  humanitarian indicator

**Comment by KKaselkar** [comment]
Rob is working on this have created a ticket in clubhouse

**Comment by KKaselkar** [comment]
@Sumit Chachra details are already provided in API as per Rob for both humanitarian indicators and cluster indicators.

**Comment by sethgold8** [comment]
working now :)

![Screen Shot 2018-10-08 at 3.29.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fb6b7191a37bf110224f5c5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df542e14e52a31b3265e7752431.png)

**Comment by KKaselkar** [comment]
Only HF indicators appear in HR 
both non HF and HF indicators appear in QPR
