### ISSUE TITLE
Label for indicators

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#868]
PD number: IRQ/PCA2018245/PD2018441
dev.prp environment 
Iraq workspace
demo pmp environment

Label for indicators doesn't display the actual value in all the places where a label value should appear.
Also label should not appear for quantity type indicator.

**technical note**
- [ ] Make sure we're syncing the label values
- [x] In **ip reporting only** (no change to cluster) show labels only for percent/ration, not for quantity indicators.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/44602136-a046ad00-a7ac-11e8-9e4b-002ffa7ae9fb.png)

**Comment by sethgold8** [comment]
blocked by #871

cc @KKaselkar

**Comment by momimomo** [comment]
I'm getting `null` label value (label.label) in all responses for indicator reports from backend. (https://dev.partnerreportingportal.org/)

<img width="477" alt="screen shot 2018-08-30 at 23 22 34" src="https://user-images.githubusercontent.com/21158922/44880084-b0c6be00-acab-11e8-9a19-595c288cfbe0.png">

as for #2 - visibility limited as requested. Issuing PR.

**Comment by KKaselkar** [comment]
@sethgold8 this still doesnt work for quantity type of indicators
Quantity indicators for ip PRP do not have labels so "Data Key []" must not be displayed for quantity type of indicator both in PRP and PMP

**Comment by sethgold8** [comment]
@Kunal,

Want to keep this board focused on PRP items. The only PMP items should, be around PRP integrations. My explanation is below. Let me know if I am misunderstanding something.

The ticket #868 you created above regarding IP says:  show labels only for percent/ration

Below is an example of a Quantity indicator in IP. There is no label, hence why it was moved to UNICEF QA

![Screen Shot 2018-10-08 at 9.31.06 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fb6b7191a371f1112a4f5f595edd3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df542e14c53a716366be7722431.png)

You can see how there are labels on this, which is a percentage indicator in IP

![Screen Shot 2018-10-08 at 9.33.21 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fb6b7191a371f111284f5d5e5edd3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df542e14c53a0113165e3702431.png)

If PMP label is the issue, please add it to the clubhouse scrum board.

**Comment by KKaselkar** [comment]
checked in PRP dev its resolved
