### ISSUE TITLE
Data pulled from HR in QPR doesnt get disaggregation values

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#869]
PD number: IRQ/PCA2018245/PD2018441
dev.prp environment 
Iraq workspace
demo pmp environment

When data is pulled from HR to QPR, only totals are received, disaggregation values are not pulled.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/44602301-34187900-a7ad-11e8-9fcf-59b3627e2a7b.png)

**Comment by sethgold8** [comment]
@KKaselkar There is no way to enforce same disaggregation level for all underlying HR reports so we have to pull in the total https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/progress-reports/quarterly-progress-reports-qpr

**Comment by chachra** [comment]
Closing issue post-discussion with Kunal and as per above,
