### ISSUE TITLE
Indicator last 2 reports should only show submitted reports not draft ones

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#873]
Currently in IP reporting it shows data from draft reports as well when clicking on a specific indicator (in Indicators tab)

- [ ]  Should only show last 2 submitted or accepted reports data.

dev environment: /app/IRQ/ip-reporting/indicators/?pd_statuses=Act&page_size=10&page=1

**Comment by KKaselkar** [comment]
Indicator list displays the last 2 reporting periods
