### ISSUE TITLE
500 error when exporting PDF on Indicators page and Progress Reports list page for a PD

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#874]
We are getting a 500 error when exporting PDF on Indicators page and Progress Reports list page for a PD

@kosior 

- [ ] PDF throws error on List of Progress Reports /app/IRQ/ip-reporting/pd/422/view/reports?page_size=10&page=1

- [ ] ON the indicators tab, if user exports PDF, it throws an error. It might have to do with No data in some of the columns. Will forward email

app/IRQ/ip-reporting/indicators?pd_statuses=Act&page_size=10&page=1

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/44680061-b05bc800-aa0a-11e8-9727-74db29b78ca2.png)

**Comment by sethgold8** [comment]
Getting: AttributeError at /api/unicef/20/progress-reports/
'NoneType' object has no attribute 'strftime' when we export PDF. Forwarding email as well

**Comment by KKaselkar** [comment]
still the same error

![image](https://user-images.githubusercontent.com/32198614/46627828-b82e8200-cb09-11e8-8e01-29fb8bfd4fe4.png)


PD number: PCA 2016/09/PD2018414

**Comment by sethgold8** [comment]
@KKaselkar are there any reports you are exporting? I am seeing no reports

![Screen Shot 2018-10-08 at 1.44.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fb6b7191a379f1162f4f5a5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19f41c95df542e14e54a11a3765e17f2431.png)


cc @askhawaja

**Comment by n1207n** [comment]
@KKaselkar, this happens when you tried to export progress report list for PD when that PD does not have any report at all.

We will create a new ticket for frontend/backend to hide export feature if the PD has no reports to export.
