### ISSUE TITLE
Add exclamation or warning to calculation methods update modal

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#875]
When changing calculation method and saving, we need to update warning modal to: 
 
- [ ] add a yellow exclamation mark of some sort when updating calculation methods
- [ ] bold text

https://www.evernote.com/shard/s5/sh/9565f213-196c-44a5-9042-89c467e52d0c/f03bd53483a5e794

Dev environment: app/IRQ/ip-reporting/pd/422/view/calculation-methods
user: admin_ao

**Comment by groinder** [comment]
![screen shot 2018-08-31 at 18 04 02](https://user-images.githubusercontent.com/16709010/44923720-6562ed00-ad49-11e8-97f7-1619530ff646.png)
It will look like this.

**Comment by KKaselkar** [comment]
Resolved
