### ISSUE TITLE
Data uploader template HR and QPR

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#879]
Dev PRP environment 
Iraq workspace

Uploader template needs to be implemented in IP PRP for HR & QPR reports for entering data ,similar to cluster PRP

Specifications here https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/data-uploader-for-qpr-and-hr

**Comment by dfryta** [comment]
@sethgold8 To be double sure - in case of QPR user can also fulfill Partner contribution to date, Challenges/bottlenecks in the reporting period and Proposed way forward if excel file, right?

**Comment by sethgold8** [comment]
@dfryta yes :)

**Comment by sethgold8** [comment]
@dfryta awesome job :)

2 main comments are

- [ ] can we automatically refresh after uploading the template. The data does not upload currently unless I refresh. We should do this for the user
- [ ]  we get a 500 error when 'generating uploader template' for a report that was previously sent back. IE check  QPR2 for PCA 2016/04/SHPD2018497-1 in Agency for Technical and Emrgency Dev

**Comment by KKaselkar** [comment]
1) Challenges, proposed way forward, attachment and narrative text is not required in the uploader template for HR (uploader template for HR and QPR must be different) this can be done post pilot.
2) Format of cells for Achievement in reporting period (total across all locations) displays as date "0-Jan-1900"
3) Target for ratio is displayed in decimal value, but in PMP it is entered in 10/1 format as is displayed on the HR report screen 
4) For ratio indicators the cell doesn’t allow to enter number in format 7/1 user has to change the format to custom and then general to add the number in 7/1 format (both IP and Cluster)
5) once the file is uploaded data doesn't display in the data entry table, the page has to be manually refreshed for data to appear in the data entry table. (both IP and Cluster)
6) cells to be highlighted in the sheet where data needs to be entered for the user so they know where to enter the data? (both IP and Cluster)
7) When the template is downloaded the sheet must have the correct name of the report

**Comment by dfryta** [comment]
I would skip highlighting cells for now.

**Comment by sethgold8** [comment]
@dfryta tested on Google Sheets. I'm still seeing a lot of the issues mentioned above. WIll include images where it feels necessary

1 - [ ] Still seeing the cells for Achievement in reporting period (total across all locations) displays as date "0-Jan-1900". This should be a 0 as it is not updated unless the Progress report is submitted or sent back. If it has been submitted/sent back, then the total value should show. Image below of what currently seeing
2 - [ ] Still seeing: Target for ratio is displayed in decimal value, but in PMP it is entered as a ratio format as is displayed on the HR report screen
3 - [ ] Still getting a 500 error when I go to Reports previously 'Sent Back' and try to 'Generate Uploader Template'
4 - [ ] Still seeing: For the export, Include the name of the Location as opposed to Admin Level P Code (both IP and Cluster)

5 - [ ] Still seeing :  proposed way forward, attachment and narrative text is not required in the uploader template for HR. Those fields are not in HR so are not needed

**Comment by KKaselkar** [comment]
Date uploader is still the same for HR and QPR but resolving this ticket as requested
