### ISSUE TITLE
Api tweaks

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-partner-reporting-portal#881]
for the progress-report detail api endpoint:
`/api/unicef/20/progress-reports/id/` as well as on the list page -> `/api/unicef/20/progress-reports/` (covered in ticket #877)
is it possible to serialize: `partner_name`, `partner_vendor_number`, `unicef_focal_points`-[array of names?] ? -> for the list of reports could we also have a filter on unicef_focal_points [email of user]

We can pass in a verbosity parameter if needed: 
`/api/unicef/20/progress-reports/id/?verbosity=unicef`

**Comment by n1207n** [comment]
@robertavram I added these new fields to both ProgressReport list and details API and deployed. The dev environment should be able to see these new fields now.

`unicef_focal_points` filter parameter is also added to ProgressReport list API as a list of Person's email, delimited by comma. Whenever it gets deployed, it should be able to work.

I'm not sure how `verbosity` GET parameter would work. Any clarification on this would be great.

**Comment by robertavram** [comment]
I'll check it out and update here.. thanks!

**Comment by robertavram** [comment]
Good from our side on this one! thanks!
