### ISSUE TITLE
Target not displaying for ratio and percent indicators

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#885]
- [ ] Frontend is not rendering 'target' for Ratio and Percent indicators

**Comment by groinder** [comment]
Could you please add an URL and/or screen where this is supposed to be shown? I couldn't find it.

**Comment by sethgold8** [comment]
QPR 1 
IRQ/SSFA2018244
Dev Environment
user: seth.gold@tivix.com

![Screen Shot 2018-09-04 at 10.00.07 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f76b7191a379ef0c2b51415f49bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e74d5da4173365e077306e0a.png)

**Comment by sethgold8** [comment]
@groinder can you merge? If not let me know and will ask Silin when he returns

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46627569-de9fed80-cb08-11e8-8345-59676099b1a4.png)

Its resolved
