### ISSUE TITLE
Percent totals incorrect for ratio indicators

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#886]
The percent indicator totals are not correct. Underlined in red

app/IRQ/ip-reporting/indicators?pd_statuses=Act&page_size=10&page=1

user: tester17@gmail.com

![Screen Shot 2018-08-31 at 3.03.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6457f26b7191a37bf112284f5f585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df54ee64856a41b3066e4772431.png)

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46627776-8d442e00-cb09-11e8-90a9-575f92568808.png)


working fine
