### ISSUE TITLE
Unable to see attachment for SR reports sent back in PMP

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#887]
To reproduce
PME sends back SR after it is submitted and gives feedback.

- [ ] AO not able to see the feedback on the SR once its sent back

app/IRQ/ip-reporting/pd/558/report/700/edit

![Screen Shot 2018-08-31 at 3.36.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6457f26b7191a37bf1112d4f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df54ee64850a412366be5742431.png)

![Screen Shot 2018-08-31 at 3.35.30 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6457f26b7191a37bf1112e4f5c5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df54ee64850a410346be7712431.png)

**Comment by groinder** [comment]
`app/IRQ/ip-reporting/pd/558/report/700/edit` links to an non-existing report on dev env. I've tested it locally and it works.
![Screen Shot 2018-09-04 at 13.35.22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b8810529277090012ad827e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f76b7191a379ec0c2854415d4cbe5d4a1f06a3a3dc78e2a436628f5458bbd96e0a74c53b18ffb9871fbf08b8258c4982b4ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5ef64de14451a7143f60f43b.png)

**Comment by sethgold8** [comment]
@groinder 

user: seth.gold@tivix.com (i will send pw)

PD: PCA 2016/04/PD2018397
SR1

Am still not getting anything on dev environment
![Screen Shot 2018-09-04 at 9.55.34 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f76b7191a371f1172e4f5c5b5edd3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df54de14555a5153f63e2772431.png)

**Comment by groinder** [comment]
I didn't notice at first that it only occurred if the report was `Special Report` type. It's fixed now.

**Comment by sethgold8** [comment]
@groinder can you merge? If not let me know and will ask Silin when he returns

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46629065-959e6800-cb0d-11e8-8b78-6e663543514c.png)


PME in PMP cannot see the feedback and even the attachment

![image](https://user-images.githubusercontent.com/32198614/46629082-a4851a80-cb0d-11e8-876b-f410eab2301f.png)

**Comment by sethgold8** [comment]
@KKaselkar  @askhawaja 

We never supported 'send back' attachment. We only supported messages for send back.

If you want to add this feature, we will need to update our API and PMP will need to update their UI. 

What should happen to previously sent attachment if someone send a report back again. Please confirm as these are new to specifications.

**Comment by sethgold8** [comment]
@KKaselkar opening ticket in pmp cc @robertavram @n1207n
