### ISSUE TITLE
Dual Reporting - few reports are not generated for IP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#893]
Dev.prp environment
Chrome browser
Iraq workspace

PCA 2016/04/SHPD2018504

This PD report has the same issue as 892.
In addition to that bug it also has another issue that IP PRP HR is not generated for all reporting period dates. screenshot below:

**Comment by sethgold8** [comment]
@KKaselkar Reports are not generating correctly because HR1 and HR2 reporting requirements from PMP share exactly same reporting period but they have 2 different due dates. Therefore Report Generator only create HR 1 and HR 3 and skipped HR2. PMP needs to send valid reporting requirements.

**Comment by KKaselkar** [comment]
@sethgold8  what do you mean by "valid reporting requirements" ? I understand that both IP and Cluster calculate different due dates for their reports and I am going to talk internally  to have one due date in both IP and Cluster

**Comment by sethgold8** [comment]
@KKaselkar invalid = same reporting period. Reporting period must be unique per each reporting requirement.

Notice how HR1 and HR2 have the same reporting period. They should not be the same .

We agree due date should follow the cluster format on +1 after end of reporting period.

**Comment by KKaselkar** [comment]
@sethgold8 changing the logic of due dates in PMP for HR

**Comment by KKaselkar** [comment]
Resolving this issue as it has been fixed
