### ISSUE TITLE
Percentage Type Indicator

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#896]
prp.dev environment 
chrome browser
Iraq workspace

Percentage type Indicator:

For percentage on the data entry table totals are not displayed on the right and top of the rows in the data entry table (modal window) once the data is saved.

If unchecked the disaggregation for percentage indicator it still appears on the data entry table (modal window) indicator has 3 disaggregations with 4 categories (not able to reproduce this issue again but happened like 3 times)

check and uncheck the disaggregation for couple of times in the data entry (modal window) and click on save, system gives an error occurred message in the left bottom.

Location progress doesnt appear as we type the data in the data entry table window. If it appears after clicking on save than why do we show the location progress with no value.

Disaggregation when unchecked and data is entered and saved in the data entry table ,the next page still displays the table with blank disaggregation even though the disaggregation was unchecked.

System must display the correct error message for Denominator cannot be 0 and 0/0 is not accepted in the data entry table.

**Comment by KKaselkar** [comment]
IRQ/PCA2018245/PD2018512

![image](https://user-images.githubusercontent.com/32198614/45382702-0ae25000-b5d7-11e8-8889-2ff9fd7ccad2.png)

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/45382799-5dbc0780-b5d7-11e8-80f1-847aedf27f20.png)

**Comment by sethgold8** [comment]
@KKaselkar You can only enter in the light blue columns. Dark Blue is subtotal columns which are automatically calculated

**Comment by KKaselkar** [comment]
@sethgold8  When you enter the data  in light blur columns , totals in dark blue columns are not displayed and there is another issue as well mentioned in the ticket above.

**Comment by sethgold8** [comment]
@KKaselkar I see totals in the photo above appearing except the 0% (which looks like a bug). Can you give me specific PD , indicator, and user to check with screen shot if there are more then just the 0% not showing?

Also what is the other issue? Please be concise and list it so I can easily discern it, check, and get it fixed if it is a real bug. For example, listing specifics below in list format.

 - [ ] A does not work
- [ ] B does not work.

**Comment by KKaselkar** [comment]
PD number : IRQ/PCA2018245/PD2018512-1
dev.prp environment
Iraq workspace
Partner name :THE HUMAN RIGHT CENTER IN IRAQ

1) missing totals:
![image](https://user-images.githubusercontent.com/32198614/45711770-9cfad300-bb58-11e8-92a8-df2c1e1a4e1c.png)

2) Disaggregation when unchecked and data is entered and saved in the data entry table ,the next page still displays the table with blank disaggregation even though the disaggregation was unchecked.
![image](https://user-images.githubusercontent.com/32198614/45711810-b439c080-bb58-11e8-9982-76b07ee886e1.png)
![image](https://user-images.githubusercontent.com/32198614/45711813-b69c1a80-bb58-11e8-8868-9ac649b521f4.png)

3) check and uncheck the disaggregation for couple of times in the data entry (modal window) and click on save, system gives an error occurred message in the left bottom.

4) System must display the correct error message for Denominator cannot be 0 and 0/0 is not accepted in the data entry table.

**Comment by n1207n** [comment]
@KKaselkar, the PD no longer exists in PRP so we can't reproduce. If you experience this again, feel free to file a new ticket and Show us other PD that has 3 disaggregations and we'll take a look at it.

![Screen Shot 2018-10-08 at 2.32.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fb6b7191a37af111294f5f5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e14e51a7103764e0702431.png)
