### ISSUE TITLE
Add Narrative for SR Export PDF/XLS

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#903]
Dev.prp environment
chrome browser
Iraq

When selected sent back and exported the report in PDF and XLS it doesnt give the correct results, it provides PDF and XLS with no details for the indicator or report

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/45450829-55cb9880-b6a7-11e8-83d1-668777723e1d.png)

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/45450834-58c68900-b6a7-11e8-9941-f1f2506a575b.png)

**Comment by sethgold8** [comment]
@KKaselkar please include all information like user, PD, etc. This saves time

**Comment by sethgold8** [comment]
@KKaselkar the issue is with SR, not 'sent back'. We need to add 'Narrative' for PDF export. 

XLS needs Narrative column as well.

Just for your information, it is impossible to add the attachment into the PDF/XLS afterwards so we will not be adding that.
