### ISSUE TITLE
Submit button for QPR greys out

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#905]
Dev.prp environment
chrome browser
Iraq

When user tries to submit a QPR the submit button greys out and doesn’t submit the report. This happened with many users and they had to refresh the screen to submit the report.

**Comment by sethgold8** [comment]
@KKaselkar we need specific steps to reproduce..ie the report and PD #

Just tested and 'Submit' button is blue on QPR1 for IRQ/SSFA2018244

![Screen Shot 2018-09-12 at 1.45.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f16b7191a379f1162e4f5e565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df54de64550a6123f67e5772431.png)

**Comment by KKaselkar** [comment]
@sethgold8  
Create a PD with HR and QPR
Enter data for QPR1
Click on the submit button
Submit button turns grey and report is not submitted, you have to refresh the page.

I am not able to reproduce it now but few users performing UAT from the country office and we have faced this issue while submitting a QPR in PD IRQ/PCA2018245/PD2018512-1.

**Comment by sethgold8** [comment]
@KKaselkar ok closing then. If you can reproduce, please re open with steps and let me know
