### ISSUE TITLE
PD details routing bug

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#91]
Routing is dead when navigating to http://localhost:8080/app/BE/ip-reporting/pd/:pdId

Example:
https://drive.google.com/file/d/0BxDYQDDFAykYWFNpbmRFS0NBUkU/view?usp=sharing

**Comment by adamtlord** [comment]
This is working correctly now:
https://drive.google.com/a/tivix.com/file/d/0B3Ckg3kuw1tNOWdkTlg2YnFsTVk/view?usp=sharing

I may need to revisit depending on if we change the function that triggers the pd-details fetch (see https://github.com/unicef/etools-partner-reporting-portal/issues/29)

**Comment by rkrupinski** [comment]
Still, there's an "issue" with query string params being carried through tabs, but that does not affect user experience and we can leave it as is for now, imo.
