### ISSUE TITLE
Disaggregations group must allow upto 25 characters

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#912]
prp.dev

Disaggregation group does not include enough characters. Must allow up to 25 characters.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/45695230-fea64780-bb2e-11e8-9e59-257b23545aea.png)

**Comment by n1207n** [comment]
Actually the backend can support up to 128 characters for disaggregation group label. It is frontend component which has a fixed size of UI, forcing the input box to be 15 characters only.

**Comment by sethgold8** [comment]
Can do more then 25 characters

![Screen Shot 2018-10-31 at 4.39.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a37cf111224f5c585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24ae14f5ca6133563e1702431.png)

**Comment by KKaselkar** [comment]
Issues resolved.
Disaggregation groups allow 25 characters to be added
