### ISSUE TITLE
Monthly report generation

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#916]
dev.prp
cluster objective reports
Iraq
admin _IMO
Plan : Iraq 2018

start date of monthly report is 16th Aug in this scenario report was generated for 2 periods:

16 Aug to 31 Aug
1 Sep to 30 Sep
When the start date of monthly report was 17th or 18th Aug it only generated 1 report. System did not generate reports for 1st Sept to 30 Sept

**Comment by KKaselkar** [comment]
start date of monthly report is 16th Aug in this scenario report was generated for 2 periods:
1.	16 Aug to 31 Aug
2.	1 Sep to 30 Sep
 
When the start date of monthly report was 17th or 18th Aug it only generated 1 report. System did not generate reports for 1st Sept to 30 Sept

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/45708925-9ec09880-bb50-11e8-802c-54ff4245b076.png)

**Comment by sethgold8** [comment]
@kkaselkar just tested and working fine for me. Please reproduce and send me the specific indicator, user, response plan for me to re-test that version.


![Screen Shot 2018-09-24 at 2.55.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f76b7191a37af1172e4f5a5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ce94f53a7123060ee752431.png)

**Comment by KKaselkar** [comment]
testing in dev.prp issue is resolved
