### ISSUE TITLE
Uploader template replace 0 with blank when no data is entered

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#918]
dev.environment
Iraq
Cluster PRP
In  import template if no data has been entered totals etc. should be "blank" and not "0" since uploading the document in the system will then set it to 0's!

**Comment by sethgold8** [comment]
@dfyta , please let us know if it's possible to have the Total left as blank if there is no data. If so, can you update the ticket

![Screen Shot 2018-10-03 at 1.27.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f06b7191a379f1102c4f5f585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df543e4445da1113063e0732431.png)

**Comment by sethgold8** [comment]
Admin_IMO in Cluster Reporting
Iraq_2018
Indicator: Month Test
URl: app/IRQ/cluster-reporting/plan/1/results?page=1&indicator_type=cluster_objective&indicator=4485

![Screen Shot 2018-10-09 at 10.58.03 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fa6b7191a379ef0c2e59415f4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e84c55a31a3666e770356e0a.png)

**Comment by dfryta** [comment]
Backend is done. @sethgold8 please assign someone for frontend change also.

**Comment by n1207n** [comment]
@dfryta, is this already fixed and merged? Frontend handles the empty data value properly now in staging. If export works same way too then we can move this to delivered.

**Comment by sethgold8** [comment]
circling back on this @dfryta ? Am still seeing 0s in the total column for

admin_imo
Indicator: TATAA
Response Plan: IRAQ_2018

![Screen Shot 2018-10-15 at 3.34.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a37bf1112f4f5b575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df542e74957ad143067ef732431.png)

**Comment by dfryta** [comment]
Heh, sorry guys. It was not merged. Do it now :-O.

**Comment by sethgold8** [comment]
working :)

![Screen Shot 2018-10-17 at 2.10.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f46b7191a37af1132b4f5b575ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e94c55a3163e67e4732431.png)

**Comment by KKaselkar** [comment]
when entered 0 in uploader sheet, system displays "-". 
Issue is resolved
