### ISSUE TITLE
Cluster PRP - exports must include admin units (Locations)

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#920]
dev.prp
cluster PRP
Syria

Exports only provide the Pcode but should also give the admin units alongwith the Pcodes

**Comment by sethgold8** [comment]
@kkaselkar can you expand

**Comment by sethgold8** [comment]
@KKaselkar can you expand on the issue with what the bug is specifically?

**Comment by sethgold8** [comment]
On Dev PRP For Cluster, we now show ' Report Location Name'

![Screen Shot 2018-11-05 at 1.54.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f66b7191a379f1172f4f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24ae54851ad10316be3702431.png)

**Comment by KKaselkar** [comment]
location names do appear in export
