### ISSUE TITLE
1001 - Cluster indicator added to PD doesn't generate dual reports

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#924]
prp.dev
Iraq workspace

https://etools-demo.unicef.org/pmp/interventions/517/details

PD number: PCA 2016/04/PD2018517

Added cluster indicator from PRP cluster to a PD in PMP. PD only has cluster indicator and no UNICEF indicator.
In this scenario dual reporting must be generated as UNICEF will be reporting on cluster indicator (HR) reports.

QPR reports are generated in this scenario but HR reports are not generated.

**Comment by KKaselkar** [comment]
PCA 2016/04/PD2018496

**Comment by sethgold8** [comment]
PD has no reporting requirements so unable to reproduce
![Screen Shot 2018-10-31 at 4.59.06 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a37cf117224f5f595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24ae14e55a7143060e6772431.png)
