### ISSUE TITLE
default_unicef_user access

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-partner-reporting-portal#925]
default_unicef_user should have read access to all endpoints as it needs to read cluster indicators, clusters, partner reports etc... and it needs write access to the report accept/send back across all workspacess.

Currently this issue is blocking testing.

**Comment by chachra** [comment]
- return all workspaces for this user.
- give cluster_system_admin to default unicef user.
- new permission class UNICEFAPIUser if is_unicef in unicef.views.py and anywhere is_unicef is used in the view, add this permission class to it.

Please check all these api calls from pmp will work: https://github.com/unicef/etools-partnership-management/blob/master/pmp/modules/endpoints/endpoints.html#L140 (anything with token: 'prp' is one PMP will call PRP for.
