### ISSUE TITLE
PD's created in PMP dont appear in PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#926]
etools demo environment for PMP
dev.prp environment for PRP

Following PD's created in Iraq workspace do not appear in PRP

Partner name : AGENCY FOR TECHNICAL & EMERGENCY DEV.

PCA 2016/04/SHPD2018441 
PCA 2016/04/PD2018440-1 
PCA 2016/04/SHPD2018438-1 
PCA 2016/04/PD2018436-2

Could you please have a look and let me know the issue

**Comment by sethgold8** [comment]
Accepted via Kunal on call
