### ISSUE TITLE
Change reporting frequency from weekly to monthly

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#927]
dev.prp environment
Iraq workspace

Login as IMO 
create cluster objective indicators with weekly reporting periods.

On 14-Sep-18, I created a Cluster Objective Indicator Weekly Report with Start Date = '07-Sep-18'. 
The following reports got generated: 
     Due Date:           Reporting Period: 
     14-Sep-2018     07-Sep-2018 - 13-Sep-2018 - Due 
After the reports got generated, I changed Frequency from Weekly to Monthly. 
On 17-Sep-18, I am axpecting the following Monthly Report to be generated: 
     Due Date:           Reporting Period: 
     01-Oct-2018      14-Sep-2018 - 31-Sep-2018 - Due 

But none was generated.

**Comment by sethgold8** [comment]
@n1207n what is the expected behavior if you are weekly reporting periods and it changes to monthly in the middle of the month?

**Comment by sethgold8** [comment]
working : )

Stared on July 4 and you can see the 4 months after until todays report were generated

![Screen Shot 2018-10-31 at 12.02.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379ed0c2b53415b4dbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe04d54a6153762e67e3f6e0a.png))

**Comment by sethgold8** [comment]
You can test by setting up report and switching to monthly. It will generate at end of Month (the due date).

**Comment by KKaselkar** [comment]
Issue is resolved in dev
