### ISSUE TITLE
Monthly reports not getting generated

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#928]
dev.prp environment
Iraq

Created monthly reports with start date of 17 and 22 sept but system didnt generate any reports.

https://dev.partnerreportingportal.org/app/IRQ/cluster-reporting/plan/1/response-parameters/clusters/objective/14?page_size=10&page=1&cluster_id

https://dev.partnerreportingportal.org/app/IRQ/cluster-reporting/plan/1/response-parameters/partners/activity/4/indicators?page_size=10&page=1&cluster_id

**Comment by sethgold8** [comment]
working : )

Stared on July 4 and you can see the 4 months after until todays report were generated

![Screen Shot 2018-10-31 at 12.02.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379ed0c2b53415b4dbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe04d54a6153762e67e3f6e0a.png))

**Comment by KKaselkar** [comment]
monthly reports are getting generated , issue resolved
