### ISSUE TITLE
Reports dont get saved as cluster member

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#930]
dev.prp
Iraq workspace
IMO login

Created cluster objective indicator , reports got generated, entered data for the report but after clicking on save button nothing happens.

https://dev.partnerreportingportal.org/app/IRQ/cluster-reporting/plan/1/results/draft?page_size=10&page=1&indicator_type=cluster_objective&indicator=2016

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46093745-2415ff80-c186-11e8-8b1b-d0433625dacc.png)

**Comment by sethgold8** [comment]
@kosier, we are getting a 403 error when trying to save data as an IMO

Dev environment

will slack user details

![Screen Shot 2018-10-02 at 5.12.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f16b7191a37df113294f5d585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df543e44f50a11a3167e3702431.png)

**Comment by KKaselkar** [comment]
@sethgold8  added a cluster objective indicator "TEST_Data _save" in Iraq , role of the user is cluster member,  report was generated for the indicator but cannot save the data , nothing happens after clicking on save button

**Comment by sethgold8** [comment]
working :)

**Comment by KKaselkar** [comment]
Resolved , reports are getting saved.
