### ISSUE TITLE
Change 256 characters to 256 words for fields in the ticket

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#931]
dev.prp environment
Iraq workspace

All the narrative text limitations for progress reports must be changed from 256 characters to 256 words:
* Narrative assessment
* Partner contribution to date
* Challenges/bottlenecks in the reporting period (latest)
* Proposed way forward (latest)

**Comment by sethgold8** [comment]
It's still doing character count, not word

**Comment by n1207n** [comment]
Turned out the DB migration that makes fields TextField never ran. Ran the DB migration manually. Backend now should be fine, but frontend should still fix the counts in text UI.

**Comment by groinder** [comment]
@n1207n This was already fixed in https://github.com/unicef/etools-partner-reporting-portal/pull/949/commits/38279e859459ef54fd5c0c486245654c9b395bc2 I've remove character limit and count as restricting it to 256 words is not that quick. I've checked right now on dev and it works.

**Comment by sethgold8** [comment]
@groinder not sure I fully understand. I still see it counting characters as opposed to words. Is the feature working but character count broken? 




I don't want to spend so much time on this. If this is fixed, please push through and show with an image. If it's taking time, lets just make a quick fix to 2000 characters and finish this ticket off. It's not a major core feature so just want a quick fix. Whatever works best for you, please go ahead do :)

**Comment by groinder** [comment]
As I said, this is fixed, maybe you need to empty your browser cache? 
Here are the images, I tested on https://dev.partnerreportingportal.org/app/IRQ/ip-reporting/pd/950/report/283/edit?page=1
![image](https://user-images.githubusercontent.com/16709010/46937391-764d9080-d061-11e8-888c-fe4fff3b4491.png)
![image](https://user-images.githubusercontent.com/16709010/46937440-9aa96d00-d061-11e8-8fae-d0f043bbae81.png)

As I said, the counter and character limit is removed, I've even put **2000 words** into it without any issues.

**Comment by groinder** [comment]
There was needed a separate change for SR.

**Comment by sethgold8** [comment]
@groinder I was able to submit 9000 characters. The limit should be 2000 characters
![Screen Shot 2018-10-17 at 1.48.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f46b7191a379f116234f5b5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e94d5ca7103664ee742431.png)

**Comment by groinder** [comment]
Do we actually need to limit this?

**Comment by sethgold8** [comment]
Working. 2000 character counter

![Screen Shot 2018-10-22 at 2.11.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f16b7191a37af1132a4f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be34957a21b3364e4752431.png)

**Comment by KKaselkar** [comment]
changed to 2000 characters , resolved
