### ISSUE TITLE
Invalid error message when IMO tries to add a new higher or lower role to other user

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#934]
Browser:Chrome 
Workspace:Iraq 

Steps: 
-Login as an IMO. 
-IMO also has Cluster system admin role at country level. 
-Go to ID management. 
-Search the user email id whch already has "Cluster Co-ordinator" role assigned to it. 
-Click on "Add new permission". 
-Select the same cluster. 
-Select role as "Cluster member" 
Result: Error message "Role already exist in cluster or workspace.However, a "Cluster coordinator" cannot perform all the functions which Cluster member can.Cluster member is a higher role than cluster coordinator.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46213819-919d6980-c307-11e8-8556-d8cb6598b581.png)

**Comment by sethgold8** [comment]
@kosior lets add a validation to

- [ ]  not allow "IMO also has Cluster system admin role at country level" 

@KKaselkar ID management does not allow multiple roles to the same cluster and same workspace.

**Comment by kosior** [comment]
@sethgold8 we already have that validation I think. It is not possible to add other cluster roles for cluster system admin. Of course this is only in ID Management. There is no validation inside Django Admin.

**Comment by sethgold8** [comment]
@KKaselkar IMO should only have IMO roles. You cannot have IMO and System and Admin at the same time.

Will close this ticket after you confirm

**Comment by KKaselkar** [comment]
this works from the back end so resolving the ticket
