### ISSUE TITLE
Cluster member must not be able to add cluster objectives

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#937]
dev.prp environment
Iraq workspace

Logged in as cluster member.
Cluster member is able to add cluster objectives and cluster activities what an IMO can do.
But this is incorrect, cluster member must not be able to add cluster objectives and cluster activities what an IMO can do.

Probably can be fixed along with #939

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46354501-c291dd00-c62c-11e8-8fab-0a2d449bf79b.png)

**Comment by groinder** [comment]
Issue related to #939, fixed in #961

**Comment by sethgold8** [comment]
@KKaselkar Cluster Member should not be allowed to add a Cluster Objective

https://docs.google.com/spreadsheets/d/1RKptCboJSAyNCWyenJ_uRIZ_hFiVt68t8W2m7C3Uyzc/edit?usp=sharing​

**Comment by KKaselkar** [comment]
Resolved
