### ISSUE TITLE
Authorized Officers are not in Cluster PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#938]
dev.prp environment 
Iraq workspace

Authorized Officers are only in IP PRP, hence show list of authorized officers must not be available for cluster member on cluster PRP ID management.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46355681-4cdb4080-c62f-11e8-9b35-c6c9fe28266e.png)

**Comment by sethgold8** [comment]
Simply hide the logic for this message to show @groinder in cluster id management. Think its a frontend issue only. AO is not a role in cluster id management hence it doesn't make sense.

**Comment by sethgold8** [comment]
Fixed

![Screen Shot 2018-11-13 at 5.16.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f06b7191a37df1132d4f5f585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df249e0485da51b3e62e3702431.png)

**Comment by KKaselkar** [comment]
resolved in dev
