### ISSUE TITLE
Cluster viewer must not be able to add cluster objectives

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#939]
dev.prp environment
Iraq workspace

Logged in as cluster viewer.
Cluster viewer is able to add cluster objectives and cluster activities what an IMO can do.
But this is incorrect, cluster viewer must not be able to add cluster objectives and cluster activities what an IMO can do.

- [x] Make sure backend is also respecting the role in the same way.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46357316-95482d80-c632-11e8-9b5d-0333b422f767.png)

**Comment by groinder** [comment]
Issue occurred only in minimized version of code where function names were replaced thus the function call didn't take place causing the permissions to break. Backend respects the role properly.

**Comment by sethgold8** [comment]
Working. CLuster Member cannot add CO

![Screen Shot 2018-11-13 at 5.18.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f06b7191a37df113234f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df249e0485da7103162e7742431.png)

**Comment by KKaselkar** [comment]
resolved
