### ISSUE TITLE
Target for percentage indicator is incorrect in export

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#944]
dev.prp
Iraq workspace
PCA 2016/09/PD2018457

Target for percentage indicator is mentioned as 100% in PMP but in the export (XLS for one HR) it appears as 1

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46423004-8aa99900-c703-11e8-8bea-a1b188edaa82.png)


PMP Screenshot:

![image](https://user-images.githubusercontent.com/32198614/46423047-a6ad3a80-c703-11e8-920f-872067f84028.png)

**Comment by sethgold8** [comment]
@dfyta , is it possible to fix above? In the export it shows 1 %, but it should be 100%.

**Comment by sethgold8** [comment]
Still seeing the percentage showing 1. It should be 100% according to the Target highlighted in yellow above

![Screen Shot 2018-10-10 at 12.08.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f36b7191a379ed0c2b59415e4dbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e84c5cac153660e07e356e0a.png)

**Comment by dfryta** [comment]
This is weird. @sethgold8 provide me url of this report.

**Comment by dfryta** [comment]
@sethgold8 url you provided does not exists on https://dev.partnerreportingportal.org. Please check other one for same partner: https://dev.partnerreportingportal.org/app/IRQ/ip-reporting/pd/950/report/283/edit?page=1
![Zrzut ekranu 2018-10-11 o 11.51.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599ea4b9f8cd181455aa3f82/125516c66e82c728ace21e0d46d286803696c3ac84fbbe4db11da2c4781e6a227949f27a308aa379ee0c2e50415a47be5d4a1f06a3a3dc78e2a436628f5458bbd96e0a74c53b18ffb9871fbf08b8258c4982b4ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb51f44ee0485ca5173665f43b.png)

**Comment by sethgold8** [comment]
strange, I will take a look

**Comment by sethgold8** [comment]
@dfryta ok cool, it's working :)

![Screen Shot 2018-10-12 at 12.21.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f16b7191a379ed0c2950415c46bc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e84e52a6123567e774306e0a.png)

**Comment by KKaselkar** [comment]
Resolved, displays 100% in target and also in total cumulative column displays %
