### ISSUE TITLE
Special report when sent back cannot attach another document

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#945]
dev.prp

Iraq workspace
1) Special report document (attachment) doesnt appear in PMP
2) user is not able to attach a new document when special report is sent back from PMP to PRP

**Comment by KKaselkar** [comment]
PCA 2016/09/PD2018457

PMP:
![image](https://user-images.githubusercontent.com/32198614/46423580-e1fc3900-c704-11e8-9aba-f9169bb26890.png)


PRP:
![image](https://user-images.githubusercontent.com/32198614/46423651-07894280-c705-11e8-8399-4d7e0ecb4218.png)

**Comment by sethgold8** [comment]
blocked by #948

**Comment by n1207n** [comment]
This would be automatically fixed if #947 is fixed since it deals with same code.
