### ISSUE TITLE
'Accept' + 'Send Back'  Progress Report in PMP returns error

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#948]
- [ ] When we try to send back a progress report with comments, PMP throws the error below
![Screen Shot 2018-10-03 at 2.43.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f06b7191a37af116284f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df543e74d56a5123467e5722431.png)

- [ ] accepting a report returns 400 error
![Screen Shot 2018-10-05 at 4.59.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f66b7191a37cf117224f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29841c95df543e64551a410316ae3772431.png)

**Comment by acory** [comment]
@ sethgold8 On which environment does this happen?

**Comment by sethgold8** [comment]
E Tools Demo for *PMP*

**Comment by acory** [comment]
@sethgold8  I can't reproduce it . Can you try again and let me know if there any particular circumstances when this happens?

**Comment by sethgold8** [comment]
I will show @Kunal Kaselkar <kkaselkar@unicef.org> on our call at 1 and
include details after

**Comment by KKaselkar** [comment]
@sethgold8 tried to accept and return the report and didnt get any error message

**Comment by sethgold8** [comment]
I will demo for you on our call
