### ISSUE TITLE
Attachment not appearing in PMP when submitted

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#953]
An Attachment was made, when submitting

![Screen Shot 2018-10-05 at 11.35.29 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f66b7191a379ee0c2854415d47bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e94a53a0163267e3703e6e0a.png)

It is not showing in PMP
![Screen Shot 2018-10-05 at 11.34.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f66b7191a379ee0c2855415b48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e94a53a0153164e37f3e6e0a.png)

**Comment by n1207n** [comment]
@robertavram, PMP does call PRP API for attachment but somehow PMP UI does not expose it.

**Comment by acory** [comment]
@robertavram Should be fixed now in PMP

**Comment by KKaselkar** [comment]
Resolved in demo
