### ISSUE TITLE
UNICEF focal point in PMP is appearing as authorized officer in IP PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#956]
dev.prp environment

Focal points are been synced from PMP to IP PRP.

My name " kunal kaselkar" is added as UNICEF focal point in PMP for the partner "IRAQI AL AMAL ASSOCIATION"

in PRP my name appears as authorized officer in the annex C form.

this shouldnt happen as I am not the authorized officer in PMP.

**Comment by n1207n** [comment]
@KKaselkar, can you point out PD reference number or url for this?

**Comment by n1207n** [comment]
Fix is pushed and is deployed. Need to delete/re-sync PDs + Persons so that unicef focal points won't get Authorized Officer role during syncing.

**Comment by KKaselkar** [comment]
@sethgold8  tested it works fine there is another issue with UNICEF focal point will raise that issue
