### ISSUE TITLE
Add Zendesk on PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#957]
Could you please add zendesk on PRP , this would be used by the users to report any issues.

https://prphelp.zendesk.com/hc/en-us

**Comment by sethgold8** [comment]
This is for support, not knowledge base.

**Comment by sethgold8** [comment]
It will be similar to image below, but a message, not livechat.
![Screen Shot 2018-10-25 at 7.38.32 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f66b7191a37ff111234f5c5d5edd3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be54a5da7103f63e0772431.png)

**Comment by KKaselkar** [comment]
For knowledge base please add the link on IP PRP on the bottom left similar to etools

**Comment by sethgold8** [comment]
@KKaselkar @mpawlowski85 do we have the code snippet for knowledge base too?

**Comment by n1207n** [comment]
I've added zendesk script tag for polymer and id-management index.html for support UI.

For Knowledge Base link on Sidebar Nav, I think @groinder would be more suitable person to tackle this.

@groinder, use this link to add Sidebar nav element: https://prphelp.zendesk.com

**Comment by chachra** [comment]
@groinder - can you please make sure to give padding at the bottom of each page or something. Since it overlaps with indicators etc. in a progress report for example? Thanks.

**Comment by sethgold8** [comment]
@n1207n can you please push

**Comment by KKaselkar** [comment]
Tested in dev  working fine, resolved
