### ISSUE TITLE
UNICEF focal point sync from PMP to PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#963]
UNICEF focal points are syncing from PMP to PRP 
This avoids the UNICEF focal point to view reports in PMP until and unless that user record is deleted from PRP

**Comment by KKaselkar** [comment]
PMP:
![image](https://user-images.githubusercontent.com/32198614/46674550-6558d700-cbaa-11e8-8f40-fa3eb147890a.png)


PRP:
![image](https://user-images.githubusercontent.com/32198614/46674590-83263c00-cbaa-11e8-954f-e9db3dc707f1.png)

**Comment by sethgold8** [comment]
@mpawlowski85 @KKaselkar 

Silin pushed a fix for this and deleted all users for UNICEF Focal Points and Focal points. In the future, we will only create and update user for AO in each PD

**Comment by KKaselkar** [comment]
my unicef username is no longer getting created automatically and it was in the focal point list , so resolving this issue
