### ISSUE TITLE
When no Location Progress data is entered, it should be null (-) as opposed to 0

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#966]
For Both IP and Cluster
When NO Location Progress data is entered, it should be null (-) as opposed to 0

**Please make sure to test so this does not break anything

![Screen Shot 2018-10-09 at 1.47.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fa6b7191a379f1162c4f5a565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df542e04c5da6123466e0702431.png)

![Screen Shot 2018-10-09 at 1.49.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fa6b7191a379f116224f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e04c5da6123e63e7702431.png)

**Comment by n1207n** [comment]
@groinder, the condition to check is fairly easy. Look at the disaggregation data json and if `'()'` key has `{'c': 0, 'd': 0, 'v': 0}` then it is an empty location data. In this case, show blank text instead of 0.

**Comment by sethgold8** [comment]
It is working for Quantity indicator, but needs to work also for
- [ ] percentage
- [ ] ratio

![Screen Shot 2018-10-15 at 12.59.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a379ed0c2e58415e4fbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e84b56a7153663e771326e0a.png)
![Screen Shot 2018-10-15 at 12.59.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a379ed0c2e58415d4cbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e84b56a715366be57f336e0a.png)

**Comment by KKaselkar** [comment]
working fine with percentage and ratio.
