### ISSUE TITLE
Enter data button doesnt appear for sent back reports (QPR & SR)

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#967]
dev.prp environment 
Iraq workspace
PCA 2016/04/PD2018484 
 
Logged in as AO.

Enter data button doesn't appear for QPR and SR reports which were sent back from PMP

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46698150-51ca6200-cbe4-11e8-9a38-687b78099b6a.png)

![image](https://user-images.githubusercontent.com/32198614/46698155-54c55280-cbe4-11e8-8532-1c797cd6d9b5.png)


![image](https://user-images.githubusercontent.com/32198614/46698159-5858d980-cbe4-11e8-9a8f-3663d2bf8ee1.png)


![image](https://user-images.githubusercontent.com/32198614/46698170-5b53ca00-cbe4-11e8-8966-2dcd44c4decc.png)


Enter data button appears for HR which was not sent back from PMP:
![image](https://user-images.githubusercontent.com/32198614/46698212-71fa2100-cbe4-11e8-89c2-939e3d54c8a6.png)

**Comment by sethgold8** [comment]
specific details? Partner, PD, Report?

**Comment by sethgold8** [comment]
duplicate as #947 . Will test #947 today and close
