### ISSUE TITLE
Incorrect Percentage Calc

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-partner-reporting-portal#971]
For this report: 
app/IRQ/ip-reporting/pd/1021/report/1424/view?page=1

Partner: The human rights centre in Iraq 
PD: IRQ/PCA2018259/PD2018482

I am entering data into the 1st HR report (HR1). After Submission I can see this:
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b6fe776743c32000a1b8c2/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb2876ddb02def112d580c5e4bac41515d41fbff8e29a0a42062c80d55b98e30063e937f03a6aa8317b500bf23824e8cb0ba8c4dc0e93437aa.PNG)

I would expect that both Total cumulative progress and Achievement in reporting period to be the same. The manual calculation yields a resut of 18.7% 

Where does the 17% in Total Cumulative Progress come from?

**Comment by mpawlowski85** [comment]
@KKaselkar - for your info

**Comment by sethgold8** [comment]
working, let us know if you see it again though

![Screen Shot 2018-10-15 at 4.58.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a37cf117234f5e595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e74952ad103e65e5772431.png)

**Comment by KKaselkar** [comment]
@sethgold8  for HR1 the cumulative and achievement in reporting period shows the same  but than if HR2 is submitted than it also changes the cumulative for HR1

**Comment by KKaselkar** [comment]
and now it shows incorrect values:
HR1
![image](https://user-images.githubusercontent.com/32198614/47039971-25b66000-d153-11e8-82f3-de447cfd45e4.png)

HR2
![image](https://user-images.githubusercontent.com/32198614/47040010-3e267a80-d153-11e8-8881-b0769a1be95a.png)

**Comment by KKaselkar** [comment]
PCA 2016/04/SHPD2018493

HR1:
![image](https://user-images.githubusercontent.com/32198614/47044135-674c0880-d15d-11e8-85d7-c8897fc036e8.png)

HR2:
![image](https://user-images.githubusercontent.com/32198614/47044456-34564480-d15e-11e8-947f-6deabfba48a2.png)

**Comment by sethgold8** [comment]
The issue here was that despite us refreshing indicators, total data stayed there so it caused uneven data

**Comment by KKaselkar** [comment]
this is resolved
