### ISSUE TITLE
Calculation Methods for Ratio and Percentage Indicators

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#973]
Ratio type indicators need to calculate its progress differently then quantity indicator

- [x] Update indicator report calculation logic for ratio type to add numerators and denominators separately and divide them at the end. This is not done in common denominator multiplication #backend
- [x] When progress report is submitted (or sent back) update reportable total for ratio type to grab the latest progress reports. Grab the latest progress report that is submitted and grab the indicator report for the reportable to get its total #backend
- [x] Show `latest` for calculation method across reporting periods in frontend if the indicator is ratio type. #frontend
- [x] Remove multiplying value by 100 in `_toPercentage` utility function. Backend already converted the value before sending API response. #frontend
- [x] Update `_toPercentage` utility function to handle both ratio and percentage type formatting. Add a new function argument called `indicator_type` to `_toPercentage` function. If `indicator_type` is percentage, append '%' to value and return. If `indicator_type` is ratio, append `:1` to value and return. #frontend

Cluster
- [ ] The PRP-Cluster IMO is not able to change the denominator of a ratio indicator once it is set. #backend  #frontend 

Frontend should disable theUI  field and backend should throw a validation in indicator update API that target denominator cannot be changed

**Comment by mpawlowski85** [comment]
@sethgold8  That sounds like it captures all of the issues 
Please let me know once you added the download bits.

**Comment by n1207n** [comment]
It turned out that backend is already doing correct indicator report total calculation. Frontend needs to fix how `Total cumulative progress` and `Achievement in reporting period` is displayed for ratio and percentage type.

**Comment by n1207n** [comment]
Backend items for this ticket are done and will be deployed soon.

**Comment by groinder** [comment]
@sethgold8 @n1207n Can you provide screens/directions where those changes need to be made on the frontend? I believe the `_toPercentage` only needs to be changed in some places, because if I change it in every indicator view it doesn't look right 
![image](https://user-images.githubusercontent.com/16709010/46948612-f504f680-d07e-11e8-9d6b-fabc9e9e8a51.png)

**Comment by sethgold8** [comment]
If percentage, we should show a percentage.

If it's a ratio, we should use a colon. For example 10:1

Also highlighted the 5 areas where we should make the frontend changes

![Screen Shot 2018-10-15 at 11.48.30 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a379ee0c2f59415c4ebc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e84b57ad163362ee72346e0a.png)

**Comment by groinder** [comment]
@n1207n I've created a branch `973-calculation-methods-for-ratio-and-percentage-indicators` for this values formatting, please check if this is what we want.

@sethgold8 I don't know what this is about
> Show `latest` for calculation method across reporting periods in frontend if the indicator is ratio type. #frontend

And also this, can you give me a screen of which field we are talking about?
> Frontend should disable theUI field and backend should throw a validation in indicator update API that target denominator cannot be changed

**Comment by KKaselkar** [comment]
PD: PCA 2016/04/PD2018494
The below screenshot shows the second indicator as ratio but the target is displayed as percent

![image](https://user-images.githubusercontent.com/32198614/47165916-093c3400-d2c9-11e8-9f0f-d028d0f6e176.png)

**Comment by sethgold8** [comment]
It is our understanding target is always percentage.

How will you measure as a ratio? cc @mpawlowski85

**Comment by KKaselkar** [comment]
Calculation method for ratio works well
calculation for percentage has issues will create another ticket for this
