### ISSUE TITLE
Export for each indicator doesn't provide any data

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#975]
dev.prp environment 

Logged in as IMO
kunal.kaselkar@gmail.com was the username
Project level indicators
When clicked on the export on each indicator under submitted reports tab the excel sheet doesn't provide any data in the exported spreadsheet

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46808572-b0a1ef80-cd3a-11e8-95ff-0b910fd5054a.png)

**Comment by sethgold8** [comment]
I see data, can you attach a screen shot of the export?

**Comment by sethgold8** [comment]
duplicagte of #764. Closing
