### ISSUE TITLE
Add button is not displayed for cluster obj and cluster act (IMO)

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#977]
dev.prp environment 

cluster PRP 
Iraq workspace

Add cluster objective and cluster activity button doesnt display on the screen 
 Logged in as IMO
kunal.kaselkar@gmail.com

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46826650-849b6400-cd64-11e8-88db-6277a61dbac6.png)


![image](https://user-images.githubusercontent.com/32198614/46826668-92e98000-cd64-11e8-92c3-51db5025d7d2.png)

**Comment by sethgold8** [comment]
@groinder 

- [ ] Add Cluster Objective is missing for IMO
- [ ] Add Cluster Activity is missing for IMO

**Comment by sethgold8** [comment]
Fixed :)

![Screen Shot 2018-10-15 at 12.56.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a379ed0c2e57415c4bbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e84b56a7173462e2773e6e0a.png)

**Comment by KKaselkar** [comment]
working now just tested thanks.
