### ISSUE TITLE
Fronted Show Error message when QPR has non high frequency indicator

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#980]
When a user 'Pulls Data From HR' and the QPR has non high frequency indicators, the backend throws a 400 error.

- [ ] Frontend needs to show error message: This indicator is non-HF indicator. Data pull only works with HF indicator"

For Reference, you can see an example 
IRQ/PCA2018259/PD2018482
THE HUMAN RIGHT CENTER IN IRAQ
indicator title: 7 Ratio Ind 1 Loc 3 Dis

![Screen Shot 2018-10-12 at 12.08.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f16b7191a379ed0c2b59415d47bc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e84e52a5103260ef7e3e6e0a.png)

**Comment by sethgold8** [comment]
@groinder in

PCA 2016/04/PD2018494
Agency for Technical and Emergency Dev
Mb_Pd2018494_Hf_Indi_1_Percentage

 We need an error message for when there is no data to pull. There may be an error message but having issues with the 'snack bar: error message box'. showing

It should say

- [ ] This indicator does not have available data to pull. Enter data for HR report on this indicator first.

**Comment by groinder** [comment]
Added snackbar for this.

**Comment by sethgold8** [comment]
working :)

**Comment by KKaselkar** [comment]
Message must say high frequency indicator instead of HF indicator.

When a QPR report is sent back from PMP to PRP the error message appears for high frequency indicators as well.

Can you just show the message  just below the indicator name instead of showing  the pull data from HR button?

**Comment by groinder** [comment]
@n1207n Message is shown as it is returned from the API. I don't think that we have data to to hide the button right away. LMK if I need to change anything.

**Comment by sethgold8** [comment]
Error message showing below

![Screen Shot 2018-11-21 at 3.16.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37bf1132d4f5d5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e94957a6123262e1772431.png)
