### ISSUE TITLE
if the QPR report is submitted or accepted then pull HR button should not function and allow the user to overwrite the data.

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#981]
If the QPR report is submitted or accepted then pull HR button should not function and allow the user to overwrite the data. 

- [x] 'Pull Data from HR' button must be greyed out if the QPR is submitted or accepted.

**Comment by sethgold8** [comment]
working :)

![Screen Shot 2018-10-15 at 3.46.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a37bf1162d4f5e565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e74956a2133167e0762431.png)

**Comment by KKaselkar** [comment]
Pull HR button is now greyed out for submitted and accepted report
