### ISSUE TITLE
PD Sync is failing

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-partner-reporting-portal#984]
In Demo, Iraq
I amended PD:
IRQ/PCA2018254/PD2018428, but the reports are not generating. 

There is a problem with the sync in that it errors out on PD ID 487 (PCA 2016/04/SHPD2018487), which is completely unrelated, but errors in this unrelated PD stop the system from generating reports for my PD. 

Silin and Rob are talking about it.

**Comment by KKaselkar** [comment]
PD and reports are now appearing in IP PRP
sync works
