### ISSUE TITLE
Add ' Partner Project' and 'Partner Activity'

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#985]
These buttons are missing for admin_Imo

- [ ] Add Partner Project
- [ ] Add Partner Activity

![Screen Shot 2018-10-15 at 5.00.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a37df1122b4f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e7495da61b3466e27e2431.png)

![Screen Shot 2018-10-15 at 5.01.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a37df1122a4f5f5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df542e7495da61b3f65e5742431.png)

**Comment by KKaselkar** [comment]
For Cluster member "Add Project" button is available but "Add partner activity" is not available.For IMO, both of them are not available.

**Comment by n1207n** [comment]
Redeploying fixed. It might have been stale code during deployment.

**Comment by KKaselkar** [comment]
Add buttons for Partner Project' and 'Partner Activity are now appearing for IMO
