### ISSUE TITLE
Amended reporting requirement in PMP doesnt appear in IP PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#994]
Browser:Chrome 
workspace:Iraq 
env: PMP Demo and PRP Dev 
Steps: 
-Create a PD in PMP. 
-Add indicators to the PD. 
-Add reports to PD(QPR,HR,SR). 
-Make the PD active. 
-Check the same PD in IP-PRP. 
-Check all the reports are appearing in IP-PRP. 
-Now go to PMP. 
-Amend the PD. 
-Add a new report. 
-Click "I am done" or Save in PMP. 
-Check the PD in IP- PRP  after sync is completed. 
-Validate that new report is appearing in IP-PRP. 
Result:The report added through amendment is not displayed in IP-PRP. 
Example:PCA 2016/04/SHPD2018497: HR report with end date :19th oct was added while amending the PD.

**Comment by sethgold8** [comment]
#1002 and #996 will solve this.

Also PD sync in dev  happens every 30 minutes

@KKaselkar 

Closing this
