### ISSUE TITLE
Additional location added to the indicators

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-partner-reporting-portal#995]
In Rwanda
dev.PRP
partner: CHANCE FOR CHILDHOOD CFC
PD: RWA/PCA201879/PD2018105-1
user: pawl21@gmail.com

I am addition 2 locations to my PD - Kigali and Nyagatare. When the sync happens, I can see that each of the indicators has an additional location - Iraq (screenshot below). 

It is worth mentioning that my user seems to have access to 2 workspaces - Iraq and Rwanda.

![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b6fe776743c32000a1b8c2/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb2876ddb02def112d580c5e4bac41515d41fbff8e29a0a42062c80d55b98e30063e937f03a6aa8318b500bf2382478cb6bf8e49c1e83b37aa.PNG)

**Comment by sethgold8** [comment]
something to take a look: There might be an issue with the Locations. Rob was seeing Sudan twice and had to remap.

**Comment by sethgold8** [comment]
We deleted IRAQ location for that PD.

**Comment by mpawlowski85** [comment]
I now remove the permission to Iraq workspace for my user (pawl21@gmail.com). 
I added a new PD and Iraq still appears as a location.... 
It looks like it gets appended to all Indicators.

**Comment by sethgold8** [comment]
unable to reproduce in Demo
