### ISSUE TITLE
802 - AO's names dont match PMP and PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#996]
List of AO's do not match between PMP and IP PRP.

dev.prp environment
etools PMP
Iraq workspce

**Comment by KKaselkar** [comment]
PMP:
![image](https://user-images.githubusercontent.com/32198614/47238323-d28d1900-d3af-11e8-8550-0e9ddd3ff4a0.png)

![image](https://user-images.githubusercontent.com/32198614/47238347-e0db3500-d3af-11e8-9779-b47205eed1ae.png)

IP PRP
![image](https://user-images.githubusercontent.com/32198614/47238363-f0f31480-d3af-11e8-8ba4-cda4e5ea6ef3.png)

**Comment by KKaselkar** [comment]
created a PD and it only displayed one AO and not all the AO's listed in the PCA

**Comment by sethgold8** [comment]
Working now  :) 

Only Raphael Capony is in the agreement IRQ/SSFA2018260 and the only AO I can submit

![Screen Shot 2018-10-25 at 3.01.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f66b7191a37bf1122a4f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be44d51ad143764e0712431.png)

![Screen Shot 2018-10-25 at 3.01.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f66b7191a37bf1122a4f5b5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24be44d51ad143e65e5702431.png)

**Comment by KKaselkar** [comment]
They do match tested in Zimbabwe PD
