### ISSUE TITLE
Report generation is not stable

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#999]
dev.prp
Iraq workspace

MB_Obj_1_19th Oct_Indi_1  - no report was generated
MB_Project_1_19th OCt_Indi_1 - overdue report was generated but next due report is not generated
MB_ClustACt_2_19th Oct_indi_1 - overdue report was generated but next due report is not generated
MB_Proj_2_19th Oct_Indi_1 - overdue report was generated but next due report is not generated

**Comment by sethgold8** [comment]
Please demo this for me on next standup. I tested monthly reports and it worked just fine.

![Screen Shot 2018-10-31 at 12.02.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379ed0c2b53415b4dbc21254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe04d54a6143061e170316e0a.png)

**Comment by sethgold8** [comment]
@robertavram, 

@n1207n needs the logs to debug or dev access to rancher for Dev.PRP

Reports are generating when you add a location, but they are not generating for new reports in the future. For example there should be a new report below as it is 11/7, but the latest report shows period 10/30-11/5 with a due date of 11/6.

![Screen Shot 2018-11-07 at 4.38.51 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a37cf111234f5a5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24ae74e52a11a3f64e0732431.png)

**Comment by KKaselkar** [comment]
tested in dev and reports are getting generated as per the frequency

**Comment by KKaselkar** [comment]
Tested in dev environment and only overdue reports are generating for project indicators added to custom projects, due reports are not getting generated. @sethgold8  @n1207n

**Comment by KKaselkar** [comment]
Reports are getting generated as per the frequency of reporting
